// Curated list of IATA airport codes with city/name.
// Focus: Italy, Brazil, Europe, and major world hubs.
export type Airport = { code: string; name: string };

export const AIRPORTS: Airport[] = [
  // Italy
  { code: "FCO", name: "Roma Fiumicino" },
  { code: "CIA", name: "Roma Ciampino" },
  { code: "MXP", name: "Milano Malpensa" },
  { code: "LIN", name: "Milano Linate" },
  { code: "BGY", name: "Milano Bergamo Orio al Serio" },
  { code: "VCE", name: "Venezia Marco Polo" },
  { code: "TSF", name: "Treviso" },
  { code: "BLQ", name: "Bologna" },
  { code: "FLR", name: "Firenze" },
  { code: "PSA", name: "Pisa" },
  { code: "NAP", name: "Napoli" },
  { code: "BRI", name: "Bari" },
  { code: "CTA", name: "Catania" },
  { code: "PMO", name: "Palermo" },
  { code: "TRN", name: "Torino" },
  { code: "VRN", name: "Verona" },
  { code: "CAG", name: "Cagliari" },
  { code: "OLB", name: "Olbia" },
  { code: "AHO", name: "Alghero" },
  { code: "GOA", name: "Genova" },
  { code: "TRS", name: "Trieste" },
  { code: "AOI", name: "Ancona" },
  { code: "PSR", name: "Pescara" },
  { code: "REG", name: "Reggio Calabria" },
  { code: "SUF", name: "Lamezia Terme" },
  { code: "BDS", name: "Brindisi" },
  // Brazil
  { code: "GRU", name: "São Paulo Guarulhos" },
  { code: "CGH", name: "São Paulo Congonhas" },
  { code: "VCP", name: "Campinas Viracopos" },
  { code: "GIG", name: "Rio de Janeiro Galeão" },
  { code: "SDU", name: "Rio de Janeiro Santos Dumont" },
  { code: "BSB", name: "Brasília" },
  { code: "CNF", name: "Belo Horizonte Confins" },
  { code: "PLU", name: "Belo Horizonte Pampulha" },
  { code: "SSA", name: "Salvador" },
  { code: "REC", name: "Recife" },
  { code: "FOR", name: "Fortaleza" },
  { code: "POA", name: "Porto Alegre" },
  { code: "CWB", name: "Curitiba" },
  { code: "FLN", name: "Florianópolis" },
  { code: "MAO", name: "Manaus" },
  { code: "BEL", name: "Belém" },
  { code: "NAT", name: "Natal" },
  { code: "MCZ", name: "Maceió" },
  { code: "AJU", name: "Aracaju" },
  { code: "VIX", name: "Vitória" },
  { code: "CGB", name: "Cuiabá" },
  { code: "CGR", name: "Campo Grande" },
  { code: "GYN", name: "Goiânia" },
  { code: "IGU", name: "Foz do Iguaçu" },
  { code: "NVT", name: "Navegantes" },
  { code: "JPA", name: "João Pessoa" },
  { code: "THE", name: "Teresina" },
  { code: "SLZ", name: "São Luís" },
  { code: "PMW", name: "Palmas" },
  { code: "PVH", name: "Porto Velho" },
  { code: "BVB", name: "Boa Vista" },
  { code: "MCP", name: "Macapá" },
  { code: "RBR", name: "Rio Branco" },
  { code: "UDI", name: "Uberlândia" },
  { code: "IPN", name: "Ipatinga" },
  { code: "MOC", name: "Montes Claros" },
  // Europe hubs
  { code: "CDG", name: "Paris Charles de Gaulle" },
  { code: "ORY", name: "Paris Orly" },
  { code: "LHR", name: "London Heathrow" },
  { code: "LGW", name: "London Gatwick" },
  { code: "STN", name: "London Stansted" },
  { code: "LTN", name: "London Luton" },
  { code: "LCY", name: "London City" },
  { code: "FRA", name: "Frankfurt" },
  { code: "MUC", name: "Munich" },
  { code: "BER", name: "Berlin Brandenburg" },
  { code: "HAM", name: "Hamburg" },
  { code: "DUS", name: "Düsseldorf" },
  { code: "CGN", name: "Cologne Bonn" },
  { code: "STR", name: "Stuttgart" },
  { code: "AMS", name: "Amsterdam Schiphol" },
  { code: "BRU", name: "Brussels" },
  { code: "CRL", name: "Brussels Charleroi" },
  { code: "LUX", name: "Luxembourg" },
  { code: "ZRH", name: "Zurich" },
  { code: "GVA", name: "Geneva" },
  { code: "BSL", name: "Basel EuroAirport" },
  { code: "VIE", name: "Vienna" },
  { code: "PRG", name: "Prague" },
  { code: "WAW", name: "Warsaw Chopin" },
  { code: "KRK", name: "Kraków" },
  { code: "BUD", name: "Budapest" },
  { code: "OTP", name: "Bucharest Otopeni" },
  { code: "SOF", name: "Sofia" },
  { code: "ATH", name: "Athens" },
  { code: "SKG", name: "Thessaloniki" },
  { code: "IST", name: "Istanbul" },
  { code: "SAW", name: "Istanbul Sabiha Gökçen" },
  { code: "MAD", name: "Madrid Barajas" },
  { code: "BCN", name: "Barcelona El Prat" },
  { code: "AGP", name: "Málaga" },
  { code: "PMI", name: "Palma de Mallorca" },
  { code: "VLC", name: "Valencia" },
  { code: "SVQ", name: "Seville" },
  { code: "BIO", name: "Bilbao" },
  { code: "LIS", name: "Lisbon" },
  { code: "OPO", name: "Porto" },
  { code: "FAO", name: "Faro" },
  { code: "FNC", name: "Madeira Funchal" },
  { code: "DUB", name: "Dublin" },
  { code: "EDI", name: "Edinburgh" },
  { code: "MAN", name: "Manchester" },
  { code: "CPH", name: "Copenhagen" },
  { code: "ARN", name: "Stockholm Arlanda" },
  { code: "OSL", name: "Oslo" },
  { code: "HEL", name: "Helsinki" },
  { code: "KEF", name: "Reykjavík Keflavík" },
  { code: "RIX", name: "Riga" },
  { code: "TLL", name: "Tallinn" },
  { code: "VNO", name: "Vilnius" },
  { code: "LJU", name: "Ljubljana" },
  { code: "ZAG", name: "Zagreb" },
  { code: "BEG", name: "Belgrade" },
  { code: "TIA", name: "Tirana" },
  { code: "SJJ", name: "Sarajevo" },
  { code: "SKP", name: "Skopje" },
  // Americas / hubs
  { code: "JFK", name: "New York JFK" },
  { code: "EWR", name: "New York Newark" },
  { code: "LGA", name: "New York LaGuardia" },
  { code: "MIA", name: "Miami" },
  { code: "MCO", name: "Orlando" },
  { code: "ATL", name: "Atlanta" },
  { code: "ORD", name: "Chicago O'Hare" },
  { code: "LAX", name: "Los Angeles" },
  { code: "SFO", name: "San Francisco" },
  { code: "IAD", name: "Washington Dulles" },
  { code: "BOS", name: "Boston" },
  { code: "IAH", name: "Houston Intercontinental" },
  { code: "DFW", name: "Dallas Fort Worth" },
  { code: "YYZ", name: "Toronto Pearson" },
  { code: "YUL", name: "Montréal Trudeau" },
  { code: "MEX", name: "Mexico City" },
  { code: "PTY", name: "Panama City Tocumen" },
  { code: "BOG", name: "Bogotá" },
  { code: "LIM", name: "Lima" },
  { code: "SCL", name: "Santiago de Chile" },
  { code: "EZE", name: "Buenos Aires Ezeiza" },
  { code: "AEP", name: "Buenos Aires Aeroparque" },
  { code: "MVD", name: "Montevideo" },
  { code: "ASU", name: "Asunción" },
  { code: "UIO", name: "Quito" },
  { code: "GYE", name: "Guayaquil" },
  { code: "CCS", name: "Caracas" },
  // Middle East / Africa / Asia hubs
  { code: "DXB", name: "Dubai" },
  { code: "AUH", name: "Abu Dhabi" },
  { code: "DOH", name: "Doha" },
  { code: "TLV", name: "Tel Aviv" },
  { code: "CAI", name: "Cairo" },
  { code: "JNB", name: "Johannesburg" },
  { code: "CPT", name: "Cape Town" },
  { code: "ADD", name: "Addis Ababa" },
  { code: "NBO", name: "Nairobi" },
  { code: "CMN", name: "Casablanca" },
  { code: "ALG", name: "Algiers" },
  { code: "TUN", name: "Tunis" },
  { code: "LOS", name: "Lagos" },
  { code: "BKK", name: "Bangkok Suvarnabhumi" },
  { code: "SIN", name: "Singapore Changi" },
  { code: "HKG", name: "Hong Kong" },
  { code: "PEK", name: "Beijing Capital" },
  { code: "PKX", name: "Beijing Daxing" },
  { code: "PVG", name: "Shanghai Pudong" },
  { code: "SHA", name: "Shanghai Hongqiao" },
  { code: "CAN", name: "Guangzhou" },
  { code: "NRT", name: "Tokyo Narita" },
  { code: "HND", name: "Tokyo Haneda" },
  { code: "ICN", name: "Seoul Incheon" },
  { code: "TPE", name: "Taipei Taoyuan" },
  { code: "KUL", name: "Kuala Lumpur" },
  { code: "CGK", name: "Jakarta" },
  { code: "MNL", name: "Manila" },
  { code: "DEL", name: "Delhi" },
  { code: "BOM", name: "Mumbai" },
  { code: "SYD", name: "Sydney" },
  { code: "MEL", name: "Melbourne" },
  { code: "AKL", name: "Auckland" },
];
