// Curated list of IATA airport codes.
// Brazilian airports include city, UF, and lat/lon for map display.
export type Airport = {
  code: string;
  name: string;
  city?: string;
  uf?: string;   // Brazilian state (UF) or country code
  lat?: number;
  lon?: number;
};

export const AIRPORTS: Airport[] = [
  // Italy
  { code: "FCO", name: "Roma Fiumicino" },
  { code: "CIA", name: "Roma Ciampino" },
  { code: "MXP", name: "Milano Malpensa" },
  { code: "LIN", name: "Milano Linate" },
  { code: "BGY", name: "Milano Bergamo Orio al Serio" },
  { code: "VCE", name: "Venezia Marco Polo" },
  { code: "TSF", name: "Treviso" },
  { code: "BLQ", name: "Bologna" },
  { code: "FLR", name: "Firenze" },
  { code: "PSA", name: "Pisa" },
  { code: "NAP", name: "Napoli" },
  { code: "BRI", name: "Bari" },
  { code: "CTA", name: "Catania" },
  { code: "PMO", name: "Palermo" },
  { code: "TRN", name: "Torino" },
  { code: "VRN", name: "Verona" },
  { code: "CAG", name: "Cagliari" },
  { code: "OLB", name: "Olbia" },
  { code: "AHO", name: "Alghero" },
  { code: "GOA", name: "Genova" },
  { code: "TRS", name: "Trieste" },
  { code: "AOI", name: "Ancona" },
  { code: "PSR", name: "Pescara" },
  { code: "REG", name: "Reggio Calabria" },
  { code: "SUF", name: "Lamezia Terme" },
  { code: "BDS", name: "Brindisi" },
  // Brazil
  { code: "CZS", name: "Cruzeiro do Sul Airport", city: "Cruzeiro Do Sul", uf: "AC", lat: -7.59991, lon: -72.769501 },
  { code: "RBR", name: "Rio Branco-Plácido de Castro International Airport", city: "Rio Branco", uf: "AC", lat: -9.869031, lon: -67.893984 },
  { code: "MCZ", name: "Zumbi dos Palmares International Airport", city: "Maceió", uf: "AL", lat: -9.512559, lon: -35.791839 },
  { code: "BAZ", name: "Barcelos Airport", city: "Barcelos", uf: "AM", lat: -0.981191, lon: -62.918603 },
  { code: "RBB", name: "Borba Airport", city: "Borba", uf: "AM", lat: -4.40634, lon: -59.602402 },
  { code: "CAF", name: "Carauari Airport", city: "Carauari", uf: "AM", lat: -4.871473, lon: -66.897552 },
  { code: "LBR", name: "Lábrea Airport", city: "Lábrea", uf: "AM", lat: -7.27897, lon: -64.769501 },
  { code: "MAO", name: "Eduardo Gomes International Airport", city: "Manaus", uf: "AM", lat: -3.03861, lon: -60.049702 },
  { code: "MNX", name: "Manicoré Airport", city: "Manicoré", uf: "AM", lat: -5.81138, lon: -61.278301 },
  { code: "IRZ", name: "Tapuruquara Airport", city: "Santa Isabel do Rio Negro", uf: "AM", lat: -0.378604, lon: -64.992558 },
  { code: "SJL", name: "São Gabriel da Cachoeira Airport", city: "São Gabriel da Cachoeira", uf: "AM", lat: -0.14835, lon: -66.9855 },
  { code: "TBT", name: "Tabatinga International Airport", city: "Tabatinga", uf: "AM", lat: -4.25567, lon: -69.935799 },
  { code: "TFF", name: "Tefé Airport", city: "Tefé", uf: "AM", lat: -3.38294, lon: -64.724098 },
  { code: "MCP", name: "Macapá - Alberto Alcolumbre International Airport", city: "Macapá", uf: "AP", lat: 0.050664, lon: -51.072201 },
  { code: "BRA", name: "Dom Ricardo Weberberger Airport", city: "Barreiras", uf: "BA", lat: -12.0789, lon: -45.008999 },
  { code: "IOS", name: "Bahia - Jorge Amado Airport", city: "Ilhéus", uf: "BA", lat: -14.815929, lon: -39.033458 },
  { code: "LEC", name: "Coronel Horácio de Mattos Airport", city: "Lençóis", uf: "BA", lat: -12.4823, lon: -41.277 },
  { code: "PAV", name: "Paulo Afonso Airport", city: "Paulo Afonso", uf: "BA", lat: -9.40088, lon: -38.250599 },
  { code: "BPS", name: "Porto Seguro International Airport", city: "Porto Seguro", uf: "BA", lat: -16.438426, lon: -39.080584 },
  { code: "SSA", name: "Deputado Luiz Eduardo Magalhães International Airport", city: "Salvador", uf: "BA", lat: -12.908611, lon: -38.322498 },
  { code: "UNA", name: "Una-Comandatuba Airport", city: "Una", uf: "BA", lat: -15.354358, lon: -38.998729 },
  { code: "VAL", name: "Valença Airport", city: "Valença", uf: "BA", lat: -13.2965, lon: -38.992401 },
  { code: "VDC", name: "Glauber de Andrade Rocha Airport", city: "Vitória da Conquista", uf: "BA", lat: -14.907885, lon: -40.914804 },
  { code: "JJD", name: "Comandante Ariston Pessoa Airport", city: "Cruz", uf: "CE", lat: -2.906425, lon: -40.357338 },
  { code: "FOR", name: "Pinto Martins International Airport", city: "Fortaleza", uf: "CE", lat: -3.775833, lon: -38.532222 },
  { code: "JDO", name: "Orlando Bezerra de Menezes Airport", city: "Juazeiro do Norte", uf: "CE", lat: -7.21932, lon: -39.269096 },
  { code: "BSB", name: "Presidente Juscelino Kubitschek International Airport", city: "Brasília", uf: "DF", lat: -15.869167, lon: -47.920834 },
  { code: "GUZ", name: "Guarapari Airport", city: "Guarapari", uf: "ES", lat: -20.6465, lon: -40.491901 },
  { code: "VIX", name: "Eurico de Aguiar Salles International Airport", city: "Vitória", uf: "ES", lat: -20.258, lon: -40.285 },
  { code: "CLV", name: "Nelson Ribeiro Guimarães Airport", city: "Caldas Novas", uf: "GO", lat: -17.725096, lon: -48.606324 },
  { code: "GYN", name: "Santa Genoveva International Airport", city: "Goiânia", uf: "GO", lat: -16.632, lon: -49.220699 },
  { code: "IMP", name: "Prefeito Renato Moreira Airport", city: "Imperatriz", uf: "MA", lat: -5.53129, lon: -47.459999 },
  { code: "SLZ", name: "Marechal Cunha Machado International Airport", city: "São Luís", uf: "MA", lat: -2.586386, lon: -44.235008 },
  { code: "AAX", name: "Romeu Zema Airport", city: "Araxá", uf: "MG", lat: -19.5632, lon: -46.9604 },
  { code: "CNF", name: "Tancredo Neves International Airport", city: "Belo Horizonte", uf: "MG", lat: -19.63571, lon: -43.966928 },
  { code: "PLU", name: "Pampulha - Carlos Drummond de Andrade Airport", city: "Belo Horizonte", uf: "MG", lat: -19.8512, lon: -43.9506 },
  { code: "GVR", name: "Coronel Altino Machado Airport", city: "Governador Valadares", uf: "MG", lat: -18.895882, lon: -41.982869 },
  { code: "IPN", name: "Usiminas Airport", city: "Ipatinga", uf: "MG", lat: -19.470699, lon: -42.487598 },
  { code: "IZA", name: "Presidente Itamar Franco Airport", city: "Juiz de Fora", uf: "MG", lat: -21.513086, lon: -43.173069 },
  { code: "JDF", name: "Francisco de Assis Airport", city: "Juiz de Fora", uf: "MG", lat: -21.791482, lon: -43.386072 },
  { code: "MOC", name: "Mário Ribeiro Airport", city: "Montes Claros", uf: "MG", lat: -16.706919, lon: -43.818901 },
  { code: "PYT", name: "Pedro Rabelo de Souza Airport", city: "Paracatu", uf: "MG", lat: -17.242599, lon: -46.883099 },
  { code: "UBA", name: "Mário de Almeida Franco Airport", city: "Uberaba", uf: "MG", lat: -19.765036, lon: -47.964805 },
  { code: "UDI", name: "Ten. Cel. Aviador César Bombonato Airport", city: "Uberlândia", uf: "MG", lat: -18.883579, lon: -48.225936 },
  { code: "BYO", name: "Bonito Airport", city: "Bonito", uf: "MS", lat: -21.2473, lon: -56.452399 },
  { code: "CGR", name: "Campo Grande Airport", city: "Campo Grande", uf: "MS", lat: -20.469998, lon: -54.673988 },
  { code: "CMG", name: "Corumbá International Airport", city: "Corumbá", uf: "MS", lat: -19.01193, lon: -57.672772 },
  { code: "PMG", name: "Ponta Porã Airport", city: "Ponta Porã", uf: "MS", lat: -22.549601, lon: -55.702599 },
  { code: "TJL", name: "Plínio Alarcom Airport", city: "Três Lagoas", uf: "MS", lat: -20.752643, lon: -51.682026 },
  { code: "AFL", name: "Piloto Osvaldo Marques Dias Airport", city: "Alta Floresta", uf: "MT", lat: -9.866389, lon: -56.106298 },
  { code: "CGB", name: "Várzea Grande–Marechal Rondon International Airport", city: "Cuiabá", uf: "MT", lat: -15.6529, lon: -56.116699 },
  { code: "ROO", name: "Maestro Marinho Franco Airport", city: "Rondonópolis", uf: "MT", lat: -16.584292, lon: -54.724803 },
  { code: "OPS", name: "Presidente João Batista Figueiredo Airport", city: "Sinop", uf: "MT", lat: -11.885001, lon: -55.586109 },
  { code: "SMT", name: "Adolino Bedin Regional Airport", city: "Sorriso", uf: "MT", lat: -12.479177, lon: -55.672341 },
  { code: "TGQ", name: "Tangará da Serra Airport", city: "Tangará da Serra", uf: "MT", lat: -14.662, lon: -57.443744 },
  { code: "GGF", name: "Almeirim Airport", city: "Almeirim", uf: "PA", lat: -1.479524, lon: -52.578214 },
  { code: "ATM", name: "Altamira Interstate Airport", city: "Altamira", uf: "PA", lat: -3.253144, lon: -52.253938 },
  { code: "BEL", name: "Val de Cans/Júlio Cezar Ribeiro International Airport", city: "Belém", uf: "PA", lat: -1.379279, lon: -48.476207 },
  { code: "BVS", name: "Breves Airport", city: "Breves", uf: "PA", lat: -1.63653, lon: -50.4436 },
  { code: "ITB", name: "Itaituba Airport", city: "Itaituba", uf: "PA", lat: -4.242131, lon: -56.000651 },
  { code: "MAB", name: "João Correa da Rocha Airport", city: "Marabá", uf: "PA", lat: -5.36859, lon: -49.138 },
  { code: "TMT", name: "Trombetas Airport", city: "Oriximiná", uf: "PA", lat: -1.4896, lon: -56.396801 },
  { code: "JPE", name: "Nagib Demachki Airport", city: "Paragominas", uf: "PA", lat: -3.019798, lon: -47.316474 },
  { code: "CKS", name: "Carajás Airport", city: "Parauapebas", uf: "PA", lat: -6.117841, lon: -50.003372 },
  { code: "OPP", name: "Salinópolis Airport", city: "Salinópolis", uf: "PA", lat: -0.696111, lon: -47.336111 },
  { code: "STM", name: "Santarém - Maestro Wilson Fonseca International Airport", city: "Santarém", uf: "PA", lat: -2.422423, lon: -54.79306 },
  { code: "TUR", name: "Tucuruí Airport", city: "Tucuruí", uf: "PA", lat: -3.78601, lon: -49.720299 },
  { code: "CJZ", name: "Pedro Vieira Moreira Airport", city: "Cajazeiras", uf: "PB", lat: -6.8827, lon: -38.61583 },
  { code: "CPV", name: "Presidente João Suassuna Airport", city: "Campina Grande", uf: "PB", lat: -7.269662, lon: -35.896057 },
  { code: "JPA", name: "Presidente Castro Pinto International Airport", city: "João Pessoa", uf: "PB", lat: -7.148691, lon: -34.950554 },
  { code: "CAU", name: "Caruaru Airport", city: "Caruaru", uf: "PE", lat: -8.28239, lon: -36.0135 },
  { code: "FEN", name: "Fernando de Noronha Airport", city: "Fernando de Noronha", uf: "PE", lat: -3.854534, lon: -32.423017 },
  { code: "PNZ", name: "Senador Nilo Coelho Airport", city: "Petrolina", uf: "PE", lat: -9.362422, lon: -40.569098 },
  { code: "REC", name: "Recife/Guararapes - Gilberto Freyre International Airport", city: "Recife", uf: "PE", lat: -8.12747, lon: -34.922961 },
  { code: "SET", name: "Santa Magalhães Airport", city: "Serra Talhada", uf: "PE", lat: -8.061433, lon: -38.328888 },
  { code: "PHB", name: "Parnaíba - Prefeito Doutor João Silva Filho International Airport", city: "Parnaíba", uf: "PI", lat: -2.89375, lon: -41.731998 },
  { code: "THE", name: "Senador Petrônio Portela Airport", city: "Teresina", uf: "PI", lat: -5.06025, lon: -42.823712 },
  { code: "CAC", name: "Coronel Adalberto Mendes da Silva Airport", city: "Cascavel", uf: "PR", lat: -25.000323, lon: -53.501208 },
  { code: "CWB", name: "Curitiba-Afonso Pena International Airport", city: "Curitiba", uf: "PR", lat: -25.5285, lon: -49.1758 },
  { code: "IGU", name: "Cataratas International Airport", city: "Foz do Iguaçu", uf: "PR", lat: -25.594167, lon: -54.489444 },
  { code: "FBE", name: "Paulo Abdala Airport", city: "Francisco Beltrão", uf: "PR", lat: -26.05938, lon: -53.063827 },
  { code: "GGJ", name: "Guaíra Airport", city: "Guaíra", uf: "PR", lat: -24.0811, lon: -54.1917 },
  { code: "LDB", name: "Governor José Richa Airport", city: "Londrina", uf: "PR", lat: -23.334375, lon: -51.128365 },
  { code: "MGF", name: "Regional de Maringá - Sílvio Name Júnior Airport", city: "Maringá", uf: "PR", lat: -23.47606, lon: -52.016187 },
  { code: "PTO", name: "Juvenal Loureiro Cardoso Airport", city: "Pato Branco", uf: "PR", lat: -26.217184, lon: -52.694463 },
  { code: "PGZ", name: "Ponta Grossa Airport - Comandante Antonio Amilton Beraldo", city: "Ponta Grossa", uf: "PR", lat: -25.184476, lon: -50.143822 },
  { code: "TOW", name: "Toledo - Luiz Dalcanale Filho Municipal Airport", city: "Toledo", uf: "PR", lat: -24.6863, lon: -53.697498 },
  { code: "UMU", name: "Orlando de Carvalho Airport", city: "Umuarama", uf: "PR", lat: -23.7987, lon: -53.313801 },
  { code: "UVI", name: "José Cleto Airport", city: "União da Vitória", uf: "PR", lat: -26.233224, lon: -51.066754 },
  { code: "CFB", name: "Cabo Frio Airport", city: "Cabo Frio", uf: "RJ", lat: -22.921485, lon: -42.071874 },
  { code: "CAW", name: "Bartolomeu Lisandro Airport", city: "Campos dos Goytacazes", uf: "RJ", lat: -21.698299, lon: -41.301701 },
  { code: "GIG", name: "Rio Galeão – Tom Jobim International Airport", city: "Rio De Janeiro", uf: "RJ", lat: -22.809999, lon: -43.250557 },
  { code: "RRJ", name: "Jacarepaguá - Roberto Marinho Airport", city: "Rio de Janeiro", uf: "RJ", lat: -22.986773, lon: -43.372194 },
  { code: "SDU", name: "Santos Dumont Airport", city: "Rio de Janeiro", uf: "RJ", lat: -22.910397, lon: -43.16282 },
  { code: "MVF", name: "Dix-Sept Rosado Airport", city: "Mossoró", uf: "RN", lat: -5.20192, lon: -37.3643 },
  { code: "NAT", name: "Rio Grande do Norte/São Gonçalo do Amarante–Governador Aluízio Alves International Airport", city: "Natal", uf: "RN", lat: -5.769822, lon: -35.36661 },
  { code: "OAL", name: "Cacoal Airport", city: "Cacoal", uf: "RO", lat: -11.496, lon: -61.4508 },
  { code: "JPR", name: "Ji-Paraná Airport", city: "Ji-Paraná", uf: "RO", lat: -10.870743, lon: -61.846675 },
  { code: "PVH", name: "Governador Jorge Teixeira de Oliveira International Airport", city: "Porto Velho", uf: "RO", lat: -8.708491, lon: -63.902338 },
  { code: "BVH", name: "Brigadeiro Camarão Airport", city: "Vilhena", uf: "RO", lat: -12.6944, lon: -60.098301 },
  { code: "BVB", name: "Atlas Brasil Cantanhede International Airport", city: "Boa Vista", uf: "RR", lat: 2.84615, lon: -60.690648 },
  { code: "CEL", name: "Canela Airport", city: "Canela", uf: "RS", lat: -29.370091, lon: -50.831729 },
  { code: "CXJ", name: "Hugo Cantergiani Regional Airport", city: "Caxias Do Sul", uf: "RS", lat: -29.197183, lon: -51.187647 },
  { code: "PFB", name: "Lauro Kurtz Airport", city: "Passo Fundo", uf: "RS", lat: -28.243976, lon: -52.32777 },
  { code: "PET", name: "João Simões Lopes Neto International Airport", city: "Pelotas", uf: "RS", lat: -31.717189, lon: -52.327796 },
  { code: "POA", name: "Porto Alegre-Salgado Filho International Airport", city: "Porto Alegre", uf: "RS", lat: -29.993984, lon: -51.167482 },
  { code: "RIA", name: "Santa Maria Airport", city: "Santa Maria", uf: "RS", lat: -29.711399, lon: -53.688202 },
  { code: "SRA", name: "Luis Alberto Lehr Airport", city: "Santa Rosa", uf: "RS", lat: -27.90658, lon: -54.520628 },
  { code: "GEL", name: "Santo Ângelo Airport", city: "Santo Ângelo", uf: "RS", lat: -28.282503, lon: -54.169623 },
  { code: "URG", name: "Rubem Berta Airport", city: "Uruguaiana", uf: "RS", lat: -29.7822, lon: -57.0382 },
  { code: "XAP", name: "Serafin Enoss Bertaso Airport", city: "Chapecó", uf: "SC", lat: -27.134199, lon: -52.656601 },
  { code: "FLN", name: "Hercílio Luz International Airport", city: "Florianópolis", uf: "SC", lat: -27.670279, lon: -48.552502 },
  { code: "JJG", name: "Humberto Ghizzo Bortoluzzi Regional Airport", city: "Jaguaruna", uf: "SC", lat: -28.6753, lon: -49.0596 },
  { code: "JOI", name: "Lauro Carneiro de Loyola Airport", city: "Joinville", uf: "SC", lat: -26.224501, lon: -48.797401 },
  { code: "LAJ", name: "Lages Airport", city: "Lages", uf: "SC", lat: -27.782101, lon: -50.281502 },
  { code: "NVT", name: "Ministro Victor Konder International Airport", city: "Navegantes", uf: "SC", lat: -26.879431, lon: -48.650979 },
  { code: "AJU", name: "Aracaju - Santa Maria Airport", city: "Aracaju", uf: "SE", lat: -10.98394, lon: -37.072873 },
  { code: "AQA", name: "Araraquara Airport", city: "Araraquara", uf: "SP", lat: -21.812, lon: -48.132999 },
  { code: "ARU", name: "Araçatuba Airport", city: "Araçatuba", uf: "SP", lat: -21.141479, lon: -50.424575 },
  { code: "JTC", name: "Bauru/Arealva–Moussa Nakhal Tobias State Airport", city: "Bauru", uf: "SP", lat: -22.160755, lon: -49.070325 },
  { code: "VCP", name: "Viracopos International Airport", city: "Campinas", uf: "SP", lat: -23.007404, lon: -47.134502 },
  { code: "MII", name: "Frank Miloye Milenkowichi–Marília State Airport", city: "Marília", uf: "SP", lat: -22.196899, lon: -49.926485 },
  { code: "PPB", name: "Presidente Prudente Airport", city: "Presidente Prudente", uf: "SP", lat: -22.1751, lon: -51.424599 },
  { code: "RAO", name: "Leite Lopes Airport", city: "Ribeirão Preto", uf: "SP", lat: -21.134314, lon: -47.774053 },
  { code: "SOD", name: "Sorocaba Airport", city: "Sorocaba", uf: "SP", lat: -23.478001, lon: -47.490002 },
  { code: "SJK", name: "Professor Urbano Ernesto Stumpf Airport", city: "São José Dos Campos", uf: "SP", lat: -23.2292, lon: -45.8615 },
  { code: "SJP", name: "Prof. Eribelto Manoel Reino State Airport", city: "São José do Rio Preto", uf: "SP", lat: -20.817113, lon: -49.406963 },
  { code: "CGH", name: "Congonhas–Deputado Freitas Nobre Airport", city: "São Paulo", uf: "SP", lat: -23.627657, lon: -46.654601 },
  { code: "GRU", name: "São Paulo/Guarulhos–Governor André Franco Montoro International Airport", city: "São Paulo", uf: "SP", lat: -23.431274, lon: -46.469954 },
  { code: "AUX", name: "Araguaína Airport", city: "Araguaína", uf: "TO", lat: -7.22787, lon: -48.240501 },
  { code: "PMW", name: "Brigadeiro Lysias Rodrigues Airport", city: "Palmas", uf: "TO", lat: -10.2915, lon: -48.356998 },
  // Europe & World hubs
  { code: "CDG", name: "Paris Charles de Gaulle" },
  { code: "ORY", name: "Paris Orly" },
  { code: "LHR", name: "London Heathrow" },
  { code: "LGW", name: "London Gatwick" },
  { code: "STN", name: "London Stansted" },
  { code: "LTN", name: "London Luton" },
  { code: "LCY", name: "London City" },
  { code: "FRA", name: "Frankfurt" },
  { code: "MUC", name: "Munich" },
  { code: "BER", name: "Berlin Brandenburg" },
  { code: "HAM", name: "Hamburg" },
  { code: "DUS", name: "Düsseldorf" },
  { code: "CGN", name: "Cologne Bonn" },
  { code: "STR", name: "Stuttgart" },
  { code: "AMS", name: "Amsterdam Schiphol" },
  { code: "BRU", name: "Brussels" },
  { code: "CRL", name: "Brussels Charleroi" },
  { code: "LUX", name: "Luxembourg" },
  { code: "ZRH", name: "Zurich" },
  { code: "GVA", name: "Geneva" },
  { code: "BSL", name: "Basel EuroAirport" },
  { code: "VIE", name: "Vienna" },
  { code: "PRG", name: "Prague" },
  { code: "WAW", name: "Warsaw Chopin" },
  { code: "KRK", name: "Kraków" },
  { code: "BUD", name: "Budapest" },
  { code: "OTP", name: "Bucharest Otopeni" },
  { code: "SOF", name: "Sofia" },
  { code: "ATH", name: "Athens" },
  { code: "SKG", name: "Thessaloniki" },
  { code: "IST", name: "Istanbul" },
  { code: "SAW", name: "Istanbul Sabiha Gökçen" },
  { code: "MAD", name: "Madrid Barajas" },
  { code: "BCN", name: "Barcelona El Prat" },
  { code: "AGP", name: "Málaga" },
  { code: "PMI", name: "Palma de Mallorca" },
  { code: "VLC", name: "Valencia" },
  { code: "SVQ", name: "Seville" },
  { code: "BIO", name: "Bilbao" },
  { code: "LIS", name: "Lisbon" },
  { code: "OPO", name: "Porto" },
  { code: "FAO", name: "Faro" },
  { code: "FNC", name: "Madeira Funchal" },
  { code: "DUB", name: "Dublin" },
  { code: "EDI", name: "Edinburgh" },
  { code: "MAN", name: "Manchester" },
  { code: "CPH", name: "Copenhagen" },
  { code: "ARN", name: "Stockholm Arlanda" },
  { code: "OSL", name: "Oslo" },
  { code: "HEL", name: "Helsinki" },
  { code: "KEF", name: "Reykjavík Keflavík" },
  { code: "RIX", name: "Riga" },
  { code: "TLL", name: "Tallinn" },
  { code: "VNO", name: "Vilnius" },
  { code: "LJU", name: "Ljubljana" },
  { code: "ZAG", name: "Zagreb" },
  { code: "BEG", name: "Belgrade" },
  { code: "TIA", name: "Tirana" },
  { code: "SJJ", name: "Sarajevo" },
  { code: "SKP", name: "Skopje" },
  { code: "JFK", name: "New York JFK" },
  { code: "EWR", name: "New York Newark" },
  { code: "LGA", name: "New York LaGuardia" },
  { code: "MIA", name: "Miami" },
  { code: "MCO", name: "Orlando" },
  { code: "ATL", name: "Atlanta" },
  { code: "ORD", name: "Chicago O'Hare" },
  { code: "LAX", name: "Los Angeles" },
  { code: "SFO", name: "San Francisco" },
  { code: "IAD", name: "Washington Dulles" },
  { code: "BOS", name: "Boston" },
  { code: "IAH", name: "Houston Intercontinental" },
  { code: "DFW", name: "Dallas Fort Worth" },
  { code: "YYZ", name: "Toronto Pearson" },
  { code: "YUL", name: "Montréal Trudeau" },
  { code: "MEX", name: "Mexico City" },
  { code: "PTY", name: "Panama City Tocumen" },
  { code: "BOG", name: "Bogotá" },
  { code: "LIM", name: "Lima" },
  { code: "SCL", name: "Santiago de Chile" },
  { code: "EZE", name: "Buenos Aires Ezeiza" },
  { code: "AEP", name: "Buenos Aires Aeroparque" },
  { code: "MVD", name: "Montevideo" },
  { code: "ASU", name: "Asunción" },
  { code: "UIO", name: "Quito" },
  { code: "GYE", name: "Guayaquil" },
  { code: "CCS", name: "Caracas" },
  { code: "DXB", name: "Dubai" },
  { code: "AUH", name: "Abu Dhabi" },
  { code: "DOH", name: "Doha" },
  { code: "TLV", name: "Tel Aviv" },
  { code: "CAI", name: "Cairo" },
  { code: "JNB", name: "Johannesburg" },
  { code: "CPT", name: "Cape Town" },
  { code: "ADD", name: "Addis Ababa" },
  { code: "NBO", name: "Nairobi" },
  { code: "CMN", name: "Casablanca" },
  { code: "ALG", name: "Algiers" },
  { code: "TUN", name: "Tunis" },
  { code: "LOS", name: "Lagos" },
  { code: "BKK", name: "Bangkok Suvarnabhumi" },
  { code: "SIN", name: "Singapore Changi" },
  { code: "HKG", name: "Hong Kong" },
  { code: "PEK", name: "Beijing Capital" },
  { code: "PKX", name: "Beijing Daxing" },
  { code: "PVG", name: "Shanghai Pudong" },
  { code: "SHA", name: "Shanghai Hongqiao" },
  { code: "CAN", name: "Guangzhou" },
  { code: "NRT", name: "Tokyo Narita" },
  { code: "HND", name: "Tokyo Haneda" },
  { code: "ICN", name: "Seoul Incheon" },
  { code: "TPE", name: "Taipei Taoyuan" },
  { code: "KUL", name: "Kuala Lumpur" },
  { code: "CGK", name: "Jakarta" },
  { code: "MNL", name: "Manila" },
  { code: "DEL", name: "Delhi" },
  { code: "BOM", name: "Mumbai" },
  { code: "SYD", name: "Sydney" },
  { code: "MEL", name: "Melbourne" },
  { code: "AKL", name: "Auckland" },
];
