export type Country = { code: string; name: string };

// Curated list of common nationalities (ISO 3166-1 alpha-2). Extend as needed.
export const COUNTRIES: Country[] = [
  { code: "IT", name: "Italia / Italy" },
  { code: "BR", name: "Brasil / Brazil" },
  { code: "PT", name: "Portugal" },
  { code: "ES", name: "España / Spain" },
  { code: "FR", name: "France" },
  { code: "DE", name: "Deutschland / Germany" },
  { code: "GB", name: "United Kingdom" },
  { code: "IE", name: "Ireland" },
  { code: "NL", name: "Nederland / Netherlands" },
  { code: "BE", name: "Belgique / Belgium" },
  { code: "LU", name: "Luxembourg" },
  { code: "CH", name: "Schweiz / Switzerland" },
  { code: "AT", name: "Österreich / Austria" },
  { code: "SE", name: "Sverige / Sweden" },
  { code: "NO", name: "Norge / Norway" },
  { code: "DK", name: "Danmark / Denmark" },
  { code: "FI", name: "Suomi / Finland" },
  { code: "IS", name: "Ísland / Iceland" },
  { code: "PL", name: "Polska / Poland" },
  { code: "CZ", name: "Česko / Czechia" },
  { code: "SK", name: "Slovensko / Slovakia" },
  { code: "HU", name: "Magyarország / Hungary" },
  { code: "RO", name: "România / Romania" },
  { code: "BG", name: "България / Bulgaria" },
  { code: "GR", name: "Ελλάδα / Greece" },
  { code: "HR", name: "Hrvatska / Croatia" },
  { code: "SI", name: "Slovenija / Slovenia" },
  { code: "EE", name: "Eesti / Estonia" },
  { code: "LV", name: "Latvija / Latvia" },
  { code: "LT", name: "Lietuva / Lithuania" },
  { code: "MT", name: "Malta" },
  { code: "CY", name: "Κύπρος / Cyprus" },
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "MX", name: "México / Mexico" },
  { code: "AR", name: "Argentina" },
  { code: "UY", name: "Uruguay" },
  { code: "PY", name: "Paraguay" },
  { code: "CL", name: "Chile" },
  { code: "PE", name: "Perú / Peru" },
  { code: "CO", name: "Colombia" },
  { code: "VE", name: "Venezuela" },
  { code: "EC", name: "Ecuador" },
  { code: "BO", name: "Bolivia" },
  { code: "CR", name: "Costa Rica" },
  { code: "PA", name: "Panamá / Panama" },
  { code: "CU", name: "Cuba" },
  { code: "DO", name: "República Dominicana / Dominican Republic" },
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "New Zealand" },
  { code: "JP", name: "日本 / Japan" },
  { code: "CN", name: "中国 / China" },
  { code: "KR", name: "대한민국 / South Korea" },
  { code: "IN", name: "India / भारत" },
  { code: "SG", name: "Singapore" },
  { code: "HK", name: "Hong Kong" },
  { code: "TW", name: "Taiwan" },
  { code: "TH", name: "Thailand" },
  { code: "PH", name: "Philippines" },
  { code: "ID", name: "Indonesia" },
  { code: "VN", name: "Việt Nam / Vietnam" },
  { code: "MY", name: "Malaysia" },
  { code: "AE", name: "الإمارات / UAE" },
  { code: "SA", name: "السعودية / Saudi Arabia" },
  { code: "QA", name: "قطر / Qatar" },
  { code: "IL", name: "ישראל / Israel" },
  { code: "TR", name: "Türkiye / Turkey" },
  { code: "RU", name: "Россия / Russia" },
  { code: "UA", name: "Україна / Ukraine" },
  { code: "ZA", name: "South Africa" },
  { code: "EG", name: "مصر / Egypt" },
  { code: "MA", name: "المغرب / Morocco" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "AO", name: "Angola" },
  { code: "MZ", name: "Moçambique / Mozambique" },
  { code: "CV", name: "Cabo Verde" },
  { code: "AL", name: "Shqipëria / Albania" },
  { code: "RS", name: "Србија / Serbia" },
  { code: "BA", name: "Bosna i Hercegovina" },
  { code: "MK", name: "Северна Македонија / North Macedonia" },
  { code: "MD", name: "Moldova" },
  { code: "GE", name: "საქართველო / Georgia" },
];