import { useEffect } from "react";
import { Mail } from "lucide-react";
import { useT } from "@/lib/i18n";
import { useCanonical } from "@/lib/useCanonical";
import { Nav, ContactForm } from "./AboutUs";

const EMAIL = "info@businessmatching.global";

type Block = { type: "h2" | "p" | "li"; text: string; italic?: boolean };

const blocksIt: Block[] = [
  { type: "p", text: "Che cosa deve attraversare l'Atlantico: il prodotto finito, i componenti, il metodo, il marchio, una licenza — o nulla?" },
  { type: "p", text: "È la domanda da cui partiamo, e quasi nessuno la fa prima di aver già deciso la risposta. In alcuni casi, invece di esportare direttamente, conviene produrre su licenza in loco." },

  { type: "h2", text: "Una friggitrice ad aria" },
  { type: "p", text: "Philips ha portato in Brasile la friggitrice ad aria e ne ha brevettato la tecnologia: il flusso d'aria calda, il fondo del cestello sagomato a stella. Ha creato la categoria dal nulla." },
  { type: "p", text: "In Brasile airfryer si dice di qualunque friggitrice senza olio, come fosse una parola del vocabolario. Nessuno la associa più a chi l'ha inventata. Un brevetto protegge una via per arrivare al risultato, non il risultato: e quando le vie sono molte, il vantaggio dura il tempo che serve a trovarne un'altra. Philips ha creato un mercato ed è finita a giocarci dentro come tutti gli altri." },
  { type: "p", text: "Non si tratta di un furto. È una storia di scelte sbagliate su cosa proteggere." },
  { type: "p", text: "Un brevetto non protegge un'idea né un risultato: protegge l'invenzione così come è rivendicata, descritta riga per riga nel testo depositato. Tutto ciò che sta fuori da quelle righe è terreno libero. Alcuni elementi, però, possono essere protetti anche senza brevetto — come segreto industriale, know-how o informazione riservata — a condizione che siano state adottate misure di protezione effettive." },

  { type: "h2", text: "Due mestieri diversi" },
  { type: "p", text: "Esportare un prodotto significa scommettere su dazi, cambio, logistica e tempi doganali: variabili che non controlli e che possono cambiare in un decreto." },
  { type: "p", text: "Trasferire il metodo — cioè autorizzare un'impresa locale a fabbricare con la tua tecnologia, in cambio di un compenso — significa scommettere su una cosa sola: la tua capacità di restare avanti." },
  { type: "p", text: "Licenza: contratto con cui un'impresa autorizza un'altra a fabbricare o usare la propria tecnologia in un territorio definito, per un tempo definito. Royalty: il compenso periodico, di solito una percentuale sul venduto. Entry fee: la somma pagata all'ingresso, prima che la produzione cominci." },
  { type: "p", text: "Per molte PMI europee il Brasile è il caso da manuale: dazi e costo logistico mettono il prodotto finito fuori mercato, mentre lo stesso prodotto fabbricato in loco sarebbe competitivo. Vale, identica, nella direzione opposta: un metodo brasiliano che in Europa non arriverebbe mai come merce." },

  { type: "h2", text: "Perché il Brasile e non l'America Latina" },
  { type: "p", text: "\"America Latina\" non è un mercato, è una categoria geografica. Chi la tratta come un blocco unico finisce per spendere in cinque Paesi quello che sarebbe bastato per entrare bene in uno." },
  { type: "p", text: "Le proporzioni, in valore assoluto. Il Brasile concentra da solo circa la metà del prodotto interno lordo sudamericano. Ma il dato che conta per chi vende non è la ricchezza media: è quante persone possono permettersi il vostro prodotto — e lì la disuguaglianza brasiliana, che di solito si cita come problema, diventa aritmetica a vostro favore. Anche con una stima prudente della fascia ad alta capacità di spesa si parla di decine di milioni di persone: una platea più numerosa dell'intera popolazione del Cile, e diverse volte quella di Paraguay e Uruguay messi insieme. La sola area metropolitana di San Paolo supera i venti milioni di abitanti. Un segmento di nicchia in Brasile è più grande di un mercato intero altrove — con una lingua sola, una moneta sola, un solo regime doganale." },
  { type: "p", text: "Il Brasile non è un mercato omogeneo: è un arcipelago di mercati. Ventisei stati più il Distretto Federale, ciascuno con la propria imposta sulla circolazione delle merci, le proprie aliquote e i propri regimi agevolati per chi importa o si insedia sul suo territorio. Ne discende una cosa che sorprende quasi tutti gli europei: far arrivare la stessa merce in un porto invece che in un altro, o insediarsi in uno stato invece che nel confinante, cambia il carico fiscale, a volte in misura decisiva per il margine. Gli stati competono tra loro per attirare importazioni e stabilimenti, e questa competizione è ancora aperta — per ora. La riforma tributaria sostituisce progressivamente le imposte statali con un'imposta unica sul consumo, spostando il gettito verso lo stato di destinazione: la transizione si completa nei primi anni Trenta, e con essa la convenienza a scegliere l'ingresso in funzione fiscale è destinata a ridursi. Chi struttura la propria presenza mentre la finestra è aperta consolida un vantaggio; chi arriva dopo troverà un campo più piatto." },
  { type: "p", text: "E la scelta non è mai solo fiscale. Il Paese è grande quanto un continente e la logistica interna costa: sdoganare dove conviene fiscalmente ma a duemila chilometri dal proprio mercato di riferimento significa restituire in trasporto quello che si era risparmiato in imposte, con l'aggiunta di tempi e rischi. Lo stesso vale per il luogo di produzione. La decisione giusta è il punto di equilibrio tra i due conti, e si calcola caso per caso: dove sono i vostri clienti, quanto pesa il prodotto rispetto al suo valore, quale stato ha oggi il regime più favorevole per la vostra categoria merceologica." },
  { type: "p", text: "La difficoltà è il motivo per andarci, non per evitarlo. Dazi, complessità tributaria, certificazioni obbligatorie, logistica interna costosa: tutto vero. Ma una barriera funziona in entrambe le direzioni. Dove entrare è facile ci sono già tutti, e l'essere arrivati non vale niente. In Brasile la stessa difficoltà che oggi vi tiene fuori, domani tiene fuori chi verrebbe dopo di voi." },
  { type: "p", text: "È l'unico mercato della regione dove il trasferimento di metodo ha senso pieno, perché serve una base industriale capace di fabbricare su licenza. Il Messico ne ha una, ma è costruita attorno agli Stati Uniti: si produce lì per riesportare a nord, non per servire il mercato interno. È una logica diversa, e confonderle significa sbagliare progetto." },
  { type: "p", text: "Gli altri Paesi contano come base, non come mercato. Paraguay, Uruguay e Argentina offrono regimi di maquila, zone franche, costi industriali più bassi — e stanno dentro il Mercosur, quindi la merce prodotta lì può raggiungere il Brasile senza dazio esterno comune, rispettando le regole di origine e i relativi adempimenti documentali, salve le eccezioni previste. Non cinque mercati invece di uno: una base di costo che serve l'unico mercato che conta." },
  { type: "p", text: "Le regole cambiano mentre state decidendo. Un mercato non è solo domanda e concorrenza: è un insieme di regole, e in Brasile cambiano più spesso che in Europa. Un esempio in corso, aggiornato ad agosto 2026: la riforma tributaria ha istituito l'Imposto Seletivo — quello che i brasiliani chiamano imposto do pecado — rinviando a una legge successiva la definizione delle aliquote. Entra in vigore il 1° gennaio 2027 secondo la legge complementare già approvata e, per il principio dei novanta giorni, il testo sulle aliquote dovrebbe essere pubblicato entro l'inizio di ottobre 2026 — termine così stretto che si discute di fissarle con decreto d'urgenza anziché con legge ordinaria. Riguarda categorie precise — tabacco, bevande alcoliche, bevande zuccherate, veicoli, minerali estratti, scommesse — e se il vostro prodotto non è in quella lista non vi tocca. Ma domani sarà un'altra norma: una certificazione che diventa obbligatoria, una regola di etichettatura, un incentivo statale che apre o si chiude. Quasi tutte si vedono arrivare con mesi di anticipo, a condizione che qualcuno stia guardando dal lato giusto del corridoio. Chi è già dentro ha il tempo di adattarsi, e spesso ci guadagna: il costo di adeguarsi è uguale per tutti, ma pesa molto di più su chi deve ancora entrare." },
  { type: "p", text: "Le certificazioni sono un fossato, non solo un costo. Registrazioni INMETRO, ANVISA, MAPA o ANATEL a seconda del prodotto: mesi di lavoro e spese certe. È la ragione per cui molti rinunciano, ed è esattamente perché vale la pena farlo — una volta ottenute, obbligano ogni concorrente futuro allo stesso percorso mentre voi siete già a scaffale. Con un'avvertenza che è la chiave di volta applicata a questo caso: evitate che il distributore controlli in esclusiva registrazioni, autorizzazioni o dossier regolatori indispensabili alla continuità dell'operazione. La titolarità diretta da parte dell'impresa straniera non è sempre possibile — dipende dal prodotto, dall'autorità competente e da chi risponde legalmente di fabbricazione, importazione e distribuzione. Dove non lo è, vanno disciplinati per contratto l'accesso ai documenti, il diritto di trasferimento, la collaborazione alla migrazione e le conseguenze della cessazione. Chi detiene il registro detiene l'accesso al mercato, e cambiare distributore deve restare una vostra decisione invece che una trattativa." },
  { type: "p", text: "Quando la risposta non è il Brasile, e lo diciamo volentieri: volumi piccoli destinati a restare tali; prodotti di servizio o digitali, dove Cile e Uruguay sono molto più semplici; obiettivo di rifornire il mercato nordamericano, dove il Messico vince senza discussione." },

  { type: "h2", text: "La domanda che viene prima del contratto" },
  { type: "p", text: "Il metodo sta dentro l'oggetto o dentro le persone?" },
  { type: "p", text: "Se sta dentro l'oggetto — un elettrodomestico, uno stampo, una formulazione semplice — qualunque partner serio lo smonta e lo ricostruisce in pochi mesi. In quel caso la licenza non protegge: quello che stai vendendo è tempo di mercato e marchio. E allora il denaro va preso davanti: entry fee alto, royalty modeste, durata corta." },
  { type: "p", text: "Se sta dentro le persone e dentro una relazione continua — agronomia, controllo qualità, protocolli di processo, taratura, formazione tecnica — il trasferimento regge. Regge perché ogni anno esiste una versione nuova che il licenziatario, da solo, non saprebbe produrre." },

  { type: "h2", text: "Un frigorifero a querosene" },
  { type: "p", text: "Nel 1947, in un'officina di Brusque, in Santa Catarina, arrivò da riparare un frigorifero importato che funzionava a querosene. In Brasile, all'epoca, i frigoriferi erano solo d'importazione e stavano nelle case dei molto ricchi. I due meccanici lo smontarono pezzo per pezzo, studiarono ogni componente e decisero di costruirne uno proprio. Ne fabbricarono trentuno in quel capannone; nel 1950 l'officina diventò fabbrica a Joinville e prese il nome Consul. Il primo modello raffreddava per assorbimento, alimentato a querosene — la tecnologia adatta a un Paese dove la rete elettrica non arrivava ancora nella maggior parte delle case. Da lì sono nati un'industria nazionale dei compressori, la fusione con Brastemp e infine uno dei maggiori poli mondiali della refrigerazione." },
  { type: "p", text: "È il rovescio esatto della friggitrice. Là il produttore c'era e ha protetto la cosa sbagliata; qui non c'era affatto: vendeva un apparecchio importato, caro, progettato per un altro Paese. Nessuno lo ha copiato per malizia. È stato ricostruito perché nessuno stava rispondendo al problema vero, che non era fare freddo, ma fare freddo dove non c'è corrente." },
  { type: "p", text: "Da cui la regola: l'adattamento locale avviene comunque. L'unica variabile è se avviene con te o senza di te. Chi arriva con un catalogo tradotto e un listino in euro lascia ad altri il lavoro di adattamento — e quegli altri, dopo, non hanno più bisogno di lui." },

  { type: "h2", text: "La chiave di volta" },
  { type: "p", text: "Nell'arco, la chiave di volta è la pietra centrale: toglila e crolla tutto, per quanto perfette siano le altre pietre." },
  { type: "p", text: "In una licenza è il pezzo che non consegni. Non un pezzo qualsiasi tenuto per sé, ma quello la cui assenza ferma la produzione o ne peggiora il risultato in modo che il cliente finale se ne accorga. La semente esclusiva dietro un metodo agronomico trasferito per intero. Il ceppo di fermento dietro un processo caseario insegnato tutto. I parametri di taratura, il software di controllo, la certificazione, il marchio." },
  { type: "p", text: "Si riconosce da tre condizioni, che devono valere insieme:" },
  { type: "li", text: "Se manca, il prodotto non esce, o esce peggio in modo percepibile." },
  { type: "li", text: "Non è replicabile in loco a costo ragionevole. Se il licenziatario se la costruisce in casa con due tecnici e sei mesi, non è una chiave di volta: è un ritardo." },
  { type: "li", text: "Te la può comprare a un prezzo equo. È la condizione che quasi tutti sbagliano. Se la fai pagare troppo, sei tu a finanziare la ricerca del sostituto. La chiave di volta si difende restando conveniente, non stringendo." },
  { type: "p", text: "E ha sempre un tempo di dimezzamento. Non esiste quella definitiva: esiste quella che ti compra gli anni necessari a costruire la successiva." },
  { type: "p", text: "C'è anche una ragione fiscale, recente, per tenere il metodo vivo: le nuove regole brasiliane sui prezzi di trasferimento riconoscono il diritto alla royalty solo a chi dimostra di sviluppare, mantenere e proteggere attivamente ciò che ha dato in licenza. Chi trasferisce tutto e smette di innovare non perde solo il potere negoziale — mette a rischio la deducibilità del compenso dall'altra parte del tavolo." },

  { type: "h2", text: "Le formalità che in Brasile non si saltano" },
  { type: "p", text: "La protezione industriale è territoriale. Un brevetto o un marchio europeo, in Brasile, semplicemente non esistono. Vanno depositati all'INPI brasiliano, e il marchio va depositato prima di aprire le conversazioni: il rischio più frequente non è la copia del prodotto, è il partner che registra il marchio a proprio nome." },
  { type: "p", text: "L'averbação o registro all'INPI va valutata in funzione del contratto e degli effetti che volete ottenere. Fino a pochi anni fa era il passaggio obbligato per rimettere royalty all'estero e per dedurle: la riforma valutaria del 2021 e le regole sui prezzi di trasferimento del 2023 hanno cambiato il quadro, e oggi la rimessa dipende essenzialmente dalla prova del pagamento dell'imposta dovuta. Resta però rilevante per la certezza giuridica e, in determinate ipotesi, per produrre effetti verso terzi. È esattamente il tipo di punto su cui la risposta giusta dipende dalla struttura concreta, e va verificata con i professionisti incaricati. In particolare la deducibilità fiscale delle royalty e dei pagamenti per tecnologia, dopo le modifiche legislative del 2021 e del 2023, richiede un'analisi specifica del contratto, della natura del pagamento e del regime tributario applicabile: la posizione non è uniforme in tutti i casi." },
  { type: "p", text: "I pagamenti transfrontalieri hanno un costo fiscale proprio: ritenute alla fonte, CIDE sulle rimesse e altri effetti che variano secondo la natura del contratto, le parti coinvolte e la struttura del compenso. Vanno messi nel conto economico prima di negoziare la percentuale, non dopo." },
  { type: "p", text: "Nel testo: perimetro d'uso e territorio delimitati, minimi garantiti, diritto di verifica sui numeri di vendita, proprietà dei miglioramenti sviluppati in loco, riservatezza e divieto d'uso del know-how che sopravvivono alla fine del contratto, penale. E l'arbitrato, che nei contratti internazionali offre di norma maggiore prevedibilità procedurale del contenzioso ordinario — ma sede, istituzione, lingua, legge applicabile, misure d'urgenza e strategia di esecuzione vanno scelti caso per caso: un lodo pronunciato all'estero, per essere eseguito in Brasile, passa dall'omologazione del Superior Tribunal de Justiça." },

  { type: "h2", text: "Perché lo sentite dire di rado" },
  { type: "p", text: "Non è un segreto tecnico. Il licensing è materia da manuale, e le grandi imprese lo praticano da sempre. Quello che manca è chi lo porti alla piccola e media impresa: l'ecosistema costruito attorno a lei — camere di commercio, bandi, voucher, fiere, contributi all'internazionalizzazione — è nato per far uscire merce e misura il proprio risultato in merce uscita. Nessuno di quei soggetti ha un motivo per dire all'imprenditore che forse il suo prodotto non deve entrare come prodotto." },
  { type: "p", text: "E vale anche il rovescio, che diciamo volentieri: il trasferimento di metodo non è sempre la risposta giusta. Ne servono tre insieme — una controparte industriale che esista davvero e sappia fabbricare; un volume che giustifichi la produzione locale; un metodo abbastanza vivo da alimentare il rapporto anno dopo anno. Su una nicchia da poche centinaia di pezzi l'anno la licenza non ha senso e l'esportazione sì. Quando è così, lo diciamo prima, non dopo." },

  { type: "h2", text: "Tre obiezioni, dette apertamente" },
  { type: "p", text: "\"Serve qualcuno che stia in azienda e conosca il prodotto.\" Vero — e quel qualcuno non siamo noi. Ma il vostro prodotto lo conoscete già voi meglio di chiunque altro: l'informazione che vi manca non è nel vostro capannone, è dall'altra parte del corridoio. Le due presenze non competono, si sommano." },
  { type: "p", text: "\"Un metodo collaudato funziona su qualsiasi mercato.\" Un metodo di lavoro sì, la conoscenza di un mercato no. Chi copre trenta Paesi con la stessa procedura vi restituirà una procedura ordinata, costruita su dati che potreste acquistare da soli. Noi copriamo un corridoio solo, e ci viviamo dentro. La domanda da fare a chiunque si proponga — noi compresi: quante volte è stato fisicamente in quel mercato negli ultimi dodici mesi, in che lingua parla con le controparti, di quali associazioni locali è socio." },
  { type: "p", text: "\"Ci serve chi porta trattative, non analisi.\" Legittimo. Ma chi viene remunerato per far accadere l'export difficilmente concluderà che quel mercato non fa per voi. Noi possiamo, e a volte succede. Il primo lavoro che consegniamo è un verdetto — procedere, approfondire, lasciar perdere — e costa poche centinaia di euro proprio perché serve a farvi risparmiare le decine di migliaia che verrebbero dopo." },

  { type: "h2", text: "Come lavoriamo" },
  { type: "p", text: "Lavoriamo tra l'Europa e il Brasile e comprendiamo sia le esigenze di imprese, professionisti e clienti europei e internazionali, sia la complessa realtà normativa, amministrativa, fiscale e culturale del mercato brasiliano. La nostra competenza nasce da un percorso internazionale che unisce diritto, commercio internazionale, europrogettazione, attività imprenditoriale e conoscenza pratica dei mercati europei e brasiliani." },
  { type: "p", text: "Il nostro obiettivo è aiutarvi a comprendere meglio il contesto in cui volete operare, riducendo l'impatto del cosiddetto Custo Brasil: burocrazia, complessità regolatoria, asimmetrie informative, difficoltà interpretative e rischi operativi che possono rallentare o complicare le decisioni. Il nostro lavoro è indipendente, riservato e orientato a fornire informazioni affidabili, selezionate e realmente utili per decidere in modo informato. Niente rumore, niente riempitivi: solo le risposte che servono, nei tempi giusti." },
  { type: "p", text: "Non ci limitiamo a dire che serve un avvocato. Componiamo e coordiniamo il team — studio legale in Brasile e in Europa, consulente di proprietà industriale, fiscalista, perito tecnico dove occorre — e teniamo insieme l'architettura dell'operazione dal primo giorno all'ultima firma." },
  { type: "p", text: "È la differenza che conta davvero: chi ha in mente l'architettura completa sa cosa chiedere, a chi e in che ordine. Un parere legale eccellente su una domanda mal posta costa uguale e non protegge da nulla." },
  { type: "p", text: "In concreto:" },
  { type: "li", text: "disegniamo l'architettura dell'operazione — cosa si trasferisce, in quante fasi, cosa resta fuori e perché;" },
  { type: "li", text: "verifichiamo la controparte prima che il tavolo si apra: assetto societario, storia, contenziosi, capacità industriale reale, e cosa sa già fare da sola;" },
  { type: "li", text: "individuiamo la chiave di volta credibile nel caso specifico, e per quanti anni può reggere;" },
  { type: "li", text: "traduciamo la strategia in istruzioni precise per i professionisti incaricati, e rileggiamo il loro lavoro rispetto all'obiettivo commerciale, non solo rispetto alla norma;" },
  { type: "li", text: "teniamo il ritmo tra fusi orari, lingue, uffici e autorità diverse." },
  { type: "p", text: "Ogni passaggio ha un esito dichiarato, un tempo di consegna e un documento che resta in mano vostra: il primo è un verdetto — procedere, approfondire, lasciar perdere — con le ragioni scritte. Nessuna fase successiva parte prima che la precedente sia stata consegnata e discussa." },
  { type: "p", text: "Cosa significa selezionare. In Brasile esercitano circa 1,3 milioni di avvocati: uno ogni 164 abitanti, la proporzione più alta al mondo. Non è un problema di qualità, è un problema di scelta — e vale allo stesso modo per commercialisti, fiscalisti, agenti di proprietà industriale e periti tecnici. L'iscrizione all'albo dice che il professionista può esercitare; non dice che abbia mai visto un contratto di trasferimento di tecnologia, un'averbação all'INPI o una controparte europea dall'altro lato del tavolo. Noi selezioniamo sulla competenza dimostrata nella materia specifica — operazioni concluse, casi seguiti, capacità di lavorare tra due lingue e due ordinamenti — non sul requisito formale. Chi non conosce il Paese quel filtro non può applicarlo, perché non sa nemmeno quali domande fare." },
  { type: "p", text: "E se avete già un export manager? Tanto meglio: non prendiamo il suo posto, siamo la sua controparte dall'altra parte del corridoio. Parliamo la stessa lingua — obiettivi commerciali, margini, tempi di consegna — ma il mercato lo conosciamo da dentro: chi c'è davvero, come si fabbrica in loco, cosa chiedono le autorità, quale distributore ha smesso di pagare i fornitori l'anno scorso." },
  { type: "p", text: "Il nostro lavoro è mettergli in mano dati e valutazioni aggiornate e indipendenti. Indipendenti in senso concreto: sui servizi di analisi il compenso è fisso e non dipende dall'esito, quindi non abbiamo alcun motivo per restituire un quadro più incoraggiante di quello che è. Dove offriamo anche rappresentanza commerciale, con una componente variabile sul venduto, si tratta di un incarico distinto: non lo abbiniamo all'analisi sulla stessa operazione, e se le due cose si incontrano lo diciamo prima. Chi si occupa di export lavora meglio quando le informazioni su cui decide sono verificate e recenti — e peggio quando sono di seconda mano o di due anni fa." },
  { type: "p", text: "Di solito è un investimento piccolo rispetto a ciò che protegge: una verifica fatta in tempo costa una frazione di un container fermo in dogana, di un distributore scelto male o di un marchio registrato da qualcun altro." },
  { type: "p", text: "Non pubblichiamo nomi di clienti né casi riconoscibili. Chi ci chiede di verificare le proprie controparti si aspetta la stessa discrezione, e la ottiene." },
  { type: "p", text: "Trattiamo ogni conversazione come coperta da riservatezza dal primo messaggio, che esista o meno un documento firmato. Se preferite formalizzarlo, l'accordo bilaterale è pronto e lo firmiamo prima di entrare nel merito." },
  { type: "p", text: "I pareri legali e fiscali sono resi da professionisti abilitati nei rispettivi ordinamenti, selezionati da noi per il caso specifico e abituati a lavorare tra Brasile ed Europa; rispondono direttamente al cliente. Noi teniamo insieme il disegno." },
];

const blocksEn: Block[] = [
  { type: "p", text: "What should cross the Atlantic: the finished product, the components, the method, the brand, a licence — or nothing?" },
  { type: "p", text: "This is the question we start with, and almost nobody asks it before the answer has already been decided. In some cases, instead of exporting directly, it pays to manufacture under licence locally." },

  { type: "h2", text: "An air fryer" },
  { type: "p", text: "Philips brought the air fryer to Brazil and patented the technology behind it: the hot-air flow, the star-shaped basket floor. It created the category from scratch." },
  { type: "p", text: "In Brazil, airfryer now means any oil-free fryer, as if it were a word in the dictionary. Nobody associates it with its inventor anymore. A patent protects one route to a result, not the result itself — and when there are many routes, the advantage lasts only as long as it takes to find another one. Philips created a market and ended up playing in it like everyone else." },
  { type: "p", text: "This is not a story about theft. It is a story about choosing the wrong thing to protect." },
  { type: "p", text: "A patent does not protect an idea or a result: it protects the invention as claimed, described line by line in the filed text. Everything outside those lines is open ground. Some elements, however, can be protected even without a patent — as trade secrets, know-how or confidential information — provided effective protective measures are in place." },

  { type: "h2", text: "Two different businesses" },
  { type: "p", text: "Exporting a product means betting on tariffs, exchange rates, logistics and customs times: variables you do not control, and that can change with a single decree." },
  { type: "p", text: "Transferring the method — authorising a local company to manufacture using your technology, for a fee — means betting on one thing only: your ability to stay ahead." },
  { type: "p", text: "Licence: a contract in which one company authorises another to manufacture or use its technology in a defined territory, for a defined period. Royalty: the recurring fee, usually a percentage of sales. Entry fee: the amount paid up front, before production begins." },
  { type: "p", text: "For many European SMEs, Brazil is the textbook case: tariffs and logistics costs price the finished product out of the market, while the same product made locally would be competitive. And it holds identically in reverse: a Brazilian method that would never reach Europe as goods." },

  { type: "h2", text: "Why Brazil, and not \"Latin America\"" },
  { type: "p", text: "\"Latin America\" is not a market; it is a geographic category. Whoever treats it as a single bloc ends up spending across five countries what would have been enough to enter one properly." },
  { type: "p", text: "The proportions, in absolute terms. Brazil alone accounts for roughly half of South America's gross domestic product. But the figure that matters to a seller is not average wealth: it is how many people can afford your product — and there, Brazilian inequality, usually cited as a problem, becomes arithmetic in your favour. Even on a conservative estimate, the high-spending segment runs to tens of millions of people: more than the entire population of Chile, and several times that of Paraguay and Uruguay combined. The São Paulo metropolitan area alone exceeds twenty million inhabitants. A niche segment in Brazil is bigger than a whole market elsewhere — with one language, one currency, one customs regime." },
  { type: "p", text: "Brazil is not a homogeneous market: it is an archipelago of markets. Twenty-six states plus the Federal District, each with its own tax on the circulation of goods, its own rates and its own preferential regimes for those who import or set up on its territory. The consequence surprises almost every European: landing the same goods in one port rather than another, or setting up in one state rather than the neighbouring one, changes the tax burden — sometimes decisively for the margin. The states compete with one another to attract imports and plants, and that competition is still open — for now. Brazil's tax reform progressively replaces the state taxes with a single consumption tax, shifting revenue to the state of destination: the transition completes in the early 2030s, and with it the case for choosing your point of entry on tax grounds is set to shrink. Whoever structures their presence while the window is open locks in an advantage; whoever arrives later will find a flatter field." },
  { type: "p", text: "And the choice is never purely fiscal. The country is the size of a continent and internal logistics are expensive: clearing customs where it is fiscally convenient but two thousand kilometres from your target market means handing back in transport what you saved in taxes, with added time and risk. The same goes for where you produce. The right decision is the balance point between the two calculations, worked out case by case: where your customers are, how much the product weighs relative to its value, and which state currently has the most favourable regime for your product category." },
  { type: "p", text: "The difficulty is the reason to go, not to stay away. Tariffs, tax complexity, mandatory certifications, costly internal logistics: all true. But a barrier works in both directions. Where entry is easy, everyone is already there, and having arrived is worth nothing. In Brazil, the same difficulty that keeps you out today keeps out tomorrow whoever would come after you." },
  { type: "p", text: "It is the only market in the region where transferring the method makes full sense, because it takes an industrial base capable of manufacturing under licence. Mexico has one, but it is built around the United States: you produce there to re-export north, not to serve the domestic market. It is a different logic, and confusing the two means designing the wrong project." },
  { type: "p", text: "The other countries count as a base, not as a market. Paraguay, Uruguay and Argentina offer maquila regimes, free zones and lower industrial costs — and they sit inside Mercosur, so goods produced there can reach Brazil without the common external tariff, in compliance with the rules of origin and the related documentation, subject to the exceptions provided. Not five markets instead of one: a cost base serving the only market that counts." },
  { type: "p", text: "The rules change while you are still deciding. A market is not just demand and competition: it is a set of rules, and in Brazil they change more often than in Europe. A live example, current as of August 2026: the tax reform created the Imposto Seletivo — what Brazilians call the imposto do pecado, the \"sin tax\" — while deferring the rates to a later law. Under the complementary law already approved it takes effect on 1 January 2027 and, under the ninety-day rule, the text setting the rates should be published by early October 2026 — a deadline so tight that setting them by emergency decree rather than ordinary law is under discussion. It covers specific categories — tobacco, alcoholic drinks, sugary drinks, vehicles, extracted minerals, betting — and if your product is not on that list, it does not touch you. But tomorrow it will be another rule: a certification that becomes mandatory, a labelling requirement, a state incentive that opens or closes. Almost all of them can be seen coming months in advance — provided someone is watching from the right side of the corridor. Whoever is already inside has time to adapt, and often gains from it: the cost of compliance is the same for everyone, but weighs far more on those still outside." },
  { type: "p", text: "Certifications are a moat, not just a cost. INMETRO, ANVISA, MAPA or ANATEL registrations, depending on the product: months of work and certain expense. That is why many give up — and exactly why it is worth doing: once obtained, they force every future competitor down the same path while you are already on the shelf. With one caveat, which is the keystone applied to this case: do not let the distributor hold exclusive control over registrations, authorisations or regulatory dossiers essential to the continuity of the operation. Direct ownership by the foreign company is not always possible — it depends on the product, the competent authority and who is legally responsible for manufacturing, importing and distributing. Where it is not, the contract must govern access to the documents, the right of transfer, cooperation in migrating them and the consequences of termination. Whoever holds the registration holds access to the market — and replacing a distributor should remain your decision, not a negotiation." },
  { type: "p", text: "When the answer is not Brazil — and we say so gladly: small volumes destined to stay small; service or digital products, where Chile and Uruguay are far simpler; supplying the North American market, where Mexico wins without discussion." },

  { type: "h2", text: "The question that comes before the contract" },
  { type: "p", text: "Does the method live inside the object, or inside people?" },
  { type: "p", text: "If it lives inside the object — an appliance, a mould, a simple formulation — any serious partner will take it apart and rebuild it within months. There, the licence protects nothing: what you are selling is time-to-market and a brand. So take the money up front: high entry fee, modest royalties, short term." },
  { type: "p", text: "If it lives inside people and inside a continuing relationship — agronomy, quality control, process protocols, calibration, technical training — the transfer holds. It holds because every year there is a new version the licensee could not produce alone." },

  { type: "h2", text: "A kerosene refrigerator" },
  { type: "p", text: "In 1947, an imported kerosene-powered refrigerator was brought in for repair to a workshop in Brusque, Santa Catarina. At the time, refrigerators in Brazil were imported goods found only in very wealthy homes. The two mechanics took it apart piece by piece, studied every component and decided to build one of their own. They made thirty-one of them in that shed; in 1950 the workshop became a factory in Joinville and took the name Consul. The first model cooled by absorption, running on kerosene — the right technology for a country where the electricity grid still did not reach most houses. Out of that came a domestic compressor industry, a merger with Brastemp, and eventually one of the world's leading refrigeration hubs." },
  { type: "p", text: "It is the exact reverse of the air fryer. There, the manufacturer was present and protected the wrong thing; here it was not present at all — it sold an imported, expensive appliance designed for another country. Nobody copied it out of bad faith. It was rebuilt because nobody was answering the real problem, which was not making things cold, but making things cold where there is no power." },
  { type: "p", text: "Hence the rule: local adaptation happens either way. The only variable is whether it happens with you or without you. A company that arrives with a translated catalogue and a euro price list leaves the adaptation work to someone else — and that someone else, afterwards, no longer needs it." },

  { type: "h2", text: "The keystone" },
  { type: "p", text: "In an arch, the keystone is the central stone: remove it and everything collapses, however perfect the other stones are." },
  { type: "p", text: "In a licence, it is the piece you do not hand over. Not just any piece held back, but the one whose absence stops production or degrades the result in a way the end customer notices. The proprietary seed behind an agronomic method transferred in full. The starter culture behind a dairy process taught in full. Calibration parameters, control software, certification, the brand." },
  { type: "p", text: "Three conditions identify it, and all three must hold:" },
  { type: "li", text: "Without it, the product does not come out — or comes out visibly worse." },
  { type: "li", text: "It cannot be replicated locally at reasonable cost. If the licensee can build it in-house with two engineers and six months, it is not a keystone: it is a delay." },
  { type: "li", text: "They can buy it from you at a fair price. This is the condition almost everyone gets wrong. Overprice it and you are funding the search for a substitute yourself. A keystone is defended by staying convenient, not by squeezing." },
  { type: "p", text: "And every keystone has a half-life. There is no permanent one — only the one that buys you the years you need to build the next." },
  { type: "p", text: "There is also a recent, tax-driven reason to keep the method alive: Brazil's new transfer pricing rules recognise the right to a royalty only where the licensor can show it actively develops, maintains and protects what it has licensed. Whoever transfers everything and stops innovating does not just lose bargaining power — they put at risk the deductibility of the fee on the other side of the table." },

  { type: "h2", text: "The formalities Brazil does not let you skip" },
  { type: "p", text: "Industrial property protection is territorial. A European patent or trademark simply does not exist in Brazil: it has to be filed with the Brazilian INPI, and the trademark should be filed before conversations begin. The most common loss is not a copied product — it is a partner registering your brand in their own name." },
  { type: "p", text: "Recordal with INPI should be assessed against the contract and the effects you want. Until a few years ago it was the mandatory step for remitting royalties abroad and deducting them; the 2021 foreign exchange reform and the 2023 transfer pricing rules changed the landscape, and today remittance essentially depends on proof of payment of the tax due. It remains relevant for legal certainty and, in certain cases, for effects against third parties. This is exactly the kind of point where the right answer depends on the specific structure and must be verified with the professionals engaged. In particular, the tax deductibility of royalties and technology payments after the 2021 and 2023 legislative changes requires a specific analysis of the contract, the nature of the payment and the applicable tax regime: the position is not uniform across all cases." },
  { type: "p", text: "Cross-border payments carry their own tax cost: withholding taxes, the CIDE levy on remittances and other effects that vary with the nature of the contract, the parties involved and the structure of the fee. They belong in the business case before the percentage is negotiated, not after." },
  { type: "p", text: "In the text: defined field of use and territory, guaranteed minimums, audit rights over sales figures, ownership of improvements developed locally, confidentiality and a know-how non-use obligation surviving termination, liquidated damages. And arbitration, which in international contracts generally offers more procedural predictability than ordinary litigation — but seat, institution, language, applicable law, urgent measures and enforcement strategy must be chosen case by case: an award rendered abroad, to be enforced in Brazil, goes through recognition by the Superior Tribunal de Justiça." },

  { type: "h2", text: "Why you rarely hear this" },
  { type: "p", text: "It is not a technical secret. Licensing is textbook material, and large companies have practised it for decades. What is missing is anyone bringing it to the small and medium company: the ecosystem built around it — chambers of commerce, public funding calls, vouchers, trade fairs, internationalisation grants — was created to move goods out, and measures its own success in goods moved out. None of those actors has a reason to tell an entrepreneur that perhaps the product should not enter as a product at all." },
  { type: "p", text: "And the reverse holds too, and we say it gladly: transferring the method is not always the right answer. Three things must hold at once — a counterparty that genuinely exists and knows how to manufacture; a volume that justifies local production; a method alive enough to feed the relationship year after year. In a niche of a few hundred units a year, licensing makes no sense and exporting does. When that is the case, we say so beforehand, not afterwards." },

  { type: "h2", text: "Three objections, stated plainly" },
  { type: "p", text: "\"We need someone inside the company who knows the product.\" True — and that someone is not us. But you already know your product better than anyone: the information you are missing is not in your plant, it is on the other side of the corridor. The two presences do not compete; they add up." },
  { type: "p", text: "\"A proven method works in any market.\" A working method, yes; knowledge of a market, no. Anyone covering thirty countries with the same procedure will hand you a tidy procedure built on data you could buy yourself. We cover one corridor, and we live inside it. The question worth asking of anyone who offers — including us: how many times have you physically been in that market in the last twelve months, in which language do you speak with counterparties, which local associations are you a member of." },
  { type: "p", text: "\"We need someone who brings deals, not analysis.\" Fair. But whoever is paid to make exports happen will rarely conclude that the market is wrong for you. We can, and sometimes we do. The first thing we deliver is a verdict — proceed, investigate further, drop it — and it costs a few hundred euros precisely to save you the tens of thousands that would follow." },

  { type: "h2", text: "How we work" },
  { type: "p", text: "We work between Europe and Brazil, and we understand both the needs of European and international companies, professionals and clients, and the complex regulatory, administrative, tax and cultural reality of the Brazilian market. Our expertise comes from an international path combining law, international trade, EU project management, entrepreneurship and practical knowledge of both markets." },
  { type: "p", text: "Our goal is to help you understand the context you want to operate in, reducing the impact of the so-called Custo Brasil: bureaucracy, regulatory complexity, information asymmetries, interpretive difficulties and operational risks that slow down or complicate decisions. Our work is independent, confidential and aimed at giving you reliable, curated, genuinely useful information for informed decisions. No noise, no filler: just the answers you need, when you need them." },
  { type: "p", text: "We do not simply tell you that you need a lawyer. We assemble and coordinate the team — law firms in Brazil and in Europe, an industrial property agent, a tax adviser, technical experts where required — and we hold the architecture of the deal together from the first day to the final signature." },
  { type: "p", text: "That is the difference that counts: whoever holds the full architecture knows what to ask, of whom, and in what order. An excellent legal opinion on a badly framed question costs the same and protects you from nothing." },
  { type: "p", text: "In practice:" },
  { type: "li", text: "we design the architecture of the deal — what is transferred, in how many stages, what stays out and why;" },
  { type: "li", text: "we vet the counterparty before the table opens: ownership structure, track record, litigation, real industrial capacity, and what they can already do alone;" },
  { type: "li", text: "we identify the credible keystone in your specific case, and how many years it can hold;" },
  { type: "li", text: "we translate strategy into precise instructions for the professionals engaged, and review their work against the commercial objective, not only against the statute;" },
  { type: "li", text: "we keep the pace across time zones, languages, offices and authorities." },
  { type: "p", text: "Each step has a stated outcome, a delivery time and a document that stays in your hands: the first is a verdict — proceed, investigate further, drop it — with the reasons in writing. No later phase starts before the previous one has been delivered and discussed." },
  { type: "p", text: "What selecting actually means. Brazil has roughly 1.3 million practising lawyers: one for every 164 inhabitants, the highest ratio in the world. That is not a quality problem, it is a choice problem — and it applies equally to accountants, tax advisers, industrial property agents and technical experts. Bar registration says a professional may practise; it does not say they have ever seen a technology transfer contract, an INPI recordal, or a European counterparty across the table. We select on demonstrated competence in the specific matter — deals closed, cases handled, the ability to work across two languages and two legal systems — not on the formal credential. Anyone who does not know the country cannot apply that filter, because they do not know which questions to ask." },
  { type: "p", text: "Already have an export manager? All the better: we are not after their seat, we are their counterpart on the other side of the corridor. We speak the same language — targets, margins, lead times — but we know the market from the inside: who is actually there, how manufacturing works locally, what the authorities require, which distributor stopped paying suppliers last year." },
  { type: "p", text: "Our job is to put current, independent data and assessments in their hands. Independent in a concrete sense: on our analysis services the fee is fixed and does not depend on the outcome, so we have no reason to hand back a rosier picture than the real one. Where we also offer commercial representation, with a variable component on sales, that is a separate engagement: we do not combine it with analysis on the same deal, and if the two ever meet, we say so first." },
  { type: "p", text: "Anyone running exports works better when the information behind their decisions is verified and recent — and worse when it is second-hand or two years old. It is usually a small investment against what it protects: one check made in time costs a fraction of a container stuck in customs, a badly chosen distributor, or a trademark registered by somebody else." },
  { type: "p", text: "We do not publish client names or identifiable cases. Anyone who asks us to vet their counterparties expects the same discretion — and gets it." },
  { type: "p", text: "We treat every conversation as confidential from the first message, whether or not a document has been signed. If you prefer it formalised, the mutual agreement is ready and we sign it before going into substance." },
  { type: "p", text: "Legal and tax opinions are issued by professionals qualified to practise in their respective jurisdictions, selected by us for the specific case and used to working between Brazil and Europe; they answer directly to the client. We hold the design together." },
];

const blocksPt: Block[] = [
  { type: "p", text: "O que deve atravessar o Atlântico: o produto acabado, os componentes, o método, a marca, uma licença — ou nada?" },
  { type: "p", text: "É a pergunta de que partimos, e quase ninguém a formula antes de já ter decidido a resposta. Em alguns casos, em vez de exportar diretamente, compensa produzir sob licença no destino." },

  { type: "h2", text: "Uma fritadeira sem óleo" },
  { type: "p", text: "A Philips trouxe a airfryer para o Brasil e patenteou a tecnologia: o fluxo de ar quente, o fundo do cesto em formato de estrela. Criou a categoria do zero." },
  { type: "p", text: "No Brasil, airfryer hoje é como se chama qualquer fritadeira sem óleo, como se fosse uma palavra do dicionário. Ninguém mais a associa a quem a inventou. Uma patente protege um caminho para chegar a um resultado, não o resultado em si — e, quando os caminhos são muitos, a vantagem dura apenas o tempo de encontrar outro. A Philips criou um mercado e acabou competindo dentro dele como todos os outros." },
  { type: "p", text: "Não é uma história de roubo. É uma história de escolhas erradas sobre o que proteger." },
  { type: "p", text: "Uma patente não protege uma ideia nem um resultado: protege a invenção tal como reivindicada, descrita linha por linha no texto depositado. Tudo o que fica fora dessas linhas é terreno livre. Alguns elementos, porém, podem ser protegidos mesmo sem patente — como segredo industrial, know-how ou informação confidencial — desde que adotadas medidas efetivas de proteção." },

  { type: "h2", text: "Dois ofícios diferentes" },
  { type: "p", text: "Exportar um produto é apostar em tarifas, câmbio, logística e prazos aduaneiros: variáveis que vocês não controlam e que mudam com um decreto." },
  { type: "p", text: "Transferir o método — autorizar uma empresa local a fabricar com a sua tecnologia, mediante remuneração — é apostar em uma coisa só: a sua capacidade de continuar à frente." },
  { type: "p", text: "Licença: contrato pelo qual uma empresa autoriza outra a fabricar ou usar sua tecnologia em território e prazo definidos. Royalty: a remuneração periódica, em geral um percentual sobre as vendas. Taxa de entrada (entry fee): o valor pago no início, antes de a produção começar." },
  { type: "p", text: "Para muitas PMEs europeias, o Brasil é o caso clássico: tarifa e custo logístico tiram o produto acabado do mercado, enquanto o mesmo produto fabricado localmente seria competitivo. E vale, idêntico, no sentido inverso: um método brasileiro que jamais chegaria à Europa como mercadoria." },

  { type: "h2", text: "Por que o Brasil, e não \"a América Latina\"" },
  { type: "p", text: "\"América Latina\" não é um mercado, é uma categoria geográfica. Quem a trata como bloco único acaba gastando em cinco países o que bastaria para entrar bem em um." },
  { type: "p", text: "As proporções, em valor absoluto. O Brasil concentra sozinho cerca de metade do PIB sul-americano. Mas o dado que importa a quem vende não é a riqueza média: é quantas pessoas podem comprar o seu produto — e aí a desigualdade brasileira, em geral citada como problema, vira aritmética a seu favor. Mesmo com uma estimativa conservadora da faixa de alto poder de compra, fala-se de dezenas de milhões de pessoas: mais do que a população inteira do Chile, e várias vezes a soma de Paraguai e Uruguai. Só a região metropolitana de São Paulo passa de vinte milhões de habitantes. Um nicho no Brasil é maior do que um mercado inteiro em outro lugar — com um idioma só, uma moeda só, um único regime aduaneiro." },
  { type: "p", text: "O Brasil não é um mercado homogêneo: é um arquipélago de mercados. Vinte e seis estados mais o Distrito Federal, cada um com seu imposto sobre a circulação de mercadorias, suas alíquotas e seus regimes de incentivo para quem importa ou se instala em seu território. Daí decorre algo que surpreende quase todos os europeus: fazer a mesma mercadoria chegar a um porto em vez de outro, ou instalar-se em um estado em vez do vizinho, muda a carga tributária — às vezes de forma decisiva para a margem. Os estados competem entre si para atrair importações e plantas industriais, e essa competição ainda está aberta — por enquanto. A reforma tributária substitui progressivamente os impostos estaduais por um imposto único sobre o consumo, deslocando a arrecadação para o estado de destino: a transição se completa no início da década de 2030, e com ela a vantagem de escolher o ponto de entrada por critério fiscal tende a diminuir. Quem estrutura sua presença enquanto a janela está aberta consolida uma vantagem; quem chega depois encontra um campo mais plano." },
  { type: "p", text: "E a escolha nunca é apenas fiscal. O país tem o tamanho de um continente e a logística interna custa caro: desembaraçar onde há vantagem fiscal, mas a dois mil quilômetros do seu mercado-alvo, significa devolver em transporte o que se economizou em impostos, com prazos e riscos adicionais. O mesmo vale para o local de produção. A decisão certa é o ponto de equilíbrio entre as duas contas, calculado caso a caso: onde estão os seus clientes, quanto o produto pesa em relação ao seu valor, qual estado oferece hoje o regime mais favorável para a sua categoria de produto." },
  { type: "p", text: "A dificuldade é o motivo para vir, não para evitar. Tarifas, complexidade tributária, certificações obrigatórias, logística interna cara: tudo verdade. Mas barreira funciona nos dois sentidos. Onde entrar é fácil, já está todo mundo, e ter chegado não vale nada. No Brasil, a mesma dificuldade que hoje deixa vocês de fora amanhã deixa de fora quem viria depois." },
  { type: "p", text: "É o único mercado da região onde a transferência de método faz pleno sentido, porque exige uma base industrial capaz de fabricar sob licença. O México tem uma, mas construída em torno dos Estados Unidos: produz-se lá para reexportar ao norte, não para servir o mercado interno. É outra lógica, e confundi-las significa errar o projeto." },
  { type: "p", text: "Os demais países contam como base, não como mercado. Paraguai, Uruguai e Argentina oferecem regimes de maquila, zonas francas e custos industriais menores — e estão dentro do Mercosul, de modo que a mercadoria produzida lá pode chegar ao Brasil sem a tarifa externa comum, respeitadas as regras de origem e as respectivas exigências documentais, ressalvadas as exceções previstas. Não cinco mercados em vez de um: uma base de custo que serve ao único mercado que pesa." },
  { type: "p", text: "As regras mudam enquanto vocês decidem. Um mercado não é só demanda e concorrência: é um conjunto de regras, e no Brasil elas mudam com mais frequência do que na Europa. Um exemplo em curso, atualizado em agosto de 2026: a reforma tributária instituiu o Imposto Seletivo — o chamado imposto do pecado — deixando para lei posterior a definição das alíquotas. Pela lei complementar já aprovada, entra em vigor em 1º de janeiro de 2027 e, pelo princípio da noventena, o texto das alíquotas deveria ser publicado até o início de outubro de 2026 — prazo tão apertado que se discute fixá-las por medida de urgência em vez de lei ordinária. Alcança categorias específicas — fumígenos, bebidas alcoólicas, bebidas açucaradas, veículos, bens minerais extraídos, apostas — e, se o seu produto não está nessa lista, não o atinge. Mas amanhã será outra norma: uma certificação que se torna obrigatória, uma regra de rotulagem, um incentivo estadual que abre ou fecha. Quase todas se enxergam com meses de antecedência — desde que alguém esteja olhando do lado certo do corredor. Quem já está dentro tem tempo de se adaptar, e muitas vezes ganha com isso: o custo de se adequar é igual para todos, mas pesa muito mais em quem ainda precisa entrar." },
  { type: "p", text: "As certificações são um fosso, não apenas um custo. Registros no INMETRO, na ANVISA, no MAPA ou na ANATEL, conforme o produto: meses de trabalho e despesa certa. É por isso que muitos desistem — e é exatamente por isso que vale a pena: uma vez obtidos, obrigam todo concorrente futuro ao mesmo caminho enquanto vocês já estão na prateleira. Com uma ressalva, que é a pedra angular aplicada a este caso: evitem que o distribuidor controle com exclusividade registros, autorizações ou dossiês regulatórios indispensáveis à continuidade da operação. A titularidade direta pela empresa estrangeira nem sempre é possível — depende do produto, da autoridade competente e de quem responde legalmente pela fabricação, importação e distribuição. Onde não for, o contrato deve disciplinar o acesso aos documentos, o direito de transferência, a colaboração na migração e as consequências da rescisão. Quem detém o registro detém o acesso ao mercado — e trocar de distribuidor deve continuar sendo uma decisão de vocês, não uma negociação." },
  { type: "p", text: "Quando a resposta não é o Brasil — e dizemos com gosto: volumes pequenos que assim vão permanecer; produtos de serviço ou digitais, em que Chile e Uruguai são bem mais simples; o objetivo de abastecer o mercado norte-americano, em que o México ganha sem discussão." },

  { type: "h2", text: "A pergunta que vem antes do contrato" },
  { type: "p", text: "O método está dentro do objeto ou dentro das pessoas?" },
  { type: "p", text: "Se está dentro do objeto — um eletrodoméstico, um molde, uma formulação simples — qualquer parceiro sério o desmonta e o reconstrói em poucos meses. Nesse caso a licença não protege: o que vocês vendem é tempo de mercado e marca. Então o dinheiro se pega na frente: taxa de entrada alta, royalties modestos, prazo curto." },
  { type: "p", text: "Se está dentro das pessoas e de uma relação contínua — agronomia, controle de qualidade, protocolos de processo, calibração, formação técnica — a transferência se sustenta. Sustenta-se porque todo ano existe uma versão nova que o licenciado, sozinho, não saberia produzir." },

  { type: "h2", text: "Uma geladeira a querosene" },
  { type: "p", text: "Em 1947, chegou para conserto, numa oficina de Brusque, em Santa Catarina, uma geladeira importada movida a querosene. Naquela época, no Brasil, geladeira só existia importada e ficava na casa de gente muito rica. Os dois mecânicos desmontaram tudo, estudaram cada peça e decidiram construir a sua própria. Fizeram trinta e uma naquele galpão; em 1950 a oficina virou fábrica em Joinville e recebeu o nome Consul. O primeiro modelo refrigerava por absorção, movido a querosene — a tecnologia certa para um país onde a rede elétrica ainda não chegava à maioria das casas. Dali nasceram uma indústria nacional de compressores, a união com a Brastemp e, por fim, um dos maiores polos de refrigeração do mundo." },
  { type: "p", text: "É o exato avesso da fritadeira. Lá, o fabricante estava presente e protegeu a coisa errada; aqui, não estava presente de forma alguma: vendia um aparelho importado, caro, projetado para outro país. Ninguém copiou por má-fé. O aparelho foi reconstruído porque ninguém estava respondendo ao problema real, que não era fazer frio, e sim fazer frio onde não há energia elétrica." },
  { type: "p", text: "Daí a regra: a adaptação local acontece de qualquer jeito. A única variável é se acontece com vocês ou sem vocês. Quem chega com um catálogo traduzido e uma tabela de preços em euro deixa o trabalho de adaptação para outros — e esses outros, depois, não precisam mais dele." },

  { type: "h2", text: "A pedra angular" },
  { type: "p", text: "No arco, a pedra angular é a pedra central: retire-a e tudo desaba, por mais perfeitas que sejam as outras." },
  { type: "p", text: "Numa licença, é a peça que vocês não entregam. Não uma peça qualquer guardada para si, mas aquela cuja ausência para a produção ou piora o resultado de modo perceptível ao cliente final. A semente exclusiva por trás de um método agronômico transferido por inteiro. A cultura starter por trás de um processo de laticínio ensinado todo. Os parâmetros de calibração, o software de controle, a certificação, a marca." },
  { type: "p", text: "Reconhece-se por três condições, que precisam valer juntas:" },
  { type: "li", text: "Sem ela, o produto não sai — ou sai pior de forma perceptível." },
  { type: "li", text: "Não é replicável localmente a custo razoável. Se o licenciado a constrói em casa com dois técnicos e seis meses, não é pedra angular: é atraso." },
  { type: "li", text: "Ele consegue comprá-la por um preço justo. É a condição que quase todos erram. Cobrando demais, é você quem financia a busca pelo substituto. A pedra angular se defende continuando conveniente, não apertando." },
  { type: "p", text: "E sempre tem meia-vida. Não existe a definitiva: existe a que compra os anos necessários para construir a próxima." },
  { type: "p", text: "Há também uma razão fiscal recente para manter o método vivo: as novas regras brasileiras de preços de transferência reconhecem o direito ao royalty apenas a quem demonstra desenvolver, manter e proteger ativamente o que licenciou. Quem transfere tudo e para de inovar não perde só o poder de negociação — coloca em risco a dedutibilidade da remuneração do outro lado da mesa." },

  { type: "h2", text: "As formalidades que o Brasil não deixa pular" },
  { type: "p", text: "A proteção industrial é territorial. Uma patente ou marca europeia, no Brasil, simplesmente não existe: precisa ser depositada no INPI, e a marca deve ser depositada antes de abrir as conversas. O risco mais comum não é a cópia do produto — é o parceiro registrar a marca em nome próprio." },
  { type: "p", text: "A averbação ou o registro no INPI devem ser avaliados conforme o contrato e os efeitos pretendidos. Até poucos anos atrás era o passo obrigatório para remeter royalties ao exterior e deduzi-los; a reforma cambial de 2021 e as regras de preços de transferência de 2023 mudaram o panorama, e hoje a remessa depende essencialmente da comprovação do pagamento do imposto devido. Continua relevante, porém, para a segurança jurídica e, em determinadas hipóteses, para produzir efeitos perante terceiros. É exatamente o tipo de questão em que a resposta certa depende da estrutura concreta e deve ser verificada com os profissionais contratados. Em particular, a dedutibilidade fiscal de royalties e pagamentos por tecnologia, após as alterações legislativas de 2021 e 2023, exige análise específica do contrato, da natureza do pagamento e do regime tributário aplicável: a posição não é uniforme em todos os casos." },
  { type: "p", text: "Os pagamentos transfronteiriços têm custo fiscal próprio: retenções na fonte, CIDE sobre remessas e outros efeitos que variam conforme a natureza do contrato, as partes envolvidas e a estrutura da remuneração. Entram na conta antes de negociar o percentual, não depois." },
  { type: "p", text: "No texto: campo de uso e território delimitados, mínimos garantidos, direito de auditoria sobre os números de venda, titularidade das melhorias desenvolvidas localmente, confidencialidade e vedação de uso do know-how que sobrevivem ao fim do contrato, cláusula penal. E a arbitragem, que nos contratos internacionais em geral oferece mais previsibilidade processual do que o contencioso ordinário — mas sede, instituição, idioma, lei aplicável, medidas de urgência e estratégia de execução devem ser escolhidos caso a caso: uma sentença arbitral proferida no exterior, para ser executada no Brasil, passa pela homologação do Superior Tribunal de Justiça." },

  { type: "h2", text: "Por que vocês raramente ouvem isso" },
  { type: "p", text: "Não é um segredo técnico. Licenciamento é matéria de manual, e as grandes empresas o praticam há décadas. O que falta é quem leve isso à pequena e média empresa: o ecossistema construído em volta dela — câmaras de comércio, editais, vouchers, feiras, apoios à internacionalização — nasceu para fazer mercadoria sair e mede o próprio resultado em mercadoria saída. Nenhum desses atores tem motivo para dizer ao empresário que talvez o produto dele não deva entrar como produto." },
  { type: "p", text: "E vale também o inverso, que dizemos com gosto: transferir método nem sempre é a resposta certa. São necessárias três coisas juntas — uma contraparte industrial que exista de fato e saiba fabricar; um volume que justifique a produção local; um método vivo o bastante para alimentar a relação ano após ano. Num nicho de poucas centenas de peças por ano, a licença não faz sentido e a exportação faz. Quando é assim, dizemos antes, não depois." },

  { type: "h2", text: "Três objeções, ditas abertamente" },
  { type: "p", text: "\"É preciso alguém dentro da empresa, que conheça o produto.\" Verdade — e esse alguém não somos nós. Mas o produto vocês já conhecem melhor do que qualquer um: a informação que falta não está no galpão de vocês, está do outro lado do corredor. As duas presenças não competem, se somam." },
  { type: "p", text: "\"Um método consolidado funciona em qualquer mercado.\" Um método de trabalho sim; o conhecimento de um mercado não. Quem cobre trinta países com o mesmo procedimento devolve um procedimento organizado, construído sobre dados que vocês poderiam comprar sozinhos. Nós cobrimos um corredor só, e moramos dentro dele. A pergunta a fazer a qualquer um que se ofereça — inclusive a nós: quantas vezes esteve fisicamente naquele mercado nos últimos doze meses, em que idioma fala com as contrapartes, de quais associações locais é membro." },
  { type: "p", text: "\"Precisamos de quem traga negociações, não análises.\" Legítimo. Mas quem é remunerado para fazer a exportação acontecer dificilmente concluirá que aquele mercado não serve para vocês. Nós podemos, e às vezes acontece. O primeiro trabalho que entregamos é um veredito — seguir, aprofundar, desistir — e custa poucas centenas de euros justamente para poupar as dezenas de milhares que viriam depois." },

  { type: "h2", text: "Como trabalhamos" },
  { type: "p", text: "Atuamos entre a Europa e o Brasil e compreendemos tanto as necessidades de empresas, profissionais e clientes europeus e internacionais quanto a complexa realidade normativa, administrativa, tributária e cultural do mercado brasileiro. Nossa competência nasce de uma trajetória internacional que une direito, comércio internacional, elaboração de projetos europeus, atividade empresarial e conhecimento prático dos dois mercados." },
  { type: "p", text: "Nosso objetivo é ajudar vocês a compreender melhor o contexto em que querem atuar, reduzindo o impacto do chamado Custo Brasil: burocracia, complexidade regulatória, assimetrias de informação, dificuldades de interpretação e riscos operacionais que atrasam ou complicam as decisões. Nosso trabalho é independente, confidencial e voltado a fornecer informações confiáveis, selecionadas e realmente úteis para decidir com base em dados. Sem ruído, sem enrolação: só as respostas necessárias, na hora certa." },
  { type: "p", text: "Não nos limitamos a dizer que é preciso um advogado. Montamos e coordenamos o time — escritório de advocacia no Brasil e na Europa, agente da propriedade industrial, tributarista, perito técnico quando necessário — e sustentamos a arquitetura da operação do primeiro dia à última assinatura." },
  { type: "p", text: "É a diferença que realmente pesa: quem tem a arquitetura completa na cabeça sabe o que perguntar, a quem e em que ordem. Um parecer jurídico excelente sobre uma pergunta mal formulada custa o mesmo e não protege de nada." },
  { type: "p", text: "Na prática:" },
  { type: "li", text: "desenhamos a arquitetura da operação — o que se transfere, em quantas etapas, o que fica de fora e por quê;" },
  { type: "li", text: "verificamos a contraparte antes de a mesa se abrir: estrutura societária, histórico, litígios, capacidade industrial real e o que ela já sabe fazer sozinha;" },
  { type: "li", text: "identificamos a pedra angular crível no caso concreto, e por quantos anos ela se sustenta;" },
  { type: "li", text: "traduzimos a estratégia em instruções precisas para os profissionais contratados, e relemos o trabalho deles à luz do objetivo comercial, não apenas da norma;" },
  { type: "li", text: "mantemos o ritmo entre fusos, idiomas, escritórios e autoridades diferentes." },
  { type: "p", text: "Cada etapa tem um resultado declarado, um prazo de entrega e um documento que fica nas mãos de vocês: o primeiro é um veredito — seguir, aprofundar, desistir — com as razões por escrito. Nenhuma fase seguinte começa antes de a anterior ter sido entregue e discutida." },
  { type: "p", text: "O que significa selecionar. No Brasil atuam cerca de 1,3 milhão de advogados: um para cada 164 habitantes, a maior proporção do mundo. Não é um problema de qualidade, é um problema de escolha — e vale igualmente para contadores, tributaristas, agentes da propriedade industrial e peritos técnicos. A inscrição na Ordem diz que o profissional pode exercer; não diz que já tenha visto um contrato de transferência de tecnologia, uma averbação no INPI ou uma contraparte europeia do outro lado da mesa. Selecionamos pela competência demonstrada na matéria específica — operações concluídas, casos conduzidos, capacidade de trabalhar entre dois idiomas e dois ordenamentos — e não pelo requisito formal. Quem não conhece o país não consegue aplicar esse filtro, porque nem sabe quais perguntas fazer." },
  { type: "p", text: "E se vocês já têm um gerente de exportação? Melhor ainda: não tomamos o lugar dele, somos a contraparte do outro lado do corredor. Falamos a mesma língua — metas comerciais, margens, prazos de entrega — mas conhecemos o mercado por dentro: quem realmente está lá, como se fabrica localmente, o que as autoridades exigem, qual distribuidor deixou de pagar fornecedores no ano passado." },
  { type: "p", text: "Nosso trabalho é colocar na mão dele dados e avaliações atualizados e independentes. Independentes em sentido concreto: nos serviços de análise a remuneração é fixa e não depende do resultado, portanto não temos motivo algum para devolver um quadro mais animador do que o real. Onde também oferecemos representação comercial, com parcela variável sobre as vendas, trata-se de um serviço distinto: não o combinamos com a análise na mesma operação, e se as duas coisas se cruzarem, avisamos antes." },
  { type: "p", text: "Quem cuida de exportação trabalha melhor quando as informações em que se apoia são verificadas e recentes — e pior quando são de segunda mão ou de dois anos atrás. Costuma ser um investimento pequeno diante do que protege: uma verificação feita a tempo custa uma fração de um contêiner parado na alfândega, de um distribuidor mal escolhido ou de uma marca registrada por outra pessoa." },
  { type: "p", text: "Não publicamos nomes de clientes nem casos identificáveis. Quem nos pede para verificar suas contrapartes espera a mesma discrição — e a recebe." },
  { type: "p", text: "Tratamos toda conversa como sigilosa desde a primeira mensagem, havendo ou não documento assinado. Se preferirem formalizar, o acordo bilateral está pronto e o assinamos antes de entrar no mérito." },
  { type: "p", text: "Os pareceres jurídicos e tributários são emitidos por profissionais habilitados em seus respectivos ordenamentos, selecionados por nós para o caso concreto e acostumados a trabalhar entre Brasil e Europa; respondem diretamente ao cliente. Nós sustentamos o desenho." },
];

export default function Method() {
  const { lang } = useT();
  const isEn = lang === "en";
  const isPt = lang === "pt";
  useCanonical("/method", {
    title: isEn
      ? "Transfer the method, not just the product | Business Matching Global"
      : isPt
        ? "Transferir o método, não apenas o produto | Business Matching Global"
        : "Trasferire il metodo, non solo il prodotto | Business Matching Global",
    description: isEn
      ? "Licence, royalties and technology transfer to Brazil: when it pays to manufacture locally instead of exporting, and how to protect the keystone."
      : isPt
        ? "Licença, royalties e transferência de tecnologia para o Brasil: quando compensa produzir localmente em vez de exportar, e como proteger a pedra angular."
        : "Licenza, royalty e trasferimento di tecnologia verso il Brasile: quando conviene produrre in loco invece di esportare, e come proteggere la chiave di volta.",
  });
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const blocks = isEn ? blocksEn : isPt ? blocksPt : blocksIt;

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Nav />
      <div className="container max-w-3xl pt-32 md:pt-40 pb-16 md:pb-24">
        <h1 className="font-display text-4xl md:text-5xl leading-tight mb-8">
          {isEn
            ? "Transfer the method, not just the product"
            : isPt
              ? "Transferir o método, não apenas o produto"
              : "Trasferire il metodo, non solo il prodotto"}
        </h1>

        <article className="space-y-6">
          {blocks.map((b, i) =>
            b.type === "h2" ? (
              <h2 key={i} className="font-display text-2xl md:text-3xl mt-10 mb-2 text-foreground">
                {b.text}
              </h2>
            ) : b.type === "li" ? (
              <p
                key={i}
                className="text-base md:text-lg leading-relaxed text-muted-foreground text-justify pl-5 border-l-2 border-border"
              >
                {b.text}
              </p>
            ) : (
              <p key={i} className="text-base md:text-lg leading-relaxed text-muted-foreground text-justify">
                {b.text}
              </p>
            )
          )}
        </article>

        <div className="mt-14 pt-10 border-t border-border">
          <h2 className="font-display text-2xl md:text-3xl mb-3">{isEn ? "→ Let's talk" : "→ Parliamone"}</h2>
          <p className="text-base md:text-lg text-muted-foreground">
            {isEn ? "Write to us at " : "Scrivici a "}
            <a href={`mailto:${EMAIL}`} className="text-primary underline hover:text-primary/80 inline-flex items-center gap-1">
              <Mail className="h-4 w-4" /> {EMAIL}
            </a>{" "}
            {isEn ? "or use the form below." : "oppure usa il modulo qui sotto."}
          </p>
        </div>

        <ContactForm />
      </div>
    </div>
  );
}
