import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useEffect } from "react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";
import { AnalysisFooter } from "@/components/AnalysisFooter";
import { useCanonical } from "@/lib/useCanonical";
import { ShareBlock } from "@/components/ShareBlock";
import { LangSwitcher } from "@/components/LangSwitcher";

type Block = { h: string } | { p: string };

const TITLE = "Voting with Their Feet";

const BACK = {
  it: "Torna alle analisi",
  en: "Back to analysis",
  pt: "Voltar às análises",
} as const;

const body: Block[] = [
  { p: "What the Ceuta crisis tells us — once the noise is filtered out" },
  { p: "Some texts are written to persuade. This one is written to verify. Since late July, an unusual volume of confident claims has circulated across European capitals and social feeds — many checkable, many baseless. What follows is not a defense of any government. It is an exercise in rebuilding the dossier, because in market intelligence, as in politics, verified facts — not statements — say what actually happened. The dossier has grown in a week: we are rewriting it whole rather than stacking updates, because an audit that accumulates without reordering itself stops being readable." },
  { h: "Fact one: Ceuta has never been part of the Schengen Area" },
  { p: "The claim that dominated the first days — that migrants entering Ceuta had “breached Schengen” and could walk freely to Milan or Helsinki — fails at the first check of the law." },
  { p: "When Spain joined the Schengen Agreement in 1991, a declaration specific to Ceuta and Melilla was annexed to its Act of Accession, excluding the two North African cities from the free-movement regime. That special status survives today in Article 41 of the Schengen Borders Code. In practice: entering Ceuta grants no right to remain in Spain, reach the Iberian Peninsula, or circulate in Europe. Exit controls between Ceuta and the mainland have existed since 1991." },
  { p: "The numbers confirm the system worked as designed. Of the roughly 50,000–60,000 people who entered in under 24 hours, Spanish authorities report over 48,000 were returned to Morocco within 48 hours. On 1 August, Commission President von der Leyen — after a call with Commissioners Brunner and Šuica — stated publicly that the vast majority had already returned and that no one had reached mainland Spain or the rest of the EU." },
  { p: "One government nevertheless suspended Schengen with Spain for a month from 1 August, reinstating selective checks at maritime and air borders — over a border Schengen never covered. Brussels noted the suspension was announced before any formal notification reached the Commission, and an EU spokesperson publicly asked Rome to explain how the crisis constituted a security threat — the legal precondition for reinstatement. The same government then co-promoted, with Denmark, a letter signed by 22 European heads of state and government calling for coordination and a united European response: unilateral suspension without notification on one hand, a call for coordination on the other, in the same news cycle. One gesture contradicts the other." },
  { p: "A more historical than legal element completes the picture. Across four decades of the mechanism's use, reinstating internal controls has always been a response to pressure from third countries — Libya, Belarus, the Balkan route — never a punitive measure against a fellow member state. The Italian suspension, and what followed (see fact eight), is therefore not merely procedural: it is a precedent in itself, the first case of Schengen used as a weapon between two founding members of the free-movement area." },
  { p: "Two clarifications complete fact one. Prime Minister Meloni's initial demand — Spain's expulsion from the entire Schengen area — was itself technically unworkable: it cannot happen against Spain's will, The Economist notes. What Italy actually did was more modest, spot checks at ports and airports — the gap between the demand and the measure is already a clue to the register (domestic politics) this played out in. And above all: on 4 August, at the emergency videoconference of EU interior ministers, the European level had already closed the file. Commissioner Brunner declared “full solidarity with Spain”; all talk of expulsion from Schengen vanished from the communiqués, replaced by the usual talking points on borders, traffickers and returns. While Rome kept its bilateral suspension in place — and the following week Madrid answered in kind — the European institution had already moved on. From that point, the Rome-Madrid standoff is no longer an EU crisis: it is a bilateral dispute, kept alive by whoever chose to keep it alive." },
  { h: "Fact two: the regularization has nothing to do with the fence" },
  { p: "A second claim linked the crisis to Spain's regularization of roughly 500,000 migrants, presented as an open invitation. The mechanics say otherwise: the process requires documented prior residence, a clean record, a work contract or sufficient means. Whoever climbed a fence in July 2026 is excluded by definition. One clarification on the number itself: 500,000 was the figure Spanish authorities expected, not the total regularized — applications actually received numbered 1.2 million, of which how many were approved is not publicly known. Even on the larger figure, this remains a documented application process with requirements — not an open gate for whoever arrives by swimming. Spanish authorities also documented a disinformation campaign that misrepresented a Supreme Court ruling on returns to convince people that reaching Ceuta guaranteed permanence. It does not; the ruling changed procedure, not rights of stay." },
  { p: "The Frontex figures cited by the Spanish government on irregular entries 2021–2026 rank the routes as follows: Italy roughly 478,600; the Western Balkans 340,600; Greece 259,800; Spain 234,760. The country that suspended Schengen with Spain registered roughly double Spain's irregular entries over the same period." },
  { p: "It is worth noting how this rebuttal was framed. While other capitals escalated — summits, closed borders, ambassadors summoned — the Spanish prime minister's reply was a post listing those Frontex figures, introduced by a single remark: solidarity and empathy are optional, respect for treaties and data is not. A table on one side, a diplomatic escalation on the other." },
  { h: "Fact three: the Spanish model, imperfect but measurable" },
  { p: "Spain is the fastest-growing large economy in the eurozone, roughly 3% annually for two consecutive years, while Germany and Italy hover near zero. The drivers: record tourism, effective absorption of Next Generation EU funds, cheap renewables and — the irony of the polemic — immigration itself, which has sustained employment and consumption in an aging continent. Real weaknesses exist: a severe housing crisis, low hourly productivity, residual precarity. But “imperfect and growing 3%” is a different sentence from the one being written about Spain these days." },
  { h: "Fact four: Morocco is not an Eldorado — and an election explains part of why" },
  { p: "Morocco has spent years promoting its image as an African success story: GDP growth above 3%, cumulative expansion of 22% since 2019, exports approaching Italy's automotive output, high-speed rail Kenitra-Marrakech, the 2030 World Cup with the largest stadium in the world." },
  { p: "The other side of the ledger: roughly two-thirds of Moroccan employment is informal — 67.6% per the HCP/ILO satellite account, over 67% per the OECD, up to 77% in other estimates. Unemployment among 15–24-year-olds exceeded 36% in 2024–2025; under the 2026 “strict sense” methodology the official rate falls to 29%, but overall youth labor underutilization remains at 45%. Female participation fell from 28% in 2000 to 19%, among the widest gaps in the world. Growth concentrates in capital-intensive sectors controlled by foreign multinationals: they absorb investment, employ few, redistribute less. The GenZ 212 movement condensed the imbalance into a slogan: we want hospitals, not stadiums. The OECD places Morocco near the top globally for departing workers." },
  { p: "A context the early accounts omitted: Morocco holds general elections on 23 September 2026. It is plausible to read the rush on the fence — tens of thousands of people on the king's own Throne Day — also as an expression of pre-election discontent, layered on the October 2025 Gen Z protests against World Cup infrastructure seen as the wrong priority over health and education. No fact stated here requires this reading to be true, but omitting it means losing a variable as relevant as any foreign actor." },
  { p: "The human toll remains the datum no sovereign narrative can absorb — and it is, as of today, still evolving and discordant across sources. Total entries, per the Spanish interior minister on 4 August, were roughly 72,000, of which 70,000 had already returned to Morocco. On the death toll, the range has widened rather than closed: 11 per Morocco's initial count, over 48,000 returned within 48 hours per Madrid, 72 fatalities reported by Spain pending joint verification, close to 100 dead and 50 missing per Spanish police on 6 August, at least 141 drowned at the breakwater per The Economist on 5 August. We flag the range rather than choose a number: the range is itself the fact, because a toll that keeps rising as searches continue says more than any final figure. One clarification on composition too: the bulk of the 30–31 July wave were Moroccan nationals, as both Rabat and content analyses document — but not all of them; among those remaining in Ceuta in early August, per The Economist, the majority were sub-Saharan migrants and unaccompanied minors, about 1,100 of whom were slated for transfer to Spain. The correct picture is not “Moroccans instead of sub-Saharans” but two distinct populations on different trajectories: Moroccans, rapidly repatriable under bilateral agreements, dropped out of the count within days; sub-Saharan migrants, in a more complex legal gray zone, are who remained. When people risk their lives between razor wire and open water, they are assigning a country a rating more honest than any agency's. They voted with their feet. It is the one ballot that cannot be spun." },
  { h: "Fact five: the accusers' own ledger — and an irony spoken over the wrong graves" },
  { p: "The governments loudest in denouncing Madrid deserve the same audit they demand of others." },
  { p: "Italy, in 2025, restricted iure sanguinis citizenship — a decree signed by the same foreign minister now attacking Spain's regularization — cutting off most South American descendants of Italian emigrants, barring children and grandchildren of the Italy-born. The same political camp now watches the popular initiative “Remigration and Reconquest” arrive in Parliament with 150,000 signatures: a text defining remigration as the assisted return of foreigners legally resident in Italy, while simultaneously proposing state support for the return of Italian descendants abroad." },
  { p: "Descendants who spent years queuing at consulates for citizenship were voting with their feet toward Italy — door closed, booked as a consular cost. Foreigners who voted with their feet toward Italy and built regular lives there are now, in the most radical proposal on the table, invited to leave. Diaspora as liability, resident population as surplus: incoherent accounting, a poor pulpit from which to lecture Madrid." },
  { p: "And on 7 August the incoherence found its sharpest image. At the ceremony marking the 70th anniversary of the Marcinelle mining disaster — where 136 Italian emigrant workers died, part of the 50,000 sent to Belgium under the 1946 “men for coal” accord — Prime Minister Meloni declared there is “no room in Europe for those who feed channels of illegal immigration for cheap labor.” Words aimed at Rabat and at traffickers. Spoken over the graves of Italians who were, in every material sense if not the legal one, exactly that: cheap labor moved across a border by an accord written to serve someone else's economy. No further comment is needed." },
  { p: "One last entry in the ledger, and Spain itself supplies it: in justifying its own countermeasure against Italy, the Spanish interior ministry officially cited nearly half a million irregular immigrants who arrived in Italy over the past five years against just 16,000 returns — figures that, in order of magnitude, confirm the Frontex data in fact two. Sánchez added a more technical, checkable accusation: that Italy has not complied with the Dublin Regulation since 2022, offloading additional migratory pressure onto other member states. This is not an opinion to referee here — it is a specific claim that would merit its own verification — but the fact that the accusation arrives with a number and a regulation article, rather than an adjective, places it in a different category from the rest of the polemic." },
  { h: "Fact six: Moroccans are already here — and they are the Italy that works" },
  { p: "The fact the invasion narrative cannot digest, because it dismantles it from within." },
  { p: "The Moroccan community is among the largest, oldest and most rooted in Italy: 412,000 residents as of 1 January 2025 per the ISMU Foundation, third nationality after Romanians and Albanians; 377,554 legal permit holders among non-EU citizens per the Labour Ministry, the country's second non-EU community. Not episodic: men arriving alone in the 1980s, families reunited in the 2000s, today 82,075 minors, 115,569 students in Italian schools, 1,190 mixed marriages in 2023 alone. And 27,000 acquisitions of Italian citizenship in 2024 — the second community by naturalizations — after over 216,000 in 2006–2017." },
  { p: "The ISTAT figure relaunched by Il Sole 24 Ore adds the missing piece: arrivals from Morocco to Italy grew almost 50% in 2025 — 36,000 people, second nationality by entries, counted by official statistics. The government loudest about the Ceuta “invasion” presides over a country where Moroccans are the third national community, where 115,000 study in its schools, marry its citizens, acquire its citizenship at a pace of 27,000 a year, and keep arriving regularly at a rate that grew 50%. The two facts cannot both be true: either Morocco is a danger, in which case forty years of documented integration need explaining; or the numbers are right — the Ceuta fence was the set of a film shot for a different audience." },
  { h: "Fact seven: who lit the fuse — and what remains contested" },
  { p: "Who mobilized tens of thousands of people toward one fence on the same day is the question on which this dossier, as of today, remains most open — and it is right to say so with the same honesty we've applied to everything else." },
  { p: "The judicial floor is documented: dozens of anonymous accounts repeated the same message — the border is open, whoever crosses stays — and accounts with thousands of followers published crossing points. The Audiencia Nacional opened an investigation into criminal networks, traffickers or a coordinated strategy; Rabat blamed “disinformation mafias”; as of 5 August, 25 people stand indicted. A call for a new mass entry on 15 August is already circulating, so far without official confirmation from either side." },
  { p: "On who is behind it, though, two credible readings do not coincide, and fact-checking does not choose on trust. Nathalie Tocci (IAI / Johns Hopkins SAIS), on 5 August on Sky TG24, proposed a three-actor taxonomy: third states weaponizing migration for leverage, as Tunisia, Libyan militias and Turkey did before Morocco; global actors — the origins of some of the disinformation traced, in her assessment, to Moscow, the American MAGA world, Israel — aiming to divide Europe starting from Sánchez's Spain; and the domestic right riding what she calls a “fake crisis.” Her sharpest point is verifiable by anyone looking at a map: reaching mainland Spain from Ceuta is harder than the direct crossing from Morocco, because exit controls from the enclave are stricter. Whoever cries invasion-via-Ceuta describes the route no rational migrant would choose." },
  { p: "Original research by scholar Myriam Cherti, published 6 August, complicates this reading. Analyzing 180 highly engaged posts from the 2024 precedent, Cherti found over 80% of the content in Moroccan Darija — a local conversation, not messaging for abroad — and concluded the mobilization was digitally enabled collective action, not a centrally directed campaign. The Associated Press found claims of trafficker coordination or deliberate Moroccan state orchestration “had not been publicly substantiated.” Even Morocco's own Interior Ministry probe, while ruling out spontaneous factors and pointing to disinformation and traffickers, stops short of proving a state design. Two credible readings, not fully overlapping: Tocci's on external actors in the campaign and its political aftermath, Cherti's on the absence of a mastermind behind the original mobilization. On who, the public file remains open — and caution applies to both attributions." },
  { p: "What happened in the square, by contrast, needs no caution: it is direct reporting. On Saturday night, hundreds of Ceuta residents took to the streets against Núcleo Nacional, a Spanish far-right movement; the next day agitator Vito Quiles appeared in Plaza de los Reyes with Save Europe Act — co-founded by Austrian Martin Sellner, with Generation Identity activists arrived from Germany — and a neighborhood protest split over his presence: “he came to provoke and divide us,” in the residents' words per the wire services. Their banner — “Sánchez must go, Spain needs remigration” — was in English; the Ceutans contesting it answered in Spanish. A banner is an act of communication, and its addressee can be deduced from its language: whoever writes in Spanish in Ceuta is speaking to Ceuta, whoever writes in English is speaking to the camera and the algorithm. Add that Ceuta is roughly half of Moroccan and Muslim origin: a casting error before a political one. Per The Economist, far-right agitators arrived from across Europe spreading “ethnic replacement” videos; Elon Musk and US Vice President J.D. Vance joined the chorus too. The external actors, this time, came in person — and remain the only ones in this whole story to have crossed more borders than the migrants." },
  { p: "One last observation closes fact seven, and it may be the sharpest in the whole dossier: the EU does not treat all migratory leverage alike. Since 2021, Belarus has flown Middle Eastern migrants toward Poland and neighboring states as political retaliation; the EU classified it as an act of hybrid warfare and tightened sanctions on Minsk. Morocco, in 2021, had already let roughly 8,000 people into Ceuta in retaliation for Spain's medical hospitality to the Polisario Front's leader — a direct precedent for what happened this year. Yet, notes The Economist, “there is no clear evidence that Morocco orchestrated the movement of migrants,” while “its security officials certainly let them stream past” — and European governments still hailed Moroccan “cooperation,” reserving hostility for anonymous traffickers and social posts. The difference in treatment is not accidental: the EU needs Moroccan cooperation on the far larger Canary Islands route too. Oxford analyst Ruben Andersson puts it this way: border externalization “creates an incentive to third countries to stir up crises — and offer to resolve them.” Migration expert Gemma Pinyol-Jiménez sums up the whole affair in a line that serves as a fitting close to this fact: “This was not primarily a migration crisis. It was a geopolitical episode.”" },
  { h: "Fact eight: the mirror — and the result is zero" },
  { p: "The last chapter, chronologically, is also the most striking. After Rome rejected Madrid's ultimatum — lift the checks by 9 August, or face “proportional measures” — Spain activated reciprocal controls on arrivals from Italy from midnight on 8 August, valid through 7 September, officially justified by “persistent irregular migratory pressure” from Italy. One detail belongs in the audit column: the 15 August date Palazzo Chigi cites as its own review point is not a formal Spanish announcement — it is, per the press in both countries, social-media chatter in Morocco that the Guardia Civil considers plausible for a new attempt. A government that suspended Schengen partly over a disinformation campaign is now justifying the length of that suspension by citing an unconfirmed rumor of the same kind." },
  { p: "But the hardest data point, a week on, is a result, not a procedure: no irregular migrant from Ceuta has been identified at Italian checks. Zero. And the same sources reporting the figure note it would in any case be impossible to establish, for North African nationals intercepted at airports, whether their entry was connected to the Ceuta crisis at all. Deputy PM Salvini said he was blocking “dozens of irregulars arriving from Spain”: the two claims — zero linked to Ceuta, dozens blocked in general — are not mutually exclusive, but the gap between what the measure was meant to prevent and what it actually intercepted remains the most telling fact of the whole affair. Spanish Interior Minister Grande-Marlaska, after the EU ministers' videoconference, put it plainly: it was acknowledged that “the Schengen area was never in danger,” and he demanded the immediate lifting of Italian checks because they do not match what was agreed there. On the Italian domestic front, opposition figures — from Fratoianni to Magi to Calenda — used different registers but the same substance: propaganda, a bully's move, electoral calculation. We do not adopt their language, but we note the criticism is not only external: it runs through Italy's own domestic debate too." },
  { h: "The method, again" },
  { p: "Eight facts, three countries, one criterion: documents before statements — and a willingness to correct our own dossier when better evidence arrives, as we did on fact seven. Brazilian firms voted with their feet against the Custo Brasil by crossing the Ponte da Amizade; Moroccans voted with their feet against their two-speed miracle; Italian descendants voted with their feet toward a homeland that stopped answering; and even Ceuta's agitators, in the end, voted with their feet — the only ones to have crossed more borders than the migrants, to narrate a crisis the migrants themselves did not recognize." },
  { p: "In every case, power answered the feet with rhetoric instead of reform." },
  { p: "Facts and figures are drawn from public sources: the Schengen Borders Code and Spain's Act of Accession (1991); European Commission statements (July–August 2026); CJEU, joined cases C-368/20 and C-369/20 (2022); HCP and OECD on the Moroccan labor market; ISMU Foundation, Migration Report 2026; Italian Labour Ministry, “The Moroccan Community in Italy — Annual Report 2025”; ISTAT, 2025 migration report; court records and reporting on the Audiencia Nacional investigation and the Ceuta demonstrations (August 2026); Nathalie Tocci interview, Sky TG24 “Timeline”, 5 August 2026; Myriam Cherti research and analysis, Bloomberg, 6 August 2026; Moroccan Interior Ministry statement via MAP, reported by Bloomberg, 3 August 2026; Italian and Spanish press on the reciprocal Schengen checks and the Marcinelle ceremony (Il Post, Sky TG24, Il Foglio, ANSA, 7–8 August 2026); The Economist, “Rushing the gates” (31 July 2026) and “The wrong lessons” (5 August 2026); statements by Spanish Interior Minister Grande-Marlaska and reporting on the 4 August EU ministers' videoconference (Sky TG24); statements by Matteo Salvini and the Italian opposition, and the Spanish interior ministry's note on the 8 August countermeasure (LaPresse, Adnkronos, Europa Today, 7–8 August 2026)." },
  { p: "Business Matching Global — market intelligence and business orchestration, Europe–Brazil corridor. Without data, you're just another person with an opinion. We'd rather be just another person with the data." },
];

export default function Ceuta() {
  const { lang, setLang } = useT();
  const article = getArticleBySlug("ceuta");
  const desc =
    "What the Ceuta crisis actually tells us: Schengen's special status, Frontex data, Morocco's two-speed economy and the migration flows that verify what press releases deny.";
  useCanonical("/ceuta", {
    title: `${TITLE} — Business Matching Global`,
    description: desc,
    type: "article",
  });

  useEffect(() => {
    const previous = lang;
    if (lang !== "en") setLang("en");
    return () => {
      if (previous !== "en") setLang(previous);
    };
  }, [lang, setLang]);

  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <div className="flex items-center justify-between gap-4 mb-8">
          <Link
            to="/analysis"
            className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            {BACK[lang]}
          </Link>
          <LangSwitcher to="/ceuta" />
        </div>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">{TITLE}</h1>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
          <ShareBlock title={TITLE} />
        </article>
        <AnalysisFooter />
      </div>
    </main>
  );
}
