import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useEffect } from "react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";
import { AnalysisFooter } from "@/components/AnalysisFooter";
import { useCanonical } from "@/lib/useCanonical";
import { ShareBlock } from "@/components/ShareBlock";
import { LangSwitcher } from "@/components/LangSwitcher";

type Block = { h: string } | { p: string };

const TITLE = "Votando com os pés";

const body: Block[] = [
  { p: "#CustoBrasil — Business Matching Global · publicado em 02-08-2026, reescrito e atualizado em 08-08-2026" },
  { p: "O que a crise de Ceuta nos diz — depois de filtrado o barulho" },
  { p: "Alguns textos são escritos para persuadir. Este foi escrito para verificar. Desde o fim de julho, circulou nas capitais europeias e nas redes sociais um volume incomum de afirmações categóricas — muitas verificáveis, muitas sem fundamento. O que segue não é a defesa de governo algum. É um exercício de reconstrução do dossiê, porque na inteligência de mercado, como na política, são os fatos verificados — não as declarações — que dizem o que realmente aconteceu. O dossiê, em uma semana, cresceu: nós o reescrevemos por inteiro em vez de empilhar atualizações, porque uma auditoria que se acumula sem se reorganizar deixa de ser legível." },
  { h: "Fato um: Ceuta nunca fez parte do Espaço Schengen" },
  { p: "A afirmação mais difundida nos primeiros dias — de que os migrantes que entraram em Ceuta teriam «violado o Schengen» e poderiam chegar livremente a Milão ou Helsinque — desmorona na primeira checagem da norma." },
  { p: "Quando a Espanha aderiu ao Acordo de Schengen em 1991, foi anexada ao seu Ato de Adesão uma declaração específica sobre Ceuta e Melilla, que exclui as duas cidades norte-africanas do regime de livre circulação. O status especial segue em vigor, hoje no artigo 41 do Código de Fronteiras Schengen. Na prática: entrar em Ceuta não dá direito de permanecer na Espanha, alcançar a Península Ibérica ou circular pela Europa. Os controles de saída entre Ceuta e o continente existem desde 1991." },
  { p: "Os números confirmam que o sistema funcionou como projetado. Das cerca de 50.000–60.000 pessoas que entraram em menos de 24 horas, as autoridades espanholas informam que mais de 48.000 foram devolvidas ao Marrocos em 48 horas. Em 1º de agosto, a presidente da Comissão von der Leyen — após uma videochamada com os comissários Brunner e Šuica — declarou publicamente que a grande maioria dos que haviam entrado já havia retornado, e que ninguém havia chegado à Espanha continental ou ao restante da UE." },
  { p: "Um governo, ainda assim, suspendeu o Schengen com a Espanha por um mês a partir de 1º de agosto, restabelecendo controles seletivos nas fronteiras marítimas e aéreas — sobre uma fronteira que o Schengen nunca cobriu. Bruxelas observou que a suspensão foi anunciada antes de qualquer notificação formal chegar à Comissão, e um porta-voz da UE pediu publicamente a Roma que explicasse de que forma a crise constituiria uma ameaça à segurança — o pressuposto jurídico exigido para o restabelecimento. O mesmo governo promoveu depois, com a Dinamarca, uma carta assinada por 22 chefes de Estado e de governo europeus pedindo coordenação e uma resposta europeia unida: suspensão unilateral sem notificação de um lado, pedido de coordenação do outro, no mesmo ciclo de notícias. Um gesto contradiz o outro." },
  { p: "Um elemento mais histórico que jurídico completa o quadro. Ao longo de quatro décadas de uso do mecanismo, o restabelecimento de controles internos sempre foi resposta a pressões de países terceiros — Líbia, Bielorrússia, a rota dos Bálcãs — nunca uma medida punitiva contra outro Estado-membro. A suspensão italiana, e o que se seguiu (ver fato oito), não é portanto apenas procedimental: é um precedente em si, o primeiro caso do Schengen usado como arma entre dois membros fundadores do espaço de livre circulação." },
  { p: "Dois esclarecimentos completam o fato um. O pedido inicial da premiê Meloni — a expulsão da Espanha de todo o espaço Schengen — era, ele próprio, tecnicamente inviável: não pode ocorrer contra a vontade da Espanha, observa a The Economist. O que a Itália de fato fez foi uma medida mais modesta, controles por amostragem em portos e aeroportos — a distância entre o pedido e a medida já é um indício do registro (política doméstica) em que o episódio se desenrolou. E, sobretudo: em 4 de agosto, na videoconferência de emergência dos ministros do Interior da UE, o nível europeu já havia arquivado o alarme. O comissário Brunner declarou «plena solidariedade com a Espanha»; todo discurso de expulsão do Schengen desapareceu dos comunicados, substituído pelos pontos programáticos habituais sobre fronteiras, traficantes e repatriações. Enquanto Roma mantinha a suspensão bilateral — e na semana seguinte Madri respondia na mesma moeda — a instituição europeia já havia encerrado o caso. O confronto Roma-Madri, a partir daquele momento, deixou de ser uma crise da UE: é uma disputa bilateral, mantida viva por quem decidiu mantê-la viva." },
  { h: "Fato dois: a regularização não tem nada a ver com a cerca" },
  { p: "Uma segunda afirmação ligou a crise à regularização espanhola de cerca de 500.000 migrantes, apresentada como convite aberto. A mecânica diz o contrário: o processo exige residência prévia documentada, ficha limpa, contrato de trabalho ou meios suficientes. Quem pulou uma cerca em julho de 2026 está, por definição, excluído dele. Um esclarecimento sobre o próprio número: 500.000 era a estimativa esperada pelas autoridades espanholas, não o total regularizado — os pedidos efetivamente recebidos foram 1,2 milhão, dos quais não se sabe publicamente quantos foram aprovados. Mesmo na versão mais ampla do dado, trata-se de um processo de solicitação documentada com requisitos — não um portão aberto para quem chega a nado. As autoridades espanholas também documentaram uma campanha de desinformação que distorceu uma decisão do Supremo Tribunal sobre devoluções para convencer as pessoas de que chegar a Ceuta garantiria a permanência. Não garante; a decisão mudou o procedimento, não os direitos de permanência." },
  { p: "Os dados da Frontex citados pelo governo espanhol sobre entradas irregulares entre 2021 e 2026 classificam as rotas assim: Itália, cerca de 478.600; Bálcãs Ocidentais, 340.600; Grécia, 259.800; Espanha, 234.760. O país que suspendeu o Schengen com a Espanha registrou aproximadamente o dobro das entradas irregulares da Espanha no mesmo período." },
  { p: "Vale notar como essa réplica foi formulada. Enquanto outras capitais escalavam — cúpulas, fronteiras fechadas, embaixadores convocados —, a resposta do primeiro-ministro espanhol foi um post listando aqueles números da Frontex, introduzidos por uma única observação: solidariedade e empatia são opcionais, o respeito aos tratados e aos dados não. De um lado uma tabela, do outro uma escalada diplomática." },
  { h: "Fato três: o modelo espanhol, imperfeito mas mensurável" },
  { p: "A Espanha é a grande economia de crescimento mais rápido da zona do euro, cerca de 3% ao ano por dois anos consecutivos, enquanto Alemanha e Itália patinam perto de zero. Os motores: turismo recorde, absorção eficaz dos fundos do Next Generation EU, renováveis baratas e — ironia da polêmica — a própria imigração, que sustentou emprego e consumo em um continente que envelhece. Há fragilidades reais: grave crise habitacional, baixa produtividade por hora trabalhada, precariedade residual. Mas «imperfeito e crescendo 3%» é uma frase bem diferente da que se escreve sobre a Espanha nestes dias." },
  { h: "Fato quatro: o Marrocos não é um Eldorado — e uma eleição explica parte do porquê" },
  { p: "O Marrocos passou anos promovendo sua imagem de história de sucesso africana: crescimento do PIB acima de 3%, expansão acumulada de 22% desde 2019, exportações que se aproximam da produção automobilística italiana, alta velocidade Kenitra-Marrakech, a Copa do Mundo de 2030 com o maior estádio do mundo." },
  { p: "O outro lado do balanço: cerca de dois terços do emprego marroquino é informal — 67,6% segundo a conta satélite HCP/OIT, mais de 67% segundo a OCDE, até 77% em outras estimativas. O desemprego entre os 15-24 anos superou 36% em 2024-2025; com a metodologia «em sentido estrito» de 2026, a taxa oficial cai para 29%, mas a subutilização geral da força de trabalho jovem permanece em 45%. A participação feminina caiu de 28% em 2000 para 19%, uma das maiores disparidades do mundo. O crescimento se concentra em setores intensivos em capital controlados por multinacionais estrangeiras: absorvem investimento, empregam poucos, redistribuem menos. O movimento GenZ 212 condensou o desequilíbrio em um slogan: queremos hospitais, não estádios. A OCDE coloca o Marrocos entre os primeiros do mundo em trabalhadores que emigram." },
  { p: "Um contexto que as primeiras reconstruções omitiram: o Marrocos tem eleições gerais em 23 de setembro de 2026. É plausível ler o assalto à cerca — dezenas de milhares de pessoas no próprio dia da Festa do Trono do rei — também como expressão de descontentamento pré-eleitoral, somada aos protestos da Gen Z de outubro de 2025 contra a infraestrutura da Copa do Mundo vista como prioridade errada frente à saúde e à educação. Nenhum fato aqui exposto exige que essa leitura seja verdadeira, mas omiti-la significa perder uma variável tão relevante quanto qualquer ator estrangeiro." },
  { p: "O balanço humano continua sendo o dado que nenhuma narrativa soberana consegue absorver — e permanece, até hoje, em evolução e discordante entre as fontes. O total de entradas, segundo o ministro do Interior espanhol em 4 de agosto, foi de cerca de 72.000 pessoas, das quais 70.000 já haviam retornado ao Marrocos. Do lado dos mortos, a margem se ampliou em vez de fechar: 11 segundo a primeira contagem marroquina, mais de 48.000 devolvidos em 48 horas segundo Madri, 72 vítimas relatadas pela Espanha aguardando verificação conjunta, quase 100 mortos e 50 desaparecidos segundo a polícia espanhola em 6 de agosto, ao menos 141 afogados no quebra-mar segundo a The Economist em 5 de agosto. Sinalizamos a margem em vez de escolher um número: ela própria é o fato, porque um balanço que continua subindo enquanto prosseguem as buscas diz mais do que qualquer cifra definitiva. Um esclarecimento também sobre a composição: o grosso da onda de 30-31 de julho era de cidadãos marroquinos, como documentam tanto Rabat quanto as análises de conteúdo — mas não todos; entre os que permaneciam em Ceuta no início de agosto, segundo a The Economist, a maioria eram migrantes subsaarianos e menores desacompanhados, cerca de 1.100 dos quais destinados à transferência para a Espanha. O quadro correto não é «marroquinos em vez de subsaarianos», mas duas populações distintas em trajetórias diferentes: os marroquinos, repatriáveis rapidamente por acordos bilaterais, saíram da contagem em poucos dias; os migrantes subsaarianos, numa zona cinzenta legal mais complexa, são os que restaram. Quando pessoas arriscam a vida entre arame farpado e mar aberto, estão atribuindo a um país um rating mais honesto que qualquer agência. Votaram com os pés. É o único voto que não pode ser manipulado." },
  { h: "Fato cinco: o balanço dos próprios acusadores — e uma ironia pronunciada sobre os túmulos errados" },
  { p: "Os governos mais estridentes em denunciar Madri merecem a mesma auditoria que exigem dos outros." },
  { p: "A Itália, em 2025, restringiu a cidadania iure sanguinis — decreto assinado pelo mesmo ministro das Relações Exteriores que hoje ataca a regularização espanhola — excluindo a maior parte dos descendentes sul-americanos de emigrantes italianos, à exceção de filhos e netos de quem nasceu na Itália. O mesmo campo político assiste agora à chegada ao Parlamento da iniciativa popular «Remigração e Reconquista», com 150.000 assinaturas: um texto que define a remigração como retorno assistido de estrangeiros legalmente residentes na Itália e que, ao mesmo tempo, propõe apoio estatal ao retorno de descendentes de italianos no exterior." },
  { p: "Os descendentes que esperaram anos nos consulados pela cidadania votavam com os pés rumo à Itália — porta fechada, contabilizados como custo consular. Os estrangeiros que votaram com os pés rumo à Itália e ali construíram uma vida regular são agora, na proposta mais radical, convidados a partir. Diáspora como passivo, população residente como excedente: contabilidade incoerente, péssimo púlpito para dar lições a Madri." },
  { p: "E em 7 de agosto a incoerência encontrou sua imagem mais nítida. Na cerimônia dos 70 anos da tragédia de Marcinelle — onde morreram 136 trabalhadores emigrantes italianos, parte dos 50.000 enviados à Bélgica pelo acordo «homens por carvão» de 1946 — a premiê Meloni declarou que «não há espaço na Europa para quem alimenta canais de imigração clandestina para obter mão de obra barata». Palavras dirigidas a Rabat e aos traficantes. Pronunciadas sobre os túmulos de italianos que foram, em todo sentido material senão no jurídico, exatamente isso: mão de obra barata transferida através de uma fronteira por um acordo escrito para servir à economia de outra nação. Não é preciso mais comentário." },
  { p: "Um último item do balanço, e é a própria Espanha quem o apresenta: ao justificar sua contramedida contra a Itália, o ministério do Interior espanhol citou oficialmente quase meio milhão de imigrantes irregulares chegados à Itália nos últimos cinco anos contra apenas 16.000 repatriações — números que, em ordem de grandeza, confirmam os dados da Frontex do fato dois. Sánchez acrescentou uma acusação mais técnica e verificável: a Itália não cumpriria, desde 2022, o Regulamento de Dublin, transferindo assim pressão migratória adicional para os demais Estados-membros. Não é uma opinião a arbitrar aqui — é uma alegação pontual que mereceria verificação própria — mas o fato de a acusação vir acompanhada de um número e de um artigo de regulamento, em vez de um adjetivo, a coloca numa categoria diferente do resto da polêmica." },
  { h: "Fato seis: os marroquinos já estão aqui — e são a Itália que funciona" },
  { p: "O fato que a narrativa da invasão não consegue digerir, porque a desmonta por dentro." },
  { p: "A comunidade marroquina está entre as maiores, mais antigas e mais enraizadas da Itália: 412.000 residentes em 1º de janeiro de 2025 segundo a Fundação ISMU, terceira nacionalidade depois de romenos e albaneses; 377.554 com permanência regular entre os não comunitários segundo o Ministério do Trabalho, segunda comunidade extra-UE do país. Não episódica: homens sozinhos nos anos 1980, famílias reunificadas nos anos 2000, hoje 82.075 menores, 115.569 estudantes nas escolas italianas, 1.190 casamentos mistos só em 2023. E 27.000 aquisições de cidadania italiana em 2024 — segunda comunidade em naturalizações — depois de mais de 216.000 entre 2006 e 2017." },
  { p: "O dado do ISTAT relançado pelo Il Sole 24 Ore acrescenta a peça que faltava: as chegadas do Marrocos à Itália cresceram quase 50% em 2025 — 36.000 pessoas, segunda nacionalidade por entradas, contadas pelas estatísticas oficiais. O governo mais barulhento sobre a «invasão» de Ceuta preside um país onde os marroquinos são a terceira comunidade nacional, estudam aos 115.000 em suas escolas, casam com seus cidadãos, adquirem sua cidadania num ritmo de 27.000 por ano, e continuam chegando regularmente a um ritmo que cresceu 50%. Os dois fatos não podem ser verdadeiros ao mesmo tempo: ou o Marrocos é um perigo, e então é preciso explicar quarenta anos de integração documentada; ou os números dizem a verdade — a cerca de Ceuta era o cenário de um filme rodado para outro público." },
  { h: "Fato sete: quem acendeu o estopim — e o que segue contestado" },
  { p: "Quem mobilizou dezenas de milhares de pessoas rumo a uma cerca no mesmo dia é a pergunta sobre a qual este dossiê, até hoje, segue mais aberto — e é justo dizê-lo com a mesma honestidade com que tratamos todo o resto." },
  { p: "O piso judicial está documentado: dezenas de contas anônimas repetiam a mesma mensagem — a fronteira está aberta, quem cruzar fica — e perfis com milhares de seguidores publicavam os pontos de travessia. A Audiencia Nacional abriu uma investigação sobre redes criminosas, traficantes ou uma estratégia coordenada; Rabat acusou as «máfias da desinformação»; em 5 de agosto, 25 pessoas estavam indiciadas. Já circula a convocação de uma nova entrada em massa para 15 de agosto, até agora sem confirmação oficial de nenhum dos dois lados." },
  { p: "Sobre quem está por trás, porém, existem duas leituras críveis que não coincidem, e o fact-checking não escolhe pela confiança. Nathalie Tocci (IAI / Johns Hopkins SAIS), em 5 de agosto na Sky TG24, propôs uma taxonomia de três atores: Estados terceiros que militarizam a migração para obter vantagens, como Tunísia, milícias líbias e Turquia antes do Marrocos; atores globais — as origens de parte da desinformação em circulação remontavam, em sua avaliação, a Moscou, ao mundo MAGA americano, a Israel — visando dividir a Europa a partir da Espanha de Sánchez; e as direitas internas cavalgando o que ela chama de «falsa crise». Seu ponto mais afiado é verificável por qualquer um que olhe um mapa: chegar à Espanha continental a partir de Ceuta é mais difícil do que a travessia direta do Marrocos, porque os controles de saída do enclave são mais rigorosos. Quem grita invasão-via-Ceuta descreve a rota que nenhum migrante racional escolheria." },
  { p: "Uma pesquisa original da estudiosa Myriam Cherti, publicada em 6 de agosto, complica porém essa leitura. Analisando 180 posts de alto engajamento do precedente de 2024, Cherti encontrou mais de 80% do conteúdo em darija marroquina — conversa local, não mensagem para o exterior — e concluiu que a mobilização foi ação coletiva viabilizada digitalmente, não uma campanha dirigida centralmente. A Associated Press constatou que as acusações de coordenação por traficantes ou de orquestração deliberada do Estado marroquino «não foram publicamente comprovadas». Até a investigação interna do Ministério do Interior marroquino, embora descarte fatores espontâneos e aponte para desinformação e traficantes, não chega a provar um desenho estatal. Duas leituras críveis, não totalmente sobrepostas: a de Tocci sobre atores externos na campanha e em seus desdobramentos políticos, a de Cherti sobre a ausência de um mentor por trás da mobilização original. Sobre o quem, o dossiê público permanece aberto — e a cautela se estende a ambas as atribuições." },
  { p: "O que aconteceu na praça, por outro lado, não exige cautela: é reportagem direta. No sábado à noite, centenas de moradores de Ceuta foram às ruas contra o Núcleo Nacional, movimento de extrema direita espanhol; no dia seguinte, o agitador Vito Quiles apareceu na Plaza de los Reyes com o Save Europe Act — cofundado pelo austríaco Martin Sellner, com ativistas da Generation Identity vindos da Alemanha — e um protesto de bairro se dividiu com sua presença: «ele veio provocar e nos dividir», nas palavras dos moradores citadas pelas agências. A faixa deles — «Sánchez must go, Spain needs remigration» — estava em inglês; os ceutis que a contestavam respondiam em espanhol. Uma faixa é um ato de comunicação, e seu destinatário se deduz da língua: quem escreve em espanhol em Ceuta fala com Ceuta, quem escreve em inglês fala com a câmera e com o algoritmo. Acrescente-se que Ceuta é cerca de metade de origem marroquina e muçulmana: um erro de casting antes ainda de ser político. Segundo a The Economist, agitadores de extrema direita vindos de toda a Europa espalharam vídeos com a retórica da «substituição étnica»; ao coro se juntaram também Elon Musk e o vice-presidente americano J.D. Vance. Os atores externos, desta vez, vieram pessoalmente — e seguem sendo os únicos, em toda esta história, a terem cruzado mais fronteiras do que os migrantes." },
  { p: "Uma última observação fecha o fato sete, e é talvez a mais afiada de todo o dossiê: a União Europeia não trata todas as alavancas migratórias da mesma forma. Desde 2021, a Bielorrússia leva migrantes do Oriente Médio de avião para a Polônia e países vizinhos como retaliação política; a UE classificou isso como ato de guerra híbrida e endureceu as sanções contra Minsk. O Marrocos, em 2021, já havia deixado cerca de 8.000 pessoas entrarem em Ceuta em retaliação pela hospitalidade médica espanhola ao líder da Frente Polisário — um precedente direto do que aconteceu este ano. No entanto, observa a The Economist, «não há prova clara de que o Marrocos tenha orquestrado o movimento de migrantes», embora «seus agentes de segurança certamente os deixaram passar» — e os governos europeus, mesmo assim, saudaram a «cooperação» marroquina, reservando a hostilidade para traficantes anônimos e posts nas redes. A diferença de tratamento não é acidental: a UE precisa da cooperação do Marrocos também na rota, bem maior, das Ilhas Canárias. O analista de Oxford Ruben Andersson resume assim: a externalização de fronteiras «cria um incentivo para países terceiros fomentarem crises — e se oferecerem para resolvê-las». A especialista em migrações Gemma Pinyol-Jiménez sintetiza todo o episódio numa frase que serve como fechamento deste fato: «Não foi principalmente uma crise migratória. Foi um episódio geopolítico.»" },
  { h: "Fato oito: o espelho — e o resultado é zero" },
  { p: "O último capítulo, cronologicamente, é também o mais notável. Depois que Roma rejeitou o ultimato espanhol — retirar os controles até 9 de agosto, sob pena de «medidas proporcionais» —, a Espanha ativou controles recíprocos sobre chegadas da Itália a partir da meia-noite de 8 de agosto, válidos até 7 de setembro, justificados oficialmente pela «persistente pressão migratória irregular» italiana. Um detalhe merece registro na coluna da auditoria: a data de 15 de agosto invocada por Palazzo Chigi como seu próprio prazo de revisão não é um anúncio espanhol formal — é, segundo a imprensa dos dois países, um «boato» nas redes sociais no Marrocos que a Guarda Civil considera plausível para uma nova tentativa. Um governo que suspendeu o Schengen citando, entre outros motivos, uma campanha de desinformação está agora justificando a duração dessa suspensão com um rumor não confirmado do mesmo tipo." },
  { p: "Mas o dado mais duro, uma semana depois, é um resultado, não um procedimento: nenhum imigrante irregular vindo de Ceuta foi identificado nos controles italianos. Zero. E as mesmas fontes que relatam o dado observam que, de todo modo, seria impossível estabelecer, para os cidadãos norte-africanos interceptados nos aeroportos, se sua entrada estava de alguma forma ligada à crise de Ceuta. O vice-premiê Salvini declarou estar bloqueando «dezenas de irregulares vindos da Espanha»: as duas afirmações — zero ligados a Ceuta, dezenas bloqueados em geral — não se excluem mutuamente, mas a distância entre o que a medida deveria prevenir e o que efetivamente interceptou continua sendo o fato mais eloquente de todo o episódio. O ministro do Interior espanhol Grande-Marlaska, após a videoconferência dos ministros da UE, disse sem rodeios: foi reconhecido que «a zona Schengen nunca esteve em perigo», e pediu a revogação imediata dos controles italianos porque não correspondem ao que foi acordado naquela reunião. Na frente doméstica italiana, as oposições — de Fratoianni a Magi a Calenda — usaram registros diferentes mas a mesma substância: propaganda, jogada de valentão, cálculo eleitoral. Não adotamos a linguagem deles, mas registramos que a crítica não vem só de fora: atravessa também o debate interno italiano." },
  { h: "O método, outra vez" },
  { p: "Oito fatos, três países, um único critério: os documentos antes das declarações — e a disposição de corrigir o próprio dossiê quando chega uma evidência melhor, como fizemos no fato sete. As empresas brasileiras votaram com os pés contra o Custo Brasil ao atravessar a Ponte da Amizade; os marroquinos votaram com os pés contra seu milagre de duas velocidades; os descendentes de italianos votaram com os pés rumo a uma pátria que parou de responder; e até os provocadores de Ceuta, no fim, votaram com os pés — os únicos a terem cruzado mais fronteiras do que os migrantes, para narrar uma crise que os próprios migrantes não reconheciam." },
  { p: "Em todos os casos, o poder respondeu aos pés com retórica em vez de reformas." },
  { p: "Os fatos e números vêm de fontes públicas: o Código de Fronteiras Schengen e o Ato de Adesão da Espanha (1991); declarações da Comissão Europeia (julho–agosto de 2026); TJUE, processos apensos C-368/20 e C-369/20 (2022); HCP e OCDE sobre o mercado de trabalho marroquino; Fundação ISMU, Relatório de Migrações 2026; Ministério do Trabalho italiano, «A comunidade marroquina na Itália — Relatório anual 2025»; ISTAT, relatório de migrações 2025; autos e coberturas sobre a investigação da Audiencia Nacional e as manifestações de Ceuta (agosto de 2026); entrevista de Nathalie Tocci à Sky TG24 «Timeline», 5 de agosto de 2026; pesquisa e análise de Myriam Cherti, Bloomberg, 6 de agosto de 2026; declaração do Ministério do Interior marroquino via MAP, reproduzida pela Bloomberg, 3 de agosto de 2026; imprensa italiana e espanhola sobre os controles recíprocos do Schengen e a cerimônia de Marcinelle (Il Post, Sky TG24, Il Foglio, ANSA, 7–8 de agosto de 2026); The Economist, «Rushing the gates» (31 de julho de 2026) e «The wrong lessons» (5 de agosto de 2026); declarações do ministro do Interior espanhol Grande-Marlaska e coberturas da videoconferência dos ministros da UE de 4 de agosto (Sky TG24); declarações de Matteo Salvini e da oposição italiana, e nota do ministério do Interior espanhol sobre a contramedida de 8 de agosto (LaPresse, Adnkronos, Europa Today, 7–8 de agosto de 2026)." },
  { p: "Business Matching Global — inteligência de mercado e orquestração de negócios no corredor Europa–Brasil. Sem dados, você é apenas mais uma pessoa com uma opinião. Nós preferimos ser apenas mais uma pessoa com os dados." },
];

export default function CeutaBR() {
  const { lang, setLang } = useT();
  const article = getArticleBySlug("ceuta_br");
  const desc =
    "O que a crise de Ceuta realmente diz: o status especial fora de Schengen, os dados da Frontex, o Marrocos de duas velocidades e os fluxos que verificam o que os comunicados negam.";
  useCanonical("/ceuta", {
    title: `${TITLE} — Business Matching Global`,
    description: desc,
    type: "article",
  });

  useEffect(() => {
    const previous = lang;
    if (lang !== "pt") setLang("pt");
    return () => {
      if (previous !== "pt") setLang(previous);
    };
  }, [lang, setLang]);

  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <div className="flex items-center justify-between gap-4 mb-8">
          <Link
            to="/analysis"
            className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            Voltar às análises
          </Link>
          <LangSwitcher to="/ceuta" />
        </div>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">{TITLE}</h1>
          <p className="text-xs text-foreground/70 mb-2">Business Matching Global</p>
          <p className="text-xs text-foreground/70 mb-10 tabular-nums">{article?.date}</p>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
          <ShareBlock title={TITLE} />
        </article>
        <AnalysisFooter />
      </div>
    </main>
  );
}