import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useEffect } from "react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";
import { AnalysisFooter } from "@/components/AnalysisFooter";
import { useCanonical } from "@/lib/useCanonical";
import { ShareBlock } from "@/components/ShareBlock";
import { LangSwitcher } from "@/components/LangSwitcher";

type Block = { h: string } | { p: string };

const TITLE = "Voting with Their Feet";

const BACK = {
  it: "Torna alle analisi",
  en: "Back to analysis",
  pt: "Voltar às análises",
} as const;

const body: Block[] = [
  { p: "What the Ceuta crisis tells us — once the noise is filtered out" },
  { p: "\"Only 17 kilometers separate us, but on the plane of mutual incomprehension it feels like 17 centuries.\" — Rachid Niny, editor of Al Akhbar, former undocumented migrant in Spain" },
  { p: "Some texts are written to persuade. This one is written to verify. Since late July, an unusual volume of confident claims has circulated across European capitals and social feeds — many checkable, many baseless. What follows is not a defense of any government. It is an exercise in rebuilding the dossier, because in market intelligence, as in politics, it is verified facts — not statements — that say what actually happened. The dossier has grown in under two weeks: we rewrite it whole rather than stacking updates, because an audit that accumulates without reordering itself stops being readable." },
  { h: "Fact one: Ceuta has never been part of the Schengen Area" },
  { p: "The claim that dominated the first days — that migrants entering Ceuta had \"breached Schengen\" and could walk freely to Milan or Helsinki — collapses at the first check of the law." },
  { p: "When Spain joined the Schengen Agreement in 1991, a declaration specific to Ceuta and Melilla was annexed to its Act of Accession, excluding the two North African cities from the free-movement regime. The special status remains in force today, in Article 41 of the Schengen Borders Code. In practice: entering Ceuta grants no right to remain in Spain, to reach the Iberian Peninsula, or to circulate in Europe. Exit controls between Ceuta and the mainland have existed since 1991." },
  { p: "It is worth recalling how that declaration came about, because it was neither a technical detail nor a simple imposition: a combination of factors determined it — a three-layer compromise in which each party obtained what it needed. Spain asked for and obtained the local border-traffic regime — visa exemption for Moroccans resident in the neighboring provinces of Tetouan and Nador — without which the economy of the two enclaves, which lives on cross-border workers and daily commerce, would have collapsed. The Schengen partners, wary of two African doors opening onto the common space, demanded in exchange mandatory identity checks on all maritime and air connections to the peninsula. And the ambiguity over status suited even Morocco, which does not recognize the two cities and would have experienced their full constitutionalization as an EU external border as a provocation. Thirty-five years later, the irony is textbook: it is precisely the filter Madrid endured as a partners' condition that has saved it — its best documentary defense against the charge of having let 70,000 people into Europe. (The reconstruction of the negotiating roles is consolidated diplomatic history, not a published act: we report it as such.)" },
  { p: "The numbers confirm the system worked as designed. Of the roughly 50,000–60,000 people who entered in under 24 hours, Spanish authorities report over 48,000 were returned to Morocco within 48 hours. On 1 August, Commission President von der Leyen — after a call with Commissioners Brunner and Šuica — stated publicly that the vast majority had already returned and that no one had reached mainland Spain or the rest of the EU." },
  { p: "One government nevertheless suspended Schengen with Spain for a month from 1 August, reinstating selective checks at maritime and air borders — over a border Schengen never covered. Brussels noted the suspension was announced before any formal notification reached the Commission, and an EU spokesperson publicly asked Rome to explain how the crisis constituted a security threat — the legal precondition for reinstatement. The same government then co-promoted, with Denmark, a letter signed by 22 European heads of state and government calling for coordination and a united European response: unilateral suspension without notification on one side, a call for coordination on the other, in the same news cycle. One gesture contradicts the other." },
  { p: "A more historical than legal element completes the picture, and it must be stated precisely because the Italian government has raised an argument that deserves an answer. It is true, as Minister Piantedosi recalled in his parliamentary hearing, that internal controls between member states have existed for years, \"including toward Italy\": Austria at the Brenner, France at Ventimiglia. But those controls respond to documented flows transiting through another member state — people counted, routes traced, notifications filed. The novelty of the Italian-Spanish case is different, and twofold: it is the first suspension adopted for retaliatory purposes out of a bilateral political dispute, with crossed ultimatums and a reciprocal countermeasure — and the first adopted at zero flows, against a movement the Commission certifies never existed. The Brenner filters a real transit; the device aimed at Spain filtered a nonexistent one. It is not a precedent on controls: those already existed. It is the precedent on the use of Schengen as an instrument of pressure between two member states — and, at that, between two of the countries that joined the free-movement area first after the five original 1985 signatories: Italy in 1990, Spain in 1991." },
  { p: "Two clarifications complete fact one. Prime Minister Meloni's initial demand — Spain's expulsion from the entire Schengen area — was itself technically unworkable: it cannot happen against Spain's will, The Economist notes. What Italy actually did was more modest, spot checks at ports and airports — the gap between the demand and the measure is already a clue to the register (domestic politics) in which this played out. And above all: on 4 August, at the emergency videoconference of EU interior ministers, the European level had already closed the alarm. Commissioner Brunner declared \"full solidarity with Spain\"; all talk of expulsion from Schengen vanished from the communiqués, replaced by the usual programmatic points on borders, traffickers and returns. While Rome kept its bilateral suspension in place — and the following week Madrid answered in kind — the European institution had already moved on. From that point, the Rome-Madrid standoff is no longer an EU crisis: it is a two-party dispute, kept alive by whoever chose to keep it alive." },
  { h: "Fact two: the regularization has nothing to do with the fence" },
  { p: "A second claim linked the crisis to Spain's regularization of roughly 500,000 migrants, presented as an open invitation. The mechanics say otherwise: the process requires documented prior residence, a clean record, a work contract or sufficient means. Whoever climbed a fence in July 2026 is excluded by definition. One clarification on the number itself: 500,000 was the figure Spanish authorities expected, not the total regularized — applications actually received numbered 1.2 million, of which how many were approved is not publicly known. Even on the larger figure, this remains a documented application process with requirements — not an open gate for whoever arrives by swimming. Spanish authorities also documented a disinformation campaign that misrepresented a Supreme Court ruling on returns to convince people that reaching Ceuta guaranteed permanence. It does not; the ruling changed procedure, not rights of stay." },
  { p: "That ruling is worth reading, because it is the true technical trigger of this affair and has been cited by everyone while almost never being described. It dates from 8 July 2026, Fifth Section of the Contentious-Administrative Chamber of the Tribunal Supremo, and arises from the State Attorney's appeal in the case of an Algerian national intercepted at sea on 14 November 2024 while attempting to swim to Ceuta, and handed over immediately to Morocco. The Court holds that the \"rechazo en frontera\" — the immediate expulsions provided for by the Tenth Additional Provision of the aliens law — does not apply to those arriving by swimming, because they cross no \"containment element\" of the border: drones, thermal cameras and sensors, the court argues, perform surveillance and alert functions, not material containment, and therefore do not trigger the exceptional regime. Such persons must instead receive the ordinary return procedure of Article 58.3 of Organic Law 4/2000. The ruling does not amend the aliens law, does not declare immediate expulsions illegal, and grants no right to stay: it changes which procedure applies, and with it the obligation to open an individual file — a step necessary, among other things, to identify minors and vulnerable persons." },
  { p: "And here lies the detail no news coverage has connected. The same ruling specifies that \"nothing would prevent\" applying immediate expulsions were \"containment elements at sea protecting the border line\" to be installed. Three weeks later, Spain laid a 500-meter floating barrier at the Tarajal. That barrier, which the press narrated as a physical deterrent, is also — and perhaps above all — a legal instrument: it creates the maritime containment element the Court had indicated as the condition for restoring the immediate pushback regime. The Spanish government did not circumvent the ruling: it executed its implicit instructions. It is a rare and instructive case of legal engineering built in the physical world — and proof that the Spanish state responded to the crisis by working on the law, while elsewhere the work went into press releases." },
  { p: "The Frontex figures cited by the Spanish government on irregular entries 2021–2026 rank the routes as follows: Italy roughly 478,600; the Western Balkans 340,600; Greece 259,800; Spain 234,760. The country that suspended Schengen with Spain registered roughly double Spain's irregular entries over the same period." },
  { p: "It is worth noting how that rebuttal was framed. While other capitals escalated — summits, closed borders, summoned ambassadors — the Spanish prime minister's reply was a post listing those Frontex figures, introduced by a single remark: solidarity and empathy are optional, respect for treaties and data is not. A table on one side, a diplomatic escalation on the other." },
  { p: "One last observation on the \"pull factor,\" and it comes from the market, not from politics. Latin American social feeds currently carry the advertisements of private migration agencies selling precisely the Spanish route: residence via the non-lucrative or digital-nomad visa, and — thanks to the preferential track the Código Civil has reserved for decades to Ibero-American citizens — the possibility of applying for citizenship after just two years, \"comment España and book your appointment.\" With the simplifications typical of marketing (the two years are the requirement to file the application; exams and years of backlog follow), but the point is another: look at whom this industry addresses. Those who can prove an income, fill out a form, book a cita — the legal, documented, by-appointment channel. The Spanish pull factor exists, and it is literally for sale: but its customer is not whoever swims around a breakwater — who is, as shown, excluded from that route by definition. The real pull factor produces case files, not fence-rushes. And one detail anticipates fact five: among these agencies' clients now increasingly figure the South American descendants of Italians turned away by Italy's 2025 restriction — the market has simply moved to the country that kept its legal doors open. (The advertisement is cited as an observed market phenomenon, not as a normative source.)" },
  { h: "Fact three: the Spanish model, imperfect but measurable" },
  { p: "Spain is the fastest-growing large economy in the eurozone, around 3% annually for two consecutive years, while Germany and Italy hover near zero. The drivers: record tourism, effective absorption of Next Generation EU funds, cheap renewables and — the irony of the polemic — immigration itself, which has sustained employment and consumption in an aging continent. Real weaknesses exist: a severe housing crisis, low hourly productivity, residual precarity. But \"imperfect and growing 3%\" is a different sentence from the one being written about Spain these days." },
  { h: "Fact four: Morocco is not an Eldorado — and an election explains part of why" },
  { p: "Morocco has spent years promoting its image as an African success story: GDP growth above 3%, cumulative expansion of 22% since 2019, exports approaching Italy's automotive output, Kenitra-Marrakech high-speed rail, the 2030 World Cup with the largest stadium in the world." },
  { p: "The other side of the ledger: roughly two-thirds of Moroccan employment is informal — 67.6% per the HCP/ILO satellite account, over 67% per the OECD, up to 77% in other estimates. Unemployment among 15–24-year-olds exceeded 36% in 2024–2025; under the 2026 \"strict sense\" methodology the official rate falls to 29%, but overall youth labor underutilization remains at 45%. Female participation fell from 28% in 2000 to 19%, among the widest gaps in the world. Growth concentrates in capital-intensive sectors controlled by foreign multinationals: they absorb investment, employ few, redistribute less. The GenZ 212 movement condensed the imbalance into a slogan: we want hospitals, not stadiums. The OECD places Morocco near the top globally for departing workers." },
  { p: "A context the early accounts omitted: Morocco holds general elections on 23 September 2026. It is plausible to read the rush on the fence — tens of thousands of people on the king's own Throne Day — also as an expression of pre-election discontent, layered on the October 2025 Gen Z protests against World Cup infrastructure seen as the wrong priority over health and education. No fact stated here requires this reading to be true, but omitting it means losing a variable as relevant as any foreign actor." },
  { p: "The voice that closes this fact, however, is not European — and that is why we save it for last. Rachid Niny, editor of Al Akhbar and of TeleMaroc, arrived in Spain in 1997 with a one-month visa to cover a congress in the Canary Islands: he never went, headed to Benidorm instead, and stayed three years as an undocumented migrant, washing dishes and cleaning pigsties after a master's degree in contemporary poetry. Out of it came Diario de un ilegal, the first testimony in Arabic on the experience of Moroccan migrants in Spain, a book built around a single image: the eldorado that vanishes the moment you reach it. Twenty-seven years later, interviewed by La Stampa in Ras Kebdana, he says nothing that happened at Ceuta is new — \"as long as there is supply and demand, these scenes will not end: the irregular-migration market knows no recession\" — and that he fears the worst if there keeps growing \"this enormous reserve of young people willing to bet their lives on a paradise that exists only in their imagination.\"" },
  { p: "His balance sheet of his own country matches this analysis's numbers, but he phrases it better than any indicator: in 1997 Morocco was drowning in debt and unemployment broke every record; today there are highways, renewables, competitive ports and growth close to 5%, but the fruits do not reach those at the bottom of the social ladder. \"Yesterday Morocco risked cardiac arrest from debt and stagnation. Today it grows, foreign investment pours in, and yet it risks a social cardiac arrest.\" On Ceuta's message to Morocco's ruling class he is blunter still: \"you have a time bomb called youth, and you must defuse it before it destroys everything.\" The emergency, for him, is the failure of public schooling — some 300,000 students drop out every year, swelling an army of adolescents without diplomas — and a minimum wage around 300 euros: \"people must feel the growth in their own pockets,\" he says, proposing to raise it to at least 500, because \"if you think the cost of education is too high, try the cost of ignorance.\"" },
  { p: "Three of Niny's observations deserve separate registration, because they correct as many shortcuts of the European narrative. First: it was not only poverty that went to Ceuta. Among those who entered were factory workers, hotel staff, bakery and café employees; some entered the water still in their work clothes, one with a bow tie around his neck. In the factories, he says, people quit over wages disproportionate to the effort: \"people are no longer willing to accept slavery in the workplace.\" Second, on social media — and it dovetails with Cherti's research cited further on: \"there is a global epidemic called influencers\" in a country where 55% of people aged 18 to 29 dream of emigrating, and among those who entered Ceuta were influencers who turned the crossing into content with millions of views, becoming models for other young people. Third, addressed to Europe, and standing as a counter-thesis to fact one: \"the security of each country's borders cannot be delegated to a third party,\" and Europe \"must stop treating us as the gendarme of its own borders\" — the same externalization that, per the Oxford analyst cited further on, creates the incentive to stir up crises and then offer to resolve them. He closes with the line this dossier has chosen as its epigraph: between the two shores \"only 17 kilometers separate us, but on the plane of mutual incomprehension it feels like 17 centuries.\"" },
  { p: "And finally the line that connects today's Morocco to yesterday's Italy, spoken by a man who came home and chose to stay: \"I take my hat off to the migrants who decide to sacrifice all this. It takes great courage to leave everything behind and emigrate. That is what Europeans do not see — or perhaps have forgotten.\" Fact five, below, shows how literally they have forgotten." },
  { p: "The human toll remains the datum no sovereign narrative can absorb — and it is, as of today, still evolving and discordant across sources. Total entries, per the Spanish interior minister on 4 August, were roughly 72,000, of which 70,000 had already returned to Morocco. On the death toll, the range has widened rather than closed: 11 per Morocco's initial count, over 48,000 returned within 48 hours per Madrid, 72 fatalities reported by Spain pending joint verification, close to 100 dead and 50 missing per Spanish police on 6 August, at least 141 drowned at the breakwater per The Economist on 5 August. We flag the range rather than choose a number: the range is itself the fact, because a toll that keeps rising as searches continue says more than any final figure. One clarification on composition too: the bulk of the 30–31 July wave were Moroccan nationals, as both Rabat and content analyses document — but not all; among those remaining in Ceuta in early August, per The Economist, the majority were sub-Saharan migrants and unaccompanied minors, about 1,100 of whom were slated for transfer to Spain. Here too the numbers diverge by source and date, and we record the range: on 13 August, in his hearing, Minister Piantedosi spoke of at least 6,000 people still in the exclave — \"though some sources speak of over 11,000\" — mostly sub-Saharan, for whom neither readmission nor return to Morocco appears practicable, and of over 1,300 unaccompanied minors who cannot be repatriated, while Spanish local estimates in the preceding days stopped at 3,000–5,000. La Stampa devoted a separate piece to the 862 children still awaiting placement, and from the city Monica Perosino's reportage records the level the emergency has reached — \"we no longer know where to put the bodies\" — while noting the silence imposed on the Moroccan side. The correct picture is not \"Moroccans instead of sub-Saharans\" but two distinct populations on different trajectories: Moroccans, rapidly repatriable under bilateral agreements, dropped out of the count within days; sub-Saharan migrants, in a more complex legal gray zone, are who remained. When people risk their lives between razor wire and open water, they are assigning a country a rating more honest than any agency's. They voted with their feet. It is the one ballot that cannot be spun." },
  { h: "Fact five: the accusers' own ledger — and an irony spoken over the wrong graves" },
  { p: "The governments loudest in denouncing Madrid deserve the same audit they demand of others." },
  { p: "Italy, in 2025, restricted iure sanguinis citizenship — a decree signed by the same foreign minister now attacking Spain's regularization — cutting off most South American descendants of Italian emigrants, barring children and grandchildren of the Italy-born. The same political camp now watches the popular initiative \"Remigration and Reconquest\" arrive in Parliament with 150,000 signatures: a text defining remigration as the assisted return of foreigners legally resident in Italy, while simultaneously proposing state support for the return of Italian descendants abroad." },
  { p: "Descendants who spent years queuing at consulates for citizenship were voting with their feet toward Italy — door closed, booked as a consular cost. Foreigners who voted with their feet toward Italy and built regular lives there are now, in the most radical proposal on the table, invited to leave. Diaspora as liability, resident population as surplus: incoherent accounting, a poor pulpit from which to lecture Madrid." },
  { p: "And on 7 August the incoherence found its sharpest image. At the ceremony marking the 70th anniversary of the Marcinelle mining disaster — where 136 Italian emigrant workers died, part of the 50,000 sent to Belgium under the 1946 \"men for coal\" accord — Prime Minister Meloni declared there is \"no room in Europe for those who feed channels of illegal immigration for cheap labor.\" Words aimed at Rabat and at traffickers. Spoken over the graves of Italians who were, in every material sense if not the legal one, exactly that: cheap labor moved across a border by an accord written to serve someone else's economy. No further comment is needed." },
  { p: "One last entry in the ledger, and Spain itself supplies it: in justifying its countermeasure against Italy, the Spanish interior ministry officially cited nearly half a million irregular immigrants arrived in Italy over the past five years against just 16,000 returns — figures that, in order of magnitude, confirm the Frontex data in fact two. Sánchez added a more technical, checkable accusation: that Italy has not complied with the Dublin Regulation since 2022, offloading additional migratory pressure onto other member states. This is not an opinion to referee here — it is a specific claim that would merit its own verification — but the fact that the accusation arrives with a number and a regulation article, rather than an adjective, places it in a different category from the rest of the polemic." },
  { h: "Fact six: Moroccans are already here — and they are the Italy that works" },
  { p: "The fact the invasion narrative cannot digest, because it dismantles it from within." },
  { p: "The Moroccan community is among the largest, oldest and most rooted in Italy: 412,000 residents as of 1 January 2025 per the ISMU Foundation, third nationality after Romanians and Albanians; 377,554 legal permit holders among non-EU citizens per the Labour Ministry, the country's second non-EU community. Not episodic: men arriving alone in the 1980s, families reunited in the 2000s, today 82,075 minors, 115,569 students in Italian schools, 1,190 mixed marriages in 2023 alone. And 27,000 acquisitions of Italian citizenship in 2024 — the second community by naturalizations — after over 216,000 in 2006–2017." },
  { p: "The ISTAT figure relaunched by Il Sole 24 Ore adds the missing piece: arrivals from Morocco to Italy grew almost 50% in 2025 — 36,000 people, second nationality by entries, counted by official statistics. The government loudest about the Ceuta \"invasion\" presides over a country where Moroccans are the third national community, where 115,000 study in its schools, marry its citizens, acquire its citizenship at a pace of 27,000 a year, and keep arriving regularly at a rate that grew 50%. The two facts cannot both be true: either Morocco is a danger, in which case forty years of documented integration need explaining; or the numbers are right — the Ceuta fence was the set of a film shot for a different audience." },
  { h: "Fact seven: who lit the fuse — and what remains contested" },
  { p: "Who mobilized tens of thousands of people toward one fence on the same day is the question on which this dossier, as of today, remains most open — and it is right to say so with the same honesty applied to everything else." },
  { p: "The judicial floor is documented: dozens of anonymous accounts repeated the same message — the border is open, whoever crosses stays — and accounts with thousands of followers published crossing points. The Audiencia Nacional opened an investigation into criminal networks, traffickers or a coordinated strategy; Rabat blamed \"disinformation mafias\"; as of 5 August, 25 people stand indicted. A call for a new mass entry on 15 August is already circulating, so far without official confirmation from either side." },
  { p: "On who is behind it, though, two credible readings do not coincide, and fact-checking does not choose on trust. Nathalie Tocci (IAI / Johns Hopkins SAIS), on 5 August on Sky TG24, proposed a three-actor taxonomy: third states weaponizing migration for leverage, as Tunisia, Libyan militias and Turkey did before Morocco; global actors — the origins of part of the circulating disinformation traced, in her assessment, to Moscow, the American MAGA world, Israel — aiming to divide Europe starting from Sánchez's Spain; and the domestic right riding what she calls a \"fake crisis.\" Her sharpest point is verifiable by anyone looking at a map: reaching mainland Spain from Ceuta is harder than the direct crossing from Morocco, because exit controls from the enclave are stricter. Whoever cries invasion-via-Ceuta describes the route no rational migrant would choose." },
  { p: "Original research by scholar Myriam Cherti, published 6 August, complicates this reading. Analyzing 180 highly engaged posts from the 2024 precedent, Cherti found over 80% of the content in Moroccan Darija — a local conversation, not messaging for abroad — and concluded the mobilization was digitally enabled collective action, not a centrally directed campaign. The Associated Press found claims of trafficker coordination or deliberate Moroccan state orchestration \"had not been publicly substantiated.\" Even Morocco's own Interior Ministry probe, while ruling out spontaneous factors and pointing to disinformation and traffickers, stops short of proving a state design. Two credible readings, not fully overlapping: Tocci's on external actors in the campaign and its political aftermath, Cherti's on the absence of a mastermind behind the original mobilization. On who, the public file remains open — and caution applies to both attributions." },
  { p: "What happened in the square, by contrast, needs no caution: it is direct reporting. On Saturday night, hundreds of Ceuta residents took to the streets against Núcleo Nacional, a Spanish far-right movement; the next day agitator Vito Quiles appeared in Plaza de los Reyes with Save Europe Act — co-founded by Austrian Martin Sellner, with Generation Identity activists arrived from Germany — and a neighborhood protest split over his presence: \"he came to provoke and divide us,\" in the residents' words per the wire services. Their banner — \"Sánchez must go, Spain needs remigration\" — was in English; the Ceutans contesting it answered in Spanish. A banner is an act of communication, and its addressee can be deduced from its language: whoever writes in Spanish in Ceuta is speaking to Ceuta, whoever writes in English is speaking to the camera and the algorithm. Add that Ceuta is roughly half of Moroccan and Muslim origin: a casting error before a political one. Per The Economist, far-right agitators arrived from across Europe spreading \"ethnic replacement\" videos; Elon Musk and US Vice President J.D. Vance joined the chorus too. The external actors, this time, came in person — and remain the only ones in this whole story to have crossed more borders than the migrants." },
  { p: "One last observation closes fact seven, and it may be the sharpest in the whole dossier: the EU does not treat all migratory leverage alike. Since 2021, Belarus has flown Middle Eastern migrants toward Poland and neighboring states as political retaliation; the EU classified it as an act of hybrid warfare and tightened sanctions on Minsk. Morocco, in 2021, had already let roughly 8,000 people into Ceuta in retaliation for Spain's medical hospitality to the Polisario Front's leader — a direct precedent for this year's events. Yet, The Economist notes, \"there is no clear evidence that Morocco orchestrated the movement of migrants,\" while \"its security officials certainly let them stream past\" — and European governments still hailed Moroccan \"cooperation,\" reserving hostility for anonymous traffickers and social posts. The difference in treatment is not accidental: the EU needs Moroccan cooperation on the far larger Canary Islands route too. Oxford analyst Ruben Andersson puts it this way: border externalization \"creates an incentive to third countries to stir up crises — and offer to resolve them.\" Migration expert Gemma Pinyol-Jiménez sums up the whole affair in a line that fittingly closes this fact: \"This was not primarily a migration crisis. It was a geopolitical episode.\"" },
  { h: "Fact eight: the mirror — and the result is zero" },
  { p: "The mirror is perhaps the most striking chapter of the whole affair. After Rome rejected Madrid's ultimatum — lift the checks by 9 August, or face \"proportional measures\" — Spain activated reciprocal controls on arrivals from Italy from midnight on 8 August, valid through 7 September, officially justified by \"persistent irregular migratory pressure\" from Italy. One detail belongs in the audit column: the 15 August date Palazzo Chigi cites as its own review point is not a formal Spanish announcement — it is, per the press in both countries, social-media chatter in Morocco that the Guardia Civil considers plausible for a new attempt. A government that suspended Schengen partly over a disinformation campaign is now justifying the length of that suspension by citing an unconfirmed rumor of the same kind." },
  { p: "But the hardest data point is a result, not a procedure. In the first week, no irregular migrant from Ceuta had been identified at Italian checks: zero. On 13 August, in his hearing before the Schengen Committee, Minister Piantedosi supplied the updated official tally: \"since the reinstatement of controls at the borders with Spain, we have made 3 arrests and turned back, as illegal, 21 third-country nationals, 6 of them Moroccan,\" announcing that the decision will not be reviewed before 15 August \"and in any case only once security risks for Italy are completely excluded.\" Apply the audit's arithmetic to that tally. Twenty-one turn-backs in thirteen days, across all flights and ferries arriving from Spain, is 1.6 people per day; the nature of the three arrests was not specified; and not even the minister claims that a single one of those twenty-one came from Ceuta. Six are Moroccan — but Moroccan does not mean \"from Ceuta\": it is the second nationality by regular entries into Italy, and whoever boards a scheduled flight has already passed the carrier's document check. These are, by every appearance, the ordinary administrative irregulars that any border control intercepts anywhere, every day: the \"zero linked to Ceuta\" figure has not been refuted — it has been repackaged. On the same day, from Ceuta, Minister Grande-Marlaska dismantled the premise of the extension: \"there is no terrorism risk\" linked to the influx, he assured, because the ministry monitors everyone who entered irregularly thanks to cooperation with Morocco — the direct reply to the \"possible terrorist infiltrations\" evoked in Rome. Already after the EU ministers' videoconference he had said plainly that it was acknowledged that \"the Schengen area was never in danger,\" demanding the lifting of the Italian checks. Deputy PM Salvini had meanwhile declared he was blocking \"dozens of irregulars arriving from Spain\": the two sets of claims do not exclude each other, but the gap between what the measure was meant to prevent and what it actually intercepted remains the most telling fact of the whole affair. On the Italian domestic front, opposition figures — from Fratoianni to Magi to Calenda — used different registers but the same substance: propaganda, a bully's move, electoral calculation. We do not adopt their language, but we note the criticism is not only external: it runs through Italy's own domestic debate too." },
  { p: "Finally, a detail of geography completes the arithmetic, and the minister himself certifies its premise: Spain not being a bordering country, the controls are limited to ships and planes. Which means that anyone leaving Spain and crossing France by car, train or bus enters Italy without encountering any Italian control: the Ventimiglia crossing, in the inbound direction, is not covered by the measure. A security device that watches the Barcelona–Fiumicino flight but not the Barcelona–Ventimiglia–Milan train is not a filter with a flaw: it is a filter with the legal bypass built in. Even someone who believed the declared threat would have to conclude that the measure, as designed, could not stop it." },
  { p: "It remains to ask what that measure was, then. Not a migration filter: a device that intercepts zero units of the phenomenon it claims to counter is not a filter. The key lies in the register in which it was communicated — we have mobilized so that no illegal migrant reaches us — which is the same grammar as the external hubs of fact nine: what matters is not how many people the device stops, but that a border be seen being defended. It is the limit case in which the symbolic character of a measure is proven precisely by its ineffectiveness: it does not serve to stop a flow that did not exist; it serves to be shown. The cost, however, is not symbolic at all: a month of reciprocal controls between two of the Union's largest Mediterranean countries, airport queues for the citizens of both, and a precedent that now exists for whoever wishes to use it." },
  { h: "Fact nine: geography as a surrogate for law — and the Danish exception" },
  { p: "A structural fact, which explains why all of this will happen again." },
  { p: "While Ceuta was being debated in terms of suspensions, Europe pressed on with the construction of the same architecture that made the crisis possible: border externalization. External hubs for processing asylum claims have been announced for some twenty years and never truly built — \"if they have never been created, perhaps there is a reason,\" observes Nathalie Tocci, who says she will believe in them \"when I see them.\" The two attempts that got furthest offer useful numbers: the Italy-Albania protocol cost hundreds of millions for centers that stood almost always empty, repeatedly emptied by court rulings and finally converted into detention centers; the British Rwanda scheme was scrapped in 2024 after some £700 million and a handful of voluntary transfers. If the criterion were administrative efficiency, projects with this yield would already have been abandoned. That they are instead being relaunched — this time with hypotheses on Rwanda, Uganda and Ghana, and with pilot projects for the \"return hubs\" of the Chisinau Declaration due by 2027 — indicates the criterion is something else." },
  { p: "What it is, is a matter of interpretation, and we record three readings without choosing one. The first, argued by the promoters, is deterrence: the goal would not be to process many cases but to break the implicit contract with the traffickers — if arriving does not guarantee staying, demand falls. The second is electoral: the center exists to be announced, and its judicial blockage is even functional, since it shifts responsibility onto judges and Brussels. The third is symbolic, and it is the hardest to refute looking at the balance sheets: what matters is not where the claim is examined, but that the claimant not touch national soil — the border as threshold, not as procedure." },
  { p: "Whatever the motivation, fact one of this dossier dismantles their common premise. At Ceuta, physical proximity was total: Spanish territory full, tens of thousands of people inside the boundaries of a European city. Yet no one entered the Schengen area, because the filter that worked was not geographic but legal — a 1991 declaration and the exit controls that flow from it. Externalization buys territory when what is needed is procedure. And in buying it, warns Swedish anthropologist Ruben Andersson (Oxford), it hands third countries the lever: outsourcing \"creates an incentive to third countries to stir up crises — and offer to resolve them.\" Rachid Niny says the same thing from the other shore: the security of each country's borders \"cannot be delegated to a third party,\" and Europe must stop treating Morocco as \"the gendarme of its own borders.\" When the European analyst and the Moroccan newspaper editor converge on the same diagnosis from opposite positions, the datum deserves attention." },
  { p: "One due clarification — and for this dossier's method it is the most important of fact nine. The demand for harder external borders does not belong to a single political family, and treating it as such would be exactly the kind of shortcut we contest here. The 22-leader letter is co-promoted by the social democrat Mette Frederiksen, who went beyond the signature: in a statement to AFP she said it is obvious the EU must weigh all options, \"including a suspension of Schengen cooperation,\" because \"uncontrolled immigration represents a threat to Europe and to Denmark.\" The letter itself, for that matter, is no tepid text: it recognizes that the Spanish Supreme Court ruling \"was used to unleash this attack and abuse our migration and asylum system,\" speaks of hybrid threats, and calls for addressing \"all policies that can act as pull factors, such as the regularization of a very high number of irregular migrants\" — that is, it explicitly attacks the Spanish amnesty. Spain and France did not sign it." },
  { p: "The Danish position, however, is no tactical adaptation of the past week: it dates to 2015 and rests on an explicit argument — that the Nordic model (universal welfare, high wages through collective bargaining, high taxation accepted because everyone contributes) holds only on tight reciprocal obligations, and that low-skilled immigration erodes its fiscal base and its consensus. It is a debatable thesis, and debated: the residential zones classified by residents' origin, the so-called \"jewelry law,\" the return centers have drawn censure from NGOs and European bodies. But it is a thesis, argued for ten years — not a factual claim. And its electoral outcome is verifiable: in Denmark the far right dissolved, the Danish People's Party falling from 21% in 2015 to 2.6% in 2019, while in Sweden, which held the opposite line, the Sweden Democrats became kingmakers." },
  { p: "Here lies the distinction this dossier has insisted on from the start. To argue that external borders must be hardened, or even that Schengen should be suspended, is a political position — harsh, contestable, held by governments of right and left — to be judged on the merits. To say that an invasion of Europe was underway at Ceuta, or that those migrants could pour into Milan or Helsinki, is a factual claim: and on the European Commission's record, it is false. None of the signatories, it must be said, used the word \"invasion\" in official documents — that word came from the agitators who traveled to Ceuta, from the American vice president, and from domestic political messaging. Fact-checking has jurisdiction only over the second type of statement. On the first, the reader will decide alone — which is exactly how it should work." },
  { h: "Fact ten: the claim — and the second window" },
  { p: "The last piece arrived when this dossier was already on its third rewrite, and it gives a visible object to the formula with which migration expert Gemma Pinyol-Jiménez closed fact seven: not a migration crisis, a geopolitical episode." },
  { p: "On 12 August, with the crisis still warm, Moroccan Justice Minister Abdellatif Ouahbi publicly reiterated that Morocco continues to claim Ceuta and Melilla — \"we continue to claim our land; this requires patience, and we want to resolve the problem through dialogue\" — while denying that Rabat needs to resort to immigration to defend its interests. The Spanish reply came from Defense Minister Robles: \"utterly Spanish\" territories, not to be touched. The claim is not new — it remains part of Morocco's official position and nationalist imagination, and in 2022 Rabat went as far as arguing, in a UN communication, that Morocco and Spain share no land border, describing Melilla as occupied territory — but the timing of its resurfacing, twelve days after the rush, is a datum an audit records. As it records the multi-year economic strategy accompanying it: between 2018 and 2019 Rabat closed Melilla's commercial customs post and ended the smuggling trade from Ceuta, and by the end of 2026 the Nador West Med port, near Melilla, will be inaugurated — a commercial asphyxiation of the enclaves conducted with perfectly lawful instruments. In the same span of days, Morocco's National Human Rights Council presented a report accusing Spanish forces of mistreating some of the migrants \"especially in places out of reach of the cameras\" — the same body that in 2022, after the 23 deaths at the Melilla fence, assigned responsibility to the Spanish authorities." },
  { p: "There is then a thread that gives documentary anchorage to the second category of Tocci's taxonomy — the one fact seven had left as an analyst's assessment. American think tanks and Republican politicians have relaunched Moroccan claims over Ceuta and Melilla, describing the two enclaves as Spain's most vulnerable point, against the backdrop of the standoff between Madrid, Washington and Tel Aviv; on 13 July the United States and Morocco signed a memorandum for a joint military facility on Moroccan soil, and analyses from that milieu argue Israel should use its influence in Washington to back Rabat diplomatically. Due precision: public advocacy is not orchestration, and no document links these circles to July's mobilization. But what on 5 August was an analyst's reading now has at least one written, signed and dated expression — and fact-checking archives it as such." },
  { p: "Finally, the second window. The alert for a new mass migration on the night of 14–15 August has risen, and this time the target, per the social chatter, may be Melilla — no longer just Ceuta. Morocco has reinforced borders, ports and stations, monitoring messages calling for gatherings at the Melilla border, and Spain has deployed two Navy frigates at Ceuta alongside the floating barrier, with reinforcements of Guardia Civil, National Police, forensic doctors and magistrates. The chats monitored by the press show the dynamic in real time: the 15th, burned by publicity, shifts; messages circulate pointing to Melilla on different days and warning off Ceuta. It is exactly the mechanism Cherti's research describes at fact seven — peer-to-peer mobilization, sliding dates, no mastermind required — and at once confirmation that the window stays open whatever happens on Ferragosto. Two details close the picture: Spanish Interior Minister Grande-Marlaska declared \"there is no place in Spain, neither in Ceuta nor in Melilla,\" for those entering irregularly; Denmark says it is \"ready to close its borders\" in case of a new wave; Germany confirms that Dublin-based removals to Italy \"will proceed as planned\" — while negotiations continue for a return center in Uganda (fact nine, punctual as clockwork). And the Morocco that on 30 July let people through — its guards stopped patrolling, The Economist documented — today stands guard: the variable that decides whether anything happens on 15 August is not in Madrid, nor in Rome. It is in Rabat, where it has always been." },
  { h: "The method, again" },
  { p: "Ten facts, three countries, one criterion: documents before statements — and the willingness to correct our own dossier when better evidence arrives, as we did on fact seven. Brazilian firms voted with their feet against the Custo Brasil by crossing the Ponte da Amizade; Moroccans voted with their feet against their two-speed miracle; Italian descendants voted with their feet toward a homeland that stopped answering; and even Ceuta's agitators, in the end, voted with their feet — the only ones to have crossed more borders than the migrants, to narrate a crisis the migrants themselves did not recognize." },
  { p: "In every case, power answered the feet with rhetoric instead of reform." },
  { p: "Facts and figures are drawn from public sources: the Schengen Borders Code and Spain's Act of Accession (1991); European Commission statements (July–August 2026); CJEU, joined cases C-368/20 and C-369/20 (2022); HCP and OECD on the Moroccan labor market; ISMU Foundation, Migration Report 2026; Italian Labour Ministry, \"The Moroccan Community in Italy — Annual Report 2025\"; ISTAT, 2025 migration report; court records and reporting on the Audiencia Nacional investigation and the Ceuta demonstrations (August 2026); Nathalie Tocci interview, Sky TG24 \"Timeline\", 5 August 2026; Myriam Cherti research and analysis, Bloomberg, 6 August 2026; Moroccan Interior Ministry statement via MAP, reported by Bloomberg, 3 August 2026; Italian and Spanish press on the reciprocal Schengen checks and the Marcinelle ceremony (Il Post, Sky TG24, Il Foglio, ANSA, 7–8 August 2026); The Economist, \"Rushing the gates\" (31 July 2026) and \"The wrong lessons\" (5 August 2026); statements by Spanish Interior Minister Grande-Marlaska and reporting on the 4 August EU ministers' videoconference (Sky TG24); statements by Matteo Salvini and the Italian opposition, and the Spanish interior ministry's note on the 8 August countermeasure (LaPresse, Adnkronos, Europa Today, 7–8 August 2026); the Rachid Niny interview from Ras Kebdana, Monica Perosino's reportage from Ceuta and the article on the 862 minors (La Stampa, August 2026); Rachid Niny, \"Diario de un ilegal\" (Spanish edition, 2002); Tribunal Supremo, Contentious-Administrative Chamber, Fifth Section, ruling of 8 July 2026 (CGPJ communiqué and reconstructions by El Independiente, Europa Press and elderecho.com); the text of the 22 European leaders' letter (governo.it, 1 August 2026); Mette Frederiksen's statement to AFP (31 July 2026); statements by Abdellatif Ouahbi and Margarita Robles's reply (Libero, Leggo, Euronews, 12–13 August 2026); the preliminary report of Morocco's CNDH (8 August 2026, via Euronews); Alexandre Aublanc, Internazionale (4 August 2026); Il Fatto Quotidiano on the relaunch of Moroccan claims by US neocon circles (1 August 2026); ANSA, Euronews, Sky TG24 and Il Giornale on the Melilla alert and the 14–15 August deployment (7–13 August 2026); Minister Piantedosi's hearing before the Schengen Committee and Grande-Marlaska's statements from Ceuta (ANSA, AGI, Open, Avvenire, Today, Il Foglio, 13 August 2026)." },
  { p: "Business Matching Global — market intelligence and business orchestration, Europe–Brazil corridor. Without data, you're just another person with an opinion. We'd rather be just another person with the data." },
];

export default function Ceuta() {
  const { lang, setLang } = useT();
  const article = getArticleBySlug("ceuta");
  const desc =
    "What the Ceuta crisis actually tells us: Schengen's special status, Frontex data, Morocco's two-speed economy and the migration flows that verify what press releases deny.";
  useCanonical("/ceuta", {
    title: `${TITLE} — Business Matching Global`,
    description: desc,
    type: "article",
  });

  useEffect(() => {
    const previous = lang;
    if (lang !== "en") setLang("en");
    return () => {
      if (previous !== "en") setLang(previous);
    };
  }, [lang, setLang]);

  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <div className="flex items-center justify-between gap-4 mb-8">
          <Link
            to="/analysis"
            className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            {BACK[lang]}
          </Link>
          <LangSwitcher to="/ceuta" />
        </div>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">{TITLE}</h1>
          <p className="text-xs text-foreground/70 mb-10">#CustoBrasil — Business Matching Global · published 2 August 2026, rewritten and updated 13 August 2026</p>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
          <ShareBlock title={TITLE} />
        </article>
        <AnalysisFooter />
      </div>
    </main>
  );
}
