import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useEffect } from "react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";
import { AnalysisFooter } from "@/components/AnalysisFooter";
import { useCanonical } from "@/lib/useCanonical";
import { ShareBlock } from "@/components/ShareBlock";
import { LangSwitcher } from "@/components/LangSwitcher";

type Block = { h: string } | { p: string };

const TITLE = "Votare con i piedi";

const body: Block[] = [
  { p: "#CustoBrasil — Business Matching Global · pubblicato il 02-08-2026, riscritto e aggiornato all'08-08-2026" },
  { p: "Cosa ci dice la crisi di Ceuta — una volta filtrato il clamore" },
  { p: "Alcuni testi sono scritti per persuadere. Questo è scritto per verificare. Da fine luglio, nelle capitali europee e sui social, è circolato un volume insolito di affermazioni categoriche — molte verificabili, molte prive di fondamento. Quanto segue non è la difesa di alcun governo. È un esercizio di ricostruzione del dossier, perché nell'analisi di mercato, come in politica, sono i fatti verificati — non le dichiarazioni — a dire cosa è davvero accaduto. Il dossier, in una settimana, è cresciuto: lo riscriviamo per intero invece di accatastare aggiornamenti, perché un audit che si accumula senza riordinarsi smette di essere leggibile." },
  { h: "Fatto uno: Ceuta non è mai stata nello spazio Schengen" },
  { p: "L'affermazione più diffusa nei primi giorni — che i migranti entrati a Ceuta avessero «violato Schengen» e potessero raggiungere liberamente Milano o Helsinki — crolla al primo controllo della normativa." },
  { p: "Quando la Spagna aderì all'Accordo di Schengen nel 1991, al suo Atto di adesione fu allegata una dichiarazione specifica su Ceuta e Melilla, che esclude le due città nordafricane dal regime di libera circolazione. Lo status speciale è ancora in vigore, oggi nell'articolo 41 del Codice frontiere Schengen. In concreto: entrare a Ceuta non dà diritto di restare in Spagna, raggiungere la penisola iberica o circolare in Europa. I controlli d'uscita tra Ceuta e la terraferma esistono dal 1991." },
  { p: "I numeri confermano che il sistema ha funzionato come previsto. Delle circa 50.000–60.000 persone entrate in meno di 24 ore, le autorità spagnole riferiscono che oltre 48.000 sono state rimpatriate in Marocco entro 48 ore. Il 1° agosto la presidente della Commissione von der Leyen — dopo una videochiamata con i commissari Brunner e Šuica — ha dichiarato pubblicamente che la stragrande maggioranza degli entrati era già rientrata e che nessuna persona aveva raggiunto la Spagna continentale o il resto dell'UE." },
  { p: "Un governo ha comunque sospeso Schengen con la Spagna per un mese, dal 1° agosto, ripristinando controlli selettivi alle frontiere marittime e aeree — su una frontiera che Schengen non ha mai coperto. Bruxelles ha osservato che la sospensione fu annunciata prima che qualsiasi notifica formale giungesse alla Commissione, e un portavoce UE ha chiesto pubblicamente a Roma di spiegare in che modo la crisi costituisse una minaccia alla sicurezza — il presupposto giuridico richiesto per il ripristino. Lo stesso governo ha poi co-promosso, con la Danimarca, una lettera firmata da 22 capi di Stato e di governo europei che chiedeva coordinamento e una risposta europea unita: sospensione unilaterale senza notifica da un lato, richiesta di coordinamento dall'altro, nello stesso ciclo di notizie. Uno dei due gesti contraddice l'altro." },
  { p: "Un elemento più storico che giuridico completa il quadro. Nei quarant'anni di applicazione del meccanismo, il ripristino dei controlli interni è sempre stato una risposta a pressioni da paesi terzi — Libia, Bielorussia, la rotta balcanica — mai una misura punitiva contro un altro Stato membro. La sospensione italiana, e quanto avvenuto dopo (vedi fatto otto), non è dunque solo procedurale: è un precedente in sé, il primo caso di Schengen usato come arma tra due membri fondatori dello spazio di libera circolazione." },
  { p: "Due precisazioni completano il fatto uno. La richiesta iniziale della premier Meloni — l'espulsione della Spagna dall'intera area Schengen — era essa stessa tecnicamente irrealizzabile: non può avvenire contro la volontà della Spagna, nota l'Economist. Ciò che l'Italia ha effettivamente fatto è stato un provvedimento più modesto, controlli a campione in porti e aeroporti — la distanza tra la richiesta e la misura è già un indizio del registro (politico interno) in cui la vicenda si è svolta. E soprattutto: il 4 agosto, alla videoconferenza d'urgenza dei ministri dell'Interno UE, il livello europeo ha già archiviato l'allarme. Il commissario Brunner ha dichiarato «piena solidarietà con la Spagna»; ogni discorso di espulsione da Schengen è scomparso dai comunicati, sostituito dai consueti punti programmatici su frontiere, trafficanti e rimpatri. Mentre Roma manteneva la sospensione bilaterale — e la settimana successiva Madrid rispondeva nella stessa moneta — l'istituzione europea aveva già chiuso il caso. Il confronto Roma-Madrid, da quel momento, non è più una crisi UE: è una disputa a due, tenuta in vita da chi ha deciso di tenerla in vita." },
  { h: "Fatto due: la regolarizzazione non c'entra con la recinzione" },
  { p: "Una seconda affermazione ha collegato la crisi alla regolarizzazione spagnola di circa 500.000 migranti, presentata come invito aperto. I meccanismi dicono il contrario: il processo richiede residenza pregressa documentata, fedina pulita, contratto di lavoro o mezzi sufficienti. Chi ha scavalcato una recinzione a luglio 2026 ne è escluso per definizione. Una precisazione sul numero stesso: 500.000 era la stima attesa dalle autorità spagnole, non il totale regolarizzato — le domande effettivamente ricevute sono state 1,2 milioni, di cui non è pubblicamente noto quante approvate. Anche nella versione più ampia del dato, resta un processo di domanda documentata con requisiti — non un cancello aperto per chi arriva a nuoto. Le autorità spagnole hanno documentato anche una campagna di disinformazione che ha travisato una sentenza della Corte Suprema sui rimpatri per convincere le persone che raggiungere Ceuta garantisse la permanenza. Non è così; la sentenza ha cambiato la procedura, non i diritti di soggiorno." },
  { p: "I dati Frontex citati dal governo spagnolo sugli ingressi irregolari 2021–2026 classificano le rotte così: Italia circa 478.600; Balcani occidentali 340.600; Grecia 259.800; Spagna 234.760. Il paese che ha sospeso Schengen con la Spagna ha registrato circa il doppio degli ingressi irregolari della Spagna nello stesso periodo." },
  { p: "Vale notare come fu formulata questa replica. Mentre altre capitali inasprivano — vertici, frontiere chiuse, ambasciatori convocati — la risposta del premier spagnolo fu un post con quei numeri Frontex, introdotti da una sola osservazione: solidarietà ed empatia sono opzionali, il rispetto dei trattati e dei dati no. Da un lato una tabella, dall'altro un'escalation diplomatica." },
  { h: "Fatto tre: il modello spagnolo, imperfetto ma misurabile" },
  { p: "La Spagna è la grande economia in più rapida crescita dell'eurozona, circa il 3% annuo per due anni consecutivi, mentre Germania e Italia restano vicine allo zero. I motori: turismo da record, assorbimento efficace dei fondi Next Generation EU, rinnovabili a basso costo e — ironia della polemica — l'immigrazione stessa, che ha sostenuto occupazione e consumi in un continente che invecchia. Punti deboli reali ci sono: crisi abitativa grave, bassa produttività oraria, precarietà residua. Ma «imperfetto e in crescita del 3%» è una frase diversa da quella che si scrive sulla Spagna in questi giorni." },
  { h: "Fatto quattro: il Marocco non è un Eldorado — e un'elezione spiega parte del perché" },
  { p: "Il Marocco ha promosso per anni la propria immagine di storia di successo africana: crescita del PIL sopra il 3%, espansione cumulata del 22% dal 2019, export che si avvicina alla produzione automobilistica italiana, alta velocità Kenitra-Marrakech, Mondiali 2030 con lo stadio più grande del mondo." },
  { p: "L'altro lato del bilancio: circa due terzi dell'occupazione marocchina è informale — 67,6% secondo il conto satellite HCP/OIT, oltre il 67% secondo l'OCSE, fino al 77% in altre stime. La disoccupazione dei 15-24enni ha superato il 36% nel 2024-2025; con la metodologia «in senso stretto» del 2026 il tasso ufficiale scende al 29%, ma la sottoutilizzazione complessiva della forza lavoro giovanile resta al 45%. La partecipazione femminile è scesa dal 28% del 2000 al 19%, tra i divari più ampi al mondo. La crescita si concentra in settori ad alta intensità di capitale controllati da multinazionali straniere: assorbono investimenti, danno lavoro a pochi, ridistribuiscono meno. Il movimento GenZ 212 ha condensato lo squilibrio in uno slogan: vogliamo ospedali, non stadi. L'OCSE colloca il Marocco ai primi posti mondiali per lavoratori in uscita." },
  { p: "Un contesto che le prime ricostruzioni hanno omesso: il Marocco vota per le elezioni generali il 23 settembre 2026. È plausibile leggere l'assalto alla recinzione — decine di migliaia di persone nel giorno della Festa del Trono del proprio re — anche come espressione di malcontento pre-elettorale, sopra le proteste Gen Z dell'ottobre 2025 contro le infrastrutture dei Mondiali percepite come priorità sbagliata rispetto a sanità e istruzione. Nessun fatto qui esposto richiede che questa lettura sia vera, ma ometterla significa perdere una variabile rilevante quanto qualsiasi attore straniero." },
  { p: "Il bilancio umano resta il dato che nessuna narrazione sovrana può assorbire — ed è, ad oggi, ancora in evoluzione e discordante tra le fonti. Il totale degli ingressi, secondo il ministro dell'Interno spagnolo al 4 agosto, è stato di circa 72.000 persone, di cui 70.000 già rientrate in Marocco. Sul lato dei morti, la forbice si è allargata invece di chiudersi: 11 secondo il primo conteggio marocchino, oltre 48.000 rimpatriati entro 48 ore secondo Madrid, 72 vittime riportate dalla Spagna in attesa di verifica congiunta, quasi 100 morti e 50 dispersi secondo la polizia spagnola al 6 agosto, almeno 141 annegati al frangiflutti secondo The Economist il 5 agosto. Segnaliamo la forbice invece di sceglierne un numero: è essa stessa il fatto, perché un bilancio che continua a crescere mentre proseguono le ricerche racconta più di qualsiasi cifra definitiva. Una precisazione anche sulla composizione: il grosso dell'ondata del 30-31 luglio era di cittadini marocchini, come documentano sia Rabat sia le analisi sui contenuti social — ma non tutti; tra chi restava a Ceuta ai primi di agosto, secondo The Economist, la maggioranza erano migranti subsahariani e minori non accompagnati, circa 1.100 dei quali destinati al trasferimento in Spagna. Il quadro corretto non è «marocchini invece di subsahariani», ma due popolazioni distinte con traiettorie diverse: i marocchini, rimpatriabili rapidamente per via degli accordi bilaterali, sono usciti dal conteggio in pochi giorni; i migranti subsahariani, in una zona grigia legale più complessa, sono quelli rimasti. Quando le persone rischiano la vita tra filo spinato e mare aperto, stanno assegnando a un paese un rating più onesto di qualunque agenzia. Hanno votato con i piedi. È l'unico voto che non può essere manipolato." },
  { h: "Fatto cinque: il bilancio degli stessi accusatori — e un'ironia pronunciata sulle tombe sbagliate" },
  { p: "I governi più accesi nel denunciare Madrid meritano la stessa verifica che esigono dagli altri." },
  { p: "L'Italia, nel 2025, ha limitato la cittadinanza iure sanguinis — decreto firmato dallo stesso ministro degli Esteri che oggi attacca la regolarizzazione spagnola — escludendo la maggior parte dei discendenti sudamericani degli emigranti italiani, salvo figli e nipoti di chi è nato in Italia. Lo stesso schieramento assiste ora all'arrivo in Parlamento dell'iniziativa popolare «Remigrazione e Riconquista», 150.000 firme: un testo che definisce la remigrazione come rimpatrio assistito degli stranieri legalmente residenti in Italia e che, contemporaneamente, propone sostegno statale per il ritorno dei discendenti italiani all'estero." },
  { p: "I discendenti che hanno atteso anni ai consolati per la cittadinanza votavano con i piedi verso l'Italia — porta chiusa, liquidati come costo consolare. Gli stranieri che hanno votato con i piedi verso l'Italia e vi hanno costruito una vita regolare sono ora, nella proposta più radicale, invitati ad andarsene. Diaspora come passivo, popolazione residente come surplus: contabilità incoerente, pessimo pulpito da cui dare lezioni a Madrid." },
  { p: "E il 7 agosto l'incoerenza ha trovato la sua immagine più netta. Alla cerimonia per il settantesimo anniversario della tragedia di Marcinelle — dove morirono 136 lavoratori emigrati italiani, parte dei 50.000 inviati in Belgio con l'accordo «uomini contro carbone» del 1946 — la premier Meloni ha dichiarato che «in Europa non c'è spazio per chi alimenta canali dell'immigrazione clandestina per avere manodopera a basso costo». Parole rivolte a Rabat e ai trafficanti. Pronunciate sulle tombe di italiani che furono, in ogni senso sostanziale se non giuridico, esattamente questo: manodopera a basso costo trasferita oltre confine da un accordo scritto per servire l'economia di qualcun altro. Non serve altro commento." },
  { p: "Un'ultima voce del bilancio, ed è la Spagna stessa a presentarla: nel motivare la propria contromisura contro l'Italia, il ministero dell'Interno spagnolo ha citato ufficialmente quasi mezzo milione di immigrati irregolari arrivati in Italia negli ultimi cinque anni a fronte di appena 16.000 rimpatri — cifre che, per ordine di grandezza, confermano i dati Frontex del fatto due. Sánchez ha aggiunto un'accusa più tecnica e verificabile: l'Italia non rispetterebbe dal 2022 il Regolamento di Dublino, scaricando così pressione migratoria aggiuntiva sugli altri Stati membri. Non è un'opinione da arbitrare qui — è un'affermazione puntuale che meriterebbe una verifica a sé — ma il fatto che l'accusa arrivi con un numero e un articolo di regolamento, invece che con un aggettivo, la colloca in una categoria diversa dal resto della polemica." },
  { h: "Fatto sei: i marocchini sono già qui — e sono l'Italia che funziona" },
  { p: "Il fatto che la narrazione dell'invasione non può digerire, perché la smonta dall'interno." },
  { p: "La comunità marocchina è tra le più grandi, antiche e radicate d'Italia: 412.000 residenti al 1° gennaio 2025 secondo Fondazione ISMU, terza nazionalità dopo romeni e albanesi; 377.554 regolarmente soggiornanti tra i non comunitari secondo il Ministero del Lavoro, seconda comunità extra-UE del paese. Non episodica: uomini soli negli anni Ottanta, famiglie ricongiunte nei Duemila, oggi 82.075 minori, 115.569 studenti nelle scuole italiane, 1.190 matrimoni misti nel solo 2023. E 27.000 acquisizioni di cittadinanza italiana nel 2024 — seconda comunità per naturalizzazioni — dopo le oltre 216.000 del 2006-2017." },
  { p: "Il dato ISTAT rilanciato da Il Sole 24 Ore aggiunge il pezzo mancante: gli arrivi dal Marocco in Italia sono cresciuti di quasi il 50% nel 2025 — 36.000 persone, seconda nazionalità per ingressi, contati dalle statistiche ufficiali. Il governo più rumoroso sull'«invasione» di Ceuta presiede un paese dove i marocchini sono la terza comunità nazionale, studiano in 115.000 nelle sue scuole, ne sposano i cittadini, ne acquisiscono la cittadinanza a un ritmo di 27.000 l'anno, e continuano ad arrivare regolarmente a un ritmo cresciuto del 50%. I due fatti non possono essere veri insieme: o il Marocco è un pericolo, e allora vanno spiegati quarant'anni di integrazione documentata; o i numeri dicono il vero — la recinzione di Ceuta era il set di un film girato per un altro pubblico." },
  { h: "Fatto sette: chi ha acceso la miccia — e cosa resta contestato" },
  { p: "Chi ha mobilitato decine di migliaia di persone verso una recinzione nello stesso giorno è la domanda su cui il dossier, ad oggi, resta più aperto — ed è giusto dirlo con la stessa onestà con cui abbiamo trattato tutto il resto." },
  { p: "Il pavimento giudiziario è documentato: decine di account anonimi ripetevano lo stesso messaggio — il confine è aperto, chi attraversa resta — e profili con migliaia di follower pubblicavano i punti di attraversamento. L'Audiencia Nacional ha aperto un'inchiesta su reti criminali, trafficanti o una strategia coordinata; Rabat ha accusato le «mafie della disinformazione»; al 5 agosto risultano incriminate 25 persone. Circola già la convocazione di un nuovo ingresso di massa per il 15 agosto, finora senza conferme ufficiali da nessuna delle due sponde." },
  { p: "Su chi sia dietro, però, esistono due letture credibili che non coincidono, e il fact-checking non sceglie sulla fiducia. Nathalie Tocci (IAI / Johns Hopkins SAIS), il 5 agosto su Sky TG24, ha proposto una tassonomia a tre attori: Stati terzi che militarizzano la migrazione per ottenere leve, come Tunisia, milizie libiche e Turchia prima del Marocco; attori globali — le provenienze di parte della disinformazione circolata riconducevano, nella sua valutazione, a Mosca, al mondo MAGA statunitense, a Israele — con l'obiettivo di dividere l'Europa a partire dalla Spagna di Sánchez; e le destre interne che cavalcano quella che definisce una «finta crisi». Il suo punto più tagliente è verificabile da chiunque guardi una mappa: raggiungere la Spagna continentale da Ceuta è più difficile del viaggio diretto dal Marocco, perché i controlli in uscita dall'enclave sono più stringenti. Chi grida all'invasione via Ceuta descrive la rotta che nessun migrante razionale sceglierebbe." },
  { p: "Una ricerca originale della studiosa Myriam Cherti, pubblicata il 6 agosto, complica però questa lettura. Analizzando 180 post ad alto coinvolgimento del precedente 2024, Cherti ha trovato oltre l'80% dei contenuti in darija marocchina — conversazione locale, non messaggio per l'estero — e ha concluso che la mobilitazione fu azione collettiva abilitata dai social, non una campagna diretta centralmente. L'Associated Press ha verificato che le accuse di coordinamento da trafficanti o di orchestrazione deliberata dello Stato marocchino «non sono state pubblicamente sostanziate». Anche l'indagine interna del ministero dell'Interno marocchino, pur escludendo fattori spontanei e puntando su disinformazione e trafficanti, non arriva a provare un disegno statale. Due letture credibili, non del tutto sovrapponibili: quella di Tocci sugli attori esterni nella campagna e nelle sue conseguenze politiche, quella di Cherti sull'assenza di un regista dietro la mobilitazione originaria. Sul chi, il fascicolo pubblico resta aperto — e la cautela va estesa a entrambe le attribuzioni." },
  { p: "Ciò che è successo in piazza, invece, non richiede cautela: è cronaca diretta. Sabato sera centinaia di ceutini sono scesi in strada contro Núcleo Nacional, movimento spagnolo di estrema destra; il giorno dopo l'agitatore Vito Quiles si è presentato in Plaza de los Reyes con Save Europe Act — co-fondato dall'austriaco Martin Sellner, con attivisti di Generation Identity arrivati dalla Germania — e una protesta di quartiere si è spaccata per la sua presenza: «è venuto a provocare e a dividerci», la frase dei residenti raccolta dalle agenzie. Il loro striscione — «Sánchez must go, Spain needs remigration» — era in inglese; i ceutini che lo contestavano rispondevano in spagnolo. Un cartello è un atto di comunicazione, e il destinatario si deduce dalla lingua: chi scrive in spagnolo a Ceuta parla a Ceuta, chi scrive in inglese parla alla telecamera e all'algoritmo. Si aggiunga che Ceuta è per circa metà di origine marocchina e musulmana: un errore di casting prima ancora che politico. Secondo The Economist, agitatori di estrema destra arrivati da tutta Europa hanno diffuso video con la retorica della «sostituzione etnica»; al coro si sono uniti anche Elon Musk e il vicepresidente USA J.D. Vance. Gli attori esterni, stavolta, sono venuti di persona — e restano gli unici, in tutta questa storia, ad aver attraversato più frontiere dei migranti." },
  { p: "Un'ultima osservazione chiude il fatto sette, ed è forse la più tagliente dell'intero dossier: l'Unione europea non tratta tutte le leve migratorie allo stesso modo. Dal 2021 la Bielorussia ha fatto volare migranti mediorientali verso Polonia e Stati confinanti come ritorsione politica; l'UE l'ha classificata come atto di guerra ibrida e ha inasprito le sanzioni contro Minsk. Il Marocco, nel 2021, aveva già fatto entrare circa 8.000 persone a Ceuta per ritorsione contro l'ospitalità sanitaria spagnola al leader del Fronte Polisario — un precedente diretto di quanto avvenuto quest'anno. Eppure, nota The Economist, «non c'è prova chiara che il Marocco abbia orchestrato il movimento dei migranti», mentre «i suoi funzionari della sicurezza li hanno certamente lasciati passare» — e i governi europei hanno comunque salutato la «cooperazione» marocchina, riservando l'ostilità a trafficanti anonimi e post sui social. La differenza di trattamento non è casuale: l'UE ha bisogno della cooperazione del Marocco anche sulla rotta ben più consistente delle Canarie. Un analista di Oxford, Ruben Andersson, la mette così: l'esternalizzazione dei confini «crea un incentivo per i paesi terzi a fomentare crisi — e offrirsi di risolverle». Gemma Pinyol-Jiménez, esperta di migrazioni, sintetizza l'intera vicenda in una frase che vale come chiusura di questo fatto: «Non è stata principalmente una crisi migratoria. È stato un episodio geopolitico.»" },
  { h: "Fatto otto: lo specchio — e il risultato è zero" },
  { p: "L'ultimo capitolo, cronologicamente, è anche il più clamoroso. Dopo che Roma ha respinto l'ultimatum spagnolo — rimuovere i controlli entro il 9 agosto, pena «misure proporzionate» — la Spagna ha attivato dalla mezzanotte dell'8 agosto controlli reciproci sugli arrivi dall'Italia, validi fino al 7 settembre, motivati ufficialmente con la «persistente pressione migratoria irregolare» italiana. Un dettaglio va registrato nella colonna dell'audit: la data del 15 agosto invocata da Palazzo Chigi come proprio termine di verifica non è un annuncio spagnolo formale — è, secondo la stampa di entrambi i paesi, un «tam tam social» in Marocco che la Guardia Civil ritiene plausibile per un nuovo tentativo. Un governo che ha sospeso Schengen anche per una campagna di disinformazione sta ora giustificando la durata di quella sospensione citando una voce non confermata dello stesso tipo." },
  { p: "Ma il dato più duro, a una settimana di distanza, è un risultato, non una procedura: nessun immigrato irregolare proveniente da Ceuta risulta identificato ai controlli italiani. Zero. E le stesse fonti che riportano il dato notano che sarebbe comunque impossibile stabilire, per i cittadini nordafricani intercettati negli aeroporti, se il loro ingresso fosse in qualche modo collegato alla crisi di Ceuta. Il vicepremier Salvini ha dichiarato di star bloccando «decine di irregolari in arrivo dalla Spagna»: le due affermazioni — zero collegati a Ceuta, decine bloccati in generale — non si escludono a vicenda, ma la distanza tra ciò che la misura doveva prevenire e ciò che ha effettivamente intercettato resta il fatto più eloquente dell'intera vicenda. Il ministro dell'Interno spagnolo Grande-Marlaska, dopo la videoconferenza dei ministri UE, lo ha detto senza giri di parole: è stato riconosciuto che «la zona Schengen non è mai stata in pericolo», e ha chiesto la revoca immediata dei controlli italiani perché non corrispondono a quanto concordato in quella sede. Sul fronte interno italiano, le opposizioni — da Fratoianni a Magi a Calenda — hanno usato registri diversi ma la stessa sostanza: propaganda, mossa da bulla, calcolo elettorale. Non adottiamo il loro linguaggio, ma segnaliamo che la critica non arriva solo da fuori: attraversa anche il dibattito interno italiano." },
  { h: "Il metodo, ancora" },
  { p: "Otto fatti, tre paesi, un solo criterio: i documenti prima delle dichiarazioni — e la disponibilità a correggere il proprio stesso dossier quando arriva un'evidenza migliore, come abbiamo fatto sul fatto sette. Le imprese brasiliane hanno votato con i piedi contro il Custo Brasil attraversando la Ponte da Amizade; i marocchini hanno votato con i piedi contro il loro miracolo a due velocità; i discendenti italiani hanno votato con i piedi verso una patria che ha smesso di rispondere; e persino i provocatori di Ceuta, alla fine, hanno votato con i piedi — gli unici ad aver attraversato più frontiere dei migranti per raccontare una crisi che i migranti stessi non riconoscevano." },
  { p: "In ogni caso, il potere ha risposto ai piedi con la retorica invece che con le riforme." },
  { p: "I fatti e le cifre sono tratti da fonti pubbliche: il Codice delle frontiere Schengen e l'Atto di adesione della Spagna (1991); dichiarazioni della Commissione europea (luglio–agosto 2026); CGUE, cause riunite C-368/20 e C-369/20 (2022); HCP e OCSE sul mercato del lavoro marocchino; Fondazione ISMU, Rapporto sulle migrazioni 2026; Ministero del Lavoro, «La comunità marocchina in Italia — Rapporto annuale 2025»; ISTAT, rapporto sulle migrazioni 2025; atti e cronache sull'inchiesta dell'Audiencia Nacional e sulle manifestazioni di Ceuta (agosto 2026); intervista a Nathalie Tocci, Sky TG24 «Timeline», 5 agosto 2026; ricerca e analisi di Myriam Cherti, Bloomberg, 6 agosto 2026; dichiarazione del ministero dell'Interno marocchino via MAP, ripresa da Bloomberg, 3 agosto 2026; stampa italiana e spagnola sui controlli reciproci Schengen e sulla cerimonia di Marcinelle (Il Post, Sky TG24, Il Foglio, ANSA, 7-8 agosto 2026); The Economist, «Rushing the gates» (31 luglio 2026) e «The wrong lessons» (5 agosto 2026); dichiarazioni del ministro dell'Interno spagnolo Grande-Marlaska e cronache sulla videoconferenza dei ministri UE del 4 agosto (Sky TG24); dichiarazioni di Matteo Salvini e delle opposizioni italiane, e nota del ministero dell'Interno spagnolo sulla contromisura dell'8 agosto (LaPresse, Adnkronos, Europa Today, 7-8 agosto 2026)." },
  { p: "Business Matching Global — analisi di mercato e coordinamento commerciale sul corridoio Europa–Brasile. Senza dati sei solo un'altra persona con un'opinione. Noi preferiamo essere un'altra persona con i dati." },
];

export default function CeutaIT() {
  const { lang, setLang } = useT();
  const article = getArticleBySlug("ceuta_it");
  const desc =
    "Cosa dice davvero la crisi di Ceuta: lo status speciale fuori Schengen, i dati Frontex, il Marocco a due velocità e i flussi che verificano ciò che i comunicati negano.";
  useCanonical("/ceuta", {
    title: `${TITLE} — Business Matching Global`,
    description: desc,
    type: "article",
  });

  useEffect(() => {
    const previous = lang;
    if (lang !== "it") setLang("it");
    return () => {
      if (previous !== "it") setLang(previous);
    };
  }, [lang, setLang]);

  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <div className="flex items-center justify-between gap-4 mb-8">
          <Link
            to="/analysis"
            className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            Torna alle analisi
          </Link>
          <LangSwitcher to="/ceuta" />
        </div>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">{TITLE}</h1>
          <p className="text-xs text-foreground/70 mb-2">Business Matching Global</p>
          <p className="text-xs text-foreground/70 mb-10 tabular-nums">{article?.date}</p>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
          <ShareBlock title={TITLE} />
        </article>
        <AnalysisFooter />
      </div>
    </main>
  );
}
