import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useEffect } from "react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";
import { AnalysisFooter } from "@/components/AnalysisFooter";
import { useCanonical } from "@/lib/useCanonical";
import { ShareBlock } from "@/components/ShareBlock";
import { LangSwitcher } from "@/components/LangSwitcher";

type Block = { h: string } | { p: string };

const TITLE = "Votando com os pés";

const body: Block[] = [
  { p: "#CustoBrasil — Business Matching Global · publicado em 02-08-2026, reescrito e atualizado em 13-08-2026" },
  { p: "O que a crise de Ceuta nos diz — depois de filtrado o barulho" },
  { p: "«Separam-nos apenas 17 quilômetros, mas no plano da incompreensão mútua parecem 17 séculos.» — Rachid Niny, diretor do Al Akhbar, ex-migrante irregular na Espanha" },
  { p: "Alguns textos são escritos para persuadir. Este foi escrito para verificar. Desde o fim de julho, circulou nas capitais europeias e nas redes um volume incomum de afirmações categóricas — muitas verificáveis, muitas sem fundamento. O que segue não é a defesa de governo algum. É um exercício de reconstrução do dossiê, porque na inteligência de mercado, como na política, são os fatos verificados — não as declarações — que dizem o que realmente aconteceu. O dossiê cresceu em menos de duas semanas: nós o reescrevemos por inteiro em vez de empilhar atualizações, porque uma auditoria que se acumula sem se reorganizar deixa de ser legível." },
  { h: "Fato um: Ceuta nunca fez parte do Espaço Schengen" },
  { p: "A afirmação que dominou os primeiros dias — de que os migrantes entrados em Ceuta teriam «violado o Schengen» e poderiam chegar livremente a Milão ou Helsinque — desmorona na primeira checagem da norma." },
  { p: "Quando a Espanha aderiu ao Acordo de Schengen em 1991, foi anexada ao seu Ato de Adesão uma declaração específica sobre Ceuta e Melilla, excluindo as duas cidades norte-africanas do regime de livre circulação. O status especial segue em vigor, hoje no artigo 41 do Código de Fronteiras Schengen. Na prática: entrar em Ceuta não dá direito de permanecer na Espanha, alcançar a Península Ibérica ou circular pela Europa. Os controles de saída entre Ceuta e o continente existem desde 1991." },
  { p: "Vale lembrar como nasceu aquela declaração, porque não foi um detalhe técnico nem uma simples imposição: foi uma combinação de fatores que a determinou — um compromisso em três camadas em que cada parte obteve o que precisava. A Espanha pediu e obteve o regime de tráfego fronteiriço local — a isenção de visto para os marroquinos residentes nas províncias vizinhas de Tetouan e Nador — sem o qual a economia dos dois enclaves, que vive de trabalhadores transfronteiriços e comércio diário, teria colapsado. Os parceiros de Schengen, desconfiados de duas portas africanas abertas para o espaço comum, exigiram em troca os controles de identidade obrigatórios em todas as conexões marítimas e aéreas com a península. E a ambiguidade sobre o status convinha até ao Marrocos, que não reconhece as duas cidades e teria vivido sua plena constitucionalização como fronteira externa da UE como uma provocação. Trinta e cinco anos depois, a ironia é de manual: foi justamente o filtro que Madri suportou como condição dos parceiros que a salvou — é sua melhor defesa documental contra a acusação de ter deixado 70.000 pessoas entrarem na Europa. (A reconstrução dos papéis negociais é história diplomática consolidada, não ato publicado: nós a relatamos como tal.)" },
  { p: "Os números confirmam que o sistema funcionou como projetado. Das cerca de 50.000–60.000 pessoas que entraram em menos de 24 horas, as autoridades espanholas informam que mais de 48.000 foram devolvidas ao Marrocos em 48 horas. Em 1º de agosto, a presidente da Comissão von der Leyen — após uma videochamada com os comissários Brunner e Šuica — declarou publicamente que a grande maioria já havia retornado e que ninguém havia chegado à Espanha continental ou ao restante da UE." },
  { p: "Um governo, ainda assim, suspendeu o Schengen com a Espanha por um mês a partir de 1º de agosto, restabelecendo controles seletivos nas fronteiras marítimas e aéreas — sobre uma fronteira que o Schengen nunca cobriu. Bruxelas observou que a suspensão foi anunciada antes de qualquer notificação formal chegar à Comissão, e um porta-voz da UE pediu publicamente a Roma que explicasse de que forma a crise constituiria uma ameaça à segurança — o pressuposto jurídico exigido para o restabelecimento. O mesmo governo promoveu depois, com a Dinamarca, uma carta assinada por 22 chefes de Estado e de governo europeus pedindo coordenação e uma resposta europeia unida: suspensão unilateral sem notificação de um lado, pedido de coordenação do outro, no mesmo ciclo de notícias. Um gesto contradiz o outro." },
  { p: "Um elemento mais histórico que jurídico completa o quadro, e deve ser formulado com precisão porque o governo italiano opôs a ele um argumento que merece resposta. É verdade, como recordou o ministro Piantedosi em audiência parlamentar, que controles internos entre Estados-membros existem há anos, «inclusive contra a Itália»: a Áustria no Brennero, a França em Ventimiglia. Mas aqueles controles respondem a fluxos documentados em trânsito por outro Estado-membro — pessoas contadas, rotas rastreadas, notificações protocoladas. A novidade do caso ítalo-espanhol é outra, e é dupla: é a primeira suspensão com finalidade retaliatória nascida de uma disputa política bilateral, com ultimatos cruzados e contramedida recíproca — e a primeira adotada com fluxos zero, contra um movimento que a Comissão certifica jamais ter existido. O Brennero filtra um trânsito real; o dispositivo contra a Espanha filtrou um trânsito inexistente. Não é um precedente sobre controles: esses já existiam. É o precedente sobre o uso do Schengen como instrumento de pressão entre dois Estados-membros — e, ainda por cima, entre dois dos países que aderiram primeiro ao espaço de livre circulação depois dos cinco signatários originais de 1985: a Itália em 1990, a Espanha em 1991." },
  { p: "Dois esclarecimentos completam o fato um. O pedido inicial da premiê Meloni — a expulsão da Espanha de todo o espaço Schengen — era, ele próprio, tecnicamente inviável: não pode ocorrer contra a vontade da Espanha, observa a The Economist. O que a Itália de fato fez foi mais modesto, controles por amostragem em portos e aeroportos — a distância entre o pedido e a medida já é um indício do registro (política doméstica) em que o episódio se desenrolou. E, sobretudo: em 4 de agosto, na videoconferência de emergência dos ministros do Interior da UE, o nível europeu já havia arquivado o alarme. O comissário Brunner declarou «plena solidariedade com a Espanha»; todo discurso de expulsão do Schengen desapareceu dos comunicados, substituído pelos pontos programáticos habituais sobre fronteiras, traficantes e repatriações. Enquanto Roma mantinha a suspensão bilateral — e na semana seguinte Madri respondia na mesma moeda — a instituição europeia já havia encerrado o caso. O confronto Roma-Madri, a partir dali, deixou de ser uma crise da UE: é uma disputa bilateral, mantida viva por quem decidiu mantê-la viva." },
  { h: "Fato dois: a regularização não tem nada a ver com a cerca" },
  { p: "Uma segunda afirmação ligou a crise à regularização espanhola de cerca de 500.000 migrantes, apresentada como convite aberto. A mecânica diz o contrário: o processo exige residência prévia documentada, ficha limpa, contrato de trabalho ou meios suficientes. Quem pulou uma cerca em julho de 2026 está, por definição, excluído. Um esclarecimento sobre o próprio número: 500.000 era a estimativa esperada pelas autoridades espanholas, não o total regularizado — os pedidos efetivamente recebidos foram 1,2 milhão, dos quais não se sabe publicamente quantos aprovados. Mesmo na versão mais ampla, trata-se de um processo de solicitação documentada com requisitos — não um portão aberto para quem chega a nado. As autoridades espanholas também documentaram uma campanha de desinformação que distorceu uma decisão do Supremo Tribunal sobre devoluções para convencer as pessoas de que chegar a Ceuta garantiria a permanência. Não garante; a decisão mudou o procedimento, não os direitos de permanência." },
  { p: "Vale a pena ler aquela decisão, porque é o verdadeiro gatilho técnico do episódio e foi citada por todos sem quase nunca ser descrita. É de 8 de julho de 2026, Quinta Seção da Sala do Contencioso-Administrativo do Tribunal Supremo, e nasce do recurso da Advocacia do Estado no caso de um cidadão argelino interceptado no mar em 14 de novembro de 2024, quando tentava chegar a Ceuta a nado, e entregue imediatamente ao Marrocos. A Corte estabelece que o «rechazo en frontera» — as expulsões imediatas previstas na Décima Disposição Adicional da lei de estrangeiros — não se aplica a quem chega a nado, porque essa pessoa não supera nenhum «elemento de contenção» da fronteira: drones, câmeras térmicas e sensores, argumenta o tribunal, exercem funções de vigilância e alerta, não de contenção material, e portanto não ativam o regime excepcional. A essas pessoas aplica-se o procedimento ordinário de repatriação do artigo 58.3 da Lei Orgânica 4/2000. A decisão não altera a lei de estrangeiros, não declara ilegais as expulsões imediatas e não atribui direito algum de permanecer: muda qual procedimento se aplica, e com ele a obrigação de abrir um processo individual — passo necessário, entre outras coisas, para identificar menores e pessoas vulneráveis." },
  { p: "E aqui está o detalhe que nenhuma cobertura conectou. A mesma decisão especifica que «nada impediria» a aplicação das expulsões imediatas caso fossem instalados «elementos de contenção no mar protegendo a linha de fronteira». Três semanas depois, a Espanha instalou no Tarajal uma barreira flutuante de 500 metros. Aquela barreira, que a imprensa narrou como medida física de dissuasão, é também — e talvez sobretudo — um instrumento jurídico: cria o elemento de contenção marítima que a Corte havia indicado como condição para restaurar o regime de devolução imediata. O governo espanhol não contornou a decisão: executou suas instruções implícitas. É um caso raro e instrutivo de engenharia jurídica construída no mundo físico — e a prova de que o aparato espanhol reagiu à crise trabalhando no direito, enquanto em outros lugares se trabalhava nos comunicados." },
  { p: "Os dados da Frontex citados pelo governo espanhol sobre entradas irregulares 2021–2026 classificam as rotas assim: Itália, cerca de 478.600; Bálcãs Ocidentais, 340.600; Grécia, 259.800; Espanha, 234.760. O país que suspendeu o Schengen com a Espanha registrou aproximadamente o dobro das entradas irregulares da Espanha no mesmo período." },
  { p: "Vale notar como essa réplica foi formulada. Enquanto outras capitais escalavam — cúpulas, fronteiras fechadas, embaixadores convocados —, a resposta do primeiro-ministro espanhol foi um post listando aqueles números da Frontex, introduzidos por uma única observação: solidariedade e empatia são opcionais, o respeito aos tratados e aos dados não. De um lado uma tabela, do outro uma escalada diplomática." },
  { p: "Uma última observação sobre o «fator de atração», e ela vem do mercado, não da política. Nas redes latino-americanas circulam nestes dias os anúncios de agências migratórias privadas que vendem exatamente o percurso espanhol: residência com visto não lucrativo ou de nômade digital, e — graças à via preferencial que o Código Civil reserva há décadas aos cidadãos ibero-americanos — a possibilidade de pedir a cidadania depois de apenas dois anos, «comente España e agende sua reunião». Com as simplificações típicas do marketing (os dois anos são o requisito para protocolar o pedido; depois vêm exames e anos de fila), mas o ponto é outro: olhar a quem essa indústria se dirige. A quem pode comprovar renda, preencher um formulário, agendar uma cita — o canal legal, documentado, com hora marcada. O fator de atração espanhol existe, e está literalmente à venda: mas seu cliente não é quem nada em volta de um quebra-mar — que desse percurso, como se viu, está excluído por definição. O verdadeiro fator de atração produz processos, não assaltos a cercas. E um detalhe antecipa o fato cinco: entre os clientes dessas agências figuram cada vez mais os ítalo-descendentes sul-americanos rejeitados pelo aperto italiano de 2025 — o mercado simplesmente migrou para o país que manteve abertas as portas legais. (O anúncio é citado como fenômeno de mercado observado, não como fonte normativa.)" },
  { h: "Fato três: o modelo espanhol, imperfeito mas mensurável" },
  { p: "A Espanha é a grande economia de crescimento mais rápido da zona do euro, cerca de 3% ao ano por dois anos consecutivos, enquanto Alemanha e Itália patinam perto de zero. Os motores: turismo recorde, absorção eficaz dos fundos do Next Generation EU, renováveis baratas e — ironia da polêmica — a própria imigração, que sustentou emprego e consumo num continente que envelhece. Há fragilidades reais: grave crise habitacional, baixa produtividade por hora, precariedade residual. Mas «imperfeito e crescendo 3%» é uma frase bem diferente da que se escreve sobre a Espanha nestes dias." },
  { h: "Fato quatro: o Marrocos não é um Eldorado — e uma eleição explica parte do porquê" },
  { p: "O Marrocos passou anos promovendo sua imagem de história de sucesso africana: crescimento do PIB acima de 3%, expansão acumulada de 22% desde 2019, exportações que se aproximam da produção automobilística italiana, alta velocidade Kenitra-Marrakech, a Copa de 2030 com o maior estádio do mundo." },
  { p: "O outro lado do balanço: cerca de dois terços do emprego marroquino é informal — 67,6% segundo a conta satélite HCP/OIT, mais de 67% segundo a OCDE, até 77% em outras estimativas. O desemprego entre 15-24 anos superou 36% em 2024-2025; com a metodologia «em sentido estrito» de 2026, a taxa oficial cai para 29%, mas a subutilização geral da força de trabalho jovem permanece em 45%. A participação feminina caiu de 28% em 2000 para 19%, uma das maiores disparidades do mundo. O crescimento se concentra em setores intensivos em capital controlados por multinacionais estrangeiras: absorvem investimento, empregam poucos, redistribuem menos. O movimento GenZ 212 condensou o desequilíbrio num slogan: queremos hospitais, não estádios. A OCDE coloca o Marrocos entre os primeiros do mundo em trabalhadores que emigram." },
  { p: "Um contexto que as primeiras reconstruções omitiram: o Marrocos tem eleições gerais em 23 de setembro de 2026. É plausível ler o assalto à cerca — dezenas de milhares de pessoas no próprio dia da Festa do Trono do rei — também como expressão de descontentamento pré-eleitoral, somado aos protestos da Gen Z de outubro de 2025 contra a infraestrutura da Copa vista como prioridade errada frente à saúde e à educação. Nenhum fato aqui exposto exige que essa leitura seja verdadeira, mas omiti-la significa perder uma variável tão relevante quanto qualquer ator estrangeiro." },
  { p: "A voz que fecha este fato, porém, não é europeia — e é por isso que a deixamos por último. Rachid Niny, diretor do Al Akhbar e da TeleMaroc, chegou à Espanha em 1997 com visto de um mês para cobrir um congresso nas Canárias: não foi, rumou para Benidorm e lá ficou três anos como irregular, lavando pratos e limpando pocilgas depois de um mestrado em poesia contemporânea. Dali nasceu Diario de un ilegal, o primeiro testemunho em língua árabe sobre a experiência dos migrantes marroquinos na Espanha, um livro construído em torno de uma única imagem: o eldorado que desaparece assim que se chega. Vinte e sete anos depois, entrevistado pelo La Stampa em Ras Kebdana, diz que nada do que aconteceu em Ceuta é novo — «enquanto houver oferta e demanda, essas cenas não terminarão: o mercado da imigração irregular não conhece recessão» — e que teme o pior se continuar crescendo «essa enorme reserva de jovens dispostos a apostar a vida num paraíso que existe apenas na imaginação deles»." },
  { p: "Seu balanço do próprio país coincide com os números desta análise, mas ele o formula melhor que qualquer indicador: em 1997 o Marrocos afundava em dívidas e o desemprego batia todos os recordes; hoje há autoestradas, renováveis, portos competitivos e crescimento perto de 5%, mas os frutos não chegam a quem está na base da escada social. «Ontem o Marrocos corria o risco de uma parada cardíaca por dívidas e estagnação. Hoje cresce, chovem investimentos estrangeiros, e ainda assim corre o risco de uma parada cardíaca social.» Sobre a mensagem de Ceuta à classe dirigente marroquina é ainda mais direto: «vocês têm uma bomba-relógio chamada juventude e precisam desarmá-la antes que destrua tudo». A emergência, para ele, é o fracasso da escola pública — cerca de 300.000 estudantes abandonam a escola todos os anos, engrossando um exército de adolescentes sem diploma — e o salário mínimo em torno de 300 euros: «as pessoas precisam sentir o crescimento nos próprios bolsos», diz, propondo elevá-lo a pelo menos 500, porque «se vocês acham que o custo da educação é alto demais, experimentem o custo da ignorância»." },
  { p: "Três observações de Niny merecem registro à parte, porque corrigem outros tantos atalhos da narrativa europeia. A primeira: não foi só a pobreza que foi a Ceuta. Entre os que entraram havia operários, funcionários de hotéis, empregados de padarias e cafés; alguns entraram na água ainda com a roupa de trabalho, um com a gravata-borboleta no pescoço. Nas fábricas, diz ele, pede-se demissão por salários desproporcionais ao esforço: «as pessoas não estão mais dispostas a aceitar a escravidão no trabalho». A segunda diz respeito às redes, e se encaixa na pesquisa de Cherti citada adiante: «existe uma epidemia global chamada influencers» num país onde 55% dos jovens de 18 a 29 anos sonham em emigrar, e entre os que entraram em Ceuta havia influencers que transformaram a travessia em conteúdo de milhões de visualizações, virando modelos para outros jovens. A terceira é dirigida à Europa, e vale como contra-tese ao fato um: «a segurança das fronteiras de cada país não pode ser delegada a um terceiro», e a Europa «precisa parar de nos tratar como o gendarme das próprias fronteiras» — a mesma externalização que, segundo o analista de Oxford citado adiante, cria o incentivo a fomentar crises e depois se oferecer para resolvê-las. Ele fecha com a frase que este dossiê escolheu como epígrafe: entre as duas margens «separam-nos apenas 17 quilômetros, mas no plano da incompreensão mútua parecem 17 séculos»." },
  { p: "E, por fim, a linha que liga o Marrocos de hoje à Itália de ontem, dita por quem voltou para casa e escolheu ficar: «tiro o chapéu para os migrantes que decidem sacrificar tudo isso. É preciso muita coragem para deixar tudo para trás e emigrar. É o que os europeus não veem — ou talvez tenham esquecido». O fato cinco, adiante, mostra quão literalmente esqueceram." },
  { p: "O balanço humano continua sendo o dado que nenhuma narrativa soberana consegue absorver — e permanece, até hoje, em evolução e discordante entre as fontes. O total de entradas, segundo o ministro do Interior espanhol em 4 de agosto, foi de cerca de 72.000 pessoas, das quais 70.000 já haviam retornado ao Marrocos. Do lado dos mortos, a margem se ampliou em vez de fechar: 11 segundo a primeira contagem marroquina, mais de 48.000 devolvidos em 48 horas segundo Madri, 72 vítimas relatadas pela Espanha aguardando verificação conjunta, quase 100 mortos e 50 desaparecidos segundo a polícia espanhola em 6 de agosto, ao menos 141 afogados no quebra-mar segundo a The Economist em 5 de agosto. Sinalizamos a margem em vez de escolher um número: ela própria é o fato, porque um balanço que continua subindo enquanto prosseguem as buscas diz mais que qualquer cifra definitiva. Um esclarecimento também sobre a composição: o grosso da onda de 30-31 de julho era de cidadãos marroquinos, como documentam tanto Rabat quanto as análises de conteúdo — mas não todos; entre os que permaneciam em Ceuta no início de agosto, segundo a The Economist, a maioria eram migrantes subsaarianos e menores desacompanhados, cerca de 1.100 destinados à transferência para a Espanha. Aqui também os números divergem por fonte e por data, e registramos a margem: em 13 de agosto, em audiência, o ministro Piantedosi falou de pelo menos 6.000 pessoas ainda no enclave — «embora algumas fontes falem em mais de 11.000» — majoritariamente subsaarianas, para as quais não seriam praticáveis nem readmissão nem retorno ao Marrocos, e de mais de 1.300 menores desacompanhados que não poderão ser repatriados, enquanto as estimativas locais espanholas dos dias anteriores paravam em 3.000-5.000. O La Stampa dedicou um texto à parte às 862 crianças ainda à espera de acolhimento, e da cidade a reportagem de Monica Perosino registra o nível da emergência — «não sabemos mais onde colocar os corpos» — assinalando também o silêncio imposto do lado marroquino. O quadro correto não é «marroquinos em vez de subsaarianos», mas duas populações distintas em trajetórias diferentes: os marroquinos, repatriáveis rapidamente pelos acordos bilaterais, saíram da contagem em poucos dias; os subsaarianos, numa zona cinzenta legal mais complexa, são os que ficaram. Quando pessoas arriscam a vida entre arame farpado e mar aberto, estão atribuindo a um país um rating mais honesto que o de qualquer agência. Votaram com os pés. É o único voto que não pode ser manipulado." },
  { h: "Fato cinco: o balanço dos próprios acusadores — e uma ironia pronunciada sobre os túmulos errados" },
  { p: "Os governos mais estridentes em denunciar Madri merecem a mesma auditoria que exigem dos outros." },
  { p: "A Itália, em 2025, restringiu a cidadania iure sanguinis — decreto assinado pelo mesmo ministro das Relações Exteriores que hoje ataca a regularização espanhola — excluindo a maior parte dos descendentes sul-americanos de emigrantes italianos, salvo filhos e netos de quem nasceu na Itália. O mesmo campo político assiste agora à chegada ao Parlamento da iniciativa popular «Remigração e Reconquista», com 150.000 assinaturas: um texto que define a remigração como retorno assistido de estrangeiros legalmente residentes na Itália e que, ao mesmo tempo, propõe apoio estatal ao retorno de descendentes de italianos no exterior." },
  { p: "Os descendentes que esperaram anos nos consulados pela cidadania votavam com os pés rumo à Itália — porta fechada, contabilizados como custo consular. Os estrangeiros que votaram com os pés rumo à Itália e ali construíram uma vida regular são agora, na proposta mais radical, convidados a partir. Diáspora como passivo, população residente como excedente: contabilidade incoerente, péssimo púlpito para dar lições a Madri." },
  { p: "E em 7 de agosto a incoerência encontrou sua imagem mais nítida. Na cerimônia dos 70 anos da tragédia de Marcinelle — onde morreram 136 trabalhadores emigrantes italianos, parte dos 50.000 enviados à Bélgica pelo acordo «homens por carvão» de 1946 — a premiê Meloni declarou que «não há espaço na Europa para quem alimenta canais de imigração clandestina para obter mão de obra barata». Palavras dirigidas a Rabat e aos traficantes. Pronunciadas sobre os túmulos de italianos que foram, em todo sentido material senão no jurídico, exatamente isso: mão de obra barata transferida através de uma fronteira por um acordo redigido para servir à economia de outra nação. Não é preciso mais comentário." },
  { p: "Um último item do balanço, e é a própria Espanha quem o apresenta: ao justificar sua contramedida contra a Itália, o ministério do Interior espanhol citou oficialmente quase meio milhão de imigrantes irregulares chegados à Itália nos últimos cinco anos contra apenas 16.000 repatriações — números que, em ordem de grandeza, confirmam os dados da Frontex do fato dois. Sánchez acrescentou uma acusação mais técnica e verificável: a Itália não cumpriria, desde 2022, o Regulamento de Dublin, transferindo pressão migratória adicional para os demais Estados-membros. Não é uma opinião a arbitrar aqui — é uma alegação pontual que mereceria verificação própria — mas o fato de a acusação vir com um número e um artigo de regulamento, em vez de um adjetivo, a coloca numa categoria diferente do resto da polêmica." },
  { h: "Fato seis: os marroquinos já estão aqui — e são a Itália que funciona" },
  { p: "O fato que a narrativa da invasão não consegue digerir, porque a desmonta por dentro." },
  { p: "A comunidade marroquina está entre as maiores, mais antigas e mais enraizadas da Itália: 412.000 residentes em 1º de janeiro de 2025 segundo a Fundação ISMU, terceira nacionalidade depois de romenos e albaneses; 377.554 com permanência regular entre os não comunitários segundo o Ministério do Trabalho, segunda comunidade extra-UE do país. Não episódica: homens sozinhos nos anos 1980, famílias reunificadas nos anos 2000, hoje 82.075 menores, 115.569 estudantes nas escolas italianas, 1.190 casamentos mistos só em 2023. E 27.000 aquisições de cidadania italiana em 2024 — segunda comunidade em naturalizações — depois de mais de 216.000 entre 2006 e 2017." },
  { p: "O dado do ISTAT relançado pelo Il Sole 24 Ore acrescenta a peça que faltava: as chegadas do Marrocos à Itália cresceram quase 50% em 2025 — 36.000 pessoas, segunda nacionalidade por entradas, contadas pelas estatísticas oficiais. O governo mais barulhento sobre a «invasão» de Ceuta preside um país onde os marroquinos são a terceira comunidade nacional, estudam aos 115.000 em suas escolas, casam com seus cidadãos, adquirem sua cidadania num ritmo de 27.000 por ano, e continuam chegando regularmente num ritmo que cresceu 50%. Os dois fatos não podem ser verdadeiros ao mesmo tempo: ou o Marrocos é um perigo, e então é preciso explicar quarenta anos de integração documentada; ou os números dizem a verdade — a cerca de Ceuta era o cenário de um filme rodado para outro público." },
  { h: "Fato sete: quem acendeu o estopim — e o que segue contestado" },
  { p: "Quem mobilizou dezenas de milhares de pessoas rumo a uma cerca no mesmo dia é a pergunta sobre a qual este dossiê, até hoje, segue mais aberto — e é justo dizê-lo com a mesma honestidade aplicada a todo o resto." },
  { p: "O piso judicial está documentado: dezenas de contas anônimas repetiam a mesma mensagem — a fronteira está aberta, quem cruzar fica — e perfis com milhares de seguidores publicavam os pontos de travessia. A Audiencia Nacional abriu investigação sobre redes criminosas, traficantes ou uma estratégia coordenada; Rabat acusou as «máfias da desinformação»; em 5 de agosto, 25 pessoas estavam indiciadas. Já circula a convocação de uma nova entrada em massa para 15 de agosto, até agora sem confirmação oficial de nenhum dos lados." },
  { p: "Sobre quem está por trás, porém, existem duas leituras críveis que não coincidem, e o fact-checking não escolhe pela confiança. Nathalie Tocci (IAI / Johns Hopkins SAIS), em 5 de agosto na Sky TG24, propôs uma taxonomia de três atores: Estados terceiros que militarizam a migração para obter alavancas, como Tunísia, milícias líbias e Turquia antes do Marrocos; atores globais — as origens de parte da desinformação em circulação remontavam, em sua avaliação, a Moscou, ao mundo MAGA americano, a Israel — visando dividir a Europa a partir da Espanha de Sánchez; e as direitas internas cavalgando o que ela chama de «falsa crise». Seu ponto mais afiado é verificável por qualquer um que olhe um mapa: chegar à Espanha continental a partir de Ceuta é mais difícil que a travessia direta do Marrocos, porque os controles de saída do enclave são mais rigorosos. Quem grita invasão-via-Ceuta descreve a rota que nenhum migrante racional escolheria." },
  { p: "Uma pesquisa original da estudiosa Myriam Cherti, publicada em 6 de agosto, complica porém essa leitura. Analisando 180 posts de alto engajamento do precedente de 2024, Cherti encontrou mais de 80% do conteúdo em darija marroquina — conversa local, não mensagem para o exterior — e concluiu que a mobilização foi ação coletiva viabilizada digitalmente, não uma campanha dirigida centralmente. A Associated Press constatou que as acusações de coordenação por traficantes ou de orquestração deliberada do Estado marroquino «não foram publicamente comprovadas». Até a investigação interna do Ministério do Interior marroquino, embora descarte fatores espontâneos e aponte para desinformação e traficantes, não chega a provar um desenho estatal. Duas leituras críveis, não totalmente sobrepostas: a de Tocci sobre atores externos na campanha e em seus desdobramentos políticos, a de Cherti sobre a ausência de um mentor por trás da mobilização original. Sobre o quem, o dossiê público permanece aberto — e a cautela se estende a ambas as atribuições." },
  { p: "O que aconteceu na praça, por outro lado, não exige cautela: é reportagem direta. No sábado à noite, centenas de moradores de Ceuta foram às ruas contra o Núcleo Nacional, movimento de extrema direita espanhol; no dia seguinte, o agitador Vito Quiles apareceu na Plaza de los Reyes com o Save Europe Act — cofundado pelo austríaco Martin Sellner, com ativistas da Generation Identity vindos da Alemanha — e um protesto de bairro rachou com sua presença: «ele veio provocar e nos dividir», nas palavras dos moradores citadas pelas agências. A faixa deles — «Sánchez must go, Spain needs remigration» — estava em inglês; os ceutis que a contestavam respondiam em espanhol. Uma faixa é um ato de comunicação, e seu destinatário se deduz da língua: quem escreve em espanhol em Ceuta fala com Ceuta, quem escreve em inglês fala com a câmera e com o algoritmo. Acrescente-se que Ceuta é cerca de metade de origem marroquina e muçulmana: um erro de casting antes de ser político. Segundo a The Economist, agitadores de extrema direita vindos de toda a Europa espalharam vídeos com a retórica da «substituição étnica»; ao coro juntaram-se também Elon Musk e o vice-presidente americano J.D. Vance. Os atores externos, desta vez, vieram pessoalmente — e seguem sendo os únicos, em toda esta história, a terem cruzado mais fronteiras que os migrantes." },
  { p: "Uma última observação fecha o fato sete, e é talvez a mais afiada de todo o dossiê: a UE não trata todas as alavancas migratórias da mesma forma. Desde 2021, a Bielorrússia leva migrantes do Oriente Médio de avião até a Polônia e países vizinhos como retaliação política; a UE classificou isso como ato de guerra híbrida e endureceu as sanções contra Minsk. O Marrocos, em 2021, já havia deixado cerca de 8.000 pessoas entrarem em Ceuta em retaliação pela hospitalidade médica espanhola ao líder da Frente Polisário — precedente direto dos eventos deste ano. No entanto, observa a The Economist, «não há prova clara de que o Marrocos tenha orquestrado o movimento de migrantes», embora «seus agentes de segurança certamente os deixaram passar» — e os governos europeus, mesmo assim, saudaram a «cooperação» marroquina, reservando a hostilidade a traficantes anônimos e posts nas redes. A diferença de tratamento não é acidental: a UE precisa da cooperação do Marrocos também na rota, bem maior, das Canárias. O analista de Oxford Ruben Andersson resume: a externalização de fronteiras «cria um incentivo para países terceiros fomentarem crises — e se oferecerem para resolvê-las». A especialista em migrações Gemma Pinyol-Jiménez sintetiza o episódio numa frase que fecha bem este fato: «Não foi principalmente uma crise migratória. Foi um episódio geopolítico.»" },
  { h: "Fato oito: o espelho — e o resultado é zero" },
  { p: "O espelho é talvez o capítulo mais notável de todo o episódio. Depois que Roma rejeitou o ultimato espanhol — retirar os controles até 9 de agosto, sob pena de «medidas proporcionais» —, a Espanha ativou controles recíprocos sobre chegadas da Itália a partir da meia-noite de 8 de agosto, válidos até 7 de setembro, justificados oficialmente pela «persistente pressão migratória irregular» italiana. Um detalhe merece registro na coluna da auditoria: a data de 15 de agosto invocada por Palazzo Chigi como seu próprio prazo de revisão não é um anúncio espanhol formal — é, segundo a imprensa dos dois países, um burburinho nas redes no Marrocos que a Guarda Civil considera plausível para uma nova tentativa. Um governo que suspendeu o Schengen citando, entre outros motivos, uma campanha de desinformação está agora justificando a duração dessa suspensão com um rumor não confirmado do mesmo tipo." },
  { p: "Mas o dado mais duro é um resultado, não um procedimento. Na primeira semana, nenhum imigrante irregular vindo de Ceuta havia sido identificado nos controles italianos: zero. Em 13 de agosto, em audiência no Comitê Schengen, o ministro Piantedosi forneceu o balanço oficial atualizado: «desde o restabelecimento dos controles nas fronteiras com a Espanha, efetuamos 3 prisões e devolvemos, por serem ilegais, 21 cidadãos de países terceiros, dos quais 6 marroquinos», anunciando que a decisão não será revista antes de 15 de agosto «e, em todo caso, apenas depois que os riscos de segurança para a Itália forem completamente excluídos». Apliquemos a aritmética da auditoria a esse balanço. Vinte e uma devoluções em treze dias, em todos os voos e balsas vindos da Espanha, dão 1,6 pessoa por dia; a natureza das três prisões não foi especificada; e nem o ministro afirma que um único desses vinte e um venha de Ceuta. Seis são marroquinos — mas marroquino não significa «de Ceuta»: é a segunda nacionalidade por entradas regulares na Itália, e quem embarca num voo comercial já passou pelo controle de documentos da companhia. São, ao que tudo indica, os irregulares administrativos ordinários que qualquer controle de fronteira intercepta em qualquer lugar, todos os dias: o dado «zero ligados a Ceuta» não foi desmentido — foi reembalado. No mesmo dia, de Ceuta, o ministro Grande-Marlaska desmontava o pressuposto da prorrogação: «não há risco de terrorismo» ligado ao afluxo, garantiu, porque o ministério monitora todos os que entraram irregularmente graças à cooperação com o Marrocos — a réplica direta às «possíveis infiltrações terroristas» evocadas em Roma. Já depois da videoconferência dos ministros da UE ele havia dito sem rodeios que foi reconhecido que «a zona Schengen nunca esteve em perigo», exigindo a revogação dos controles italianos. O vice-premiê Salvini havia declarado, entretanto, estar bloqueando «dezenas de irregulares vindos da Espanha»: os dois conjuntos de afirmações não se excluem, mas a distância entre o que a medida deveria prevenir e o que efetivamente interceptou continua sendo o fato mais eloquente de todo o episódio. Na frente doméstica italiana, as oposições — de Fratoianni a Magi a Calenda — usaram registros diferentes mas a mesma substância: propaganda, jogada de valentão, cálculo eleitoral. Não adotamos a linguagem deles, mas registramos que a crítica não vem só de fora: atravessa também o debate interno italiano." },
  { p: "Por fim, um detalhe de geografia completa a aritmética, e é o próprio ministro quem certifica sua premissa: não sendo a Espanha um país limítrofe, os controles se limitam a navios e aviões. O que significa que qualquer pessoa que parta da Espanha e atravesse a França de carro, trem ou ônibus entra na Itália sem encontrar controle italiano algum: a passagem de Ventimiglia, no sentido de entrada, não é coberta pela medida. Um dispositivo de segurança que vigia o voo Barcelona–Fiumicino mas não o trem Barcelona–Ventimiglia–Milão não é um filtro com uma falha: é um filtro com o desvio legal embutido. Mesmo quem quisesse acreditar na ameaça declarada teria de concluir que a medida, assim desenhada, não poderia detê-la." },
  { p: "Resta perguntar o que era, então, aquela medida. Não um filtro migratório: um dispositivo que intercepta zero unidades do fenômeno que declara combater não é um filtro. A chave está no registro com que foi comunicada — mobilizamo-nos para que nenhum clandestino chegue até nós — que é a mesma gramática dos hubs externos do fato nove: o que conta não é quantas pessoas o dispositivo detém, mas que se veja uma fronteira sendo defendida. É o caso-limite em que o caráter simbólico de uma medida é demonstrado justamente pela sua ineficácia: não serve para deter um fluxo que não existia, serve para ser mostrada. O custo, porém, não é nada simbólico: um mês de controles recíprocos entre dois dos maiores países mediterrâneos da União, filas nos aeroportos para os cidadãos de ambos, e um precedente que a partir de agora existe para quem quiser usá-lo." },
  { h: "Fato nove: a geografia como substituto do direito — e a exceção dinamarquesa" },
  { p: "Um fato estrutural, que explica por que tudo isso vai se repetir." },
  { p: "Enquanto em Ceuta se discutiam suspensões, na Europa prosseguia a construção da mesma arquitetura que tornou a crise possível: a externalização das fronteiras. Os hubs externos para o processamento de pedidos de asilo são anunciados há cerca de vinte anos e nunca foram realmente construídos — «se nunca foram criados, talvez haja um motivo», observa Nathalie Tocci, que diz acreditar neles «quando os vir». As duas tentativas que foram mais longe oferecem números úteis: o protocolo Itália-Albânia custou centenas de milhões por centros que ficaram quase sempre vazios, esvaziados repetidamente por decisões judiciais e por fim convertidos em centros de detenção; o esquema britânico de Ruanda foi cancelado em 2024 depois de cerca de 700 milhões de libras e um punhado de transferências voluntárias. Se o critério fosse a eficiência administrativa, projetos com esse rendimento já teriam sido abandonados. Que sejam relançados — desta vez com hipóteses sobre Ruanda, Uganda e Gana, e com projetos-piloto para os «return hubs» da Declaração de Chisinau até 2027 — indica que o critério é outro." },
  { p: "Qual seja, é matéria de interpretação, e registramos três leituras sem escolher uma. A primeira, defendida pelos promotores, é a dissuasão: o objetivo não seria processar muitos casos, mas quebrar o contrato implícito com os traficantes — se chegar não garante ficar, a demanda cai. A segunda é eleitoral: o centro existe para ser anunciado, e seu bloqueio judicial é até funcional, pois transfere a responsabilidade para juízes e Bruxelas. A terceira é simbólica, e é a mais difícil de refutar olhando os balanços: o que importa não é onde o pedido é examinado, mas que quem o apresenta não toque o solo nacional — a fronteira como limiar, não como procedimento." },
  { p: "Seja qual for a motivação, o fato um deste dossiê desmonta sua premissa comum. Em Ceuta a proximidade física era total: território espanhol cheio, dezenas de milhares de pessoas dentro dos limites de uma cidade europeia. E, mesmo assim, ninguém entrou no espaço Schengen, porque o filtro que funcionou não era geográfico, mas jurídico — uma declaração de 1991 e os controles de saída que dela decorrem. A externalização compra território quando o que se precisa é procedimento. E, ao comprá-lo, adverte o antropólogo sueco Ruben Andersson (Oxford), entrega a países terceiros a alavanca: a terceirização «cria um incentivo para países terceiros fomentarem crises — e se oferecerem para resolvê-las». Rachid Niny diz o mesmo da outra margem: a segurança das fronteiras de cada país «não pode ser delegada a um terceiro», e a Europa precisa parar de tratar o Marrocos como «o gendarme das próprias fronteiras». Quando o analista europeu e o diretor de jornal marroquino convergem no mesmo diagnóstico partindo de posições opostas, o dado merece atenção." },
  { p: "Um esclarecimento devido — e para o método deste dossiê é o mais importante do fato nove. A demanda por fronteiras externas mais rígidas não pertence a uma única família política, e tratá-la como tal seria exatamente o tipo de atalho que aqui contestamos. A carta dos 22 é copromovida pela social-democrata Mette Frederiksen, que foi além da assinatura: em declaração à AFP, disse ser óbvio que a UE deve avaliar todas as opções, «inclusive uma suspensão da cooperação Schengen», porque «uma imigração descontrolada representa uma ameaça para a Europa e para a Dinamarca». A carta, aliás, não é um texto morno: reconhece que a decisão do Supremo espanhol «foi utilizada para desencadear este ataque e abusar do nosso sistema de migração e asilo», fala em ameaças híbridas, e pede o enfrentamento de «todas as políticas que possam funcionar como fatores de atração, como a regularização de um número muito elevado de migrantes irregulares» — ou seja, ataca explicitamente a anistia espanhola. Espanha e França não a assinaram." },
  { p: "A posição dinamarquesa, porém, não é uma adaptação tática da última semana: remonta a 2015 e se apoia num argumento explícito — o de que o modelo nórdico (bem-estar universal, salários altos por negociação coletiva, alta carga tributária aceita porque todos contribuem) só se sustenta sobre obrigações recíprocas estreitas, e que a imigração de baixa qualificação erode sua base fiscal e seu consenso. É uma tese discutível no mérito, e discutida: as zonas classificadas pela origem dos moradores, a chamada «lei das joias», os centros de repatriação receberam censuras de ONGs e organismos europeus. Mas é uma tese, argumentada há dez anos — não uma afirmação factual. E seu resultado eleitoral é verificável: na Dinamarca a extrema direita se dissolveu, com o Partido Popular Dinamarquês caindo de 21% em 2015 para 2,6% em 2019, enquanto na Suécia, que manteve a linha oposta, os Democratas Suecos se tornaram decisivos." },
  { p: "Aqui está a distinção em que este dossiê insiste desde o início. Sustentar que as fronteiras externas devem ser endurecidas, ou até que o Schengen deva ser suspenso, é uma posição política — dura, contestável, defendida por governos de direita e de esquerda — que se avalia no mérito. Dizer que em Ceuta estava em curso uma invasão da Europa, ou que aqueles migrantes poderiam se espalhar por Milão ou Helsinque, é uma afirmação factual: e, nos registros da Comissão Europeia, é falsa. Nenhum dos signatários, diga-se, usou a palavra «invasão» nos documentos oficiais — essa palavra veio dos agitadores que viajaram a Ceuta, do vice-presidente americano e da comunicação política doméstica. O fact-checking tem jurisdição apenas sobre o segundo tipo de enunciado. Sobre o primeiro, o leitor decidirá sozinho — que é exatamente como deve funcionar." },
  { h: "Fato dez: a reivindicação — e a segunda janela" },
  { p: "A última peça chegou quando este dossiê já estava na terceira reescrita, e dá um objeto visível à fórmula com que a especialista em migrações Gemma Pinyol-Jiménez fechou o fato sete: não uma crise migratória, um episódio geopolítico." },
  { p: "Em 12 de agosto, com a crise ainda quente, o ministro da Justiça marroquino Abdellatif Ouahbi reiterou publicamente que o Marrocos continua reivindicando Ceuta e Melilla — «continuamos reivindicando a nossa terra; isso exige paciência, e queremos resolver o problema pelo diálogo» — negando ao mesmo tempo que Rabat precise recorrer à imigração para defender seus interesses. A réplica espanhola veio da ministra da Defesa Robles: territórios «espanholíssimos», intocáveis. A reivindicação não é nova — permanece parte da posição oficial e do imaginário nacionalista marroquino, e em 2022 Rabat chegou a sustentar, numa comunicação à ONU, que Marrocos e Espanha não têm fronteira terrestre comum, descrevendo Melilla como território ocupado — mas o timing de seu ressurgimento, doze dias depois do assalto, é um dado que uma auditoria registra. Como registra a estratégia econômica plurianual que a acompanha: entre 2018 e 2019, Rabat fechou a alfândega comercial de Melilla e pôs fim ao contrabando de Ceuta, e até o fim de 2026 será inaugurado o porto Nador West Med, perto de Melilla — uma asfixia comercial dos enclaves conduzida com instrumentos perfeitamente lícitos. No mesmo intervalo de dias, o Conselho Nacional de Direitos Humanos do Marrocos apresentou um relatório acusando as forças espanholas de maltratar parte dos migrantes «sobretudo em lugares fora do alcance das câmeras» — o mesmo órgão que em 2022, depois dos 23 mortos na cerca de Melilla, atribuiu a responsabilidade às autoridades espanholas." },
  { p: "Há ainda um fio que dá ancoragem documental à segunda categoria da taxonomia de Tocci — aquela que o fato sete havia deixado como avaliação de analista. Think tanks americanos e políticos republicanos relançaram as reivindicações marroquinas sobre Ceuta e Melilla, descrevendo os dois enclaves como o ponto mais vulnerável da Espanha, no pano de fundo do embate entre Madri, Washington e Tel Aviv; em 13 de julho, Estados Unidos e Marrocos assinaram um memorando para uma instalação militar conjunta em solo marroquino, e análises desse meio sustentam que Israel deveria usar sua influência em Washington para apoiar diplomaticamente Rabat. Precisão obrigatória: advocacy pública não é orquestração, e nenhum documento liga esses círculos à mobilização de julho. Mas o que em 5 de agosto era uma leitura de analista tem agora ao menos uma expressão escrita, assinada e datada — e o fact-checking a arquiva como tal." },
  { p: "Por fim, a segunda janela. O alerta para uma nova migração em massa na noite de 14 para 15 de agosto se levantou, e desta vez o alvo, segundo o burburinho das redes, pode ser Melilla — não mais apenas Ceuta. O Marrocos reforçou fronteiras, portos e estações, monitorando as mensagens que convocam concentrações na fronteira de Melilla, e a Espanha posicionou em Ceuta duas fragatas da Marinha ao lado da barreira flutuante, com reforços de Guarda Civil, Polícia Nacional, médicos-legistas e magistrados. Os chats monitorados pela imprensa mostram a dinâmica em tempo real: a data do 15, queimada pela publicidade, desliza; circulam mensagens apontando Melilla em dias diferentes e alertando contra Ceuta. É exatamente o mecanismo que a pesquisa de Cherti descreve no fato sete — mobilização entre pares, datas que escorregam, nenhum mentor necessário — e, ao mesmo tempo, a confirmação de que a janela permanece aberta, aconteça o que acontecer no Ferragosto. Dois detalhes fecham o quadro: o ministro do Interior espanhol Grande-Marlaska declarou que «não há lugar na Espanha, nem em Ceuta, nem em Melilla» para quem entra irregularmente; a Dinamarca se diz «pronta a fechar as fronteiras» em caso de nova onda; a Alemanha confirma que as remoções para a Itália com base em Dublin «serão feitas como previsto» — enquanto se negocia um centro de repatriação em Uganda (o fato nove, pontual como um relógio). E o Marrocos que em 30 de julho deixou passar — seus guardas pararam de patrulhar, documentou a The Economist — hoje monta guarda: a variável que decide se algo acontece em 15 de agosto não está em Madri, nem em Roma. Está em Rabat, onde sempre esteve." },
  { h: "O método, outra vez" },
  { p: "Dez fatos, três países, um único critério: os documentos antes das declarações — e a disposição de corrigir o próprio dossiê quando chega uma evidência melhor, como fizemos no fato sete. As empresas brasileiras votaram com os pés contra o Custo Brasil ao atravessar a Ponte da Amizade; os marroquinos votaram com os pés contra seu milagre de duas velocidades; os descendentes de italianos votaram com os pés rumo a uma pátria que parou de responder; e até os provocadores de Ceuta, no fim, votaram com os pés — os únicos a terem cruzado mais fronteiras que os migrantes, para narrar uma crise que os próprios migrantes não reconheciam." },
  { p: "Em todos os casos, o poder respondeu aos pés com retórica em vez de reformas." },
  { p: "Os fatos e números vêm de fontes públicas: o Código de Fronteiras Schengen e o Ato de Adesão da Espanha (1991); declarações da Comissão Europeia (julho–agosto de 2026); TJUE, processos apensos C-368/20 e C-369/20 (2022); HCP e OCDE sobre o mercado de trabalho marroquino; Fundação ISMU, Relatório de Migrações 2026; Ministério do Trabalho italiano, «A comunidade marroquina na Itália — Relatório anual 2025»; ISTAT, relatório de migrações 2025; autos e coberturas sobre a investigação da Audiencia Nacional e as manifestações de Ceuta (agosto de 2026); entrevista de Nathalie Tocci à Sky TG24 «Timeline», 5 de agosto de 2026; pesquisa e análise de Myriam Cherti, Bloomberg, 6 de agosto de 2026; declaração do Ministério do Interior marroquino via MAP, reproduzida pela Bloomberg, 3 de agosto de 2026; imprensa italiana e espanhola sobre os controles recíprocos do Schengen e a cerimônia de Marcinelle (Il Post, Sky TG24, Il Foglio, ANSA, 7–8 de agosto de 2026); The Economist, «Rushing the gates» (31 de julho de 2026) e «The wrong lessons» (5 de agosto de 2026); declarações do ministro do Interior espanhol Grande-Marlaska e coberturas da videoconferência dos ministros da UE de 4 de agosto (Sky TG24); declarações de Matteo Salvini e da oposição italiana, e nota do ministério do Interior espanhol sobre a contramedida de 8 de agosto (LaPresse, Adnkronos, Europa Today, 7–8 de agosto de 2026); entrevista de Rachid Niny em Ras Kebdana, reportagem de Monica Perosino de Ceuta e artigo sobre os 862 menores (La Stampa, agosto de 2026); Rachid Niny, «Diario de un ilegal» (edição espanhola, 2002); Tribunal Supremo, Sala do Contencioso-Administrativo, Quinta Seção, decisão de 8 de julho de 2026 (comunicado do CGPJ e reconstruções de El Independiente, Europa Press e elderecho.com); texto da carta dos 22 líderes europeus (governo.it, 1º de agosto de 2026); declaração de Mette Frederiksen à AFP (31 de julho de 2026); declarações de Abdellatif Ouahbi e réplica de Margarita Robles (Libero, Leggo, Euronews, 12–13 de agosto de 2026); relatório preliminar do CNDH marroquino (8 de agosto de 2026, via Euronews); Alexandre Aublanc, Internazionale (4 de agosto de 2026); Il Fatto Quotidiano sobre o relançamento das reivindicações por círculos neocon dos EUA (1º de agosto de 2026); ANSA, Euronews, Sky TG24 e Il Giornale sobre o alerta de Melilla e o dispositivo de 14–15 de agosto (7–13 de agosto de 2026); audiência do ministro Piantedosi no Comitê Schengen e declarações de Grande-Marlaska de Ceuta (ANSA, AGI, Open, Avvenire, Today, Il Foglio, 13 de agosto de 2026)." },
  { p: "Business Matching Global — inteligência de mercado e orquestração de negócios no corredor Europa–Brasil. Sem dados, você é apenas mais uma pessoa com uma opinião. Nós preferimos ser apenas mais uma pessoa com os dados." },
];

export default function CeutaBR() {
  const { lang, setLang } = useT();
  const article = getArticleBySlug("ceuta_br");
  const desc =
    "O que a crise de Ceuta realmente diz: o status especial fora de Schengen, os dados da Frontex, o Marrocos de duas velocidades e os fluxos que verificam o que os comunicados negam.";
  useCanonical("/ceuta", {
    title: `${TITLE} — Business Matching Global`,
    description: desc,
    type: "article",
  });

  useEffect(() => {
    const previous = lang;
    if (lang !== "pt") setLang("pt");
    return () => {
      if (previous !== "pt") setLang(previous);
    };
  }, [lang, setLang]);

  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <div className="flex items-center justify-between gap-4 mb-8">
          <Link
            to="/analysis"
            className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            Voltar às análises
          </Link>
          <LangSwitcher to="/ceuta" />
        </div>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">{TITLE}</h1>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
          <ShareBlock title={TITLE} />
        </article>
        <AnalysisFooter />
      </div>
    </main>
  );
}
