import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useEffect } from "react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";
import { AnalysisFooter } from "@/components/AnalysisFooter";
import { useCanonical } from "@/lib/useCanonical";
import { ShareBlock } from "@/components/ShareBlock";
import { LangSwitcher } from "@/components/LangSwitcher";

type Block = { h: string } | { p: string };

const TITLE = "Votare con i piedi";

const body: Block[] = [
  { p: "#CustoBrasil — Business Matching Global · pubblicato il 02-08-2026, riscritto e aggiornato al 13-08-2026" },
  { p: "Cosa ci dice la crisi di Ceuta — una volta filtrato il clamore" },
  { p: "«Ci separano appena 17 chilometri, ma sul piano dell'incomprensione reciproca sembrano 17 secoli.» — Rachid Niny, direttore di Al Akhbar, ex migrante irregolare in Spagna" },
  { p: "Alcuni testi sono scritti per persuadere. Questo è scritto per verificare. Da fine luglio, nelle capitali europee e sui social, è circolato un volume insolito di affermazioni categoriche — molte verificabili, molte prive di fondamento. Quanto segue non è la difesa di alcun governo. È un esercizio di ricostruzione del dossier, perché nell'analisi di mercato, come in politica, sono i fatti verificati — non le dichiarazioni — a dire cosa è davvero accaduto. Il dossier, in una settimana, è cresciuto: lo riscriviamo per intero invece di accatastare aggiornamenti, perché un audit che si accumula senza riordinarsi smette di essere leggibile." },
  { h: "Fatto uno: Ceuta non è mai stata nello spazio Schengen" },
  { p: "L'affermazione più diffusa nei primi giorni — che i migranti entrati a Ceuta avessero «violato Schengen» e potessero raggiungere liberamente Milano o Helsinki — crolla al primo controllo della normativa." },
  { p: "Quando la Spagna aderì all'Accordo di Schengen nel 1991, al suo Atto di adesione fu allegata una dichiarazione specifica su Ceuta e Melilla, che esclude le due città nordafricane dal regime di libera circolazione. Lo status speciale è ancora in vigore, oggi nell'articolo 41 del Codice frontiere Schengen. In concreto: entrare a Ceuta non dà diritto di restare in Spagna, raggiungere la penisola iberica o circolare in Europa. I controlli d'uscita tra Ceuta e la terraferma esistono dal 1991." },
  { p: "Vale la pena ricordare come nacque quella dichiarazione, perché non fu un dettaglio tecnico né una semplice imposizione: fu una combinazione di fattori a determinarla, un compromesso a tre strati in cui ciascuna parte ottenne ciò che le serviva. La Spagna chiese e ottenne il regime di traffico frontaliero locale — l'esenzione dal visto per i marocchini residenti nelle province limitrofe di Tetouan e Nador — senza il quale l'economia delle due enclavi, che vive di lavoratori transfrontalieri e commercio quotidiano, sarebbe collassata. I partner Schengen, diffidenti verso due porte africane aperte sullo spazio comune, pretesero in cambio i controlli d'identità obbligatori su tutte le connessioni marittime e aeree verso la penisola. E l'ambiguità sullo status conveniva perfino al Marocco, che le due città non le riconosce e che una loro piena costituzionalizzazione come frontiera esterna UE avrebbe vissuto come una provocazione. Trentacinque anni dopo, l'ironia è da manuale: è proprio il filtro che Madrid subì come condizione dei partner ad averla salvata — è la sua migliore difesa documentale contro l'accusa di aver lasciato entrare 70.000 persone in Europa. (La ricostruzione dei ruoli negoziali è storia diplomatica consolidata, non atto pubblicato: la riportiamo come tale.)" },
  { p: "I numeri confermano che il sistema ha funzionato come previsto. Delle circa 50.000–60.000 persone entrate in meno di 24 ore, le autorità spagnole riferiscono che oltre 48.000 sono state rimpatriate in Marocco entro 48 ore. Il 1° agosto la presidente della Commissione von der Leyen — dopo una videochiamata con i commissari Brunner e Šuica — ha dichiarato pubblicamente che la stragrande maggioranza degli entrati era già rientrata e che nessuna persona aveva raggiunto la Spagna continentale o il resto dell'UE." },
  { p: "Un governo ha comunque sospeso Schengen con la Spagna per un mese, dal 1° agosto, ripristinando controlli selettivi alle frontiere marittime e aeree — su una frontiera che Schengen non ha mai coperto. Bruxelles ha osservato che la sospensione fu annunciata prima che qualsiasi notifica formale giungesse alla Commissione, e un portavoce UE ha chiesto pubblicamente a Roma di spiegare in che modo la crisi costituisse una minaccia alla sicurezza — il presupposto giuridico richiesto per il ripristino. Lo stesso governo ha poi co-promosso, con la Danimarca, una lettera firmata da 22 capi di Stato e di governo europei che chiedeva coordinamento e una risposta europea unita: sospensione unilaterale senza notifica da un lato, richiesta di coordinamento dall'altro, nello stesso ciclo di notizie. Uno dei due gesti contraddice l'altro." },
  { p: "Un elemento più storico che giuridico completa il quadro, e va formulato con precisione perché il governo italiano vi ha opposto un argomento che merita risposta. È vero, come ha ricordato il ministro Piantedosi in audizione, che controlli interni tra Stati membri esistono da anni, «anche nei confronti dell'Italia»: l'Austria al Brennero, la Francia a Ventimiglia. Ma quei controlli rispondono a flussi documentati in transito attraverso un altro Stato membro — persone contate, rotte tracciate, notifiche depositate. La novità del caso italo-spagnolo è un'altra, ed è duplice: è la prima sospensione a scopo ritorsivo nata da una disputa politica bilaterale, con ultimatum incrociati e contromisura reciproca — e la prima adottata a flussi zero, contro un movimento che la Commissione certifica non essere mai esistito. Il Brennero filtra un transito reale; il dispositivo verso la Spagna ha filtrato un transito inesistente. Non è un precedente sui controlli: quelli c'erano già. È il precedente sull'uso di Schengen come strumento di pressione tra due Stati membri — per giunta tra due dei paesi che allo spazio di libera circolazione aderirono per primi dopo i cinque firmatari originari del 1985: l'Italia nel 1990, la Spagna nel 1991." },
  { p: "Due precisazioni completano il fatto uno. La richiesta iniziale della premier Meloni — l'espulsione della Spagna dall'intera area Schengen — era essa stessa tecnicamente irrealizzabile: non può avvenire contro la volontà della Spagna, nota l'Economist. Ciò che l'Italia ha effettivamente fatto è stato un provvedimento più modesto, controlli a campione in porti e aeroporti — la distanza tra la richiesta e la misura è già un indizio del registro (politico interno) in cui la vicenda si è svolta. E soprattutto: il 4 agosto, alla videoconferenza d'urgenza dei ministri dell'Interno UE, il livello europeo ha già archiviato l'allarme. Il commissario Brunner ha dichiarato «piena solidarietà con la Spagna»; ogni discorso di espulsione da Schengen è scomparso dai comunicati, sostituito dai consueti punti programmatici su frontiere, trafficanti e rimpatri. Mentre Roma manteneva la sospensione bilaterale — e la settimana successiva Madrid rispondeva nella stessa moneta — l'istituzione europea aveva già chiuso il caso. Il confronto Roma-Madrid, da quel momento, non è più una crisi UE: è una disputa a due, tenuta in vita da chi ha deciso di tenerla in vita." },
  { h: "Fatto due: la regolarizzazione non c'entra con la recinzione" },
  { p: "Una seconda affermazione ha collegato la crisi alla regolarizzazione spagnola di circa 500.000 migranti, presentata come invito aperto. I meccanismi dicono il contrario: il processo richiede residenza pregressa documentata, fedina pulita, contratto di lavoro o mezzi sufficienti. Chi ha scavalcato una recinzione a luglio 2026 ne è escluso per definizione. Una precisazione sul numero stesso: 500.000 era la stima attesa dalle autorità spagnole, non il totale regolarizzato — le domande effettivamente ricevute sono state 1,2 milioni, di cui non è pubblicamente noto quante approvate. Anche nella versione più ampia del dato, resta un processo di domanda documentata con requisiti — non un cancello aperto per chi arriva a nuoto. Le autorità spagnole hanno documentato anche una campagna di disinformazione che ha travisato una sentenza della Corte Suprema sui rimpatri per convincere le persone che raggiungere Ceuta garantisse la permanenza. Non è così; la sentenza ha cambiato la procedura, non i diritti di soggiorno." },
  { p: "Vale la pena leggerla, quella sentenza, perché è il vero innesco tecnico della vicenda ed è stata citata da tutti senza quasi mai essere descritta. È dell'8 luglio 2026, Sezione Quinta della Sala Contenzioso-Amministrativa del Tribunal Supremo, e nasce dal ricorso dell'Avvocatura dello Stato nel caso di un cittadino algerino intercettato in mare il 14 novembre 2024 mentre tentava di raggiungere Ceuta a nuoto, e consegnato immediatamente al Marocco. La Corte stabilisce che il «rechazo en frontera» — le espulsioni immediate previste dalla Disposizione aggiuntiva decima della legge sugli stranieri — non si applica a chi arriva a nuoto, perché costui non supera alcun «elemento di contenimento» della frontiera: droni, telecamere termiche e sensori, argomenta il tribunale, svolgono funzioni di sorveglianza e allerta, non di contenimento materiale, e quindi non attivano il regime eccezionale. A queste persone va applicata la procedura ordinaria di rimpatrio dell'articolo 58.3 della legge organica 4/2000. La sentenza non modifica la legge sugli stranieri, non dichiara illegali le espulsioni immediate e non attribuisce alcun diritto di restare: cambia quale procedura si applica, e con essa l'obbligo di aprire un fascicolo individuale — passaggio necessario, tra l'altro, per identificare minori e persone vulnerabili." },
  { p: "E qui si trova il dettaglio che nessuna cronaca ha collegato. La stessa sentenza precisa che «nulla impedirebbe» di applicare le espulsioni immediate qualora venissero installati «elementi di contenimento in mare a protezione della linea di frontiera». Tre settimane dopo, la Spagna ha posato al Tarajal una barriera galleggiante di 500 metri. Quella barriera, che la stampa ha raccontato come misura fisica di deterrenza, è anche — e forse soprattutto — uno strumento giuridico: crea l'elemento di contenimento marittimo che la Corte aveva indicato come condizione per ripristinare il regime di respingimento immediato. Il governo spagnolo non ha aggirato la sentenza: ne ha eseguito le istruzioni implicite. È un caso raro e istruttivo di ingegneria giuridica costruita nel mondo fisico, ed è anche la prova che l'apparato spagnolo ha reagito alla crisi lavorando sul diritto, mentre altrove si lavorava sui comunicati." },
  { p: "I dati Frontex citati dal governo spagnolo sugli ingressi irregolari 2021–2026 classificano le rotte così: Italia circa 478.600; Balcani occidentali 340.600; Grecia 259.800; Spagna 234.760. Il paese che ha sospeso Schengen con la Spagna ha registrato circa il doppio degli ingressi irregolari della Spagna nello stesso periodo." },
  { p: "Vale notare come fu formulata questa replica. Mentre altre capitali inasprivano — vertici, frontiere chiuse, ambasciatori convocati — la risposta del premier spagnolo fu un post con quei numeri Frontex, introdotti da una sola osservazione: solidarietà ed empatia sono opzionali, il rispetto dei trattati e dei dati no. Da un lato una tabella, dall'altro un'escalation diplomatica." },
  { p: "Un'ultima osservazione sul «fattore di attrazione», e viene dal mercato, non dalla politica. Sui social latinoamericani circolano in questi giorni le inserzioni di agenzie migratorie private che vendono esattamente il percorso spagnolo: residenza con visto non lucrativo o da nomade digitale, e — grazie alla corsia preferenziale che il Código Civil riserva da decenni ai cittadini iberoamericani — possibilità di chiedere la cittadinanza dopo appena due anni, «commenta España e prenota il tuo appuntamento». Con le semplificazioni tipiche del marketing (i due anni sono il requisito per presentare la domanda, poi vengono esami e anni di coda), ma il punto è un altro: guardare a chi si rivolge questa industria. A chi può dimostrare un reddito, compilare un formulario, prenotare una cita — il canale legale, documentato, con appuntamento. Il fattore di attrazione spagnolo esiste, ed è letteralmente in vendita: ma il suo cliente non è chi nuota attorno a un frangiflutti — che da quel percorso, come si è visto, è escluso per definizione. Il pull factor vero produce pratiche, non assalti. E c'è un dettaglio che anticipa il fatto cinque: tra i clienti di queste agenzie figurano sempre più spesso anche gli italo-discendenti sudamericani respinti dalla stretta italiana del 2025 — il mercato si è semplicemente spostato sul paese che le porte legali le ha lasciate aperte. (L'inserzione è citata come fenomeno di mercato osservato, non come fonte normativa.)" },
  { h: "Fatto tre: il modello spagnolo, imperfetto ma misurabile" },
  { p: "La Spagna è la grande economia in più rapida crescita dell'eurozona, circa il 3% annuo per due anni consecutivi, mentre Germania e Italia restano vicine allo zero. I motori: turismo da record, assorbimento efficace dei fondi Next Generation EU, rinnovabili a basso costo e — ironia della polemica — l'immigrazione stessa, che ha sostenuto occupazione e consumi in un continente che invecchia. Punti deboli reali ci sono: crisi abitativa grave, bassa produttività oraria, precarietà residua. Ma «imperfetto e in crescita del 3%» è una frase diversa da quella che si scrive sulla Spagna in questi giorni." },
  { h: "Fatto quattro: il Marocco non è un Eldorado — e un'elezione spiega parte del perché" },
  { p: "Il Marocco ha promosso per anni la propria immagine di storia di successo africana: crescita del PIL sopra il 3%, espansione cumulata del 22% dal 2019, export che si avvicina alla produzione automobilistica italiana, alta velocità Kenitra-Marrakech, Mondiali 2030 con lo stadio più grande del mondo." },
  { p: "L'altro lato del bilancio: circa due terzi dell'occupazione marocchina è informale — 67,6% secondo il conto satellite HCP/OIT, oltre il 67% secondo l'OCSE, fino al 77% in altre stime. La disoccupazione dei 15-24enni ha superato il 36% nel 2024-2025; con la metodologia «in senso stretto» del 2026 il tasso ufficiale scende al 29%, ma la sottoutilizzazione complessiva della forza lavoro giovanile resta al 45%. La partecipazione femminile è scesa dal 28% del 2000 al 19%, tra i divari più ampi al mondo. La crescita si concentra in settori ad alta intensità di capitale controllati da multinazionali straniere: assorbono investimenti, danno lavoro a pochi, ridistribuiscono meno. Il movimento GenZ 212 ha condensato lo squilibrio in uno slogan: vogliamo ospedali, non stadi. L'OCSE colloca il Marocco ai primi posti mondiali per lavoratori in uscita." },
  { p: "Un contesto che le prime ricostruzioni hanno omesso: il Marocco vota per le elezioni generali il 23 settembre 2026. È plausibile leggere l'assalto alla recinzione — decine di migliaia di persone nel giorno della Festa del Trono del proprio re — anche come espressione di malcontento pre-elettorale, sopra le proteste Gen Z dell'ottobre 2025 contro le infrastrutture dei Mondiali percepite come priorità sbagliata rispetto a sanità e istruzione. Nessun fatto qui esposto richiede che questa lettura sia vera, ma ometterla significa perdere una variabile rilevante quanto qualsiasi attore straniero." },
  { p: "La voce che chiude questo fatto, però, non è europea — ed è la ragione per cui la riportiamo per ultima. Rachid Niny, direttore di Al Akhbar e di TeleMaroc, arrivò in Spagna nel 1997 con un visto di un mese per seguire un congresso alle Canarie: non ci andò, si diresse a Benidorm e vi rimase tre anni da irregolare, lavando piatti e pulendo porcilaie dopo un master in poesia contemporanea. Ne trasse Diario de un ilegal, il primo testimonio in lingua araba sull'esperienza dei migranti marocchini in Spagna, un libro costruito attorno a un'immagine sola: l'eldorado che svanisce appena lo si raggiunge. Ventisette anni dopo, intervistato da La Stampa a Ras Kebdana, dice che nulla di ciò che è accaduto a Ceuta è nuovo — «finché ci saranno domanda e offerta queste scene non finiranno: il mercato dell'immigrazione irregolare non conosce recessione» — e che teme il peggio se continuerà a crescere «questa enorme riserva di giovani disposti a scommettere la vita per un paradiso che esiste soltanto nella loro immaginazione»." },
  { p: "Il suo bilancio del proprio paese coincide con i numeri di questa analisi, ma lo formula meglio di qualsiasi indicatore: nel 1997 il Marocco era sommerso dai debiti e la disoccupazione batteva ogni record; oggi ci sono autostrade, rinnovabili, porti competitivi e crescita vicina al 5%, ma i frutti non arrivano a chi sta in fondo alla scala sociale. «Ieri il Marocco rischiava un arresto cardiaco per debiti e stagnazione. Oggi cresce, piovono investimenti stranieri, e tuttavia rischia un arresto cardiaco sociale.» Sul messaggio di Ceuta alla classe dirigente marocchina è ancora più netto: «avete una bomba a orologeria chiamata gioventù e dovete disinnescarla prima che distrugga tutto». L'emergenza, per lui, è il fallimento della scuola pubblica — circa 300.000 studenti abbandonano ogni anno, ingrossando un esercito di adolescenti senza diploma — e il salario minimo attorno ai 300 euro: «le persone devono sentire la crescita nelle proprie tasche», dice, proponendo di portarlo almeno a 500, perché «se pensate che il costo dell'istruzione sia troppo alto, provate il costo dell'ignoranza»." },
  { p: "Tre osservazioni di Niny meritano di essere registrate a parte, perché correggono altrettante scorciatoie della narrazione europea. La prima: a Ceuta non è andata solo la povertà. Tra chi è entrato c'erano operai, lavoratori d'albergo, dipendenti di panetterie e caffè; alcuni sono entrati in acqua con gli abiti da lavoro, uno con il papillon al collo. Nelle fabbriche, dice, ci si dimette per salari sproporzionati allo sforzo: «le persone non sono più disposte ad accettare la schiavitù sul posto di lavoro». La seconda riguarda i social, e integra la ricerca di Cherti citata più avanti: «esiste un'epidemia globale chiamata influencer» in un paese dove il 55% dei giovani tra i 18 e i 29 anni sogna di emigrare, e tra chi è entrato a Ceuta c'erano influencer che hanno trasformato la traversata in contenuti da milioni di visualizzazioni, diventando modelli per altri giovani. La terza è rivolta all'Europa, e vale come contro-tesi al fatto uno: «la sicurezza delle frontiere di ciascun Paese non può essere delegata a una terza parte», e l'Europa «deve smettere di considerarci il gendarme delle proprie frontiere» — la stessa esternalizzazione che, secondo l'analista di Oxford citato più avanti, crea l'incentivo a fomentare crisi e poi offrirsi di risolverle. Chiude con la frase che questo dossier ha scelto come esergo: tra le due sponde «ci separano appena 17 chilometri, ma sul piano dell'incomprensione reciproca sembrano 17 secoli»." },
  { p: "E infine la riga che collega il Marocco di oggi all'Italia di ieri, pronunciata da chi è tornato a casa e ha scelto di restarci: «mi tolgo il cappello davanti ai migranti che decidono di sacrificare tutto questo. Ci vuole un grande coraggio per lasciarsi tutto alle spalle ed emigrare. È ciò che gli europei non vedono, o forse hanno dimenticato». Il fatto cinque, più avanti, mostra quanto letteralmente abbiano dimenticato." },
  { p: "Il bilancio umano resta il dato che nessuna narrazione sovrana può assorbire — ed è, ad oggi, ancora in evoluzione e discordante tra le fonti. Il totale degli ingressi, secondo il ministro dell'Interno spagnolo al 4 agosto, è stato di circa 72.000 persone, di cui 70.000 già rientrate in Marocco. Sul lato dei morti, la forbice si è allargata invece di chiudersi: 11 secondo il primo conteggio marocchino, oltre 48.000 rimpatriati entro 48 ore secondo Madrid, 72 vittime riportate dalla Spagna in attesa di verifica congiunta, quasi 100 morti e 50 dispersi secondo la polizia spagnola al 6 agosto, almeno 141 annegati al frangiflutti secondo The Economist il 5 agosto. Segnaliamo la forbice invece di sceglierne un numero: è essa stessa il fatto, perché un bilancio che continua a crescere mentre proseguono le ricerche racconta più di qualsiasi cifra definitiva. Una precisazione anche sulla composizione: il grosso dell'ondata del 30-31 luglio era di cittadini marocchini, come documentano sia Rabat sia le analisi sui contenuti social — ma non tutti; tra chi restava a Ceuta ai primi di agosto, secondo The Economist, la maggioranza erano migranti subsahariani e minori non accompagnati, circa 1.100 dei quali destinati al trasferimento in Spagna. Anche qui i numeri divergono per fonte e per data, e registriamo la forbice: il 13 agosto, in audizione, il ministro Piantedosi ha parlato di almeno 6.000 persone ancora nell'exclave — «anche se alcune fonti parlano di oltre 11.000» — prevalentemente subsahariane, per le quali non risulterebbero praticabili né riammissione né ritorno in Marocco, e di oltre 1.300 minori non accompagnati che non potranno essere rimpatriati, mentre le stime locali spagnole dei giorni precedenti si fermavano a 3.000-5.000. La Stampa ha dedicato un pezzo a parte agli 862 bambini rimasti in attesa di collocazione, e dalla città il reportage di Monica Perosino registra il livello raggiunto dall'emergenza — «non sappiamo più dove mettere i corpi» — segnalando insieme il silenzio imposto sul lato marocchino. Il quadro corretto non è «marocchini invece di subsahariani», ma due popolazioni distinte con traiettorie diverse: i marocchini, rimpatriabili rapidamente per via degli accordi bilaterali, sono usciti dal conteggio in pochi giorni; i migranti subsahariani, in una zona grigia legale più complessa, sono quelli rimasti. Quando le persone rischiano la vita tra filo spinato e mare aperto, stanno assegnando a un paese un rating più onesto di qualunque agenzia. Hanno votato con i piedi. È l'unico voto che non può essere manipolato." },
  { h: "Fatto cinque: il bilancio degli stessi accusatori — e un'ironia pronunciata sulle tombe sbagliate" },
  { p: "I governi più accesi nel denunciare Madrid meritano la stessa verifica che esigono dagli altri." },
  { p: "L'Italia, nel 2025, ha limitato la cittadinanza iure sanguinis — decreto firmato dallo stesso ministro degli Esteri che oggi attacca la regolarizzazione spagnola — escludendo la maggior parte dei discendenti sudamericani degli emigranti italiani, salvo figli e nipoti di chi è nato in Italia. Lo stesso schieramento assiste ora all'arrivo in Parlamento dell'iniziativa popolare «Remigrazione e Riconquista», 150.000 firme: un testo che definisce la remigrazione come rimpatrio assistito degli stranieri legalmente residenti in Italia e che, contemporaneamente, propone sostegno statale per il ritorno dei discendenti italiani all'estero." },
  { p: "I discendenti che hanno atteso anni ai consolati per la cittadinanza votavano con i piedi verso l'Italia — porta chiusa, liquidati come costo consolare. Gli stranieri che hanno votato con i piedi verso l'Italia e vi hanno costruito una vita regolare sono ora, nella proposta più radicale, invitati ad andarsene. Diaspora come passivo, popolazione residente come surplus: contabilità incoerente, pessimo pulpito da cui dare lezioni a Madrid." },
  { p: "E il 7 agosto l'incoerenza ha trovato la sua immagine più netta. Alla cerimonia per il settantesimo anniversario della tragedia di Marcinelle — dove morirono 136 lavoratori emigrati italiani, parte dei 50.000 inviati in Belgio con l'accordo «uomini contro carbone» del 1946 — la premier Meloni ha dichiarato che «in Europa non c'è spazio per chi alimenta canali dell'immigrazione clandestina per avere manodopera a basso costo». Parole rivolte a Rabat e ai trafficanti. Pronunciate sulle tombe di italiani che furono, in ogni senso sostanziale se non giuridico, esattamente questo: manodopera a basso costo trasferita oltre confine da un accordo scritto per servire l'economia di qualcun altro. Non serve altro commento." },
  { p: "Un'ultima voce del bilancio, ed è la Spagna stessa a presentarla: nel motivare la propria contromisura contro l'Italia, il ministero dell'Interno spagnolo ha citato ufficialmente quasi mezzo milione di immigrati irregolari arrivati in Italia negli ultimi cinque anni a fronte di appena 16.000 rimpatri — cifre che, per ordine di grandezza, confermano i dati Frontex del fatto due. Sánchez ha aggiunto un'accusa più tecnica e verificabile: l'Italia non rispetterebbe dal 2022 il Regolamento di Dublino, scaricando così pressione migratoria aggiuntiva sugli altri Stati membri. Non è un'opinione da arbitrare qui — è un'affermazione puntuale che meriterebbe una verifica a sé — ma il fatto che l'accusa arrivi con un numero e un articolo di regolamento, invece che con un aggettivo, la colloca in una categoria diversa dal resto della polemica." },
  { h: "Fatto sei: i marocchini sono già qui — e sono l'Italia che funziona" },
  { p: "Il fatto che la narrazione dell'invasione non può digerire, perché la smonta dall'interno." },
  { p: "La comunità marocchina è tra le più grandi, antiche e radicate d'Italia: 412.000 residenti al 1° gennaio 2025 secondo Fondazione ISMU, terza nazionalità dopo romeni e albanesi; 377.554 regolarmente soggiornanti tra i non comunitari secondo il Ministero del Lavoro, seconda comunità extra-UE del paese. Non episodica: uomini soli negli anni Ottanta, famiglie ricongiunte nei Duemila, oggi 82.075 minori, 115.569 studenti nelle scuole italiane, 1.190 matrimoni misti nel solo 2023. E 27.000 acquisizioni di cittadinanza italiana nel 2024 — seconda comunità per naturalizzazioni — dopo le oltre 216.000 del 2006-2017." },
  { p: "Il dato ISTAT rilanciato da Il Sole 24 Ore aggiunge il pezzo mancante: gli arrivi dal Marocco in Italia sono cresciuti di quasi il 50% nel 2025 — 36.000 persone, seconda nazionalità per ingressi, contati dalle statistiche ufficiali. Il governo più rumoroso sull'«invasione» di Ceuta presiede un paese dove i marocchini sono la terza comunità nazionale, studiano in 115.000 nelle sue scuole, ne sposano i cittadini, ne acquisiscono la cittadinanza a un ritmo di 27.000 l'anno, e continuano ad arrivare regolarmente a un ritmo cresciuto del 50%. I due fatti non possono essere veri insieme: o il Marocco è un pericolo, e allora vanno spiegati quarant'anni di integrazione documentata; o i numeri dicono il vero — la recinzione di Ceuta era il set di un film girato per un altro pubblico." },
  { h: "Fatto sette: chi ha acceso la miccia — e cosa resta contestato" },
  { p: "Chi ha mobilitato decine di migliaia di persone verso una recinzione nello stesso giorno è la domanda su cui il dossier, ad oggi, resta più aperto — ed è giusto dirlo con la stessa onestà con cui abbiamo trattato tutto il resto." },
  { p: "Il pavimento giudiziario è documentato: decine di account anonimi ripetevano lo stesso messaggio — il confine è aperto, chi attraversa resta — e profili con migliaia di follower pubblicavano i punti di attraversamento. L'Audiencia Nacional ha aperto un'inchiesta su reti criminali, trafficanti o una strategia coordinata; Rabat ha accusato le «mafie della disinformazione»; al 5 agosto risultano incriminate 25 persone. Circola già la convocazione di un nuovo ingresso di massa per il 15 agosto, finora senza conferme ufficiali da nessuna delle due sponde." },
  { p: "Su chi sia dietro, però, esistono due letture credibili che non coincidono, e il fact-checking non sceglie sulla fiducia. Nathalie Tocci (IAI / Johns Hopkins SAIS), il 5 agosto su Sky TG24, ha proposto una tassonomia a tre attori: Stati terzi che militarizzano la migrazione per ottenere leve, come Tunisia, milizie libiche e Turchia prima del Marocco; attori globali — le provenienze di parte della disinformazione circolata riconducevano, nella sua valutazione, a Mosca, al mondo MAGA statunitense, a Israele — con l'obiettivo di dividere l'Europa a partire dalla Spagna di Sánchez; e le destre interne che cavalcano quella che definisce una «finta crisi». Il suo punto più tagliente è verificabile da chiunque guardi una mappa: raggiungere la Spagna continentale da Ceuta è più difficile del viaggio diretto dal Marocco, perché i controlli in uscita dall'enclave sono più stringenti. Chi grida all'invasione via Ceuta descrive la rotta che nessun migrante razionale sceglierebbe." },
  { p: "Una ricerca originale della studiosa Myriam Cherti, pubblicata il 6 agosto, complica però questa lettura. Analizzando 180 post ad alto coinvolgimento del precedente 2024, Cherti ha trovato oltre l'80% dei contenuti in darija marocchina — conversazione locale, non messaggio per l'estero — e ha concluso che la mobilitazione fu azione collettiva abilitata dai social, non una campagna diretta centralmente. L'Associated Press ha verificato che le accuse di coordinamento da trafficanti o di orchestrazione deliberata dello Stato marocchino «non sono state pubblicamente sostanziate». Anche l'indagine interna del ministero dell'Interno marocchino, pur escludendo fattori spontanei e puntando su disinformazione e trafficanti, non arriva a provare un disegno statale. Due letture credibili, non del tutto sovrapponibili: quella di Tocci sugli attori esterni nella campagna e nelle sue conseguenze politiche, quella di Cherti sull'assenza di un regista dietro la mobilitazione originaria. Sul chi, il fascicolo pubblico resta aperto — e la cautela va estesa a entrambe le attribuzioni." },
  { p: "Ciò che è successo in piazza, invece, non richiede cautela: è cronaca diretta. Sabato sera centinaia di ceutini sono scesi in strada contro Núcleo Nacional, movimento spagnolo di estrema destra; il giorno dopo l'agitatore Vito Quiles si è presentato in Plaza de los Reyes con Save Europe Act — co-fondato dall'austriaco Martin Sellner, con attivisti di Generation Identity arrivati dalla Germania — e una protesta di quartiere si è spaccata per la sua presenza: «è venuto a provocare e a dividerci», la frase dei residenti raccolta dalle agenzie. Il loro striscione — «Sánchez must go, Spain needs remigration» — era in inglese; i ceutini che lo contestavano rispondevano in spagnolo. Un cartello è un atto di comunicazione, e il destinatario si deduce dalla lingua: chi scrive in spagnolo a Ceuta parla a Ceuta, chi scrive in inglese parla alla telecamera e all'algoritmo. Si aggiunga che Ceuta è per circa metà di origine marocchina e musulmana: un errore di casting prima ancora che politico. Secondo The Economist, agitatori di estrema destra arrivati da tutta Europa hanno diffuso video con la retorica della «sostituzione etnica»; al coro si sono uniti anche Elon Musk e il vicepresidente USA J.D. Vance. Gli attori esterni, stavolta, sono venuti di persona — e restano gli unici, in tutta questa storia, ad aver attraversato più frontiere dei migranti." },
  { p: "Un'ultima osservazione chiude il fatto sette, ed è forse la più tagliente dell'intero dossier: l'Unione europea non tratta tutte le leve migratorie allo stesso modo. Dal 2021 la Bielorussia ha fatto volare migranti mediorientali verso Polonia e Stati confinanti come ritorsione politica; l'UE l'ha classificata come atto di guerra ibrida e ha inasprito le sanzioni contro Minsk. Il Marocco, nel 2021, aveva già fatto entrare circa 8.000 persone a Ceuta per ritorsione contro l'ospitalità sanitaria spagnola al leader del Fronte Polisario — un precedente diretto di quanto avvenuto quest'anno. Eppure, nota The Economist, «non c'è prova chiara che il Marocco abbia orchestrato il movimento dei migranti», mentre «i suoi funzionari della sicurezza li hanno certamente lasciati passare» — e i governi europei hanno comunque salutato la «cooperazione» marocchina, riservando l'ostilità a trafficanti anonimi e post sui social. La differenza di trattamento non è casuale: l'UE ha bisogno della cooperazione del Marocco anche sulla rotta ben più consistente delle Canarie. Un analista di Oxford, Ruben Andersson, la mette così: l'esternalizzazione dei confini «crea un incentivo per i paesi terzi a fomentare crisi — e offrirsi di risolverle». Gemma Pinyol-Jiménez, esperta di migrazioni, sintetizza l'intera vicenda in una frase che vale come chiusura di questo fatto: «Non è stata principalmente una crisi migratoria. È stato un episodio geopolitico.»" },
  { h: "Fatto otto: lo specchio — e il risultato è zero" },
  { p: "Lo specchio è il capitolo forse più clamoroso dell'intera vicenda. Dopo che Roma ha respinto l'ultimatum spagnolo — rimuovere i controlli entro il 9 agosto, pena «misure proporzionate» — la Spagna ha attivato dalla mezzanotte dell'8 agosto controlli reciproci sugli arrivi dall'Italia, validi fino al 7 settembre, motivati ufficialmente con la «persistente pressione migratoria irregolare» italiana. Un dettaglio va registrato nella colonna dell'audit: la data del 15 agosto invocata da Palazzo Chigi come proprio termine di verifica non è un annuncio spagnolo formale — è, secondo la stampa di entrambi i paesi, un «tam tam social» in Marocco che la Guardia Civil ritiene plausibile per un nuovo tentativo. Un governo che ha sospeso Schengen anche per una campagna di disinformazione sta ora giustificando la durata di quella sospensione citando una voce non confermata dello stesso tipo." },
  { p: "Ma il dato più duro è un risultato, non una procedura. Nella prima settimana, nessun immigrato irregolare proveniente da Ceuta risultava identificato ai controlli italiani: zero. Il 13 agosto, in audizione al Comitato Schengen, il ministro Piantedosi ha fornito il bilancio ufficiale aggiornato: «dal ripristino dei controlli alle frontiere con la Spagna, abbiamo effettuato 3 arresti e respinto, in quanto illegali, 21 cittadini di Paesi terzi, di cui 6 marocchini», annunciando che la decisione non sarà rivista prima del 15 agosto «e comunque solo dopo che saranno completamente esclusi rischi di sicurezza per l'Italia». Applichiamo l'aritmetica dell'audit a quel bilancio. Ventuno respingimenti in tredici giorni, su tutti i voli e i traghetti in arrivo dalla Spagna, fanno 1,6 persone al giorno; la natura dei tre arresti non è stata specificata; e nemmeno il ministro sostiene che uno solo di quei ventuno provenga da Ceuta. Sei sono marocchini — ma marocchino non significa «da Ceuta»: è la seconda nazionalità per ingressi regolari in Italia, e chi sale su un volo di linea ha già superato il controllo documenti del vettore. Sono, con ogni evidenza, gli ordinari irregolari amministrativi che qualunque controllo di frontiera intercetta ovunque, ogni giorno: il dato «zero collegati a Ceuta» non è stato smentito — è stato riconfezionato. Nello stesso giorno, da Ceuta, il ministro Grande-Marlaska smontava il presupposto della proroga: «non vi è alcun rischio di terrorismo» legato all'afflusso, ha assicurato, perché il ministero monitora tutti gli entrati irregolarmente grazie alla cooperazione con il Marocco — la replica diretta alle «possibili infiltrazioni terroristiche» evocate a Roma. Già dopo la videoconferenza dei ministri UE aveva detto senza giri di parole che era stato riconosciuto che «la zona Schengen non è mai stata in pericolo», chiedendo la revoca dei controlli italiani. Il vicepremier Salvini aveva intanto dichiarato di star bloccando «decine di irregolari in arrivo dalla Spagna»: le due serie di affermazioni non si escludono, ma la distanza tra ciò che la misura doveva prevenire e ciò che ha effettivamente intercettato resta il fatto più eloquente dell'intera vicenda. Sul fronte interno italiano, le opposizioni — da Fratoianni a Magi a Calenda — hanno usato registri diversi ma la stessa sostanza: propaganda, mossa da bulla, calcolo elettorale. Non adottiamo il loro linguaggio, ma segnaliamo che la critica non arriva solo da fuori: attraversa anche il dibattito interno italiano." },
  { p: "C'è infine un dettaglio di geografia che completa l'aritmetica, ed è il ministro stesso a certificarne la premessa: non essendo la Spagna un paese confinante, i controlli sono limitati a navi e aerei. Il che significa che chiunque parta dalla Spagna e attraversi la Francia in auto, in treno o in autobus entra in Italia senza incontrare alcun controllo italiano: il valico di Ventimiglia, in direzione entrante, non è coperto dalla misura. Un dispositivo di sicurezza che sorveglia il volo Barcellona-Fiumicino ma non il treno Barcellona-Ventimiglia-Milano non è un filtro con una falla: è un filtro con l'aggiramento legale incorporato. Anche chi volesse credere alla minaccia dichiarata dovrebbe concludere che la misura, così disegnata, non potrebbe fermarla." },
  { p: "Resta da chiedersi cosa fosse, allora, quella misura. Non un filtro migratorio: un dispositivo che intercetta zero unità del fenomeno che dichiara di contrastare non è un filtro. La chiave sta nel registro con cui è stata comunicata — ci siamo attivati perché nessun clandestino arrivi da noi — che è la stessa grammatica degli hub esterni di cui al fatto nove: ciò che conta non è quante persone il dispositivo fermi, ma che si veda un confine mentre viene difeso. È il caso limite in cui il carattere simbolico di una misura è dimostrato proprio dalla sua inefficacia: non serve a fermare un flusso che non esisteva, serve a essere mostrato. Il costo, però, non è simbolico affatto: un mese di controlli reciproci tra due dei maggiori paesi mediterranei dell'Unione, code negli aeroporti per i cittadini di entrambi, e un precedente che da oggi esiste per chiunque vorrà usarlo." },
  { h: "Fatto nove: la geografia come surrogato del diritto — e l'eccezione danese" },
  { p: "Un fatto strutturale, che spiega perché tutto questo si ripeterà." },
  { p: "Mentre a Ceuta si discuteva di sospensioni, in Europa proseguiva la costruzione della stessa architettura che ha reso possibile la crisi: l'esternalizzazione delle frontiere. Gli hub esterni per il trattamento delle domande d'asilo si annunciano da circa vent'anni e non sono mai stati realizzati davvero — «se non sono mai stati creati, forse qualche motivo c'è», osserva Nathalie Tocci, che dice di crederci «quando li vedrò». I due tentativi arrivati più avanti offrono numeri utili: il protocollo Italia-Albania è costato centinaia di milioni per centri rimasti quasi sempre vuoti, svuotati a ripetizione dalle pronunce dei giudici e infine riconvertiti a CPR; lo schema britannico verso il Ruanda è stato cancellato nel 2024 dopo circa 700 milioni di sterline e una manciata di trasferimenti volontari. Se il criterio fosse l'efficienza amministrativa, progetti con questo rendimento sarebbero già stati abbandonati. Che vengano invece rilanciati — questa volta con ipotesi su Ruanda, Uganda e Ghana, e con l'avvio entro il 2027 di progetti pilota per i «return hub» previsti dalla Dichiarazione di Chisinau — indica che il criterio è un altro." },
  { p: "Quale, è materia di interpretazione, e ne registriamo tre senza sceglierne una. La prima, sostenuta dai promotori, è deterrente: l'obiettivo non sarebbe processare molti casi, ma spezzare il contratto implicito con i trafficanti, perché se arrivare non garantisce restare la domanda cala. La seconda è elettorale: il centro esiste per essere annunciato, e il suo blocco giudiziario è persino funzionale, poiché sposta la responsabilità su magistrati e Bruxelles. La terza è simbolica, ed è la più difficile da confutare guardando i bilanci: ciò che conta non è dove la domanda viene esaminata, ma che chi la presenta non tocchi il territorio nazionale — la frontiera come soglia, non come procedura." },
  { p: "Qualunque sia la motivazione, il fatto uno di questo dossier ne smonta il presupposto comune. A Ceuta la prossimità fisica era totale: territorio spagnolo pieno, decine di migliaia di persone dentro i confini di una città europea. Eppure nessuno è entrato nello spazio Schengen, perché il filtro che ha funzionato non era geografico ma giuridico — una dichiarazione del 1991 e i controlli in uscita che ne discendono. L'esternalizzazione compra territorio quando ciò che serve è procedura. E nel comprarlo, avverte l'antropologo svedese Ruben Andersson (Oxford), consegna ai paesi terzi la leva: l'outsourcing «crea un incentivo per i paesi terzi a fomentare crisi — e offrirsi di risolverle». Rachid Niny dice la stessa cosa dall'altra sponda: la sicurezza delle frontiere di ciascun paese «non può essere delegata a una terza parte», e l'Europa deve smettere di considerare il Marocco «il gendarme delle proprie frontiere». Quando l'analista europeo e il direttore di giornale marocchino convergono sulla stessa diagnosi partendo da posizioni opposte, il dato merita attenzione." },
  { p: "Una precisazione doverosa, e per il metodo di questo dossier è la più importante del fatto nove. La domanda di frontiere esterne più rigide non appartiene a una sola famiglia politica, e trattarla come tale sarebbe esattamente il tipo di scorciatoia che qui contestiamo. La lettera dei 22 è co-promossa dalla socialdemocratica Mette Frederiksen, che si è spinta oltre la firma: in una dichiarazione all'AFP ha detto che è ovvio che l'UE debba valutare tutte le opzioni, «anche una sospensione della cooperazione Schengen», perché «un'immigrazione incontrollata rappresenta una minaccia per l'Europa e per la Danimarca». La lettera stessa, del resto, non è un testo tiepido: riconosce che la sentenza della Corte Suprema spagnola «è stata utilizzata per scatenare questo attacco e abusare del nostro sistema di migrazione e asilo», parla di minacce ibride, e chiede di affrontare «tutte le politiche che possono fungere da fattori di attrazione, come la regolarizzazione di un numero molto elevato di migranti irregolari» — cioè attacca esplicitamente la sanatoria spagnola. Spagna e Francia non l'hanno firmata." },
  { p: "La posizione danese, però, non è un adattamento tattico dell'ultima settimana: risale al 2015 e poggia su un argomento esplicito, cioè che il modello nordico — welfare universale, salari alti per contrattazione collettiva, pressione fiscale elevata accettata perché tutti contribuiscono — regga solo su obblighi reciproci stretti, e che l'immigrazione a bassa qualificazione ne eroda base fiscale e consenso. È una tesi discutibile nel merito, e discussa: le zone classificate per origine dei residenti, il cosiddetto «pacchetto gioielli», i centri di rimpatrio hanno raccolto censure da ONG e organismi europei. Ma è una tesi, argomentata da dieci anni, non un'affermazione fattuale. E il suo esito elettorale è verificabile: in Danimarca l'estrema destra si è dissolta, il Partito del Popolo Danese è passato dal 21% del 2015 al 2,6% del 2019, mentre in Svezia, che ha tenuto la linea opposta, i Democratici Svedesi sono diventati determinanti." },
  { p: "Qui sta la distinzione su cui questo dossier insiste dall'inizio. Sostenere che le frontiere esterne vadano irrigidite, o perfino che Schengen vada sospeso, è una posizione politica — dura, contestabile, sostenuta da governi di destra e di sinistra — e si valuta nel merito. Dire che a Ceuta fosse in corso un'invasione dell'Europa, o che quei migranti potessero riversarsi a Milano o Helsinki, è un'affermazione fattuale: e agli atti della Commissione europea è falsa. Nessuno dei firmatari, va detto, ha usato la parola «invasione» nei documenti ufficiali — quella è arrivata dagli agitatori arrivati a Ceuta, dal vicepresidente americano e dalla comunicazione politica interna. Il fact-checking ha giurisdizione solo sul secondo tipo di enunciato. Sul primo, il lettore deciderà da sé, che è esattamente come dovrebbe funzionare." },
  { h: "Fatto dieci: la rivendicazione — e la seconda finestra" },
  { p: "L'ultimo tassello è arrivato quando questo dossier era già alla terza riscrittura, e dà un oggetto visibile alla formula con cui l'esperta di migrazioni Gemma Pinyol-Jiménez aveva chiuso il fatto sette: non una crisi migratoria, un episodio geopolitico." },
  { p: "Il 12 agosto, a crisi ancora calda, il ministro della Giustizia marocchino Abdellatif Ouahbi ha ribadito pubblicamente che il Marocco continua a rivendicare Ceuta e Melilla — «continuiamo a rivendicare la nostra terra, questo richiede pazienza e vogliamo risolvere il problema attraverso il dialogo» — negando al contempo che Rabat abbia bisogno di ricorrere all'immigrazione per difendere i propri interessi. La replica spagnola è arrivata dalla ministra della Difesa Robles: territori «spagnolissimi», non si toccano. La rivendicazione non è nuova — resta parte della posizione ufficiale e dell'immaginario nazionalista marocchino, e nel 2022 Rabat arrivò a sostenere in una comunicazione ONU che Marocco e Spagna non avessero frontiera terrestre comune, descrivendo Melilla come territorio occupato — ma il tempismo della sua riemersione, a dodici giorni dall'assalto, è un dato che un audit registra. Come registra la strategia economica pluriennale che la accompagna: tra il 2018 e il 2019 Rabat ha chiuso la dogana commerciale di Melilla e messo fine al contrabbando da Ceuta, ed entro la fine del 2026 sarà inaugurato il porto Nador West Med, vicino a Melilla — un'asfissia commerciale delle enclavi condotta con strumenti perfettamente leciti. Nello stesso arco di giorni, il Consiglio nazionale marocchino per i diritti umani ha presentato un rapporto che accusa le forze spagnole di aver maltrattato parte dei migranti «soprattutto in luoghi fuori dalla portata delle telecamere» — lo stesso organismo che nel 2022, dopo i 23 morti dell'assalto alla recinzione di Melilla, attribuì la responsabilità alle autorità spagnole." },
  { p: "C'è poi un filone che dà un ancoraggio documentale alla seconda categoria della tassonomia di Tocci, quella che al fatto sette avevamo lasciato come valutazione d'analista. Think tank statunitensi e politici repubblicani hanno rilanciato le rivendicazioni marocchine su Ceuta e Melilla descrivendo le due enclavi come il punto più vulnerabile della Spagna, sullo sfondo dello scontro tra Madrid, Washington e Tel Aviv; il 13 luglio Stati Uniti e Marocco hanno firmato un memorandum per una struttura militare congiunta in terra marocchina, e analisi di quell'area sostengono che Israele dovrebbe usare la propria influenza a Washington per sostenere diplomaticamente Rabat. Precisione d'obbligo: advocacy pubblica non è orchestrazione, e nessun documento collega questi ambienti alla mobilitazione di luglio. Ma ciò che il 5 agosto era una lettura d'analista ha ora almeno un'espressione scritta, firmata e datata — e il fact-checking la archivia come tale." },
  { p: "Infine, la seconda finestra. L'allerta per una nuova migrazione di massa nella notte tra il 14 e il 15 agosto si è alzata, e questa volta l'obiettivo, stando al tam tam social, potrebbe essere Melilla — non più solo Ceuta. Il Marocco ha rafforzato frontiere, porti e stazioni, monitorando i messaggi che invitano a raduni al confine di Melilla, e la Spagna ha schierato a Ceuta due fregate della Marina accanto alla barriera galleggiante, con rinforzi di Guardia Civil, Polizia nazionale, medici legali e magistrati. Le chat monitorate dalla stampa mostrano la dinamica in tempo reale: la data del 15, bruciata dalla pubblicità, si sposta; circolano messaggi che indirizzano su Melilla in giorni diversi e mettono in guardia da Ceuta. È esattamente il meccanismo che la ricerca di Cherti descrive al fatto sette — mobilitazione tra pari, date che scivolano, nessun regista necessario — e insieme la conferma che la finestra resta aperta comunque vada il Ferragosto. Due dettagli chiudono il quadro: il ministro dell'Interno spagnolo Grande-Marlaska ha dichiarato che «non c'è posto in Spagna, né a Ceuta, né a Melilla» per chi entra irregolarmente; la Danimarca si dice «pronta a chiudere le frontiere» in caso di nuova ondata; la Germania conferma che le espulsioni verso l'Italia sulla base di Dublino «si faranno come previsto» — mentre si tratta per un centro rimpatri in Uganda (il fatto nove, puntuale come un orologio). E il Marocco che il 30 luglio lasciò passare — le sue guardie smisero di pattugliare, documentò The Economist — oggi presidia: la variabile che decide se il 15 agosto succede qualcosa non è a Madrid né a Roma. È a Rabat, dov'è sempre stata." },
  { h: "Il metodo, ancora" },
  { p: "Dieci fatti, tre paesi, un solo criterio: i documenti prima delle dichiarazioni — e la disponibilità a correggere il proprio stesso dossier quando arriva un'evidenza migliore, come abbiamo fatto sul fatto sette. Le imprese brasiliane hanno votato con i piedi contro il Custo Brasil attraversando la Ponte da Amizade; i marocchini hanno votato con i piedi contro il loro miracolo a due velocità; i discendenti italiani hanno votato con i piedi verso una patria che ha smesso di rispondere; e persino i provocatori di Ceuta, alla fine, hanno votato con i piedi — gli unici ad aver attraversato più frontiere dei migranti per raccontare una crisi che i migranti stessi non riconoscevano." },
  { p: "In ogni caso, il potere ha risposto ai piedi con la retorica invece che con le riforme." },
  { p: "I fatti e le cifre sono tratti da fonti pubbliche: il Codice delle frontiere Schengen e l'Atto di adesione della Spagna (1991); dichiarazioni della Commissione europea (luglio–agosto 2026); CGUE, cause riunite C-368/20 e C-369/20 (2022); HCP e OCSE sul mercato del lavoro marocchino; Fondazione ISMU, Rapporto sulle migrazioni 2026; Ministero del Lavoro, «La comunità marocchina in Italia — Rapporto annuale 2025»; ISTAT, rapporto sulle migrazioni 2025; atti e cronache sull'inchiesta dell'Audiencia Nacional e sulle manifestazioni di Ceuta (agosto 2026); intervista a Nathalie Tocci, Sky TG24 «Timeline», 5 agosto 2026; ricerca e analisi di Myriam Cherti, Bloomberg, 6 agosto 2026; dichiarazione del ministero dell'Interno marocchino via MAP, ripresa da Bloomberg, 3 agosto 2026; stampa italiana e spagnola sui controlli reciproci Schengen e sulla cerimonia di Marcinelle (Il Post, Sky TG24, Il Foglio, ANSA, 7-8 agosto 2026); The Economist, «Rushing the gates» (31 luglio 2026) e «The wrong lessons» (5 agosto 2026); dichiarazioni del ministro dell'Interno spagnolo Grande-Marlaska e cronache sulla videoconferenza dei ministri UE del 4 agosto (Sky TG24); dichiarazioni di Matteo Salvini e delle opposizioni italiane, e nota del ministero dell'Interno spagnolo sulla contromisura dell'8 agosto (LaPresse, Adnkronos, Europa Today, 7-8 agosto 2026); intervista a Rachid Niny da Ras Kebdana, reportage di Monica Perosino da Ceuta e articolo sugli 862 minori (La Stampa, agosto 2026); Rachid Niny, «Diario de un ilegal» (ed. spagnola 2002); Tribunal Supremo, Sala de lo Contencioso-Administrativo, Sezione Quinta, sentenza dell'8 luglio 2026 (comunicato CGPJ e ricostruzioni di El Independiente, Europa Press ed elderecho.com); testo della lettera dei 22 leader europei (governo.it, 1 agosto 2026); dichiarazione di Mette Frederiksen all'AFP (31 luglio 2026); dichiarazioni di Abdellatif Ouahbi e replica di Margarita Robles (Libero, Leggo, Euronews, 12-13 agosto 2026); rapporto preliminare del CNDH marocchino (8 agosto 2026, via Euronews); Alexandre Aublanc, Internazionale (4 agosto 2026); Il Fatto Quotidiano sul rilancio delle rivendicazioni da ambienti neocon USA (1 agosto 2026); ANSA, Euronews, Sky TG24 e Il Giornale sull'allerta Melilla e sul dispositivo del 14-15 agosto (7-13 agosto 2026); audizione del ministro Piantedosi al Comitato Schengen e dichiarazioni di Grande-Marlaska da Ceuta (ANSA, AGI, Open, Avvenire, Today, Il Foglio, 13 agosto 2026)." },
  { p: "Business Matching Global — analisi di mercato e coordinamento commerciale sul corridoio Europa–Brasile. Senza dati sei solo un'altra persona con un'opinione. Noi preferiamo essere un'altra persona con i dati." },
];

export default function CeutaIT() {
  const { lang } = useT();
  const article = getArticleBySlug("ceuta_it");
  const desc =
    "Cosa dice davvero la crisi di Ceuta: lo status speciale fuori Schengen, i dati Frontex, il Marocco a due velocità e i flussi che verificano ciò che i comunicati negano.";
  useCanonical("/ceuta", {
    title: `${TITLE} — Business Matching Global`,
    description: desc,
    type: "article",
  });


  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <div className="flex items-center justify-between gap-4 mb-8">
          <Link
            to="/analysis"
            className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            Torna alle analisi
          </Link>
          <LangSwitcher to="/ceuta" />
        </div>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">{TITLE}</h1>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
          <ShareBlock title={TITLE} />
        </article>
        <AnalysisFooter />
      </div>
    </main>
  );
}
