import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";
import { AnalysisComments } from "@/components/AnalysisComments";
import { AnalysisFooter } from "@/components/AnalysisFooter";

type BodyBlock = { h: string } | { p: string };

const content: Record<"it" | "en" | "pt", { back: string; body: BodyBlock[] }> = {
  it: {
    back: "Torna alle analisi",
    body: [
      { p: "Da ieri, 22 luglio, importare merci brasiliane negli Stati Uniti costa il 25% in più. Il dazio, fondato su un'indagine ai sensi della Sezione 301 durata un anno intero, colpisce oltre 11 miliardi di dollari di interscambio risparmiando circa 2.100 prodotti — tra cui carne bovina, caffè e succo d'arancia. Ogni guerra commerciale produce dazi. Questa ha prodotto qualcosa di mai visto: il primo dazio della storia imposto non contro un prodotto, ma contro un metodo. Il rapporto dell'USTR ne indica il bersaglio per nome. Si chiama Pix." },
      { h: "Il complimento più costoso mai pagato" },
      { p: "A leggere le conclusioni dell'indagine, l'elenco delle accuse è lungo — commercio digitale, accordi tariffari preferenziali, accesso al mercato dell'etanolo, proprietà intellettuale, applicazione delle norme anticorruzione, deforestazione illegale. Ma l'elemento che dà a questo dazio il suo carattere storico è la constatazione che le politiche pubbliche brasiliane favoriscono il Pix e pongono le società americane dei pagamenti elettronici in una posizione di \"svantaggio sleale\"." },
      { p: "Si consideri che cosa viene sanzionato. Il Pix non è un'azienda. Non ha azionisti, non ha una riga di ricavi, non emette fatture di esportazione. È un pezzo di infrastruttura finanziaria pubblica costruito dal Banco Central do Brasil in meno di due anni e acceso nel novembre 2020. Nel 2024 processava 64 miliardi di transazioni l'anno — più di Visa e Mastercard messe insieme nel Paese — e raggiungeva il 93% degli adulti brasiliani, con oltre 170 milioni di utenti registrati: più della popolazione economicamente attiva del Brasile. Ha portato dentro il sistema finanziario, gratuitamente, decine di milioni di cittadini che non avevano un conto." },
      { p: "Niente di tutto questo attraversa un confine. Nessun container lo trasporta, nessun doganiere può trattenerlo al porto. Eppure oggi regge un dazio del 25% su beni fisici che con i pagamenti non c'entrano nulla. Non potendo tassare il metodo, Washington ha tassato tutto ciò che gli sta intorno. Non esiste complimento più costoso." },
      { h: "Che cosa contesta davvero Washington" },
      { p: "Il percorso procedurale merita una pausa. L'USTR ha proposto il dazio il 1° giugno 2026, a indagine conclusa. Le audizioni pubbliche si sono tenute il 6 e 7 luglio; il governo Lula ha scelto di non mandare nessuno a parlare — presenti solo osservatori dell'ambasciata a Washington, una sedia vuota come dichiarazione di principio. La conferma è arrivata il 15 luglio; l'entrata in vigore, una settimana dopo." },
      { p: "Dopo l'annuncio, un alto funzionario dell'amministrazione americana ha tenuto a chiarire che Washington non vuole la fine del Pix, ne riconosce l'importanza per i brasiliani e chiede soltanto che le aziende americane possano competere ad armi pari. Ma si guardino le obiezioni specifiche, e uno schema emerge. L'USTR contesta il doppio ruolo del Banco Central come regolatore e insieme gestore dello schema. Contesta il mandato che rende il Pix gratuito per le persone fisiche. Contesta i tetti alle commissioni per gli esercenti e l'obbligo per le banche di dare al sistema evidenza visiva nelle proprie app." },
      { p: "Tolto il linguaggio giuridico, ogni obiezione punta alla stessa cosa: non la tecnologia, ma le decisioni di governance che hanno reso la tecnologia universale. La contestazione, in altre parole, riguarda il metodo in sé — una banca centrale disposta a fare da proprietaria dello schema, a imporre la partecipazione e a prezzare un binario di pagamento come infrastruttura pubblica anziché come casello. L'ironia si scrive da sola: mentre il dazio veniva messo a punto, i brasiliani movimentavano circa 8 miliardi di dollari al mese in stablecoin denominate in dollari — un canale al quale Washington non ha nulla da obiettare." },
      { h: "Il muro di Brasilia" },
      { p: "Se il dazio doveva dividere il Brasile, ha ottenuto l'opposto. La risposta del presidente Lula è arrivata con un post sui social: \"É público, é de graça e vai continuar assim\" — è pubblico, è gratuito e resterà così — sotto il titolo che la sovranità non si negozia. Ancora più eloquente la reazione dall'altra parte dell'emiciclo. Flávio Bolsonaro, tutto fuorché un alleato del governo, si è rifiutato di mettere il Pix sul tavolo, proponendo semmai un compromesso: l'impegno del Brasile a non collegare mai il Pix a un'infrastruttura internazionale di pagamenti rivale di quella americana." },
      { p: "Quella concessione proposta è la frase più rivelatrice dell'intera vicenda. Ammette che il sistema domestico è intoccabile — e identifica la vera posta in gioco: l'interoperabilità. Non se i brasiliani si paghino tra loro con un codice fiscale e un QR code, ma se il metodo si colleghi verso l'esterno, ai sistemi degli altri Paesi, formando corridoi che aggirano i binari americani." },
      { p: "La risposta formale dell'Itamaraty, depositata il 1° luglio, ha aggiunto l'argomento cui Washington fatica di più a rispondere: gli Stati Uniti hanno un surplus commerciale con il Brasile. Un procedimento ex Sezione 301, concepito per rimediare a pratiche che gravano sul commercio americano, viene usato contro un Paese che dall'America compra più di quanto le venda. Perfino Paul Krugman, che non è un difensore d'ufficio di Brasilia, ha liquidato la cornice della \"pratica sleale\" con una domanda che resta sospesa: da quando è sleale che un Paese offra ai propri cittadini un modo migliore di pagare — o che un'azienda perda quote di mercato a vantaggio di un concorrente con un prodotto migliore e più economico?" },
      { h: "Il calcolo della non-ritorsione" },
      { p: "La postura ufficiale di Brasilia è una de-escalation deliberata. Il vicepresidente Alckmin, dopo aver incontrato i settori colpiti — macchinari (3,3 miliardi di dollari esposti), legno (colpito l'81% dell'export verso gli USA), gomma, alimentare, tessile — ha escluso esplicitamente la ritorsione: l'idea non è la reciprocità, ha detto; gli strumenti esistono e potranno essere usati al momento opportuno, nella forma adeguata. La Lei de Reciprocidade resta nel cassetto, la via dell'OMC in riserva. Gli stessi settori hanno chiesto più credito dentro il programma Brasil Soberano, barriere contro la deviazione delle importazioni cinesi e la prosecuzione della diplomazia — non contro-dazi." },
      { p: "Dietro la moderazione c'è un'aritmetica: la quota americana sull'export brasiliano è scesa al 9,4% nel 2026, dal picco recente del 13,7%. Dolorosa, non esistenziale. E il calendario consiglia pazienza per un'altra ragione: questo venerdì, 24 luglio, Washington decide su un possibile secondo dazio — del 12,5%, ai sensi della Sezione 122, fondato su accuse di lavoro forzato — destinato a sostituire i sovrapprezzi del 10% in scadenza a fine mese. Quel caso porta con sé un paradosso, di cui abbiamo già scritto: le prove poggiano sulla lista suja brasiliana, il registro pubblico dei datori di lavoro sorpresi a impiegare manodopera in condizioni analoghe alla schiavitù. Uno strumento di trasparenza che la maggior parte dei Paesi non possiede, trasformato in arma contro l'unico Paese abbastanza onesto da pubblicarlo." },
      { h: "Il mondo che Washington sta leggendo correttamente" },
      { p: "Liquidare il dazio come semplice protezionismo a favore di Visa e Mastercard significa non vedere ciò che il Tesoro americano vede davvero. Il segretario Scott Bessent ha descritto la nuova postura come la diplomazia economica del XXI secolo, nella quale l'accesso al dollaro e all'infrastruttura finanziaria americana non è più incondizionato. Da quel punto di osservazione, la mappa globale dei pagamenti è davvero allarmante: la Russia, tagliata fuori dai binari occidentali, gira ormai su un proprio sistema di messaggistica (SFPS) e una propria rete di carte (Mir). Il CIPS cinese, rivale transfrontaliero di Swift, ha registrato a marzo una media giornaliera record di 920 miliardi di yuan — circa 130 miliardi di dollari, il 20% in più di un anno prima — con un primato in un solo giorno di 1.200 miliardi di yuan ad aprile. L'UPI indiano opera in nove Paesi, e l'NPCI lo promuove all'estero con il vocabolario della sovranità: aiutare i Paesi a onorare i propri impegni interni e a condurre la propria agenda nazionale." },
      { p: "Ognuno di questi è un metodo che si propaga. Il dazio sul Pix si capisce meglio come un tentativo di alzare il prezzo d'ingresso a quella propagazione — un segnale rivolto meno a Brasilia che a ogni capitale che stia studiando il manuale brasiliano." },
      { h: "L'Europa possiede già l'hardware" },
      { p: "La lettura standard del capitolo europeo di questa storia è che l'Europa stia aspettando — aspettando l'euro digitale prima di poter rispondere alla domanda che Aurore Lalucq ha posto al Parlamento europeo: che cosa succede se degli Stati Uniti ostili tagliano l'accesso all'infrastruttura dei pagamenti? \"Non potrete dire di non essere stati avvertiti\", ha detto ai colleghi, esortando l'Europa a costruire le proprie alternative — un appello ripreso dai vertici delle banche britanniche, che discutono di un rivale domestico ai circuiti delle carte, e dalla stessa Christine Lagarde." },
      { p: "Quella lettura è sbagliata, e conta che lo sia. All'Europa non manca il binario. I bonifici istantanei SEPA raggiungono 41 Paesi; per effetto del Regolamento sui pagamenti istantanei, da gennaio 2025 non possono costare più di un bonifico ordinario, e da ottobre 2025 ogni banca dell'area euro deve verificare gratuitamente il nome del beneficiario rispetto all'IBAN prima che il denaro parta. Veloce, economico, verificato: la tubatura che il Brasile ha costruito nel 2020, l'Europa l'ha in gran parte costruita anche lei." },
      { p: "Ciò che all'Europa manca è tutto quello che il Pix ha stratificato sopra la tubatura — ed è qui che il confronto diventa una diagnosi. Primo, l'anagrafica: il Pix ha sostituito il numero di conto con un alias — un codice fiscale, un numero di telefono, un'email — risolto attraverso un unico registro nazionale gestito dalla banca centrale. La risposta europea all'alias esiste, ma in frammenti: Wero, il portafoglio costruito dalle banche francesi, tedesche e del Benelux dell'European Payments Initiative (che ha assorbito l'olandese iDeal), usa il numero di telefono; così Bizum in Spagna, MB Way in Portogallo, Blik in Polonia, Swish in Svezia. Cinque anagrafiche, cinque marchi, e un'interoperabilità transfrontaliera ancora in cantiere. Secondo, il mandato: il Banco Central do Brasil ha obbligato ogni istituto ad aderire a un unico schema, gratuito per le persone fisiche, dal primo giorno. Nessuna autorità europea ha imposto un unico schema alle proprie banche; il regolamento impone il binario, non la rete che ci corre sopra. Terzo, la cassa: il Pix ha spiazzato le carte nel punto vendita con un QR code. SEPA Instant, con tutta la sua velocità, resta in larga parte uno strumento da persona a persona; alla cassa europea, il duopolio americano continua a riscuotere il pedaggio." },
      { p: "Gli incumbent se ne sono accorti. Il presidente di Mastercard per l'Europa si è messo a sostenere che una rete di pagamenti europea esiste già — ed è Mastercard —, corroborando la tesi con 500 milioni di euro investiti in infrastruttura europea, un centro tecnologico in Polonia previsto per il 2027 e tre data center in Francia da 250 milioni di euro, oltre a una partnership per i pagamenti in tempo reale con la cinese UnionPay. Visa e Mastercard, con margini operativi sopra il 50%, indicano ormai il trattamento \"preferenziale\" riservato ai sistemi di pagamento domestici come rischio d'impresa nelle proprie relazioni annuali. Quando un duopolio comincia a scrivere il tuo metodo nelle proprie informative sui rischi, il metodo sta funzionando." },
      { h: "L'Italia, intanto, ha condotto in sordina l'esperimento di controllo" },
      { p: "Satispay è la cosa più vicina a un Pix costruito da privati che esista in Europa: un alias al posto dell'IBAN, trasferimenti gratuiti da persona a persona, una rete proprietaria deliberatamente instradata fuori dai circuiti delle carte. Per un decennio, con circa mezzo miliardo di euro di capitale di rischio, ha comprato un utente alla volta ciò che il Banco Central do Brasil ha ottenuto per decreto. Il tabellone racconta la storia: 6,5 milioni di utenti e 450.000 esercenti — circa un decimo degli adulti italiani, contro il 93% dei brasiliani del Pix — ricavi di rete per 46 milioni di euro nel 2024 a fronte di una perdita netta di 47 milioni, con lungo il percorso un richiamo d'informativa dei revisori sulla continuità aziendale. E quando l'azienda ha finalmente dato un prezzo alla propria rete, nell'aprile 2025, introducendo una commissione dell'1% per gli esercenti, alcuni se ne sono semplicemente andati: parte della proposta di valore, si è scoperto, era il sussidio stesso." },
      { p: "Questo luglio l'esperimento è arrivato alla sua destinazione logica. Satispay ha lanciato le carte di debito — su circuito Mastercard. Non potendo comprare l'universalità e non potendo decretarla, lo sfidante anti-carte sta ora prendendo in affitto l'accettazione proprio dal duopolio che si era proposto di aggirare, monetizzando con piani in abbonamento sul modello Revolut mentre il circuito proprietario serve la nicchia domestica. Il suo fondatore parla, senza ironia, di diventare un giorno una banca proprietaria di un circuito di pagamento. Il teorema non poteva essere dimostrato più pulitamente: senza un proprietario dello schema dotato del potere di mandato, l'universalità non è in vendita — solo in affitto, e i locatori sono due." },
      { h: "Il che porta alla conclusione scomoda" },
      { p: "Nessuno dei tre strati mancanti richiede l'euro digitale, promesso per il 2029. Un'anagrafica è governance. Un mandato è regolamentazione. L'accettazione degli esercenti è disegno dello schema. Al Brasile non è servita una valuta digitale di banca centrale per costruire il Pix — è servita una banca centrale disposta a fare da proprietaria dello schema, e il decennio di Satispay dimostra che nessuna quantità di capitale privato può sostituirla. Ciò che separa il panorama europeo dei pagamenti dalla sovranità non è un ritardo tecnologico di tre anni, ma un atto di volontà istituzionale." },
      { h: "Il prezzo della sovranità, detto con onestà" },
      { p: "La frammentazione non è gratuita, e le ragioni della cautela meritano un ascolto leale. Un rapporto sponsorizzato da Swift stima che, se gli andamenti attuali proseguono, la frammentazione finanziaria potrebbe togliere il 2,6% al PIL globale entro il 2030. Il Financial Stability Board avverte che la proliferazione dei sistemi nazionali impedirà probabilmente al G20 di centrare gli obiettivi su rimesse più economiche e veloci fissati nel 2020. E come osserva Josh Lipsky dell'Atlantic Council, un mondo di sistemi regionali incompatibili è un mondo con più frodi e un'elusione delle sanzioni più facile. I Paesi potrebbero scoprire — così concludeva l'analisi originale dell'Economist — che il prezzo della sovranità nei pagamenti è più alto di quanto immaginano; e lo stesso potrebbe valere per gli Stati Uniti." },
      { p: "Ma si noti che cosa implica quell'avvertimento per questo dazio. Se il pericolo è la frammentazione, la politica americana razionale sarebbe tenere i sistemi di pagamento del mondo interoperabili con il proprio. Un dazio punitivo sul metodo di pagamento pubblico di maggior successo mai realizzato fa l'opposto: certifica che il metodo minaccia gli incumbent, alza il valore percepito dell'indipendenza e consegna a ogni ministero delle finanze un argomento da 25% per costruirsi i propri binari. Il dazio non rallenta la frammentazione che teme. La pubblicizza." },
      { h: "Il metodo è già sul tavolo" },
      { p: "Tolto il vocabolario da guerra commerciale, resta una transazione strana. Gli Stati Uniti hanno attaccato un cartellino da 25% a un metodo — e così facendo lo hanno pubblicizzato presso ogni giurisdizione che osserva. La risposta del Brasile al dazio verrà negoziata tra Brasilia e Washington. La risposta dell'Europa, se ne vorrà una, non richiede alcun negoziato: i binari sono posati, i bonifici sono istantanei e gratuiti, le verifiche del beneficiario sono operative. Ogni componente del metodo che Washington ha appena dichiarato una minaccia è già lì, non assemblato, dentro il sistema europeo dei pagamenti. Assemblarlo non è un progetto tecnologico con una data di consegna. È una decisione." },
      { p: "È questo che rende il dazio storico al di là del suo 25%. I dazi sui prodotti si assorbono, si aggirano, si aspettano. Un dazio su un metodo fa qualcosa che nessun dazio aveva mai fatto: certifica che il metodo funziona, lo nomina pubblicamente e sfida tutti gli altri ad adottarlo. Il Brasile ha costruito il Pix in meno di due anni con una banca centrale disposta a fare da proprietaria dello schema. La domanda che il dazio lascia sul tavolo non è se il metodo possa attraversare l'Atlantico — è quale sponda dell'Atlantico deciderà di volerlo per prima." },
      { p: "In BMG leggiamo la politica commerciale per ciò che rivela, più che per ciò che dichiara. Questa rivela più di molte altre: l'export brasiliano più pesantemente sanzionato del 2026 non è una materia prima, e non si può trattenere in dogana. Che aspetto ha la mappa del Brasile della vostra organizzazione, quando la cosa più preziosa che attraversa il confine è un metodo?" },
      { h: "Fonti" },
      { p: "rapporto USTR Sezione 301 e avvisi del Federal Register; Banco Central do Brasil; The Economist (via O Estado de S. Paulo); Folha de S.Paulo; O Tempo; Poder360; nota dell'Itamaraty del 1° luglio 2026; comunicazioni societarie Satispay e bilancio 2024 come riportati da Milano Finanza e Sky TG24." },
    ],
  },
  en: {
    back: "Back to analysis",
    body: [
      { p: "Since yesterday, July 22, importing Brazilian goods into the United States costs 25% more. The tariff, built on a Section 301 investigation that took a full year, hits over US$11 billion in trade while sparing roughly 2,100 products — beef, coffee, orange juice among them. Every trade war produces tariffs. This one produced something without precedent: the first tariff in history levied not against a product, but against a method. The USTR's report names its target explicitly. It is called Pix." },
      { h: "The most expensive compliment ever paid" },
      { p: "Read the investigation's conclusions and the charge sheet is long — digital trade, preferential tariff agreements, ethanol market access, intellectual property, anti-corruption enforcement, illegal deforestation. But the item that gives this tariff its historic character is the finding that Brazil's public policies favor Pix and place American electronic-payment companies at an \"unfair disadvantage.\"" },
      { p: "Consider what is being sanctioned. Pix is not a company. It has no shareholders, no revenue line, no export invoice. It is a piece of public financial plumbing built by the Banco Central do Brasil in under two years and switched on in November 2020. By 2024 it was processing 64 billion transactions annually — more than Visa and Mastercard combined in the country — and reaching 93% of Brazilian adults, with over 170 million registered users, more than Brazil's economically active population. It brought tens of millions of unbanked citizens into the financial system, free of charge." },
      { p: "None of that crosses a border. No container carries it, no customs officer can hold it at the port. And yet it now anchors a 25% duty on physical goods that have nothing to do with payments. Washington could not tariff the method, so it tariffed everything around it. There is no more expensive compliment." },
      { h: "What Washington actually objects to" },
      { p: "The procedural record is worth pausing on. The USTR proposed the tariff on June 1, 2026, after concluding its investigation. Public hearings were held on July 6 and 7; the Lula government chose not to send anyone to speak — only observers from the embassy in Washington attended, an empty chair as a statement of principle. Confirmation came on July 15; entry into force, one week later." },
      { p: "After the announcement, a senior US administration official was at pains to clarify that Washington does not want to end Pix, recognizes its importance to Brazilians, and merely wants American companies to compete on equal terms. Look at the specific objections, though, and a pattern emerges. The USTR faults the Banco Central's dual role as regulator and operator of the scheme. It faults the mandate that makes Pix free for individuals. It faults the caps on merchant fees and the requirement that banks give the system visual prominence in their apps." },
      { p: "Strip the legal language and each objection targets the same thing: not the technology, but the governance decisions that made the technology universal. The complaint, in other words, is with the method itself — a central bank willing to act as scheme owner, to mandate participation, and to price a payment rail as public infrastructure rather than as a toll booth. The irony writes itself: while the tariff was being finalized, Brazilians were moving an estimated US$8 billion a month through dollar-denominated stablecoins, a channel Washington has no objection to at all." },
      { h: "The wall in Brasília" },
      { p: "If the tariff was meant to divide Brazil, it achieved the opposite. President Lula's response came as a social-media card: \"É público, é de graça e vai continuar assim\" — public, free, and staying that way — under the caption that sovereignty is not for negotiation. More telling was the reaction across the aisle. Flávio Bolsonaro, no ally of the government, declined to put Pix on the table, floating instead a compromise in which Brazil would commit never to link Pix to an international payments infrastructure rivaling America's." },
      { p: "That proposed concession is the most revealing sentence in the entire dispute. It concedes that the domestic system is untouchable — and identifies what the fight is actually about: interoperability. Not whether Brazilians pay each other with a tax ID and a QR code, but whether the method connects outward, to other countries' systems, forming corridors that route around the American rails." },
      { p: "The Itamaraty's formal response, filed on July 1, added the argument Washington finds hardest to answer: the United States runs a goods surplus with Brazil. A Section 301 case, designed to remedy practices that burden American commerce, is being deployed against a country that buys more from America than it sells. Even Paul Krugman, no reflexive defender of Brasília, dismissed the \"unfair practice\" framing with a question that lingers: since when is it unfair for a country to offer its own citizens a better way to pay — or for a company to lose market share to a competitor with a better, cheaper product?" },
      { h: "The calculus of not retaliating" },
      { p: "Brasília's official posture is deliberate de-escalation. Vice-President Alckmin, after meeting the affected sectors — machinery (US$3.3 billion exposed), wood (81% of its US exports hit), rubber, food, textiles — ruled out retaliation explicitly: reciprocity is not the idea, he said; the instruments exist and can be used at the opportune moment, in the adequate form. The Lei de Reciprocidade stays in the drawer, the WTO route in reserve. The sectors themselves asked for more credit under the Brasil Soberano program, barriers against Chinese import diversion, and continued diplomacy — not counter-tariffs." },
      { p: "Behind the restraint sits arithmetic: the American share of Brazilian exports has fallen to 9.4% in 2026, from 13.7% at its recent peak. Painful, not existential. And the calendar counsels patience for another reason: this Friday, July 24, Washington decides on a possible second tariff — 12.5%, under Section 122, grounded in forced-labor allegations, replacing the 10% surcharges that expire at month's end. That case carries its own paradox, one we have written about before: the evidence base leans on Brazil's lista suja, the public registry of employers caught using slave-like labor. An instrument of transparency that most countries lack, turned into ammunition against the one country honest enough to publish it." },
      { h: "The world Washington is reading correctly" },
      { p: "To dismiss the tariff as mere protectionism for Visa and Mastercard is to miss what the US Treasury actually sees. Secretary Scott Bessent has described the new posture as the economic diplomacy of the 21st century, in which access to the dollar and to American financial infrastructure is no longer unconditional. From that vantage point, the global payments map is genuinely alarming: Russia, cut off from Western rails, now runs on its own messaging system (SFPS) and card network (Mir). China's CIPS, the cross-border rival to Swift, posted a record daily average of 920 billion yuan in March — roughly US$130 billion, 20% above a year earlier — with a single-day record of 1.2 trillion yuan in April. India's UPI operates in nine countries, and the NPCI markets it abroad in the language of sovereignty: helping countries meet their own domestic commitments and conduct their own national agenda." },
      { p: "Every one of these is a method propagating. The tariff on Pix is best understood as an attempt to raise the price of joining that propagation — a signal aimed less at Brasília than at every capital studying the Brazilian playbook." },
      { h: "Europe already owns the hardware" },
      { p: "The standard reading of the European chapter of this story is that Europe is waiting — waiting for the digital euro before it can answer the question Aurore Lalucq put to the European Parliament: what happens if a hostile United States cuts access to payment infrastructure? \"You will not be able to say you were not warned,\" she told colleagues, urging Europe to build its own alternatives, a call echoed by British bank executives discussing a homegrown rival to the card networks and by Christine Lagarde herself." },
      { p: "That reading is wrong, and it matters that it is wrong. Europe does not lack the rail. SEPA Instant credit transfers reach 41 countries; under the Instant Payments Regulation they must cost no more than an ordinary transfer since January 2025, and since October 2025 every euro-area bank must verify the beneficiary's name against the IBAN, free of charge, before the money moves. Fast, cheap, verified: the plumbing Brazil built in 2020, Europe has largely built too." },
      { p: "What Europe lacks is everything Pix layered on top of the plumbing — and this is where the comparison becomes a diagnosis. First, the directory: Pix replaced the account number with an alias — a tax ID, a phone number, an email — resolved through a single national registry operated by the central bank. Europe's answer to the alias exists, but in fragments: Wero, the wallet built by the European Payments Initiative's French, German and Benelux banks (which absorbed the Netherlands' iDeal), uses a phone number; so do Bizum in Spain, MB Way in Portugal, Blik in Poland, Swish in Sweden. Five directories, five brands, and cross-border interoperability still a construction site. Second, the mandate: the Banco Central do Brasil obliged every institution to join one scheme, free for individuals, on day one. No European authority has imposed a single scheme on its banks; the regulation mandates the rail, not the network on top of it. Third, the till: Pix displaced cards at the point of sale through a QR code. SEPA Instant, for all its speed, remains largely a person-to-person tool; at the European checkout, the American duopoly still collects the toll." },
      { p: "The incumbents have noticed. Mastercard's president for Europe has taken to arguing that a European payments network already exists — and that it is Mastercard — backing the claim with €500 million in European infrastructure, a technology center in Poland due in 2027, and three data centers in France costing €250 million, alongside a real-time payments partnership with China's UnionPay. Visa and Mastercard, with operating margins above 50%, now list the \"preferential\" treatment of domestic payment systems as a business risk in their annual reports. When a duopoly starts writing your method into its risk disclosures, the method is working." },
      { h: "Italy, meanwhile, has quietly run the control experiment" },
      { p: "Satispay is the closest thing Europe has to a privately built Pix: an alias instead of an IBAN, free person-to-person transfers, a proprietary network deliberately routed around the card circuits. For a decade, and with roughly half a billion euros of venture capital, it has been buying one user at a time what the Banco Central do Brasil obtained by decree. The scoreboard tells the story: 6.5 million users and 450,000 merchants — about a tenth of Italian adults, against Pix's 93% of Brazilians — network revenues of €46 million in 2024 against a net loss of €47 million, with an auditors' going-concern emphasis note along the way. And when the company finally priced its network in April 2025, introducing a 1% merchant fee, some merchants simply walked: part of the value proposition, it turned out, was the subsidy itself." },
      { p: "This July the experiment reached its logical destination. Satispay launched debit cards — on the Mastercard network. Unable to buy universality and unable to decree it, the anti-card challenger is now renting acceptance from the very duopoly it set out to bypass, monetizing through subscription tiers in the Revolut mold while its proprietary circuit serves the domestic niche. Its founder speaks, without irony, of one day becoming a bank that owns a payment circuit. The theorem could not be demonstrated more cleanly: without a scheme owner holding mandate power, universality is not for sale — only for rent, and there are only two landlords." },
      { h: "Which leads to the uncomfortable conclusion" },
      { p: "None of the three missing layers requires the digital euro, promised for 2029. A directory is governance. A mandate is regulation. Merchant acceptance is scheme design. Brazil needed no central bank digital currency to build Pix — it needed a central bank willing to act as scheme owner, and Satispay's decade proves that no amount of private capital substitutes for one. What separates the European payments landscape from sovereignty is not a technology gap of three years but an act of institutional will." },
      { h: "The price of sovereignty, honestly stated" },
      { p: "Fragmentation is not free, and the case for caution deserves a fair hearing. A report sponsored by Swift estimates that if current patterns hold, financial fragmentation could shave 2.6% off global GDP by 2030. The Financial Stability Board warns that the proliferation of national systems will likely prevent the G20 from meeting the cheaper-faster remittance targets it set in 2020. And as the Atlantic Council's Josh Lipsky observes, a world of incompatible regional systems is a world with more fraud and easier sanctions evasion. Countries may discover, as the original Economist analysis concluded, that the price of payment sovereignty is higher than they imagine — and the same may prove true for the United States." },
      { p: "But note what that warning implies for this tariff. If fragmentation is the danger, the rational American policy would be to keep the world's payment systems interoperable with its own. A punitive tariff on the most successful public payment method ever deployed does the opposite: it certifies that the method threatens the incumbents, raises the perceived value of independence, and hands every finance ministry a 25% argument for building its own rails. The tariff does not slow the fragmentation it fears. It advertises it." },
      { h: "The method is already on the table" },
      { p: "Strip away the trade-war vocabulary and what remains is a strange transaction. The United States has attached a 25% price tag to a method — and in doing so, has advertised it to every jurisdiction watching. Brazil's answer to the tariff will be negotiated in Brasília and Washington. Europe's answer, if it wants one, requires no negotiation at all: the rails are laid, the transfers are instant and free, the beneficiary checks are live. Every component of the method that Washington just declared a threat already sits, unassembled, inside the European payments system. Assembling it is not a technology project with a delivery date. It is a decision." },
      { p: "That is what makes this tariff historic beyond its 25%. Tariffs on products can be absorbed, rerouted, waited out. A tariff on a method does something no tariff has done before: it certifies that the method works, names it publicly, and dares everyone else to adopt it. Brazil built Pix in under two years with a central bank willing to act as scheme owner. The question the tariff leaves on the table is not whether the method can cross the Atlantic — it is which side of the Atlantic decides to want it first." },
      { p: "At BMG, we read trade policy for what it reveals rather than what it declares. This one reveals more than most: the most heavily sanctioned Brazilian export of 2026 is not a commodity, and it cannot be held at customs. What does your organization's map of Brazil look like when the most valuable thing crossing the border is a method?" },
      { h: "Sources" },
      { p: "USTR Section 301 report and Federal Register notices; Banco Central do Brasil; The Economist (via O Estado de S. Paulo); Folha de S.Paulo; O Tempo; Poder360; Itamaraty note of July 1, 2026; Satispay company statements and FY2024 filings as reported by Milano Finanza and Sky TG24." },
    ],
  },
  pt: {
    back: "Voltar às análises",
    body: [
      { p: "O PIX é o sistema de pagamentos instantâneos criado pelo Banco Central do Brasil, em operação desde novembro de 2020. Permite transferências entre contas em poucos segundos, 24/7, com custo muito baixo ou nulo para pessoas físicas." },
      { p: "Para empresas europeias que operam ou vendem no Brasil, o PIX tornou-se um canal de recebimento indispensável: adotado por centenas de milhões de usuários, é utilizado em e-commerce, varejo físico, faturamento B2B e pagamento de serviços públicos." },
      { p: "Pontos-chave para uma empresa estrangeira: identificação por chave (CPF, CNPJ, e-mail, telefone ou chave aleatória), conciliação automática via QR Code estático ou dinâmico, integração por APIs bancárias ou gateways de pagamento, e conformidade com as normas brasileiras de PLD/FT e a LGPD." },
    ],
  },
};

export default function Pix() {
  const { lang } = useT();
  const article = getArticleBySlug("pix");
  const c = content[lang];

  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <Link
          to="/analysis"
          className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          {c.back}
        </Link>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">
            {article?.title[lang]}
          </h1>
          <p className="text-xs text-foreground/50 mb-10 tabular-nums">{article?.date}</p>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {c.body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
        </article>
        <AnalysisComments slug="pix" />
        <AnalysisFooter />
      </div>
    </main>
  );
}