import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";

import { AnalysisFooter } from "@/components/AnalysisFooter";
import { useCanonical } from "@/lib/useCanonical";
import { ShareBlock } from "@/components/ShareBlock";
import { LangSwitcher } from "@/components/LangSwitcher";

type BodyBlock = { h: string } | { p: string };

const content: Record<"it" | "en" | "pt", { back: string; body: BodyBlock[]; dateLabel?: string }> = {
  it: {
    back: "Torna alle analisi",
    dateLabel: "Aggiornato al 1° agosto 2026",
    body: [
      { p: "Da mercoledì 22 luglio, importare merci brasiliane negli Stati Uniti costa il 25% in più. Da venerdì 24, un ulteriore 12,5%. Il primo dazio, fondato su un'indagine ai sensi della Sezione 301 durata un anno intero, colpisce oltre 11 miliardi di dollari di interscambio risparmiando circa 2.100 prodotti — tra cui carne bovina, caffè e succo d'arancia. Il secondo, frutto di una seconda indagine sul lavoro forzato, porta il carico cumulato al 37,5% sulla gran parte delle vendite brasiliane verso gli USA: tra i livelli più alti che Washington applichi a un partner qualsiasi. Ogni guerra commerciale produce dazi. Questa ha prodotto qualcosa di mai visto: il primo dazio della storia imposto non contro un prodotto, ma contro un metodo. Il rapporto dell'USTR ne indica il bersaglio per nome. Si chiama Pix." },
      { h: "Il complimento più costoso mai pagato" },
      { p: "A leggere le conclusioni dell'indagine, l'elenco delle accuse è lungo — commercio digitale, accordi tariffari preferenziali, accesso al mercato dell'etanolo, proprietà intellettuale, applicazione delle norme anticorruzione, deforestazione illegale. Ma l'elemento che dà a questo dazio il suo carattere storico è la constatazione che le politiche pubbliche brasiliane favoriscono il Pix e pongono le società americane dei pagamenti elettronici in una posizione di \"svantaggio sleale\"." },
      { p: "Si consideri che cosa viene sanzionato. Il Pix non è un'azienda. Non ha azionisti, non ha una riga di ricavi, non emette fatture di esportazione. È un pezzo di infrastruttura finanziaria pubblica costruito dal Banco Central do Brasil in meno di due anni e acceso nel novembre 2020. Nel 2024 processava 64 miliardi di transazioni l'anno — più di Visa e Mastercard messe insieme nel Paese — e raggiungeva il 93% degli adulti brasiliani, con oltre 170 milioni di utenti registrati: più della popolazione economicamente attiva del Brasile. Ha portato dentro il sistema finanziario, gratuitamente, decine di milioni di cittadini che non avevano un conto." },
      { p: "Niente di tutto questo attraversa un confine. Nessun container lo trasporta, nessun doganiere può trattenerlo al porto. Eppure oggi regge un dazio del 25% su beni fisici che con i pagamenti non c'entrano nulla. Non potendo tassare il metodo, Washington ha tassato tutto ciò che gli sta intorno. Non esiste complimento più costoso." },
      { h: "Che cosa contesta davvero Washington" },
      { p: "Il percorso procedurale merita una pausa. L'USTR ha proposto il dazio il 1° giugno 2026, a indagine conclusa. Le audizioni pubbliche si sono tenute il 6 e 7 luglio; il governo Lula ha scelto di non mandare nessuno a parlare — presenti solo osservatori dell'ambasciata a Washington, una sedia vuota come dichiarazione di principio. La conferma è arrivata il 15 luglio; l'entrata in vigore, una settimana dopo." },
      { p: "Dopo l'annuncio, un alto funzionario dell'amministrazione americana ha tenuto a chiarire che Washington non vuole la fine del Pix, ne riconosce l'importanza per i brasiliani e chiede soltanto che le aziende americane possano competere ad armi pari. Ma si guardino le obiezioni specifiche, e uno schema emerge. L'USTR contesta il doppio ruolo del Banco Central come regolatore e insieme gestore dello schema. Contesta il mandato che rende il Pix gratuito per le persone fisiche. Contesta i tetti alle commissioni per gli esercenti e l'obbligo per le banche di dare al sistema evidenza visiva nelle proprie app." },
      { p: "Tolto il linguaggio giuridico, ogni obiezione punta alla stessa cosa: non la tecnologia, ma le decisioni di governance che hanno reso la tecnologia universale. La contestazione, in altre parole, riguarda il metodo in sé — una banca centrale disposta a fare da proprietaria dello schema, a imporre la partecipazione e a prezzare un binario di pagamento come infrastruttura pubblica anziché come casello. L'ironia si scrive da sola: mentre il dazio veniva messo a punto, i brasiliani movimentavano circa 8 miliardi di dollari al mese in stablecoin denominate in dollari — un canale al quale Washington non ha nulla da obiettare." },
      { h: "Il muro di Brasilia" },
      { p: "Se il dazio doveva dividere il Brasile, ha ottenuto l'opposto. La risposta del presidente Lula è arrivata con un post sui social: \"É público, é de graça e vai continuar assim\" — è pubblico, è gratuito e resterà così — sotto il titolo che la sovranità non si negozia. Ancora più eloquente la reazione dall'altra parte dell'emiciclo. Flávio Bolsonaro, tutto fuorché un alleato del governo, si è rifiutato di mettere il Pix sul tavolo, proponendo semmai un compromesso: l'impegno del Brasile a non collegare mai il Pix a un'infrastruttura internazionale di pagamenti rivale di quella americana." },
      { p: "Quella concessione proposta è la frase più rivelatrice dell'intera vicenda. Ammette che il sistema domestico è intoccabile — e identifica la vera posta in gioco: l'interoperabilità. Non se i brasiliani si paghino tra loro con un codice fiscale e un QR code, ma se il metodo si colleghi verso l'esterno, ai sistemi degli altri Paesi, formando corridoi che aggirano i binari americani." },
      { p: "Quell'infrastruttura rivale, peraltro, ha già un nome e un indirizzo. Si chiama Progetto Nexus, è nato nel BIS Innovation Hub di Basilea ed è disegnato per interconnettere i sistemi di pagamento istantaneo nazionali — il Pix, l'UPI indiano, il PromptPay tailandese — fino a una sessantina di Paesi, aggirando sia i circuiti delle carte sia Swift. Il BIS stima una fase di test a partire dal 2027; il Banco Central do Brasil vi partecipa, per ora, da osservatore con intenzione dichiarata. Il che chiarisce che cosa prezzi davvero il 25%: non ciò che il Pix è, ma ciò che sta per diventare." },
      { p: "La risposta formale dell'Itamaraty, depositata il 1° luglio, ha aggiunto l'argomento cui Washington fatica di più a rispondere: gli Stati Uniti hanno un surplus commerciale con il Brasile. Un procedimento ex Sezione 301, concepito per rimediare a pratiche che gravano sul commercio americano, viene usato contro un Paese che dall'America compra più di quanto le venda. Perfino Paul Krugman, che non è un difensore d'ufficio di Brasilia, ha liquidato la cornice della \"pratica sleale\" con una domanda che resta sospesa: da quando è sleale che un Paese offra ai propri cittadini un modo migliore di pagare — o che un'azienda perda quote di mercato a vantaggio di un concorrente con un prodotto migliore e più economico?" },
      { h: "La risposta in due tempi" },
      { p: "La postura di Brasilia è cambiata nell'arco di quarantotto ore. Mercoledì era de-escalation deliberata: il vicepresidente Alckmin, dopo aver incontrato i settori colpiti — macchinari (3,3 miliardi di dollari esposti), legno (colpito l'81% dell'export verso gli USA), gomma, alimentare, tessile — escludeva esplicitamente la ritorsione: l'idea non è la reciprocità, diceva; gli strumenti esistono e potranno essere usati al momento opportuno. Gli stessi settori chiedevano più credito dentro il programma Brasil Soberano, barriere contro la deviazione delle importazioni cinesi e la prosecuzione della diplomazia — non contro-dazi." },
      { p: "Giovedì sera, all'annuncio della seconda tariffa, il registro si è rovesciato. La nota del Planalto ha definito le misure \"completamente arbitrarie e ingiustificate\", annunciando l'avvio immediato dei trâmites della Lei de Reciprocidade — approvata all'unanimità dal Congresso — e il ricorso all'OMC. Ma la lettura di chi conosce i dossier resta prudente: dietro le quinte l'attivazione è considerata una segnalazione politica, l'iter prevede analisi settoriali e consultazioni pubbliche, e una decisione effettiva difficilmente arriverà prima delle elezioni di ottobre. Anche perché la via OMC è più simbolica che operativa: l'organo d'appello dell'organizzazione è stato smontato proprio dall'ostruzione americana." },
      { p: "Dietro la moderazione resta l'aritmetica: la quota americana sull'export brasiliano è scesa al 9,4% nel 2026, dal picco recente del 13,7%. Dolorosa, non esistenziale. E c'è una voce contrarian che merita registrazione: per Monica de Bolle (Peterson Institute) il Brasile dovrebbe rispondere subito con un'imposta temporanea sulle esportazioni — strumento del 1977, compatibile con le regole OMC — sui beni in cui detiene potere di mercato, compensando gli esportatori attraverso il Brasil Soberano. La sua lettura della lista di esenzioni è la più affilata in circolazione: ciò che Washington esenta — il caffè, di cui il Brasile copre circa un terzo del mercato americano, il succo d'arancia, la carne, il ferro-gusa, il nióbio, perfino i componenti aeronautici — è l'inventario delle proprie vulnerabilità. In un solo documento, due mappe: ciò che tassa misura la competitività brasiliana; ciò che risparmia misura la dipendenza americana." },
      { h: "La seconda tariffa e la terza architettura" },
      { p: "La tariffa attesa per venerdì 24 è arrivata puntuale: 12,5%, esito di una seconda indagine sul lavoro forzato, in sostituzione delle sovrattasse del 10% ex Sezione 122 in scadenza a fine mese. Il Brasile figura in una lista di 60 partner commerciali tassati tra il 10% e il 12,5% — con dentro l'Unione Europea, il Giappone, la Corea del Sud, il Regno Unito e la Svizzera: il dossier ha smesso di essere una storia brasiliana. Per il Brasile, cinque i prodotti accusati per il periodo 2021-2025: alluminio, cotone, elettronica, batterie al litio e tabacco." },
      { p: "Ma il dettaglio che rivela l'architettura sta nelle esenzioni. Oltre alle 2.113 voci esentate per il Brasile e altri 46 Paesi, tredici economie hanno ricevuto liste di esenzione aggiuntive — l'Argentina 93 prodotti in più, la Malesia 105, il Regno Unito 49, l'Unione Europea 43 — perché vietano le importazioni da lavoro forzato al modo americano, si sono impegnate a farlo in accordi reciproci o hanno regimi parziali di prevenzione. Il Brasile è rimasto nel gruppo pieno, e i numeri del differenziale li ha messi in fila Sergio Vale (MB Associados): il 3,4% della pauta tariffata — 470 milioni di dollari, con la madeira processada per l'edilizia americana, le pietre preziose e le protesi mediche in prima fila — subirà la concorrenza di Paesi trattati meglio. Il vero svantaggio, però, non dipende da nessuna lista: sono i 27,5 punti percentuali strutturali che derivano dall'essere l'unico Paese al mondo con una tariffa propria del 25% sommata a quella sul lavoro forzato." },
      { p: "Qui il paradosso che avevamo descritto si è fatto ufficiale. Nella sua risposta formale, il governo brasiliano si difende citando esattamente lo strumento che lo distingue: la lista suja, il registro pubblico dei datori di lavoro sorpresi a impiegare manodopera in condizioni analoghe alla schiavitù — e ricorda di aver ratificato 66 convenzioni dell'Organizzazione Internazionale del Lavoro, contro le 10 firmate dagli Stati Uniti. Ma la logica delle esenzioni rivela il commercio vero di questa famiglia tariffaria: chi adotta l'architettura americana di enforcement — il divieto d'importazione alla frontiera, sul modello della Sezione 307 — ottiene lo sconto; l'architettura brasiliana, che punisce i propri produttori con la trasparenza di un registro pubblico invece di bloccare le merci altrui alla dogana, non vale nulla ai fini tariffari. Un dazio che vende un metodo mentre ne punisce un altro: anche su questo fronte, la partita non è mai stata sui prodotti." },
      { h: "Il mondo che Washington sta leggendo correttamente" },
      { p: "Liquidare il dazio come semplice protezionismo a favore di Visa e Mastercard significa non vedere ciò che il Tesoro americano vede davvero. Il segretario Scott Bessent ha descritto la nuova postura come la diplomazia economica del XXI secolo, nella quale l'accesso al dollaro e all'infrastruttura finanziaria americana non è più incondizionato. Da quel punto di osservazione, la mappa globale dei pagamenti è davvero allarmante: la Russia, tagliata fuori dai binari occidentali, gira ormai su un proprio sistema di messaggistica (SFPS) e una propria rete di carte (Mir). Il CIPS cinese, rivale transfrontaliero di Swift, ha registrato a marzo una media giornaliera record di 920 miliardi di yuan — circa 130 miliardi di dollari, il 20% in più di un anno prima — con un primato in un solo giorno di 1.200 miliardi di yuan ad aprile. L'UPI indiano opera in nove Paesi, e l'NPCI lo promuove all'estero con il vocabolario della sovranità: aiutare i Paesi a onorare i propri impegni interni e a condurre la propria agenda nazionale." },
      { p: "Ognuno di questi è un metodo che si propaga. Il dazio sul Pix si capisce meglio come un tentativo di alzare il prezzo d'ingresso a quella propagazione — un segnale rivolto meno a Brasilia che a ogni capitale che stia studiando il manuale brasiliano." },
      { h: "L'Europa possiede già l'hardware" },
      { p: "La lettura standard del capitolo europeo di questa storia è che l'Europa stia aspettando — aspettando l'euro digitale prima di poter rispondere alla domanda che Aurore Lalucq ha posto al Parlamento europeo: che cosa succede se degli Stati Uniti ostili tagliano l'accesso all'infrastruttura dei pagamenti? \"Non potrete dire di non essere stati avvertiti\", ha detto ai colleghi, esortando l'Europa a costruire le proprie alternative — un appello ripreso dai vertici delle banche britanniche, che discutono di un rivale domestico ai circuiti delle carte, e dalla stessa Christine Lagarde." },
      { p: "Quella lettura è sbagliata, e conta che lo sia. All'Europa non manca il binario. I bonifici istantanei SEPA raggiungono 41 Paesi; per effetto del Regolamento sui pagamenti istantanei, da gennaio 2025 non possono costare più di un bonifico ordinario, e da ottobre 2025 ogni banca dell'area euro deve verificare gratuitamente il nome del beneficiario rispetto all'IBAN prima che il denaro parta. Veloce, economico, verificato: la tubatura che il Brasile ha costruito nel 2020, l'Europa l'ha in gran parte costruita anche lei." },
      { p: "Ciò che all'Europa manca è tutto quello che il Pix ha stratificato sopra la tubatura — ed è qui che il confronto diventa una diagnosi. Primo, l'anagrafica: il Pix ha sostituito il numero di conto con un alias — un codice fiscale, un numero di telefono, un'email — risolto attraverso un unico registro nazionale gestito dalla banca centrale. La risposta europea all'alias esiste, ma in frammenti: Wero, il portafoglio costruito dalle banche francesi, tedesche e del Benelux dell'European Payments Initiative (che ha assorbito l'olandese iDeal), usa il numero di telefono; così Bizum in Spagna, MB Way in Portogallo, Blik in Polonia, Swish in Svezia. Cinque anagrafiche, cinque marchi, e un'interoperabilità transfrontaliera ancora in cantiere. Secondo, il mandato: il Banco Central do Brasil ha obbligato ogni istituto ad aderire a un unico schema, gratuito per le persone fisiche, dal primo giorno. Nessuna autorità europea ha imposto un unico schema alle proprie banche; il regolamento impone il binario, non la rete che ci corre sopra. Terzo, la cassa: il Pix ha spiazzato le carte nel punto vendita con un QR code. SEPA Instant, con tutta la sua velocità, resta in larga parte uno strumento da persona a persona; alla cassa europea, il duopolio americano continua a riscuotere il pedaggio." },
      { p: "Gli incumbent se ne sono accorti. Il presidente di Mastercard per l'Europa si è messo a sostenere che una rete di pagamenti europea esiste già — ed è Mastercard —, corroborando la tesi con 500 milioni di euro investiti in infrastruttura europea, un centro tecnologico in Polonia previsto per il 2027 e tre data center in Francia da 250 milioni di euro, oltre a una partnership per i pagamenti in tempo reale con la cinese UnionPay. Visa e Mastercard, con margini operativi sopra il 50%, indicano ormai il trattamento \"preferenziale\" riservato ai sistemi di pagamento domestici come rischio d'impresa nelle proprie relazioni annuali. Quando un duopolio comincia a scrivere il tuo metodo nelle proprie informative sui rischi, il metodo sta funzionando." },
      { p: "L'Italia, intanto, ha condotto in sordina l'esperimento di controllo. Satispay è la cosa più vicina a un Pix costruito da privati che esista in Europa: un alias al posto dell'IBAN, trasferimenti gratuiti da persona a persona, una rete proprietaria deliberatamente instradata fuori dai circuiti delle carte. Per un decennio, con circa mezzo miliardo di euro di capitale di rischio, ha comprato un utente alla volta ciò che il Banco Central do Brasil ha ottenuto per decreto. Il tabellone racconta la storia: 6,5 milioni di utenti e 450.000 esercenti — circa un decimo degli adulti italiani, contro il 93% dei brasiliani del Pix — ricavi di rete per 46 milioni di euro nel 2024 a fronte di una perdita netta di 47 milioni, con lungo il percorso un richiamo d'informativa dei revisori sulla continuità aziendale. E quando l'azienda ha finalmente dato un prezzo alla propria rete, nell'aprile 2025, introducendo una commissione dell'1% per gli esercenti, alcuni se ne sono semplicemente andati: parte della proposta di valore, si è scoperto, era il sussidio stesso." },
      { p: "Questo luglio l'esperimento è arrivato alla sua destinazione logica. Satispay ha lanciato le carte di debito — su circuito Mastercard. Non potendo comprare l'universalità e non potendo decretarla, lo sfidante anti-carte sta ora prendendo in affitto l'accettazione proprio dal duopolio che si era proposto di aggirare, monetizzando con piani in abbonamento sul modello Revolut mentre il circuito proprietario serve la nicchia domestica. Il suo fondatore parla, senza ironia, di diventare un giorno una banca proprietaria di un circuito di pagamento. Il teorema non poteva essere dimostrato più pulitamente: senza un proprietario dello schema dotato del potere di mandato, l'universalità non è in vendita — solo in affitto, e i locatori sono due." },
      { p: "Il che porta alla conclusione scomoda: nessuno dei tre strati mancanti richiede l'euro digitale, promesso per il 2029. Un'anagrafica è governance. Un mandato è regolamentazione. L'accettazione degli esercenti è disegno dello schema. Al Brasile non è servita una valuta digitale di banca centrale per costruire il Pix — è servita una banca centrale disposta a fare da proprietaria dello schema, e il decennio di Satispay dimostra che nessuna quantità di capitale privato può sostituirla. Ciò che separa il panorama europeo dei pagamenti dalla sovranità non è un ritardo tecnologico di tre anni, ma un atto di volontà istituzionale." },
      { h: "Il prezzo della sovranità, detto con onestà" },
      { p: "La frammentazione non è gratuita, e le ragioni della cautela meritano un ascolto leale. Un rapporto sponsorizzato da Swift stima che, se gli andamenti attuali proseguono, la frammentazione finanziaria potrebbe togliere il 2,6% al PIL globale entro il 2030. Il Financial Stability Board avverte che la proliferazione dei sistemi nazionali impedirà probabilmente al G20 di centrare gli obiettivi su rimesse più economiche e veloci fissati nel 2020. E come osserva Josh Lipsky dell'Atlantic Council, un mondo di sistemi regionali incompatibili è un mondo con più frodi e un'elusione delle sanzioni più facile. I Paesi potrebbero scoprire — così concludeva l'analisi originale dell'Economist — che il prezzo della sovranità nei pagamenti è più alto di quanto immaginano; e lo stesso potrebbe valere per gli Stati Uniti." },
      { p: "Ma si noti che cosa implica quell'avvertimento per questo dazio. Se il pericolo è la frammentazione, la politica americana razionale sarebbe tenere i sistemi di pagamento del mondo interoperabili con il proprio. Un dazio punitivo sul metodo di pagamento pubblico di maggior successo mai realizzato fa l'opposto: certifica che il metodo minaccia gli incumbent, alza il valore percepito dell'indipendenza e consegna a ogni ministero delle finanze un argomento da 25% per costruirsi i propri binari. Il dazio non rallenta la frammentazione che teme. La pubblicizza." },
      { h: "Il metodo è già sul tavolo" },
      { p: "Tolto il vocabolario da guerra commerciale, resta una transazione strana. Gli Stati Uniti hanno attaccato un cartellino da 25% a un metodo — e così facendo lo hanno pubblicizzato presso ogni giurisdizione che osserva. La risposta del Brasile al dazio verrà negoziata tra Brasilia e Washington. La risposta dell'Europa, se ne vorrà una, non richiede alcun negoziato: i binari sono posati, i bonifici sono istantanei e gratuiti, le verifiche del beneficiario sono operative. Ogni componente del metodo che Washington ha appena dichiarato una minaccia è già lì, non assemblato, dentro il sistema europeo dei pagamenti. Assemblarlo non è un progetto tecnologico con una data di consegna. È una decisione." },
      { p: "È questo che rende il dazio storico al di là del suo 25%. I dazi sui prodotti si assorbono, si aggirano, si aspettano. Un dazio su un metodo fa qualcosa che nessun dazio aveva mai fatto: certifica che il metodo funziona, lo nomina pubblicamente e sfida tutti gli altri ad adottarlo. Il Brasile ha costruito il Pix in meno di due anni con una banca centrale disposta a fare da proprietaria dello schema. La domanda che il dazio lascia sul tavolo non è se il metodo possa attraversare l'Atlantico — è quale sponda dell'Atlantico deciderà di volerlo per prima." },
      { p: "In BMG leggiamo la politica commerciale per ciò che rivela, più che per ciò che dichiara. Questa rivela più di molte altre: l'export brasiliano più pesantemente sanzionato del 2026 non è una materia prima, e non si può trattenere in dogana. Che aspetto ha la mappa del Brasile della vostra organizzazione, quando la cosa più preziosa che attraversa il confine è un metodo?" },
      { h: "Aggiornamento — 1° agosto 2026" },
      { p: "Il metodo che nessuno finanzia. La settimana si è chiusa con il paradosso più rivelatore dell'intera vicenda, documentato dalla Folha: i tagli al bilancio del Banco Central minacciano sicurezza e innovazione del Pix. Il budget discrezionale dell'autorità è fermo a R$444 milioni — sotto la soglia dei R$500 milioni, ammettono i tecnici, il rischio di guasti \"cresce significativamente\" — dopo un taglio di R$92 milioni a giugno che ha messo a rischio il rinnovo dei contratti tecnologici che sostengono il sistema; lo sblocco d'emergenza di R$45 milioni ne lascia mancare 75 per evitare il congelamento degli investimenti. Parliamo dell'infrastruttura che muove R$3 trilioni al mese: il suo intero bilancio annuale vale meno dei tre data center che Mastercard sta costruendo in Francia. La serie storica completa il quadro: la spesa dell'autorità, corretta per l'inflazione, è scesa da R$543 milioni nel 2015 al minimo di R$346 nel 2024 — il Pix è stato costruito, lanciato e portato a decine di miliardi di transazioni negli anni più magri del decennio, e il tetto 2026 resta sotto il livello di undici anni fa. Nel 2024 gli investimenti previsti sul sistema sono già stati rinviati; l'ampliamento del data center pianificato per il 2026 arriva con le macchine al limite di capacità; e l'attacco del giugno 2025 alla C&M Software — circa R$1 miliardo sottratto attraverso un fornitore connesso all'infrastruttura, mai violato il cuore del sistema — ricorda cosa c'è in gioco, come lo ricorda il precedente che i tecnici brasiliani evocano apertamente: la crisi energetica del 2001, figlia di anni di investimenti mancati. Persino il Fondo Monetario, nel rapporto del 23 luglio, elogia il Pix per l'inclusione finanziaria e nella stessa pagina raccomanda di rafforzarne la supervisione contro attacchi e frodi. Il governo assicura che le risorse non mancheranno, indicando lo sblocco generale da R$5,7 miliardi e la legge di bilancio 2027; ma promettere di finanziare domani ciò che processa R$3 trilioni oggi è, esattamente, il punto. La lezione, per Brasilia come per Bruxelles, è la stessa: Washington prezza il metodo al 37,5%; chi lo possiede deve prezzarlo nel proprio bilancio. Uno scheme owner non è solo un atto di volontà istituzionale — è una voce di spesa permanente, e una sovranità non finanziata è una sovranità in prestito." },
      { p: "Tutto, tranne il metodo. Le cronache delle trattative confermano intanto dove passa la linea. Nei quattro incontri tra il ministro Elias Rosa e il rappresentante Greer, Brasilia ha messo sul tavolo concessioni su ogni asse dell'indagine — fino alla riduzione delle proprie tariffe su circa trecento tipologie di scambi, estesa a più Paesi per restare nei binari OMC — con una sola esclusione, dichiarata non negoziabile: il Pix, \"patrimonio del nostro popolo\" secondo la nota ufficiale del governo. Un negoziato che offre tutto tranne il metodo è la definizione operativa della tesi di questa analisi. E un secondo premio Nobel si è intanto aggiunto al registro: per Joseph Stiglitz, intervistato dalla BBC News Brasil, le giustificazioni della tariffa sono una \"farsa disonesta\" e la molla vera è l'insofferenza verso la difesa brasiliana di democrazia, sovranità digitale e sistemi di pagamento indipendenti — con l'avvertenza che la strategia rischia di indebolire gli Stati Uniti e rafforzare l'influenza della Cina nell'economia globale." },
      { p: "La scala, aggiornata. I numeri consolidati del 2025 alzano ulteriormente la posta: quasi 80 miliardi di transazioni nell'anno, con il record di 313 milioni in un solo giorno il 5 dicembre; da settembre 2025 i pagamenti verso le imprese superano quelli tra persone, e nell'e-commerce il Pix ha sorpassato le carte di credito (42% contro 41%) — la cassa che in Europa resta al duopolio, in Brasile è già caduta. Sul fronte frodi, l'obiezione registrata più sopra ha ora una risposta operativa: il nuovo meccanismo di devoluzione del Banco Central traccia algoritmicamente i fondi sottratti lungo intere catene di conti-prestanome e ne orchestra il recupero. Un dettaglio per il lettore europeo: il prototipo del Progetto Nexus è già stato testato in connessione con l'Eurosistema — l'Europa, al tavolo tecnico, c'è già stata. E mentre la diplomazia rallenta verso le elezioni di ottobre, la diversificazione accelera: l'Apex prepara per agosto un piano da R$130 milioni per spingere l'export verso Unione Europea, Sud-Est asiatico e Asia centrale. Il corridoio, appunto." },
      { h: "Fonti" },
      { p: "rapporto USTR Sezione 301 e avvisi del Federal Register; Banco Central do Brasil; BIS Innovation Hub (Progetto Nexus); The Economist (via O Estado de S. Paulo); Folha de S.Paulo (tra cui Adriana Fernandes, 27 luglio 2026); O Tempo; Poder360; Bloomberg Línea (intervista a Monica de Bolle, 22 lug 2026); CNN Brasil; Agência Brasil; FMI (rapporto del 23 luglio 2026); BBC News Brasil (intervista a Joseph Stiglitz, Julia Braun); note del Planalto/Secom del 1° e 23 luglio 2026; comunicazioni societarie Satispay e bilancio 2024 come riportati da Milano Finanza e Sky TG24." },
    ],
  },
  en: {
    back: "Back to analysis",
    dateLabel: "Updated August 1, 2026",
    body: [
      { p: "Since Wednesday, July 22, importing Brazilian goods into the United States costs 25% more. Since Friday, July 24, an additional 12.5%. The first tariff, built on a Section 301 investigation that took a full year, hits over US$11 billion in trade while sparing roughly 2,100 products — beef, coffee, orange juice among them. The second, the outcome of a separate investigation into forced labor, lifts the cumulative burden to 37.5% on the bulk of Brazilian sales to the US: among the highest rates Washington applies to any trading partner. Every trade war produces tariffs. This one produced something without precedent: the first tariff in history levied not against a product, but against a method. The USTR's report names its target explicitly. It is called Pix." },
      { h: "The most expensive compliment ever paid" },
      { p: "Read the investigation's conclusions and the charge sheet is long — digital trade, preferential tariff agreements, ethanol market access, intellectual property, anti-corruption enforcement, illegal deforestation. But the item that gives this tariff its historic character is the finding that Brazil's public policies favor Pix and place American electronic-payment companies at an \"unfair disadvantage.\"" },
      { p: "Consider what is being sanctioned. Pix is not a company. It has no shareholders, no revenue line, no export invoice. It is a piece of public financial plumbing built by the Banco Central do Brasil in under two years and switched on in November 2020. By 2024 it was processing 64 billion transactions annually — more than Visa and Mastercard combined in the country — and reaching 93% of Brazilian adults, with over 170 million registered users, more than Brazil's economically active population. It brought tens of millions of unbanked citizens into the financial system, free of charge." },
      { p: "None of that crosses a border. No container carries it, no customs officer can hold it at the port. And yet it now anchors a 25% duty on physical goods that have nothing to do with payments. Washington could not tariff the method, so it tariffed everything around it. There is no more expensive compliment." },
      { h: "What Washington actually objects to" },
      { p: "The procedural record is worth pausing on. The USTR proposed the tariff on June 1, 2026, after concluding its investigation. Public hearings were held on July 6 and 7; the Lula government chose not to send anyone to speak — only observers from the embassy in Washington attended, an empty chair as a statement of principle. Confirmation came on July 15; entry into force, one week later." },
      { p: "After the announcement, a senior US administration official was at pains to clarify that Washington does not want to end Pix, recognizes its importance to Brazilians, and merely wants American companies to compete on equal terms. Look at the specific objections, though, and a pattern emerges. The USTR faults the Banco Central's dual role as regulator and operator of the scheme. It faults the mandate that makes Pix free for individuals. It faults the caps on merchant fees and the requirement that banks give the system visual prominence in their apps." },
      { p: "Strip the legal language and each objection targets the same thing: not the technology, but the governance decisions that made the technology universal. The complaint, in other words, is with the method itself — a central bank willing to act as scheme owner, to mandate participation, and to price a payment rail as public infrastructure rather than as a toll booth. The irony writes itself: while the tariff was being finalized, Brazilians were moving an estimated US$8 billion a month through dollar-denominated stablecoins, a channel Washington has no objection to at all." },
      { h: "The wall in Brasília" },
      { p: "If the tariff was meant to divide Brazil, it achieved the opposite. President Lula's response came as a social-media card: \"É público, é de graça e vai continuar assim\" — public, free, and staying that way — under the caption that sovereignty is not for negotiation. More telling was the reaction across the aisle. Flávio Bolsonaro, no ally of the government, declined to put Pix on the table, floating instead a compromise in which Brazil would commit never to link Pix to an international payments infrastructure rivaling America's." },
      { p: "That proposed concession is the most revealing sentence in the entire dispute. It concedes that the domestic system is untouchable — and identifies what the fight is actually about: interoperability. Not whether Brazilians pay each other with a tax ID and a QR code, but whether the method connects outward, to other countries' systems, forming corridors that route around the American rails." },
      { p: "That rival infrastructure, as it happens, already has a name and an address. It is called Project Nexus, it was conceived at the BIS Innovation Hub in Basel, and it is designed to interconnect national instant-payment systems — Pix, India's UPI, Thailand's PromptPay — across some sixty countries, bypassing both the card networks and Swift. The BIS estimates a testing phase from 2027; Brazil's central bank participates, for now, as an observer with declared intent. Which clarifies what the 25% actually prices: not what Pix is, but what it is about to become." },
      { p: "The Itamaraty's formal response, filed on July 1, added the argument Washington finds hardest to answer: the United States runs a goods surplus with Brazil. A Section 301 case, designed to remedy practices that burden American commerce, is being deployed against a country that buys more from America than it sells. Even Paul Krugman, no reflexive defender of Brasília, dismissed the \"unfair practice\" framing with a question that lingers: since when is it unfair for a country to offer its own citizens a better way to pay — or for a company to lose market share to a competitor with a better, cheaper product?" },
      { h: "The response, in two acts" },
      { p: "Brasília's posture flipped within forty-eight hours. On Wednesday it was deliberate de-escalation: Vice-President Alckmin, after meeting the affected sectors — machinery (US$3.3 billion exposed), wood (81% of its US exports hit), rubber, food, textiles — ruled out retaliation explicitly: reciprocity is not the idea, he said; the instruments exist and can be used at the opportune moment. The sectors themselves asked for more credit under the Brasil Soberano program, barriers against Chinese import diversion, and continued diplomacy — not counter-tariffs." },
      { p: "By Thursday evening, at the announcement of the second tariff, the register had reversed. The Planalto's statement called the measures \"completely arbitrary and unjustified\" and announced the immediate initiation of proceedings under the Lei de Reciprocidade — approved unanimously by Congress — along with a WTO challenge. Those who know the dossiers, however, read it cautiously: behind the scenes the activation is treated as political signaling, the process requires sector analyses and public consultations, and an actual decision is unlikely before October's elections. Not least because the WTO route is more symbolic than operational: the organization's appellate body was dismantled by American obstruction in the first place." },
      { p: "Behind the restraint sits arithmetic: the American share of Brazilian exports has fallen to 9.4% in 2026, from 13.7% at its recent peak. Painful, not existential. And one contrarian voice deserves the record: for Monica de Bolle of the Peterson Institute, Brazil should respond immediately with a temporary export tax — an instrument dating to 1977, compatible with WTO rules — on goods where it holds market power, compensating exporters through Brasil Soberano. Her reading of the exemption list is the sharpest in circulation: what Washington exempts — coffee, of which Brazil supplies roughly a third of the American market, orange juice, beef, pig iron, niobium, even aircraft components — is an inventory of its own vulnerabilities. One document, two maps: what it taxes measures Brazilian competitiveness; what it spares measures American dependence." },
      { h: "The second tariff and the third architecture" },
      { p: "The tariff expected on Friday the 24th arrived on schedule: 12.5%, the outcome of a second investigation into forced labor, replacing the 10% surcharges under Section 122 that expire at month's end. Brazil sits on a list of 60 trading partners taxed between 10% and 12.5% — a list that includes the European Union, Japan, South Korea, the United Kingdom and Switzerland: the file has stopped being a Brazilian story. For Brazil, five products stand accused for the 2021–2025 period: aluminum, cotton, electronics, lithium batteries and tobacco." },
      { p: "But it is the exemptions that reveal the architecture. Beyond the 2,113 items exempted for Brazil and 46 other countries, thirteen economies received additional exemption lists — Argentina 93 more products, Malaysia 105, the United Kingdom 49, the European Union 43 — because they ban forced-labor imports the American way, committed to doing so in reciprocal agreements, or run partial prevention regimes. Brazil stayed in the full group, and Sergio Vale (MB Associados) has put numbers on the differential: 3.4% of the tariffed export basket — US$470 million, with processed wood for American construction, gemstones and medical prostheses first in line — will face competitors treated better. The real disadvantage, though, depends on no list at all: it is the structural 27.5 percentage points that come from being the only country in the world carrying its own 25% tariff on top of the forced-labor one." },
      { p: "Here the paradox we had described became official. In its formal response, the Brazilian government defends itself by citing precisely the instrument that sets it apart: the lista suja, the public registry of employers caught using slave-like labor — and it notes that Brazil has ratified 66 conventions of the International Labour Organization, against the 10 signed by the United States. But the logic of the exemptions reveals what this tariff family actually trades in: adopt the American enforcement architecture — the import ban at the border, on the Section 307 model — and the rate falls; Brazil's architecture, which punishes its own producers through the transparency of a public registry rather than blocking other countries' goods at customs, counts for nothing in tariff terms. A tariff that sells one method while punishing another: on this front too, the story was never about products." },
      { h: "The world Washington is reading correctly" },
      { p: "To dismiss the tariff as mere protectionism for Visa and Mastercard is to miss what the US Treasury actually sees. Secretary Scott Bessent has described the new posture as the economic diplomacy of the 21st century, in which access to the dollar and to American financial infrastructure is no longer unconditional. From that vantage point, the global payments map is genuinely alarming: Russia, cut off from Western rails, now runs on its own messaging system (SFPS) and card network (Mir). China's CIPS, the cross-border rival to Swift, posted a record daily average of 920 billion yuan in March — roughly US$130 billion, 20% above a year earlier — with a single-day record of 1.2 trillion yuan in April. India's UPI operates in nine countries, and the NPCI markets it abroad in the language of sovereignty: helping countries meet their own domestic commitments and conduct their own national agenda." },
      { p: "Every one of these is a method propagating. The tariff on Pix is best understood as an attempt to raise the price of joining that propagation — a signal aimed less at Brasília than at every capital studying the Brazilian playbook." },
      { h: "Europe already owns the hardware" },
      { p: "The standard reading of the European chapter of this story is that Europe is waiting — waiting for the digital euro before it can answer the question Aurore Lalucq put to the European Parliament: what happens if a hostile United States cuts access to payment infrastructure? \"You will not be able to say you were not warned,\" she told colleagues, urging Europe to build its own alternatives, a call echoed by British bank executives discussing a homegrown rival to the card networks and by Christine Lagarde herself." },
      { p: "That reading is wrong, and it matters that it is wrong. Europe does not lack the rail. SEPA Instant credit transfers reach 41 countries; under the Instant Payments Regulation they must cost no more than an ordinary transfer since January 2025, and since October 2025 every euro-area bank must verify the beneficiary's name against the IBAN, free of charge, before the money moves. Fast, cheap, verified: the plumbing Brazil built in 2020, Europe has largely built too." },
      { p: "What Europe lacks is everything Pix layered on top of the plumbing — and this is where the comparison becomes a diagnosis. First, the directory: Pix replaced the account number with an alias — a tax ID, a phone number, an email — resolved through a single national registry operated by the central bank. Europe's answer to the alias exists, but in fragments: Wero, the wallet built by the European Payments Initiative's French, German and Benelux banks (which absorbed the Netherlands' iDeal), uses a phone number; so do Bizum in Spain, MB Way in Portugal, Blik in Poland, Swish in Sweden. Five directories, five brands, and cross-border interoperability still a construction site. Second, the mandate: the Banco Central do Brasil obliged every institution to join one scheme, free for individuals, on day one. No European authority has imposed a single scheme on its banks; the regulation mandates the rail, not the network on top of it. Third, the till: Pix displaced cards at the point of sale through a QR code. SEPA Instant, for all its speed, remains largely a person-to-person tool; at the European checkout, the American duopoly still collects the toll." },
      { p: "The incumbents have noticed. Mastercard's president for Europe has taken to arguing that a European payments network already exists — and that it is Mastercard — backing the claim with €500 million in European infrastructure, a technology center in Poland due in 2027, and three data centers in France costing €250 million, alongside a real-time payments partnership with China's UnionPay. Visa and Mastercard, with operating margins above 50%, now list the \"preferential\" treatment of domestic payment systems as a business risk in their annual reports. When a duopoly starts writing your method into its risk disclosures, the method is working." },
      { p: "Italy, meanwhile, has quietly run the control experiment. Satispay is the closest thing Europe has to a privately built Pix: an alias instead of an IBAN, free person-to-person transfers, a proprietary network deliberately routed around the card circuits. For a decade, and with roughly half a billion euros of venture capital, it has been buying one user at a time what the Banco Central do Brasil obtained by decree. The scoreboard tells the story: 6.5 million users and 450,000 merchants — about a tenth of Italian adults, against Pix's 93% of Brazilians — network revenues of €46 million in 2024 against a net loss of €47 million, with an auditors' going-concern emphasis note along the way. And when the company finally priced its network in April 2025, introducing a 1% merchant fee, some merchants simply walked: part of the value proposition, it turned out, was the subsidy itself." },
      { p: "This July the experiment reached its logical destination. Satispay launched debit cards — on the Mastercard network. Unable to buy universality and unable to decree it, the anti-card challenger is now renting acceptance from the very duopoly it set out to bypass, monetizing through subscription tiers in the Revolut mold while its proprietary circuit serves the domestic niche. Its founder speaks, without irony, of one day becoming a bank that owns a payment circuit. The theorem could not be demonstrated more cleanly: without a scheme owner holding mandate power, universality is not for sale — only for rent, and there are only two landlords." },
      { p: "Which leads to the uncomfortable conclusion: none of the three missing layers requires the digital euro, promised for 2029. A directory is governance. A mandate is regulation. Merchant acceptance is scheme design. Brazil needed no central bank digital currency to build Pix — it needed a central bank willing to act as scheme owner, and Satispay's decade proves that no amount of private capital substitutes for one. What separates the European payments landscape from sovereignty is not a technology gap of three years but an act of institutional will." },
      { h: "The price of sovereignty, honestly stated" },
      { p: "Fragmentation is not free, and the case for caution deserves a fair hearing. A report sponsored by Swift estimates that if current patterns hold, financial fragmentation could shave 2.6% off global GDP by 2030. The Financial Stability Board warns that the proliferation of national systems will likely prevent the G20 from meeting the cheaper-faster remittance targets it set in 2020. And as the Atlantic Council's Josh Lipsky observes, a world of incompatible regional systems is a world with more fraud and easier sanctions evasion. Countries may discover, as the original Economist analysis concluded, that the price of payment sovereignty is higher than they imagine — and the same may prove true for the United States." },
      { p: "But note what that warning implies for this tariff. If fragmentation is the danger, the rational American policy would be to keep the world's payment systems interoperable with its own. A punitive tariff on the most successful public payment method ever deployed does the opposite: it certifies that the method threatens the incumbents, raises the perceived value of independence, and hands every finance ministry a 25% argument for building its own rails. The tariff does not slow the fragmentation it fears. It advertises it." },
      { h: "The method is already on the table" },
      { p: "Strip away the trade-war vocabulary and what remains is a strange transaction. The United States has attached a 25% price tag to a method — and in doing so, has advertised it to every jurisdiction watching. Brazil's answer to the tariff will be negotiated in Brasília and Washington. Europe's answer, if it wants one, requires no negotiation at all: the rails are laid, the transfers are instant and free, the beneficiary checks are live. Every component of the method that Washington just declared a threat already sits, unassembled, inside the European payments system. Assembling it is not a technology project with a delivery date. It is a decision." },
      { p: "That is what makes this tariff historic beyond its 25%. Tariffs on products can be absorbed, rerouted, waited out. A tariff on a method does something no tariff has done before: it certifies that the method works, names it publicly, and dares everyone else to adopt it. Brazil built Pix in under two years with a central bank willing to act as scheme owner. The question the tariff leaves on the table is not whether the method can cross the Atlantic — it is which side of the Atlantic decides to want it first." },
      { p: "At BMG, we read trade policy for what it reveals rather than what it declares. This one reveals more than most: the most heavily sanctioned Brazilian export of 2026 is not a commodity, and it cannot be held at customs. What does your organization's map of Brazil look like when the most valuable thing crossing the border is a method?" },
      { h: "Update — August 1, 2026" },
      { p: "The method nobody funds. The week closed with the most revealing paradox of the entire affair, documented by Folha: budget cuts at the Banco Central are threatening Pix's security and innovation. The authority's discretionary budget stands at R$444 million — below the R$500 million threshold under which, its own technicians admit, the risk of failures \"rises significantly\" — after a R$92 million cut in June that jeopardized the renewal of the technology contracts sustaining the system; an emergency release of R$45 million still leaves 75 missing to avoid freezing investments. This is the infrastructure that moves R$3 trillion a month: its entire annual budget is worth less than the three data centers Mastercard is building in France. The historical series completes the picture: the authority's spending, adjusted for inflation, fell from R$543 million in 2015 to a low of R$346 million in 2024 — Pix was built, launched and scaled to tens of billions of transactions in the leanest years of the decade, and the 2026 ceiling remains below the level of eleven years ago. Investments planned for the system were already postponed in 2024; the data-center expansion scheduled for 2026 arrives with the machines at the limit of their capacity; and the June 2025 attack on C&M Software — roughly R$1 billion siphoned through a supplier connected to the infrastructure, the system's core never breached — is a reminder of what is at stake, as is the precedent Brazilian technicians now invoke openly: the 2001 energy crisis, the child of years of missed investment. Even the IMF, in its July 23 report, praises Pix for financial inclusion and on the same page recommends strengthening its supervision against attacks and fraud. The government insists resources will not be lacking, pointing to a general R$5.7 billion budget release and to the 2027 budget bill; but promising to fund tomorrow what processes R$3 trillion today is, precisely, the point. The lesson, for Brasília as for Brussels, is the same: Washington prices the method at 37.5%; whoever owns it must price it into their own budget. A scheme owner is not merely an act of institutional will — it is a permanent budget line, and unfunded sovereignty is sovereignty on loan." },
      { p: "Everything but the method. The chronicles of the negotiations, meanwhile, confirm where the line runs. Across four meetings between Minister Elias Rosa and Representative Greer, Brasília put concessions on the table across every axis of the investigation — up to and including a reduction of its own tariffs on some three hundred categories of trade, extended to several countries to stay within WTO rules — with a single exclusion, declared non-negotiable: Pix, \"a heritage of our people\" in the government's official words. A negotiation that offers everything except the method is the operational definition of this analysis's thesis. And a second Nobel laureate has joined the record: for Joseph Stiglitz, interviewed by BBC News Brasil, the tariff's justifications are a \"dishonest farce\" and the real driver is hostility toward Brazil's defense of democracy, digital sovereignty and independent payment systems — with the warning that the strategy may end up weakening the United States and strengthening China's hand in the global economy." },
      { p: "The scale, updated. The consolidated 2025 numbers raise the stakes further: nearly 80 billion transactions over the year, with a record 313 million in a single day on December 5; since September 2025, payments to businesses have outnumbered person-to-person transfers, and in e-commerce Pix has overtaken credit cards (42% versus 41%) — the till that in Europe still belongs to the duopoly has, in Brazil, already fallen. On the fraud front, the objection recorded above now has an operational answer: the Banco Central's new refund mechanism algorithmically traces stolen funds along entire chains of mule accounts and orchestrates their recovery. One detail for the European reader: the Project Nexus prototype has already been tested in connection with the Eurosystem — Europe has, in fact, already sat at the technical table. And while diplomacy slows toward October's elections, diversification accelerates: Apex-Brasil is preparing a R$130 million plan for August to push exports toward the European Union, Southeast Asia and Central Asia. The corridor, indeed." },
      { h: "Sources" },
      { p: "USTR Section 301 report and Federal Register notices; Banco Central do Brasil; BIS Innovation Hub (Project Nexus); The Economist (via O Estado de S. Paulo); Folha de S.Paulo (incl. Adriana Fernandes, July 27, 2026); O Tempo; Poder360; Bloomberg Línea (interview with Monica de Bolle, July 22, 2026); CNN Brasil; Agência Brasil; IMF (report of July 23, 2026); BBC News Brasil (interview with Joseph Stiglitz, Julia Braun); Planalto/Secom statements of July 1 and 23, 2026; Satispay company statements and FY2024 filings as reported by Milano Finanza and Sky TG24." },
    ],
  },
  pt: {
    back: "Voltar às análises",
    dateLabel: "Atualizado em 25 de julho de 2026",
    body: [
      { p: "Desde quarta-feira, 22 de julho, importar produtos brasileiros para os Estados Unidos custa 25% a mais. Desde sexta-feira, 24, mais 12,5%. A primeira tarifa, construída sobre uma investigação nos termos da Seção 301 que durou um ano inteiro, atinge mais de US$ 11 bilhões em comércio, poupando cerca de 2.100 produtos — carne bovina, café e suco de laranja entre eles. A segunda, resultado de uma investigação separada sobre trabalho forçado, eleva a carga cumulativa a 37,5% sobre a maior parte das vendas brasileiras aos EUA: entre as alíquotas mais altas que Washington aplica a qualquer parceiro comercial. Toda guerra comercial produz tarifas. Esta produziu algo sem precedentes: a primeira tarifa da história aplicada não contra um produto, mas contra um método. O relatório do USTR nomeia o alvo explicitamente. Chama-se Pix." },
      { h: "O elogio mais caro já feito" },
      { p: "Leiam-se as conclusões da investigação e a lista de acusações é longa — comércio digital, acordos tarifários preferenciais, acesso ao mercado de etanol, propriedade intelectual, aplicação das normas anticorrupção, desmatamento ilegal. Mas o item que confere a esta tarifa seu caráter histórico é a constatação de que as políticas públicas brasileiras favorecem o Pix e colocam as empresas americanas de pagamentos eletrônicos em \"desvantagem injusta\"." },
      { p: "Considere-se o que está sendo sancionado. O Pix não é uma empresa. Não tem acionistas, não tem linha de receita, não emite fatura de exportação. É uma peça de infraestrutura financeira pública, construída pelo Banco Central do Brasil em menos de dois anos e ligada em novembro de 2020. Em 2024 já processava 64 bilhões de transações por ano — mais do que Visa e Mastercard somadas no país — e alcançava 93% dos adultos brasileiros, com mais de 170 milhões de usuários cadastrados: mais do que a população economicamente ativa do Brasil. Trouxe para dentro do sistema financeiro, gratuitamente, dezenas de milhões de cidadãos que não tinham conta." },
      { p: "Nada disso atravessa uma fronteira. Nenhum contêiner o transporta, nenhum fiscal aduaneiro pode retê-lo no porto. E no entanto, ele agora sustenta uma tarifa de 25% sobre bens físicos que nada têm a ver com pagamentos. Não podendo tarifar o método, Washington tarifou tudo o que está ao seu redor. Não existe elogio mais caro." },
      { h: "O que Washington contesta de verdade" },
      { p: "O percurso processual merece uma pausa. O USTR propôs a tarifa em 1º de junho de 2026, concluída a investigação. As audiências públicas ocorreram em 6 e 7 de julho; o governo Lula optou por não enviar ninguém para falar — compareceram apenas observadores da embaixada em Washington, uma cadeira vazia como declaração de princípio. A confirmação veio em 15 de julho; a entrada em vigor, uma semana depois." },
      { p: "Após o anúncio, um alto funcionário do governo americano fez questão de esclarecer que Washington não quer o fim do Pix, reconhece sua importância para os brasileiros e deseja apenas que as empresas americanas possam competir em igualdade de condições. Mas olhem-se as objeções específicas, e um padrão emerge. O USTR contesta o duplo papel do Banco Central como regulador e, ao mesmo tempo, operador do arranjo. Contesta a determinação que torna o Pix gratuito para pessoas físicas. Contesta os tetos às tarifas cobradas dos lojistas e a exigência de que os bancos deem destaque visual ao sistema em seus aplicativos." },
      { p: "Retirada a linguagem jurídica, cada objeção aponta para a mesma coisa: não a tecnologia, mas as decisões de governança que tornaram a tecnologia universal. A reclamação, em outras palavras, é contra o próprio método — um banco central disposto a atuar como dono do arranjo, a tornar a participação obrigatória e a precificar um trilho de pagamentos como infraestrutura pública, e não como pedágio. A ironia se escreve sozinha: enquanto a tarifa era finalizada, os brasileiros movimentavam cerca de US$ 8 bilhões por mês em stablecoins denominadas em dólar — um canal ao qual Washington não faz objeção alguma." },
      { h: "O muro em Brasília" },
      { p: "Se a tarifa pretendia dividir o Brasil, conseguiu o oposto. A resposta do presidente Lula veio em um card nas redes sociais: \"É público, é de graça e vai continuar assim\" — sob a legenda de que a soberania não está em negociação. Mais reveladora ainda foi a reação do outro lado do espectro. Flávio Bolsonaro, que não é nenhum aliado do governo, recusou-se a colocar o Pix na mesa, propondo em vez disso um compromisso: o Brasil se obrigaria a jamais vincular o Pix a uma infraestrutura internacional de pagamentos rival da americana." },
      { p: "Essa concessão proposta é a frase mais reveladora de toda a disputa. Ela admite que o sistema doméstico é intocável — e identifica o que está realmente em jogo: a interoperabilidade. Não se os brasileiros pagam uns aos outros com um CPF e um QR code, mas se o método se conecta para fora, aos sistemas de outros países, formando corredores que contornam os trilhos americanos." },
      { p: "Essa infraestrutura rival, aliás, já tem nome e endereço. Chama-se Projeto Nexus, nasceu no BIS Innovation Hub, na Basilea, e foi desenhado para interconectar os sistemas nacionais de pagamentos instantâneos — o Pix, o UPI indiano, o PromptPay tailandês — em cerca de sessenta países, contornando tanto as bandeiras de cartões quanto o Swift. O BIS estima uma fase de testes a partir de 2027; o Banco Central do Brasil participa, por enquanto, como observador com intenção declarada. O que esclarece o que os 25% realmente precificam: não o que o Pix é, mas o que ele está prestes a se tornar." },
      { p: "A resposta formal do Itamaraty, protocolada em 1º de julho, acrescentou o argumento que Washington tem mais dificuldade de rebater: os Estados Unidos têm superávit comercial com o Brasil. Um processo da Seção 301, concebido para remediar práticas que oneram o comércio americano, é movido contra um país que compra dos Estados Unidos mais do que lhes vende. Até Paul Krugman, que não é defensor automático de Brasília, descartou o enquadramento da \"prática desleal\" com uma pergunta que fica no ar: desde quando é desleal um país oferecer aos próprios cidadãos uma forma melhor de pagar — ou uma empresa perder mercado para um concorrente com um produto melhor e mais barato?" },
      { h: "A resposta em dois atos" },
      { p: "A postura de Brasília virou em quarenta e oito horas. Na quarta-feira, era distensão deliberada: o vice-presidente Alckmin, depois de reunir-se com os setores atingidos — máquinas e equipamentos (US$ 3,3 bilhões expostos), madeira (81% das exportações para os EUA atingidas), borracha, alimentos, têxteis —, descartou explicitamente a retaliação: a ideia não é a reciprocidade, disse; os instrumentos existem e podem ser usados no momento oportuno. Os próprios setores pediram mais crédito no âmbito do programa Brasil Soberano, barreiras contra o desvio de importações chinesas e a continuidade da diplomacia — não contratarifas." },
      { p: "Na noite de quinta-feira, com o anúncio da segunda tarifa, o registro se inverteu. A nota do Planalto classificou as medidas como \"completamente arbitrárias e injustificadas\" e anunciou o início imediato dos trâmites da Lei de Reciprocidade — aprovada por unanimidade pelo Congresso — além do recurso à OMC. Quem conhece os dossiês, porém, lê com cautela: nos bastidores, a ativação é tratada como sinalização política, o rito exige análises setoriais e consultas públicas, e uma decisão efetiva dificilmente virá antes das eleições de outubro. Até porque a via da OMC é mais simbólica do que operacional: o órgão de apelação da organização foi desmontado justamente pela obstrução americana." },
      { p: "Por trás da contenção segue a aritmética: a participação americana nas exportações brasileiras caiu para 9,4% em 2026, ante o pico recente de 13,7%. Dolorosa, não existencial. E uma voz contrária merece registro: para Monica de Bolle, do Peterson Institute, o Brasil deveria responder de imediato com um imposto de exportação temporário — instrumento de 1977, compatível com as regras da OMC — sobre os bens em que detém poder de mercado, compensando os exportadores pelo Brasil Soberano. Sua leitura da lista de exceções é a mais afiada em circulação: o que Washington isenta — o café, de que o Brasil fornece cerca de um terço do mercado americano, o suco de laranja, a carne, o ferro-gusa, o nióbio, até componentes aeronáuticos — é o inventário das próprias vulnerabilidades. Um documento, dois mapas: o que ele tributa mede a competitividade brasileira; o que ele poupa mede a dependência americana." },
      { h: "A segunda tarifa e a terceira arquitetura" },
      { p: "A tarifa esperada para sexta-feira, 24, chegou pontual: 12,5%, resultado de uma segunda investigação sobre trabalho forçado, em substituição às sobretaxas de 10% da Seção 122 que expiram no fim do mês. O Brasil figura numa lista de 60 parceiros comerciais tarifados entre 10% e 12,5% — lista que inclui a União Europeia, o Japão, a Coreia do Sul, o Reino Unido e a Suíça: o dossiê deixou de ser uma história brasileira. Para o Brasil, cinco produtos acusados no período 2021-2025: alumínio, algodão, eletrônicos, baterias de lítio e tabaco." },
      { p: "Mas é nas isenções que a arquitetura se revela. Além dos 2.113 itens isentos para o Brasil e outros 46 países, treze economias receberam listas de isenção adicionais — a Argentina, 93 produtos a mais; a Malásia, 105; o Reino Unido, 49; a União Europeia, 43 — por proibirem as importações de trabalho forçado à maneira americana, terem se comprometido a fazê-lo em acordos recíprocos ou manterem regimes parciais de prevenção. O Brasil ficou no grupo cheio, e Sergio Vale (MB Associados) pôs números no diferencial: 3,4% da pauta tarifada — US$ 470 milhões, com a madeira processada para a construção civil americana, as pedras preciosas e as próteses médicas na primeira fila — enfrentará concorrentes com tratamento melhor. A desvantagem real, porém, não depende de lista nenhuma: são os 27,5 pontos percentuais estruturais de ser o único país do mundo a carregar uma tarifa própria de 25% somada à do trabalho forçado." },
      { p: "Aqui, o paradoxo que havíamos descrito tornou-se oficial. Na resposta formal, o governo brasileiro se defende citando exatamente o instrumento que o distingue: a lista suja, o cadastro público de empregadores flagrados com mão de obra em condições análogas à escravidão — e lembra que o Brasil ratificou 66 convenções da Organização Internacional do Trabalho, contra as 10 assinadas pelos Estados Unidos. Mas a lógica das isenções revela o que esta família tarifária de fato negocia: quem adota a arquitetura americana de enforcement — a proibição de importação na fronteira, no modelo da Seção 307 — ganha o desconto; a arquitetura brasileira, que pune os próprios produtores pela transparência de um cadastro público em vez de barrar as mercadorias alheias na alfândega, não vale nada em termos tarifários. Uma tarifa que vende um método enquanto pune outro: também nesta frente, a história nunca foi sobre produtos." },
      { h: "O mundo que Washington está lendo corretamente" },
      { p: "Descartar a tarifa como mero protecionismo em favor de Visa e Mastercard é não enxergar o que o Tesouro americano realmente vê. O secretário Scott Bessent descreveu a nova postura como a diplomacia econômica do século XXI, na qual o acesso ao dólar e à infraestrutura financeira americana já não é incondicional. Desse ponto de observação, o mapa global de pagamentos é genuinamente alarmante: a Rússia, cortada dos trilhos ocidentais, roda hoje sobre um sistema próprio de mensageria (SFPS) e uma rede própria de cartões (Mir). O CIPS chinês, rival transfronteiriço do Swift, registrou em março uma média diária recorde de 920 bilhões de yuans — cerca de US$ 130 bilhões, 20% acima do ano anterior —, com um recorde de 1,2 trilhão de yuans em um único dia em abril. O UPI indiano opera em nove países, e a NPCI o promove no exterior com o vocabulário da soberania: ajudar os países a cumprir seus próprios compromissos domésticos e a conduzir sua própria agenda nacional." },
      { p: "Cada um deles é um método em propagação. A tarifa sobre o Pix se entende melhor como uma tentativa de elevar o preço de adesão a essa propagação — um sinal dirigido menos a Brasília do que a cada capital que estuda o manual brasileiro." },
      { h: "A Europa já possui o hardware" },
      { p: "A leitura padrão do capítulo europeu desta história é a de que a Europa está esperando — esperando o euro digital para poder responder à pergunta que Aurore Lalucq fez ao Parlamento Europeu: o que acontece se uns Estados Unidos hostis cortarem o acesso à infraestrutura de pagamentos? \"Vocês não poderão dizer que não foram avisados\", disse ela aos colegas, instando a Europa a construir suas próprias alternativas — apelo ecoado por executivos de bancos britânicos, que discutem um rival doméstico às bandeiras de cartões, e pela própria Christine Lagarde." },
      { p: "Essa leitura está errada, e importa que esteja. À Europa não falta o trilho. As transferências instantâneas SEPA alcançam 41 países; por força do Regulamento de Pagamentos Instantâneos, desde janeiro de 2025 elas não podem custar mais do que uma transferência comum, e desde outubro de 2025 todo banco da zona do euro deve verificar gratuitamente o nome do beneficiário contra o IBAN antes de o dinheiro sair. Rápido, barato, verificado: o encanamento que o Brasil construiu em 2020, a Europa também construiu, em grande parte." },
      { p: "O que falta à Europa é tudo aquilo que o Pix acrescentou por cima do encanamento — e é aqui que a comparação vira diagnóstico. Primeiro, o diretório: o Pix substituiu o número da conta por uma chave — um CPF, um telefone, um e-mail — resolvida por meio de um único cadastro nacional operado pelo banco central, o DICT. A resposta europeia à chave existe, mas em fragmentos: o Wero, a carteira criada pelos bancos franceses, alemães e do Benelux na European Payments Initiative (que absorveu o iDeal holandês), usa o número de telefone; assim também o Bizum na Espanha, o MB Way em Portugal, o Blik na Polônia, o Swish na Suécia. Cinco cadastros, cinco marcas, e uma interoperabilidade transfronteiriça ainda em obras. Segundo, o mandato: o Banco Central do Brasil obrigou toda instituição a aderir a um único arranjo, gratuito para pessoas físicas, desde o primeiro dia. Nenhuma autoridade europeia impôs um arranjo único a seus bancos; o regulamento determina o trilho, não a rede que corre sobre ele. Terceiro, o caixa: o Pix deslocou os cartões no ponto de venda com um QR code. O SEPA Instant, com toda a sua velocidade, segue sendo em larga medida uma ferramenta de pessoa para pessoa; no caixa europeu, o duopólio americano continua cobrando o pedágio." },
      { p: "Os incumbents perceberam. O presidente da Mastercard para a Europa passou a argumentar que uma rede europeia de pagamentos já existe — e que ela é a própria Mastercard —, sustentando a tese com € 500 milhões investidos em infraestrutura europeia, um centro de tecnologia na Polônia previsto para 2027 e três data centers na França ao custo de € 250 milhões, além de uma parceria de pagamentos em tempo real com a chinesa UnionPay. Visa e Mastercard, com margens operacionais acima de 50%, já listam o tratamento \"preferencial\" dado aos sistemas domésticos de pagamento como risco de negócio em seus relatórios anuais. Quando um duopólio começa a escrever o seu método nas próprias divulgações de risco, o método está funcionando." },
      { h: "A Itália, enquanto isso, conduziu discretamente o experimento de controle" },
      { p: "O Satispay é o que a Europa tem de mais próximo de um Pix construído pela iniciativa privada: uma chave no lugar do IBAN, transferências gratuitas de pessoa para pessoa, uma rede proprietária deliberadamente traçada por fora dos circuitos de cartões. Por uma década, com cerca de meio bilhão de euros de capital de risco, comprou, um usuário de cada vez, o que o Banco Central do Brasil obteve por decreto. O placar conta a história: 6,5 milhões de usuários e 450 mil lojistas — cerca de um décimo dos adultos italianos, contra os 93% dos brasileiros no Pix —, receita de rede de € 46 milhões em 2024 contra um prejuízo líquido de € 47 milhões, com uma ressalva de ênfase dos auditores sobre a continuidade operacional pelo caminho. E quando a empresa finalmente pôs preço na própria rede, em abril de 2025, introduzindo uma taxa de 1% para os lojistas, alguns simplesmente saíram: parte da proposta de valor, descobriu-se, era o próprio subsídio." },
      { p: "Neste julho, o experimento chegou ao seu destino lógico. O Satispay lançou cartões de débito — na bandeira Mastercard. Incapaz de comprar a universalidade e incapaz de decretá-la, o desafiante anticartões passou a alugar a aceitação justamente do duopólio que se propunha a contornar, monetizando por planos de assinatura no modelo Revolut, enquanto o circuito próprio atende ao nicho doméstico. Seu fundador fala, sem ironia, em tornar-se um dia um banco dono de um circuito de pagamentos. O teorema não poderia ser demonstrado com mais clareza: sem um dono do arranjo detentor do poder de mandato, a universalidade não está à venda — apenas para alugar, e os locadores são só dois." },
      { h: "O que leva à conclusão incômoda" },
      { p: "O que leva à conclusão incômoda: nenhuma das três camadas ausentes exige o euro digital, prometido para 2029. Um diretório é governança. Um mandato é regulação. A aceitação pelos lojistas é desenho de arranjo. O Brasil não precisou de uma moeda digital de banco central para construir o Pix — precisou de um banco central disposto a atuar como dono do arranjo, e a década do Satispay prova que nenhum volume de capital privado o substitui. O que separa o cenário europeu de pagamentos da soberania não é uma defasagem tecnológica de três anos, mas um ato de vontade institucional." },
      { h: "O preço da soberania, dito com franqueza" },
      { p: "A fragmentação não é de graça, e os argumentos pela cautela merecem escuta leal. Um relatório patrocinado pela Swift estima que, mantidos os padrões atuais, a fragmentação financeira pode subtrair 2,6% do PIB global até 2030. O Conselho de Estabilidade Financeira alerta que a proliferação de sistemas nacionais provavelmente impedirá o G20 de cumprir as metas de remessas mais baratas e rápidas fixadas em 2020. E, como observa Josh Lipsky, do Atlantic Council, um mundo de sistemas regionais incompatíveis é um mundo com mais fraude e evasão de sanções mais fácil. Os países podem descobrir — assim concluía a análise original da The Economist — que o preço da soberania nos pagamentos é mais alto do que imaginam; e o mesmo pode valer para os Estados Unidos." },
      { p: "Mas note-se o que esse alerta implica para esta tarifa. Se o perigo é a fragmentação, a política americana racional seria manter os sistemas de pagamento do mundo interoperáveis com o seu. Uma tarifa punitiva sobre o método de pagamento público de maior sucesso já implantado faz o oposto: certifica que o método ameaça os incumbentes, eleva o valor percebido da independência e entrega a cada ministério da Fazenda um argumento de 25% para construir os próprios trilhos. A tarifa não retarda a fragmentação que teme. Ela a anuncia." },
      { h: "O método já está na mesa" },
      { p: "Retirado o vocabulário de guerra comercial, o que sobra é uma transação estranha. Os Estados Unidos penduraram uma etiqueta de 25% em um método — e, ao fazê-lo, o anunciaram a todas as jurisdições que observam. A resposta do Brasil à tarifa será negociada entre Brasília e Washington. A resposta da Europa, se ela quiser uma, não exige negociação alguma: os trilhos estão assentados, as transferências são instantâneas e gratuitas, a verificação do beneficiário está em operação. Cada componente do método que Washington acaba de declarar uma ameaça já está lá, desmontado, dentro do sistema europeu de pagamentos. Montá-lo não é um projeto de tecnologia com data de entrega. É uma decisão." },
      { p: "É isso que torna esta tarifa histórica para além dos seus 25%. Tarifas sobre produtos podem ser absorvidas, desviadas, esperadas. Uma tarifa sobre um método faz algo que nenhuma tarifa fez antes: certifica que o método funciona, o nomeia publicamente e desafia todos os demais a adotá-lo. O Brasil construiu o Pix em menos de dois anos com um banco central disposto a atuar como dono do arranjo. A pergunta que a tarifa deixa na mesa não é se o método pode atravessar o Atlântico — é qual lado do Atlântico vai decidir querê-lo primeiro." },
      { p: "Na BMG, lemos a política comercial pelo que ela revela, mais do que pelo que declara. Esta revela mais do que a maioria: a exportação brasileira mais pesadamente sancionada de 2026 não é uma commodity, e não pode ser retida na alfândega. Como fica o mapa do Brasil da sua organização quando a coisa mais valiosa a cruzar a fronteira é um método?" },
      { h: "Fontes" },
      { p: "Business Matching Global — inteligência de mercado e orquestração de negócios no corredor Europa–Brasil. Fontes: relatório da Seção 301 do USTR e avisos do Federal Register; Banco Central do Brasil; BIS Innovation Hub (Projeto Nexus); The Economist (via O Estado de S. Paulo); Folha de S.Paulo; O Tempo; Poder360; Bloomberg Línea (entrevista com Monica de Bolle, 22 de julho de 2026); CNN Brasil; notas do Planalto/Secom de 1º e 23 de julho de 2026; comunicados da Satispay e demonstrações de 2024 conforme reportados por Milano Finanza e Sky TG24." },
    ],
  },
};

export default function Pix() {
  const { lang } = useT();
  const article = getArticleBySlug("pix");
  const c = content[lang];
  const desc =
    lang === "it"
      ? "Il primo dazio USA su un metodo di pagamento: cosa dice l'inchiesta USTR sul Pix brasiliano e cosa significa per l'Europa."
      : lang === "pt"
      ? "A primeira tarifa dos EUA sobre um método de pagamento: o que diz a investigação da USTR sobre o Pix e o que significa para a Europa."
      : "The first US tariff on a payment method: what the USTR Section 301 report says about Pix and what it means for Europe.";
  useCanonical("/pix", {
    title: `${article?.title[lang] ?? "Pix"} — Business Matching Global`,
    description: desc,
    type: "article",
  });

  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <div className="flex items-center justify-between gap-4 mb-8">
        <Link
          to="/analysis"
          className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" />
          {c.back}
        </Link>
          <LangSwitcher />
        </div>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">
            {article?.title[lang]}
          </h1>
          <p className="text-xs text-foreground/70 mb-10 tabular-nums">{c.dateLabel ?? article?.date}</p>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {c.body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
        </article>
        <ShareBlock title={article?.title[lang] ?? "Pix"} />
        <AnalysisFooter />
      </div>
    </main>
  );
}