import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useEffect } from "react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";
import { AnalysisFooter } from "@/components/AnalysisFooter";
import { useCanonical } from "@/lib/useCanonical";
import { ShareBlock } from "@/components/ShareBlock";
import { LangSwitcher } from "@/components/LangSwitcher";

type Block = { h: string } | { p: string };

const TITLE = "Terre rare in Brasile: la geologia è assodata. Tutto il resto è conteso.";

const BACK = {
  it: "Torna alle analisi",
  en: "Back to analysis",
  pt: "Voltar às análises",
} as const;

const body: Block[] = [
  { p: `C'è un numero che dovrebbe togliere il sonno a chiunque si occupi di industria, difesa o transizione energetica: oggi il 100% delle terre rare pesanti che alimentano i magneti, i motori elettrici e i sistemi di difesa avanzati dell'Europa arriva, direttamente o indirettamente, dalla Cina. Non il 60%, non l'80%. La totalità.` },
  { p: `Pechino controlla circa il 60% dell'estrazione mondiale e la stragrande maggioranza della capacità di separazione e raffinazione. Anche quando il minerale viene scavato altrove, il collo di bottiglia tecnologico resta nelle mani di un unico attore — che ha ripetutamente dimostrato di saper usare le restrizioni all'export come leva geopolitica.` },
  { p: `In questo scenario, il Brasile detiene le seconde riserve dichiarate al mondo — circa 21 milioni di tonnellate — e lo Stato del Minas Gerais ospita quelli che potrebbero essere i giacimenti non sviluppati più strategici al di fuori della Cina. L'Unione Europea se n'è accorta: il Commissario per i Partenariati Internazionali Jozef Síkela si è recato in Brasile nel giugno 2026 nel quadro della strategia Global Gateway, e Bruxelles ha indicato alcuni progetti minerari critici brasiliani — tra cui il progetto di terre rare Colossus a Poços de Caldas — come prioritari ai sensi del Critical Raw Materials Act (CRMA).` },
  { p: `Fin qui, tutto rialzista. Ma chi presenta il Minas Gerais come una giurisdizione priva di rischi non sta raccontando tutta la storia. La geologia è straordinaria. Le licenze, i tribunali, il Congresso e le comunità sono tutt'altra faccenda — e per un investitore europeo, capire questa seconda metà è ciò che separa una tesi da un titolo di giornale.` },
  { p: `Ecco il quadro completo, ad agosto 2026.` },
  { h: `1. Perché questa geologia è davvero diversa` },
  { p: `Il vantaggio brasiliano non è il volume. È il tipo di giacimento.` },
  { p: `Il planalto vulcanico di Poços de Caldas — una caldera alcalina di circa 750 km² nel sud del Minas Gerais — ospita massicce formazioni di argille ad adsorbimento ionico (IAC): geologicamente, quasi un copia-incolla dei depositi della Cina meridionale, nel Jiangxi e nel Guangdong, che per decenni hanno fornito la quasi totalità delle terre rare pesanti mondiali. Due sviluppatori quotati in Australia dominano il distretto:` },
  { p: `Viridis Mining & Minerals — Progetto Colossus: 228,6 km² di concessioni, una risorsa di 493 Mt con tenore medio di ~2.508 ppm TREO e un paniere di terre rare magnetiche (NdPr, Dy, Tb) diverse volte più ricco dei tenori tipici operati in Cina. NPV ante imposte stimato intorno a 1,4 miliardi di USD; lettere di supporto da agenzie di credito all'esportazione tra cui Export Development Canada, Bpifrance ed Export Finance Australia; una JV downstream paritetica ("Viridion") con Ionic Rare Earths, pre-qualificata per un programma di finanziamento BNDES/FINEP da 5 miliardi di Reais.` },
  { p: `Meteoric Resources — Progetto Caldeira: 77 licenze su 193 km², una risorsa di scala provinciale superiore al miliardo di tonnellate, ampiamente descritta come il giacimento IAC a più alto tenore conosciuto al mondo. Un MoU di offtake con Ucore Rare Metals destinerà 3.000 t/anno di carbonato misto di terre rare al Louisiana Strategic Metals Complex negli USA — un impianto sostenuto dal Dipartimento della Difesa americano. Caldeira è inoltre l'unico progetto minerario incluso nella prima fase della Brazil Climate and Ecological Transformation Investment Platform (BIP) presentata al G20.` },
  { p: `Rispetto alla roccia dura, i depositi IAC offrono tre vantaggi strutturali: estrazione "free-dig" con normali escavatori (niente perforazioni, niente esplosivi, CAPEX e OPEX drasticamente inferiori); lisciviazione a temperatura ambiente con sali a basso costo invece del roasting ad alta temperatura con acidi concentrati; e nessuna diga di sterili — le argille esauste sono chimicamente inerti e possono essere reinserite nei pozzi, consentendo una riabilitazione progressiva.` },
  { p: `Sulla carta, è il percorso più efficiente in termini di capitale e a minor rischio ESG oggi esistente verso una fornitura occidentale di terre rare pesanti. Sulla carta.` },
  { h: `2. La battaglia delle licenze: cosa è successo davvero a Poços de Caldas` },
  { p: `Ed ecco la parte che raramente arriva nei deck per gli investitori.` },
  { p: `Nel novembre 2025, il Ministério Público Federal (MPF) ha inviato raccomandazioni urgenti agli organi ambientali del Minas Gerais (FEAM e il consiglio ambientale statale, Copam) chiedendo di ritirare dall'ordine del giorno i processi di licenza preliminare sia di Colossus sia di Caldeira. Le obiezioni del MPF non erano cavilli procedurali. Includevano:` },
  { p: `Una liminar giudiziaria presuntamente violata che vietava la concessione di nuovi diritti minerari nella regione — il MPF ha segnalato una possibile illegalità nel procedere tout court;` },
  { p: `L'assenza di consultazione libera, previa e informata delle comunità indigene e quilombola interessate dal Progetto Caldeira — requisito vincolante della Convenzione OIL 169, la cui omissione, nella lettura del MPF, impedisce l'avanzamento della licenza;` },
  { p: `La sovrapposizione con un'area protetta: parte di Caldeira ricade nell'APA Santuário Ecológico da Pedra Branca, a Caldas, dove la legge municipale vieta l'attività mineraria — e il consiglio gestore dell'APA aveva già respinto la richiesta;` },
  { p: `Il licenziamento frammentato: valutare ogni progetto singolarmente, ha argomentato il MPF, non può cogliere gli impatti cumulativi e sinergici di più miniere su un planalto sensibile di falde interconnesse e Mata Atlântica; ha chiesto una Valutazione Ambientale Strategica o Integrata per l'intero distretto;` },
  { p: `Un vizio di governance: il Copam e la sua Camera delle Attività Minerarie operavano con mandati scaduti e composizione non rinnovata da maggio 2025, minando la parità richiesta tra Stato e società civile.` },
  { p: `I progetti furono ritirati dall'ordine del giorno di novembre — poi, il 19 dicembre 2025, un giorno dopo l'invio di ulteriori raccomandazioni del MPF, la camera mineraria del Copam ha approvato comunque entrambe le licenze preliminari (LP), in una sessione virtuale di sette ore con più di cinquanta interventi della società civile iscritti a parlare. Colossus è passato all'unanimità; Caldeira con undici voti favorevoli.` },
  { p: `Le approvazioni non hanno chiuso il conflitto. Lo hanno spostato:` },
  { p: `Nel marzo 2026, la commissione speciale sulle terre rare della Câmara Municipal di Poços de Caldas ha iniziato a esaminare un laudo pericial trasmesso dal potere giudiziario del Minas — anche in relazione a una possibile estrazione irregolare di minerali;` },
  { p: `Nel maggio 2026, a Poços de Caldas si è svolta una Marcia contro l'estrazione di terre rare, seguita da un'udienza pubblica all'Assemblea Legislativa statale;` },
  { p: `L'opposizione locale non è marginale: comprende più di 900 produttori agricoli (caffè, latte, uva, rose), operatori turistici legati all'economia termale, consiglieri di entrambi i municipi ospitanti e ONG che fanno notare come alcuni pozzi previsti si trovino a poche centinaia di metri da un ospedale, un aeroporto e quartieri residenziali, su una zona di ricarica di falda con decine di sorgenti naturali.` },
  { p: `La lezione per l'investitore: le licenze preliminari esistono, ma sono licenze contestate, ottenute nonostante un'esplicita obiezione del MPF che richiama una liminar giudiziaria. Il passaggio dalla LP alla licenza di installazione (LI) — il documento che autorizza davvero la costruzione e sblocca la concessione mineraria — è il punto in cui tutte queste questioni irrisolte convergono. Chi modella le tempistiche dovrebbe trattare la catena delle licenze come un rischio contenzioso vivo, non come una formalità amministrativa.` },
  { h: `3. L'ombra nucleare` },
  { p: `C'è una ragione storica precisa per cui questa regione combatte così duramente.` },
  { p: `Poços de Caldas e la vicina Caldas ospitano la prima miniera di uranio del Brasile, operata dalla statale INB fino al 1995. Il sito ha lasciato circa 15 milioni di metri cubi di roccia esposta che genera drenaggio acido e circa 12.000 tonnellate di residui altamente radioattivi noti come "Torta II" — eredità del trattamento della monazite, stoccati in fusti e sili in degrado, in un impianto mai completamente dismesso. Alcuni dei nuovi pozzi IAC sono previsti entro circa due chilometri dal perimetro INB. Il timore locale — che il traffico pesante, le vibrazioni superficiali e l'alterazione dei flussi di falda possano compromettere fragili strutture di contenimento — qui non è un'astrazione. È memoria vissuta.` },
  { p: `La risposta regolatoria, finora, ha in realtà favorito gli sviluppatori: sulla base di decine di migliaia di campioni di perforazione, le autorità nucleari hanno riscontrato livelli di uranio e torio nelle argille mineralizzate ben al di sotto della soglia di esenzione radiologica, esentando formalmente i progetti dai protocolli di contenimento di grado nucleare. E il dossier è gestito attivamente: nel giugno 2026, la nuova Autoridade Nacional de Segurança Nuclear (ANSN) ha ispezionato le piante pilota di Meteoric e Viridis sul planalto, raccogliendo campioni per verificare la classificazione degli impianti. Le terre rare possono essere associate a uranio e torio, e ogni giacimento va valutato singolarmente — ma finora la scienza ha dato ragione alla tesi IAC.` },
  { p: `Meteoric, dal canto suo, ha accettato un protocollo municipale vincolante con 46 condizioni di salvaguardia ambientale — incluso l'allungamento di 30 km delle rotte dei camion per aggirare integralmente il perimetro INB, e obblighi di backfilling progressivo che limitano il numero di pozzi aperti contemporaneamente. Questo è il costo della licenza sociale in questo distretto. Mettetelo nei modelli.` },
  { h: `4. Il duello legislativo: chi governerà davvero i minerali critici brasiliani?` },
  { p: `Mentre la battaglia sulle licenze si gioca a livello statale, il Congresso federale si contende il libro delle regole — ed è questo, più della geologia, a determinare cosa il capitale estero potrà o non potrà fare.` },
  { p: `Il testo di testa: PL 2.780/2024. Approvato dalla Câmara dos Deputados a maggio 2026 e ora al Senato, il disegno di legge crea una Politica Nazionale per i Minerali Critici e Strategici: consiglio federale, registro dei progetti, criteri per aggiornare la lista dei minerali (rischio di approvvigionamento, dipendenza esterna, transizione energetica, difesa, rilevanza economica). Sul piano finanziario, prevede un fondo di garanzia da 2 miliardi di Reais e fino a 5 miliardi di Reais in crediti d'imposta federali tra il 2030 e il 2034, oltre ad aste di aree ANM e permessi di ricerca fino a dieci anni. La contropartita: le imprese verserebbero, per sei anni, lo 0,2% dei ricavi operativi lordi al fondo e lo 0,3% per ricerca e innovazione — in aggiunta alla CFEM del 2% e alla tassazione ordinaria. I giuristi che seguono il dossier apprezzano il fondo di garanzia (i progetti minerari early-stage in Brasile sono notoriamente difficili da finanziare) pur rilevando che il testo necessita ancora di aggiustamenti su punti sensibili. Le sue innovazioni istituzionali di maggior valore — certificazione della miniera a basso carbono, mineração urbana, tracciabilità della produzione — vanno ben oltre i minerali critici.` },
  { p: `Il rivale: PL 4.443/2025. Fermo alla Comissão de Infraestrutura del Senato, questo disegno concorrente crea un'architettura di policy diversa, definisce minerali prioritari e istituisce "zone di trasformazione minerale". I due testi si sovrappongono; il Senato dovrà fonderli o sceglierne uno. Organi con funzioni duplicate significherebbero costi più alti e decisioni contraddittorie — l'esatto contrario di ciò che serve agli investitori.` },
  { p: `La questione di governance centrale — come l'ha inquadrata Loyanna Menezes, CEO di Abi-Ackel Advogados e responsabile dell'area regolatoria dello studio, in una recente intervista a LexLegal — è delimitare le competenze tra il nuovo CIMCE (il Consiglio Nazionale per l'Industrializzazione dei Minerali Critici e Strategici) e l'ANM, l'agenzia mineraria: il Consiglio deve formulare la strategia e definire le priorità, mentre l'Agenzia deve conservare l'istruttoria tecnica, l'esecuzione regolatoria e la vigilanza. La sua ricetta per il quadro nel suo complesso: prevedibilità regolatoria combinata con incentivi condizionati all'industrializzazione, e sovranità protetta da criteri oggettivi di screening delle operazioni strategiche — non da restrizioni generiche al capitale straniero.` },
  { p: `Quest'ultimo punto conta, perché le restrizioni generiche sono esattamente ciò che propone una terza corrente legislativa. Disegni di legge dell'ala interventista del partito di governo vorrebbero rimettere lo Stato al comando esclusivo dei minerali critici — una proposta arriverebbe a vietare alle società a controllo estero di esplorare, estrarre, lavorare o vendere tali minerali. E un disegno di legge, presentato nel 2026, prende di mira questo distretto per nome: dichiarerebbe il planalto vulcanico del sud del Minas Gerais e di San Paolo — il massiccio alcalino di Poços de Caldas, definito per coordinate — Riserva Nazionale, sospendendo autorizzazioni di ricerca, concessioni minerarie, licenze ambientali e gare nell'area finché non siano soddisfatte condizioni speciali fissate dall'Esecutivo federale.` },
  { p: `Gli analisti ritengono improbabile che le clausole nazionaliste estreme passino in un Congresso centrista. Ma "improbabile" non è "impossibile", e la sola esistenza di un disegno di legge che congelerebbe l'esatto poligono in cui sorgono Colossus e Caldeira è un fattore di rischio che merita un posto in ogni memo di comitato investimenti — e una ragione per strutturarsi attraverso veicoli locali con attento ring-fencing.` },
  { h: `5. Cosa deve capire il capitale estero del sistema brasiliano` },
  { p: `Alcune caratteristiche strutturali del diritto minerario brasiliano che ogni consiglio di amministrazione europeo dovrebbe interiorizzare prima di redigere term sheet:` },
  { p: `Il minerale appartiene all'Unione, punto. La proprietà della superficie è giuridicamente separata dal sottosuolo. Gli investitori esteri partecipano tramite una società costituita in Brasile; il trasferimento dei diritti minerari richiede approvazione pubblica; fascia di frontiera, terre indigene e sostanze del settore nucleare seguono regimi speciali. Il capitale compra una partecipazione in un progetto — mai il giacimento.` },
  { p: `La catena delle licenze è sequenziale e indipendente. Autorizzazione di ricerca ANM → rapporto finale di esplorazione → concessione di lavra (con piano di sviluppo e piano di chiusura) — e, separatamente, la catena ambientale: licenza preliminare (LP) → licenza di installazione (LI) → licenza di esercizio (LO). Il titolo minerario non apre la miniera; licenze ambientali, uso dell'acqua e soppressione di vegetazione richiedono ciascuno approvazioni proprie. Il ritardo dell'organo pubblico non genera mai autorizzazione automatica. I progetti classificati come strategici possono ottenere un'analisi prioritaria tramite la licenza ambientale speciale — che accelera l'istruttoria, ma non elimina studi, consultazioni né prescrizioni.` },
  { p: `Lo stack delle royalty. Le terre rare sono soggette alla CFEM del 2% sui ricavi lordi; dove l'estrazione avviene su terreni privati — quasi sempre, in questi distretti agricoli — il proprietario superficiale ha diritto per legge a una royalty aggiuntiva pari al 50% della CFEM versata allo Stato. Aggiungete i previsti prelievi dello 0,2% + 0,3% del PL 2.780/2024, la tassazione societaria ordinaria e le ritenute sui dividendi rimpatriati, e l'onere sulla top line diventa un input centrale di ogni modello di cassa.` },
  { p: `Popoli indigeni e comunità tradizionali hanno una tutela costituzionale propria. L'articolo 231 richiede autorizzazione del Congresso, consultazione delle comunità interessate e partecipazione ai risultati della lavra per le terre indigene; una licenza amministrativa ordinaria non può aprire quelle aree. Oltre le terre formalmente demarcate, gli impatti su comunità tradizionali possono far scattare la consultazione libera, previa e informata — esattamente il terreno su cui il MPF ha contestato Caldeira. Gli errori qui sospendono i lavori e compromettono il financing.` },
  { p: `La due diligence sui titoli non perdona. Matricola, servitù, indennizzi, partecipazione del proprietario alla lavra e restrizioni territoriali vanno tutti verificati; la superficie può essere privata, pubblica o occupata da comunità. In questo distretto non è boilerplate — è il punto su cui i progetti sono già inciampati.` },
  { h: `6. Downstream: dove si concentrano la disputa — e il valore` },
  { p: `Estrarre il carbonato misto di terre rare è solo metà del percorso. Il beneficiamento rimuove le impurità e concentra gli elementi pagabili; poi arrivano i passaggi davvero difficili — separazione chimica, produzione di ossidi e metalli, fabbricazione di componenti, inclusi i magneti permanenti che finiscono in EV, turbine ed elettronica. È in quel tratto della catena che si concentrano la tecnologia, i posti di lavoro qualificati e la maggior parte del valore commerciale. Un Paese che esporta solo concentrato resta dipendente dal processamento fatto all'estero — e un minatore che vende MREC viene tipicamente pagato intorno al 70% del valore nominale degli ossidi contenuti, con noli e cariche di raffinazione implicitamente dedotti.` },
  { p: `Il Brasile lo sa, e agisce su tre livelli:` },
  { p: `Condizionalità di governo. Brasília è stata esplicita: gli incentivi devono essere vincolati all'industrializzazione su suolo brasiliano — credito agevolato e benefici fiscali legati a ricerca, tracciabilità, sviluppo tecnologico e obiettivi verificabili. È il criterio decisivo che si sta scrivendo nel nuovo marco legal: senza contropartite, gli incentivi aumenterebbero l'estrazione senza ampliare la capacità industriale brasiliana.` },
  { p: `MagBras. A Lagoa Santa, Minas Gerais, questa iniziativa sviluppa tecnologia nazionale per la fabbricazione di magneti permanenti di terre rare — il caso di riferimento su come orientare gli incentivi pubblici, e un segnale di dove lo Stato vuole far atterrare la catena.` },
  { p: `Viridion. La joint venture Viridis–Ionic sta costruendo capacità di separazione, raffinazione e riciclo a Poços de Caldas, pre-qualificata per il programma BNDES/FINEP da 5 miliardi di Reais — concepita per produrre un prodotto pre-raffinato destinato alle "gigafactory dei metalli" occidentali come il complesso Ucore in Louisiana.` },
  { p: `Per le imprese europee di ingegneria chimica, i costruttori di macchinari e gli istituti di ricerca, questo è il punto d'ingresso. Il Brasile non chiede all'Europa solo capitale; chiede l'unica cosa che la Cina non venderà mai: il know-how di separazione. La sovrapposizione tra ciò che Brasília esige e ciò che l'industria europea può offrire è l'argomento più forte a favore del corridoio.` },
  { h: `7. Cosa significa per gli attori europei` },
  { p: `Tirando i fili, l'opportunità europea oggi si presenta così — con la lente del rischio attaccata:` },
  { p: `1. Finanziamento e copertura politica — reali, ma acerbi. L'impegno Global Gateway e la priorità CRMA sono genuini e recenti. Ma a oggi, le discussioni di finanziamento europee restano in larga parte al livello delle intenzioni, senza grandi impegni formalizzati. Le ECA (EDC, Bpifrance, EFA) sono più avanti di Bruxelles. I first mover plasmeranno le condizioni; si porteranno anche il rischio della catena delle licenze descritto sopra.` },
  { p: `2. Offtake — l'asset scarso è il MREC allineato all'Occidente. Viridis ha scelto esplicitamente di trattare solo con acquirenti occidentali; il carbonato di Meteoric è già in parte impegnato verso una raffineria americana sostenuta dalla difesa. L'industria europea — automotive, eolico, difesa — compete per i volumi residui con controparti americane che si muovono più in fretta e pagano premi di policy. Aspettare la concessione della LI prima di negoziare significa negoziare dal fondo della fila.` },
  { p: `3. Trasferimento tecnologico — la porta più larga, e la meno affollata. La direzione regolatoria è inequivocabile: incentivi condizionati all'industrializzazione, screening invece di restrizioni generiche, contenuto nazionale nella catena di lavorazione. Un fornitore europeo di tecnologia di separazione, strumentazione analitica o know-how magnetico entra in questo mercato spingendo una porta aperta — e, a differenza dell'investitore puramente finanziario, è largamente al riparo dal rischio di coda nazionalista, perché è precisamente ciò che ogni versione del marco legal vuole in più.` },
  { p: `4. Strutturarsi per la politica. Veicoli di diritto brasiliano, partner locali, due diligence accurata sui titoli, conformità OIL 169 incorporata dal primo giorno, e protocolli con le comunità trattati come costo del fare impresa, non come imboscata. Il precedente Meteoric — 46 condizioni, 30 km di strade deviate — è il template realistico.` },
  { h: `In sintesi` },
  { p: `Il Minas Gerais offre ancora una delle proposizioni più asimmetriche dei minerali critici globali: geologia di classe mondiale ad argille ioniche, un profilo ESG strutturalmente superiore in fase estrattiva, denaro delle ECA già sul tavolo, e un'UE che finalmente si è presentata di persona.` },
  { p: `Ma la versione onesta della tesi ha tre clausole, non una. La geologia è assodata. Le licenze sono concesse ma contestate — dai procuratori federali, dai tribunali, da due consigli comunali e da novecento agricoltori con la memoria lunga su cosa l'industria nucleare ha lasciato dietro di sé. E il libro delle regole viene riscritto in tempo reale, in un Senato che soppesa due quadri sovrapposti mentre una corrente nazionalista propone di congelare per decreto proprio questo planalto.` },
  { p: `Per chi prende decisioni di investimento o di policy, la domanda non è più se il Brasile diventerà un pilastro della filiera atlantica delle terre rare. È chi la governerà, a quali condizioni, e chi sarà nella stanza quando quelle condizioni verranno scritte. In questo momento, quella stanza è ancora in fase di arredamento. È quella — non l'argilla — la vera finestra.` },
  { h: `Nota per il lettore non specialista: cosa sono davvero le terre rare` },
  { p: `Diciassette elementi, un nome fuorviente. Le terre rare (REE) sono un gruppo di 17 metalli chimicamente affini — i quindici lantanidi più scandio e ittrio. Il nome è un incidente storico: rare non lo sono affatto. Il cerio è più abbondante del rame nella crosta terrestre; persino le terre rare più scarse sono più comuni dell'oro. Ciò che è genuinamente raro è trovarle concentrate abbastanza da poterle estrarre economicamente e — soprattutto — separarle l'una dall'altra. Poiché i loro atomi sono quasi identici per dimensione e carica, si presentano mescolate negli stessi minerali e resistono ai metodi ordinari di separazione chimica. La "rarità" non è mai stata nel sottosuolo: è sempre stata nella chimica.` },
  { p: `La famiglia ha due rami — e non sono uguali. Le terre rare "leggere" (lantanio, cerio, neodimio, praseodimio) sono relativamente abbondanti ed estratte in diversi Paesi. Le "pesanti" (disprosio, terbio e altre) sono molto più scarse in concentrazioni sfruttabili, valgono molto di più e storicamente sono arrivate quasi per intero dai depositi di argille ioniche della Cina meridionale — ed è precisamente per questo che le argille geologicamente analoghe di Poços de Caldas contano così tanto.` },
  { p: `A cosa servono. Le terre rare sono gli abilitatori invisibili della tecnologia moderna. L'uso più strategico sono i magneti permanenti (neodimio-ferro-boro, "temprati" con disprosio e terbio per le alte temperature): i magneti più potenti conosciuti, insostituibili nei motori dei veicoli elettrici, nei generatori eolici, nei droni, nella robotica, negli hard disk e nei componenti degli smartphone. Oltre ai magneti, le terre rare stanno negli attuatori dei caccia, nei sistemi di guida missilistica, in radar e sonar, nei catalizzatori auto e di raffineria, nella lucidatura del vetro, nei laser, nell'imaging medicale e nei fosfori che illuminano gli schermi. Un singolo EV può contenere un chilo o più di magneti di terre rare; un F-35 ne contiene oltre 400 kg in materiali. Non esiste transizione energetica, industria della difesa moderna o economia digitale senza di esse — e per la maggior parte di questi usi non esiste un sostituto commercialmente viabile.` },
  { p: `Perché l'estrazione è un problema. L'estrazione convenzionale di terre rare ha una delle impronte ambientali più pesanti dell'industria mineraria, per tre ragioni. Primo, la radioattività: nella maggior parte dei depositi in roccia dura le terre rare convivono con uranio e torio, per cui estrazione e lavorazione generano residui radioattivi da confinare per decenni — l'eredità "Torta II" di Poços de Caldas è esattamente questo problema, ereditato dal trattamento della monazite. Secondo, la chimica aggressiva: "craccare" il minerale richiede tipicamente roasting ad alta temperatura con acido solforico o cloridrico concentrato, producendo gas tossici ed enormi volumi di reflui acidi e salini; il distretto di Baotou, in Cina, è circondato da laghi di sterili diventati l'immagine da manuale del costo di questa industria. Terzo, l'intensità della separazione: trasformare il concentrato misto in singoli ossidi puri richiede centinaia di stadi sequenziali di estrazione a solvente, ognuno dei quali consuma reagenti e genera effluenti. Nell'estrazione storica delle argille ioniche cinesi è emerso un quarto problema: il leaching in-situ, con solfato di ammonio iniettato direttamente nei versanti, ha contaminato le falde e fatto franare colline in intere contee prima di essere limitato.` },
  { p: `È in questo contesto che i progetti brasiliani ad argille ioniche avanzano la loro tesi centrale: argille superficiali a radioattività trascurabile, lisciviate in vasca a temperatura ambiente con sali riciclabili, niente roasting acido, niente dighe di sterili, backfilling progressivo dei pozzi. Se la tesi regge su scala industriale, sarebbe il percorso di produzione primaria di terre rare più pulito mai operato. Se regga davvero — sotto lo scrutinio regolatorio brasiliano, sopra le falde, accanto a un sito dell'eredità nucleare — è, come ha argomentato questo articolo, esattamente la posta in gioco della battaglia sulle licenze a Poços de Caldas.` },
  { p: `I dati di progetto citati derivano da comunicazioni societarie e studi a livello di pre-fattibilità e sono soggetti a revisione. I riferimenti legislativi riflettono lo stato dei procedimenti come pubblicamente riportato ad agosto 2026. Questo contributo ha finalità divulgative e non costituisce consulenza finanziaria, di investimento o legale.` },
];

export default function RareIT() {
  const { lang } = useT();
  const article = getArticleBySlug("rare_it");
  const desc =
    "Il Brasile detiene le seconde riserve di terre rare al mondo, ma le licenze a Poços de Caldas sono contestate e il quadro normativo è in riscrittura. Il quadro completo di agosto 2026 per investitori europei.";
  useCanonical("/rare_it", {
    title: "Terre rare in Brasile: la geologia è assodata. Tutto il resto è conteso.",
    description: desc,
    type: "article",
  });


  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <div className="flex items-center justify-between gap-4 mb-8">
          <Link
            to="/analysis"
            className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            {BACK["it"]}
          </Link>
          <LangSwitcher to="/rare_it" />
        </div>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">
            {TITLE}
          </h1>
          <p className="text-xs text-foreground/70 mb-2">#CustoBrasil — Business Matching Global</p>
          <p className="text-xs text-foreground/70 mb-10 tabular-nums">{article?.date}</p>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
          <ShareBlock title={TITLE} />
        </article>
        <AnalysisFooter />
      </div>
    </main>
  );
}
