import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useT } from "@/lib/i18n";
import { getArticleBySlug } from "@/lib/analysis";

const content = {
  it: {
    back: "Torna alle analisi",
    body: [
      { h: "Due cantieri, un crimine, due architetture" },
      { p: "Cinquantacinque anni di lavoro domestico non retribuito. L'accordo: un appartamento arredato e circa 8.500 euro in contanti." },
      { p: "Nel luglio 2026, gli ispettori del lavoro di Fortaleza hanno liberato una donna di 62 anni tenuta dalla stessa famiglia attraverso tre generazioni — dal 1971 — come lavoratrice domestica non retribuita. Nessun salario, nessuna ferie, nessuna alfabetizzazione, nessun contatto con il mondo esterno. Sua madre aveva servito la stessa famiglia prima di lei. Il caso è emerso nell'unico modo in cui questi casi emergono in Brasile: una segnalazione anonima." },
      { p: "I media europei leggeranno questa notizia come sempre leggono il Brasile: come conferma di una vergogna lontana e tropicale." },
      { p: "Sei settimane prima, nel cuore di Milano." },
      { p: "Nel maggio 2026, la procura ha posto Caddell Construction — il colosso dell'Alabama che sta costruendo il nuovo Consolato Generale degli Stati Uniti in Piazzale Accursio, appalto da 200 milioni di dollari — sotto controllo giudiziario d'urgenza per caporalato. L'indagine descrive ciò che i magistrati stessi chiamano \"para-schiavismo\": centinaia di lavoratori indiani reclutati tramite un'agenzia a Nuova Delhi, ciascuno con una tassa di 5.000 euro per il privilegio; salari reali di 1–2 euro l'ora dissimulati con un doppio-cedolino tra India e Italia; dodici ore al giorno, sei giorni a settimana, nessun riposo, nessuna malattia. Nei picchi, 450–500 lavoratori. Due dirigenti in custodia cautelare — uno arrestato all'aeroporto di Bergamo mentre tentava di lasciare il Paese. Il giudice per le indagini preliminari ha scritto che lo sfruttamento era \"prassi aziendale.\" La procura chiede ora permessi di soggiorno umanitari per almeno un centinaio di lavoratori che collaborano." },
      { p: "Stesso crimine. Stesso semestre. Due emisferi. La storia non è che il Brasile ha un problema di schiavitù e l'Europa no. La storia è cosa succede dopo che il crimine viene scoperto — perché lì i due sistemi divergono completamente." },
      { h: "Brasile: l'architettura che l'Europa non sa di avere bisogno" },
      { p: "I dati brasiliani 2025 sull'enforcement, pubblicati dal Ministero del Lavoro nel gennaio 2026, mostrano un sistema in movimento:" },
      { p: "2.772 lavoratori liberati in 1.594 operazioni ispettive — +38% sul 2024, terza cifra annuale più alta dall'inizio delle ispezioni sistematiche nel 1995. Oltre 68.000 persone liberate in trent'anni." },
      { p: "Per la prima volta in assoluto, i salvataggi urbani (68%) hanno superato quelli rurali. Lo stereotipo del lavoro schiavo come fenomeno di fazenda remota è oggi statisticamente obsoleto." },
      { p: "Il lavoro domestico è diventato priorità dichiarata: 122 ispezioni mirate nel 2025 contro 22 nel 2024 — un aumento di cinque volte." },
      { p: "L'83% dei liberati si autodichiara nero. La continuità coloniale non è retorica; è il profilo demografico del carico di lavoro." },
      { p: "Al centro di questa architettura c'è uno strumento che non ha equivalenti in Europa: il Cadastro de Empregadores — la \"lista suja.\" Un registro pubblico, gratuito, aggiornato semestralmente, di datori di lavoro — aziende e persone fisiche — con condanne amministrative definitive per aver sottoposto lavoratori a condizioni analoghe alla schiavitù. I nomi restano pubblicati per due anni. La Corte Suprema brasiliana ne ha confermato la costituzionalità nel 2020 (ADPF 509) come trasparenza attiva, non sanzione. Banche e retailer brasiliani la usano già nello screening del credito e dei fornitori." },
      { p: "L'aggiornamento di aprile 2026 dice dove va l'enforcement: dei 169 nuovi ingressi, la categoria più grande è stata quella dei servizi domestici (23 inclusioni) — davanti all'allevamento bovino e al caffè. Lo stesso aggiornamento ha incluso BYD, dopo un accordo da R$40 milioni con il MPT sulle condizioni del cantiere della fabbrica in Bahia. Il meccanismo raggiunge sia le famiglie di Fortaleza sia i più grandi player industriali del pianeta." },
      { p: "Il sistema ha un collo di bottiglia costituzionale — l'articolo 5 rende inviolabile la casa, per questo ogni salvataggio domestico parte da una denuncia anonima, e per questo il record 2025 di 4.516 denunce contano quanto le ispezioni. E ha un rischio di governance da nominare con onestà: interventi ministeriali che hanno scavalcato gli auditor su inclusioni nella lista suja — soprattutto il caso JBS Aves — hanno provocato proteste del corpo ispettivo a inizio 2026. Lo strumento è potente; la sua indipendenza è contestata. Le controparti serie monitorano entrambi." },
      { h: "Italia: rimedio senza registro" },
      { p: "Guardiamo ora la risposta italiana — perché l'Italia ha uno strumento, e ne ha uno che al Brasile manca." },
      { p: "Oltre alla cornice penale anti-caporalato (Legge 199/2016, art. 603-bis c.p.), la Procura di Milano ha sperimentato qualcosa di più chirurgico: porre società sane e non indagate sotto amministrazione giudiziaria — misura preventiva mutuata dal codice antimafia (art. 34, d.lgs. 159/2011) — per aver colposamente agevolato lo sfruttamento lungo la catena dei subappalti. Il settore moda mostra il modello su scala. Alviero Martini, Armani Operations, Manufactures Dior, Valentino, Loro Piana, Tod's: case di lusso le cui filiere terminavano in laboratori dove una giacca in cashmere venduta a 3.000 euro veniva assemblata per circa 100 euro. A febbraio 2026 la Procura di Prato ha esteso il modello oltre Milano con Piazza Italia — lavoratori sotto i 4 euro l'ora, sette giorni su sette, margini stimati al 300% sul costo di produzione. A dicembre 2025 altri tredici marchi erano nei fascicoli milanesi. Il caso Caddell in Piazzale Accursio appartiene alla stessa filosofia di enforcement: spostare la responsabilità in alto nella catena, sul committente." },
      { p: "E lo strumento corregge. Loro Piana è entrata in amministrazione giudiziaria nel luglio 2025 ed è uscita nell'aprile 2026, con il tribunale che ha definito \"virtuoso\" il riordino della filiera — governance rafforzata, audit indipendenti, fornitori non conformi risolti. Nove mesi dal sequestro al benchmark." },
      { p: "Ma ecco l'asimmetria: quando il rimedio finisce, non c'è nessun registro. Nessuna lista pubblica dove una banca, un general contractor o un ufficio acquisti possa verificare se un'azienda è stata giudicata responsabile, o abbia colposamente agevolato, lo sfruttamento del lavoro. L'unico strumento pubblico permanente in Italia è la Rete del lavoro agricolo di qualità — una white list volontaria, limitata all'agricoltura." },
      { p: "Leggete il contrasto con precisione. Il Brasile pubblica i nomi dei colpevoli, due volte l'anno, in ogni settore, famiglie incluse, validato dalla Corte Suprema — uno strumento di memoria che informa tutto il mercato ma non corregge nessuno. Milano sequestra e riabilita un committente alla volta — uno strumento di rimedio che corregge l'azienda ma non lascia traccia consultabile per il mercato. Due strumenti sofisticati, perfettamente complementari. Nessuna delle due giurisdizioni ha adottato quello dell'altra." },
      { p: "E la meccanica dello sfruttamento era quasi identica nei due casi: debito di reclutamento (5.000 euro a Nuova Delhi; aliciamento in Maranhão), dipendenza abitativa (alloggi aziendali fuori Milano; alojamentos nei cantieri brasiliani), vulnerabilità linguistica, dissimulazione salariale. Ciò che l'articolo 149 del Codice Penale brasiliano chiama \"condizione analoga alla schiavitù,\" la Procura di Milano chiama \"para-schiavismo.\" Stesso fenomeno. Architettura istituzionale di risposta differente." },
      { h: "La traduzione business" },
      { p: "Con la CSDDD modificata (post-Omnibus, Direttiva 2026/470), la due diligence obbligatoria UE si applica ora solo ai gruppi più grandi — oltre 5.000 dipendenti, 1,5 miliardi di euro di fatturato, compliance dal 2029. Ma quei gruppi comprano caffè, carne, minerali e prodotti manifatturieri brasiliani, e la direttiva elenca esplicitamente il livello di enforcement in una data geografia tra i fattori di rischio da pesare. I loro obblighi ricadranno contrattualmente su ogni importatore europeo di media dimensione nelle loro catene." },
      { p: "Milano ha appena dimostrato che la geografia del rischio di lavoro forzato include la Lombardia. Il Brasile dimostra, due volte l'anno, come si presenta uno strumento di trasparenza per quel rischio." },
      { p: "La lista suja — pubblica, gratuita, aggiornata ogni sei mesi — è lo strumento di screening della supply-chain più economico disponibile per il mercato brasiliano. In quindici anni di lavoro nei corridoi, non ho ancora incontrato un importatore europeo che l'abbia consultata prima di firmare un contratto di fornitura." },
      { p: "Un cantiere del governo USA a Milano è andato avanti con lavoro a 2 euro l'ora per due anni prima che qualcuno intervenisse. Il Brasile pubblica un registro esattamente di questa condotta, due volte l'anno, a costo zero di consultazione. Con quale dei due sistemi preferirebbe lavorare il vostro ufficio compliance — e perché l'Europa ancora non ce l'ha?" },
    ],
  },
  en: {
    back: "Back to analysis",
    body: [
      { h: "Two Construction Sites, One Crime, Two Architectures" },
      { p: "Fifty-five years of unpaid domestic work. The settlement: a furnished apartment and roughly €8,500 in cash." },
      { p: "In July 2026, labor inspectors in Fortaleza freed a 62-year-old woman held by the same family across three generations — since 1971 — as an unpaid domestic worker. No salary, no holidays, no literacy, no contact with the outside world. Her mother had served the same family before her. The case surfaced the only way these cases ever surface in Brazil: an anonymous tip." },
      { p: "European media will read this the way European media always reads Brazil: as confirmation of a distant, tropical shame." },
      { p: "Six weeks earlier, in the heart of Milan." },
      { p: "In May 2026, prosecutors placed Caddell Construction — the Alabama-based giant building the new United States Consulate General at Piazzale Accursio, a $200 million contract — under emergency judicial control for caporalato. The investigation describes what magistrates themselves call \"para-slavery\": hundreds of Indian workers recruited through an agency in New Delhi, each paying a €5,000 fee for the privilege; real wages of €1–2 per hour concealed behind a double-payslip mechanism between India and Italy; twelve-hour days, six days a week, no rest, no sick leave. At peak, 450–500 workers. Two managers are in pre-trial detention — one arrested at Bergamo airport while attempting to leave the country. The investigating judge wrote that exploitation was \"company custom.\" Prosecutors are now requesting humanitarian residence permits for at least a hundred workers cooperating with the investigation." },
      { p: "Same crime. Same semester. Two hemispheres. The story is not that Brazil has a slavery problem and Europe doesn't. The story is what happens after the crime is discovered — because there, the two systems diverge completely." },
      { h: "Brazil: the architecture Europe doesn't know it needs" },
      { p: "Brazil's 2025 enforcement data, released by the Ministry of Labor in January 2026, shows a system in motion:" },
      { p: "2,772 workers rescued in 1,594 inspection operations — up 38% on 2024, the third-highest annual figure since systematic inspections began in 1995. Over 68,000 people rescued in thirty years." },
      { p: "For the first time ever, urban rescues (68%) exceeded rural ones. The stereotype of slave labor as a remote-fazenda phenomenon is now statistically obsolete." },
      { p: "Domestic work became a declared enforcement priority: 122 targeted inspections in 2025 against 22 in 2024 — a fivefold increase." },
      { p: "83% of those rescued self-declare as Black. The colonial continuity is not rhetoric; it is the demographic profile of the caseload." },
      { p: "At the center of this architecture sits an instrument with no equivalent anywhere in Europe: the Cadastro de Empregadores — the \"lista suja.\" A public, free, semi-annually updated register of employers — companies and private individuals — with final administrative convictions for submitting workers to conditions analogous to slavery. Names stay published for two years. Brazil's Supreme Court confirmed its constitutionality in 2020 (ADPF 509) as active transparency, not sanction. Brazilian banks and retailers already use it in credit and supplier screening." },
      { p: "The April 2026 update tells you where enforcement is heading: of 169 new entries, the single largest category was domestic services (23 inclusions) — ahead of cattle ranching and coffee. The same update included BYD, following a R$40 million settlement with labor prosecutors over conditions at its Bahia factory construction site. The mechanism reaches households in Fortaleza and the largest industrial players on the planet alike." },
      { p: "The system has a constitutional bottleneck — Article 5 makes the home inviolable, which is why every domestic rescue starts with an anonymous complaint, and why 2025's record 4,516 hotline denunciations matter as much as the inspections. And it has governance risk worth naming honestly: ministerial interventions overriding auditors on lista suja inclusions — the JBS Aves case above all — triggered protests from the inspection corps in early 2026. The tool is powerful; its independence is contested. Serious counterparties monitor both." },
      { h: "Italy: remediation without a register" },
      { p: "Now look at the Italian response — because Italy does have an instrument, and it is one Brazil lacks." },
      { p: "Beyond the criminal anti-caporalato framework (Law 199/2016, Article 603-bis of the Criminal Code), Milan prosecutors have pioneered something more surgical: placing healthy, non-indicted companies under judicial administration — a preventive measure borrowed from the anti-mafia code (Article 34, Legislative Decree 159/2011) — for negligently facilitating exploitation down their subcontracting chains. The fashion sector shows the model at scale. Alviero Martini, Armani Operations, Manufactures Dior, Valentino, Loro Piana, Tod's: luxury houses whose supply chains ended in workshops where a cashmere jacket retailing at €3,000 was assembled for roughly €100. In February 2026, Prato prosecutors extended the model beyond Milan with Piazza Italia — workers at under €4 per hour, seven days a week, margins estimated at 300% over production cost. By December 2025, thirteen more brands sat in the Milan files. The Caddell case at Piazzale Accursio belongs to the same enforcement philosophy: move liability up the chain, to the principal." },
      { p: "And the instrument corrects. Loro Piana entered judicial administration in July 2025 and exited in April 2026, with the court calling its supply-chain overhaul — reinforced governance, independent audits, terminated non-compliant suppliers — a \"virtuous\" path. Nine months from seizure to benchmark." },
      { p: "But here is the asymmetry: when the remediation ends, there is no register. No public list where a bank, a general contractor or a procurement officer can check whether a company was found responsible for, or negligently facilitated, labor exploitation. Italy's only standing public instrument is the Rete del lavoro agricolo di qualità — a voluntary white list, limited to agriculture." },
      { p: "So read the contrast precisely. Brazil publishes the names of the guilty, twice a year, across every sector, households included, validated by its Supreme Court — an instrument of memory that informs the entire market but corrects no one. Milan seizes and rehabilitates one principal at a time — an instrument of remediation that corrects the company but leaves no consultable trace for the market. Two sophisticated tools, perfectly complementary. Neither jurisdiction has adopted the other's." },
      { p: "And the mechanics of exploitation were nearly identical in both cases: recruitment debt (€5,000 in New Delhi; aliciamento in Maranhão), housing dependency (company residences outside Milan; alojamentos on Brazilian sites), linguistic vulnerability, wage concealment. What Article 149 of the Brazilian Criminal Code calls \"condition analogous to slavery,\" the Milan prosecutors call \"para-schiavismo.\" Same phenomenon. Different institutional response architecture." },
      { h: "The business translation" },
      { p: "Under the amended CSDDD (post-Omnibus, Directive 2026/470), mandatory EU due diligence now applies only to the largest groups — 5,000+ employees, €1.5 billion turnover, compliance from 2029. But those groups buy Brazilian coffee, beef, minerals and manufactured goods, and the directive explicitly lists the level of law enforcement in a given geography among the risk factors to weigh. Their obligations will cascade contractually onto every mid-sized European importer in their chains." },
      { p: "Milan just demonstrated that the geography of forced-labor risk includes Lombardy. Brazil demonstrates, twice a year, what a transparency instrument for that risk looks like." },
      { p: "The lista suja — public, free, updated every six months — is the cheapest supply-chain screening instrument available for the Brazilian market. In fifteen years of corridor work, I have yet to meet a European importer who consulted it before signing a supply contract." },
      { p: "A U.S. government construction site in Milan ran on €2-an-hour labor for two years before anyone intervened. Brazil publishes a register of exactly this conduct, twice a year, at zero cost to consult. Which of the two systems would your compliance department rather work with — and why does Europe still not have one?" },
    ],
  },
  pt: {
    back: "Voltar às análises",
    body: [
      { h: "Dois canteiros, um crime, duas arquiteturas" },
      { p: "Cinquenta e cinco anos de trabalho doméstico não remunerado. O acordo: um apartamento mobiliado e cerca de 8.500 euros em dinheiro." },
      { p: "Em julho de 2026, auditores-fiscais do trabalho em Fortaleza libertaram uma mulher de 62 anos mantida pela mesma família ao longo de três gerações — desde 1971 — como trabalhadora doméstica não remunerada. Sem salário, sem férias, sem alfabetização, sem contato com o mundo exterior. Sua mãe havia servido a mesma família antes dela. O caso veio à tona da única forma em que esses casos vêm à tona no Brasil: uma denúncia anônima." },
      { p: "A mídia europeia lerá isso como sempre lê o Brasil: como confirmação de uma vergonha distante e tropical." },
      { p: "Seis semanas antes, no coração de Milão." },
      { p: "Em maio de 2026, a Procuradoria colocou a Caddell Construction — o gigante do Alabama que constrói o novo Consulado Geral dos Estados Unidos na Piazzale Accursio, contrato de US$ 200 milhões — sob controle judicial de urgência por caporalato. A investigação descreve o que os próprios magistrados chamam de \"para-escravidão\": centenas de trabalhadores indianos recrutados por uma agência em Nova Delhi, cada um pagando 5.000 euros pelo privilégio; salários reais de 1 a 2 euros por hora ocultos por um duplo contracheque entre Índia e Itália; doze horas por dia, seis dias por semana, sem descanso, sem licença médica. No pico, 450–500 trabalhadores. Dois gestores estão em prisão preventiva — um preso no aeroporto de Bergamo tentando deixar o país. O juiz de instrução escreveu que a exploração era \"costume da empresa.\" A Procuradoria agora pede vistos humanitários para pelo menos cem trabalhadores que cooperam com a investigação." },
      { p: "Mesmo crime. Mesmo semestre. Dois hemisférios. A história não é que o Brasil tem um problema de escravidão e a Europa não. A história é o que acontece depois que o crime é descoberto — porque aí os dois sistemas divergem completamente." },
      { h: "Brasil: a arquitetura que a Europa não sabe que precisa" },
      { p: "Os dados brasileiros de fiscalização de 2025, divulgados pelo Ministério do Trabalho em janeiro de 2026, mostram um sistema em movimento:" },
      { p: "2.772 trabalhadores resgatados em 1.594 operações de fiscalização — alta de 38% sobre 2024, terceiro maior número anual desde o início das fiscalizações sistemáticas em 1995. Mais de 68.000 pessoas resgatadas em trinta anos." },
      { p: "Pela primeira vez, os resgates urbanos (68%) superaram os rurais. O estereótipo do trabalho escravo como fenômeno de fazenda remota é hoje estatisticamente obsoleto." },
      { p: "O trabalho doméstico tornou-se prioridade declarada de fiscalização: 122 inspeções direcionadas em 2025 contra 22 em 2024 — aumento de cinco vezes." },
      { p: "83% dos resgatados autodeclaram-se pretos ou pardos. A continuidade colonial não é retórica; é o perfil demográfico da carga de casos." },
      { p: "No centro dessa arquitetura está um instrumento sem equivalente na Europa: o Cadastro de Empregadores — a \"lista suja.\" Um registro público, gratuito, atualizado semestralmente, de empregadores — empresas e pessoas físicas — com condenações administrativas definitivas por submeter trabalhadores a condições análogas à escravidão. Os nomes permanecem publicados por dois anos. O STF confirmou sua constitucionalidade em 2020 (ADPF 509) como transparência ativa, não sanção. Bancos e varejistas brasileiros já a usam em análise de crédito e de fornecedores." },
      { p: "A atualização de abril de 2026 mostra para onde vai a fiscalização: das 169 novas inclusões, a maior categoria foi serviços domésticos (23 inclusões) — à frente da pecuária e do café. A mesma atualização incluiu a BYD, após um TAC de R$ 40 milhões com o MPT sobre as condições no canteiro da fábrica na Bahia. O mecanismo alcança tanto famílias em Fortaleza quanto os maiores players industriais do planeta." },
      { p: "O sistema tem um gargalo constitucional — o artigo 5º torna o domicílio inviolável, e por isso todo resgate doméstico começa por uma denúncia anônima, e por isso o recorde de 4.516 denúncias de 2025 pesa tanto quanto as fiscalizações. E tem um risco de governança que precisa ser nomeado com honestidade: intervenções ministeriais que passaram por cima dos auditores em inclusões na lista suja — o caso JBS Aves acima de tudo — provocaram protestos do corpo de fiscalização no início de 2026. O instrumento é potente; sua independência é contestada. Contrapartes sérias monitoram ambos." },
      { h: "Itália: remediação sem registro" },
      { p: "Olhe agora a resposta italiana — porque a Itália tem um instrumento, e é um que falta ao Brasil." },
      { p: "Além do marco penal anti-caporalato (Lei 199/2016, art. 603-bis do Código Penal), a Procuradoria de Milão foi pioneira em algo mais cirúrgico: colocar empresas saudáveis e não indiciadas sob administração judicial — medida preventiva emprestada do código antimáfia (art. 34, d.lgs. 159/2011) — por facilitar culposamente a exploração ao longo das suas cadeias de subcontratação. O setor da moda mostra o modelo em escala. Alviero Martini, Armani Operations, Manufactures Dior, Valentino, Loro Piana, Tod's: casas de luxo cujas cadeias terminavam em oficinas onde um casaco de caxemira vendido a 3.000 euros era montado por cerca de 100 euros. Em fevereiro de 2026, a Procuradoria de Prato estendeu o modelo para além de Milão com a Piazza Italia — trabalhadores abaixo de 4 euros por hora, sete dias por semana, margens estimadas em 300% sobre o custo de produção. Em dezembro de 2025, mais treze marcas figuravam nos autos milaneses. O caso Caddell na Piazzale Accursio pertence à mesma filosofia: subir a responsabilidade na cadeia, até o tomador." },
      { p: "E o instrumento corrige. A Loro Piana entrou em administração judicial em julho de 2025 e saiu em abril de 2026, com o tribunal chamando de \"virtuosa\" a reforma da cadeia — governança reforçada, auditorias independentes, fornecedores não conformes rescindidos. Nove meses do sequestro ao benchmark." },
      { p: "Mas aqui está a assimetria: quando a remediação termina, não há registro. Nenhuma lista pública onde um banco, um contratante principal ou um comprador possa checar se uma empresa foi julgada responsável, ou facilitou culposamente, a exploração do trabalho. O único instrumento público permanente da Itália é a Rete del lavoro agricolo di qualità — uma white list voluntária, limitada à agricultura." },
      { p: "Leia o contraste com precisão. O Brasil publica os nomes dos culpados, duas vezes por ano, em todos os setores, incluindo famílias, validado pelo STF — instrumento de memória que informa todo o mercado mas não corrige ninguém. Milão sequestra e reabilita um tomador por vez — instrumento de remediação que corrige a empresa mas não deixa rastro consultável para o mercado. Dois instrumentos sofisticados, perfeitamente complementares. Nenhuma das jurisdições adotou o da outra." },
      { p: "E a mecânica da exploração era quase idêntica nos dois casos: dívida de recrutamento (5.000 euros em Nova Delhi; aliciamento no Maranhão), dependência habitacional (residências da empresa fora de Milão; alojamentos em canteiros brasileiros), vulnerabilidade linguística, ocultação salarial. O que o artigo 149 do Código Penal brasileiro chama de \"condição análoga à escravidão,\" a Procuradoria de Milão chama de \"para-schiavismo.\" Mesmo fenômeno. Arquitetura institucional de resposta diferente." },
      { h: "A tradução para o negócio" },
      { p: "Com a CSDDD alterada (pós-Omnibus, Diretiva 2026/470), a due diligence obrigatória da UE aplica-se agora apenas aos maiores grupos — 5.000+ empregados, 1,5 bilhão de euros de faturamento, compliance a partir de 2029. Mas esses grupos compram café, carne, minerais e manufaturados brasileiros, e a diretiva lista explicitamente o nível de fiscalização em uma dada geografia entre os fatores de risco a ponderar. Suas obrigações cascatearão contratualmente sobre cada importador europeu de médio porte em suas cadeias." },
      { p: "Milão acaba de demonstrar que a geografia do risco de trabalho forçado inclui a Lombardia. O Brasil demonstra, duas vezes por ano, como se parece um instrumento de transparência para esse risco." },
      { p: "A lista suja — pública, gratuita, atualizada a cada seis meses — é o instrumento de screening de cadeia de suprimentos mais barato disponível para o mercado brasileiro. Em quinze anos de trabalho nos corredores, ainda não conheci um importador europeu que a tenha consultado antes de assinar um contrato de fornecimento." },
      { p: "Um canteiro do governo dos EUA em Milão operou com trabalho a 2 euros por hora por dois anos antes que alguém interviesse. O Brasil publica um registro exatamente dessa conduta, duas vezes por ano, a custo zero de consulta. Com qual dos dois sistemas o seu departamento de compliance preferiria trabalhar — e por que a Europa ainda não tem um?" },
    ],
  },
} as const;

export default function Suja() {
  const { lang } = useT();
  const article = getArticleBySlug("suja");
  const c = content[lang];

  return (
    <main className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16 md:py-24">
        <Link
          to="/analysis"
          className="inline-flex items-center gap-2 text-sm text-foreground/70 hover:text-foreground mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          {c.back}
        </Link>
        <article className="prose-invert">
          <h1 className="text-3xl md:text-5xl font-semibold tracking-tight mb-4">
            {article?.title[lang]}
          </h1>
          <p className="text-xs text-foreground/50 mb-10 tabular-nums">{article?.date}</p>
          <div className="space-y-5 text-foreground/85 text-justify leading-relaxed">
            {c.body.map((block, i) =>
              "h" in block ? (
                <h2 key={i} className="text-xl md:text-2xl font-semibold text-foreground text-left mt-8 mb-2">
                  {block.h}
                </h2>
              ) : (
                <p key={i}>{block.p}</p>
              )
            )}
          </div>
        </article>
      </div>
    </main>
  );
}